<?
//require("header.phtml");
require_once("viewpoint_connect_ro.phtml");
require_once("viewpoint_libs.inc");
require('mh_lib.inc');
require('report_lib.inc');

if ($job=="") die('none');
$job=addslashes($job);
$jobinfo=getoneb("select * from jobinfo where jobinfo_id = '$job'");


$vp_job_info=is_valid_viewpoint_job($jobinfo->contract_num);
$phases_locked=ms_getoneb("select * from JCJM with (NOLOCK) where JCCo = 1 and Job = '$vp_job_info->job' and LockPhases = 'Y'");

if ($phases_locked) {
	$query="select * from JCJP with (NOLOCK) INNER JOIN JCCH with (NOLOCK) on JCJP.JCCo = JCCH.JCCo and JCJP.Job = JCCH.Job and JCJP.Phase = JCCH.Phase where JCJP.Job = '$vp_job_info->job' and JCJP.JCCo = 1 and JCJP.ActiveYN = 'Y' and JCCH.CostType = '1'";
	} else { 
	$query="select * from JCPC with (NOLOCK),JCPM with (NOLOCK) where JCPC.Phase = JCPM.Phase and JCPC.CostType = 1 and JCPC.PhaseGroup = 1 and JCPM.PhaseGroup = 1";
	}

$res=@mssql_query($query);

echo "
<select name=phase>
<option></option>
";
while ($row=@mssql_fetch_object($res)) {
	$phase=ereg_replace("- *$","",$row->Phase);
	$phase=ereg_replace("- *$","",$phase);
	$row->Description=substr($row->Description,0,14);
	echo "<option>$phase - $row->Description</option>";
	}
echo "</select>";
?>
