<?php
global $use_odbc;
$use_odbc = 0;
session_write_close();
include("reports/report_lib.inc");
require("viewpoint_connect_ro.phtml");
require_once("viewpoint_libs.inc");

include ("graph1/jpgraph.php");
include ("graph1/jpgraph_line.php");

$ydata=array();
$textx=array();
$max=0;
$contract_num=get_vp_contract_num();

$sql = "select PREndDate,sum(Hrs) as Hours from PRJC where Job like '$contract_num%' and Phase like '17%' ";

if (!empty($week_starting))
{
	$sql .= " AND PREndDate >= '$week_starting' ";
}

if (!empty($week_ending))
{
	$sql .= " AND PREndDate <= '$week_ending' ";
}

$sql .= " group by PREndDate order by PREndDate";


if ($use_odbc)
{
$res=odbc_exec($conn,$sql);

$results_count=odbc_num_rows($res); 
if ($results_count<1) {
    // GPH MARK - absolute path
	$fullpath="/data/web/pipeline/images/na.jpg";
	$fsize=@filesize($fullpath);
	jpg_mime_header("na.jpg");
	@readfile($fullpath);
	exit;
	}

while ($row=odbc_fetch_object($res)) {
	if ($row->Hours > $max) $max=$row->Hours;
	array_push($ydata,$row->Hours);
	$wedate=date('m/d/y',strtotime($row->PREndDate));
	array_push($textx,$wedate);
	}
}
else
{
	$res=mssql_query($sql);

	$results_count=mssql_num_rows($res); 
	if ($results_count<1) {
		// GPH MARK - absolute path
		$fullpath="/data/web/pipeline/images/na.jpg";
		$fsize=@filesize($fullpath);
		jpg_mime_header("na.jpg");
		@readfile($fullpath);
		exit;
		}
	
	while ($row=mssql_fetch_object($res)) {
		if ($row->Hours > $max) $max=$row->Hours;
		array_push($ydata,$row->Hours);
		$wedate=date('m/d/y',strtotime($row->PREndDate));
		array_push($textx,$wedate);
		}	
}

//die(print_r($ydata, true));

$graph = new Graph(475,300,"auto");	
$graph->SetScale("intlin",'','',0,sizeof($ydata)-1);
$graph->SetMarginColor("$fd_color_1");
$graph->SetBackgroundGradient("$fd_color_4:1.1","black:0.5",GRAD_HOR,BGRAD_PLOT);

$graph->SetTitleBackground("$fd_color_4:1.1",TITLEBKG_STYLE1);


// Create the linear plots
$lineplot=new LinePlot($ydata);
$lineplot->SetColor("$fd_color_3");
$lineplot->SetWeight(1);

$lineplot->SetLegend("Hours");
//$lineplot2->SetLegend("Bah");
$graph->legend->Pos(0.05,0.7,"right","center");

//$graph->xaxis->SetFont(FF_ARIAL,FS_NORMAL,11);
$graph->xaxis->SetTickLabels($textx);
$graph->xaxis->SetLabelAngle(90);
//$graph->xaxis->scale->ticks->Set(7,1);

// Add the plot to the graph
$graph->Add($lineplot);

$graph->img->SetMargin(80,65,30,65);
$graph->title->Set("Sheet Metal Hours by week");
//$graph->xaxis->title->Set("Time");
$graph->xaxis->SetPos("min");
$graph->yaxis->title->Set("Hours");
$graph->yaxis->SetTitleMargin(60);

// Display the graph
$graph->Stroke();
?>