<?php

require_once('classes/ReportTable.php');
use classes\ReportTable\ReportTable;

$today = date('m-d-Y');
//$query_search_add = query_search_add_text();
$order_by = " order by
submittallog.spec_section + 0,
submittallog.spec_section,
submittallog.spec_sub_para + 0,
submittallog.spec_sub_para,
submittallog.spec_sub_sub_para + 0,
submittallog.spec_sub_sub_para,
submittallog.submittallog_id";
$query_final = "
select *,
submittallog.notes as submittal_notes
from submittallog 
left join documents on 
(documents.doc_type = 'submittallog' and 
documents.app_record_id = submittallog.submittallog_id)
left join contacts ON (contacts.contacts_id = submittallog.subcontractor)
where 
submittallog.jobinfo_id = '{$_SESSION['global_jobinfo_id']}' and
submittallog.section = '{$_SESSION['current_submittallog_section']}'
$order_by
";


$query_final_csv = "
select 
	'$global_jobinfo->contract_num' as 'Contract #',
	spec_section as 'Spec Section',
	spec_sub_para as 'Spec Sub Paragraph',
	spec_sub_sub_para as 'Spec Sub Sub Paragraph',
	submittal_description as 'Description',
	submittal_num as 'Submittal #',
	pkg_num as 'Package #',
	gc_num as 'GC #',
	tag as 'Tag',
	subcontractor_ref_num as 'Subcontractor Ref #',
	status as 'Status',
	notes as 'Notes'
 from submittallog 
left join documents on 
(documents.doc_type = 'submittallog' and 
documents.app_record_id = submittallog.submittallog_id)
where 
submittallog.jobinfo_id = '{$_SESSION['global_jobinfo_id']}' and
submittallog.section = '{$_SESSION['current_submittallog_section']}'
order by 
spec_section + 0,
spec_section,
spec_sub_para + 0, 
spec_sub_para,
spec_sub_sub_para + 0, 
spec_sub_sub_para,
submittallog_id
";


if ($csvdump == 1) {
    header("Content-Type: application/octet-stream; ");
    header("Content-Disposition: inline; filename=\"" . $global_jobinfo->contract_num . "_submittallog.csv\"");
    echo "Contract #,Spec Section,Spec Sub Paragraph,Spec Sub Sub Paragraph,Description,Submittal #,Package #,GC #,Tag,Subcontractor Ref #,Current Status,Current Status Date,Orig Status,Orig Status Date,Notes\r\n";
    $res = @mysql_query($query_final);
    while ($row = @mysql_fetch_object($res)) {
        $orig_status = getoneb("select * from submittallog_history where submittallog_id = '$row->submittallog_id' order by document_date,create_time,last_changed limit 1");
        $current_status = getoneb("select * from submittallog_history where submittallog_id = '$row->submittallog_id' order by document_date desc,create_time desc,last_changed desc limit 1");
        $row->spec_section = preg_replace('/,/', ";", $row->spec_section);
        $row->spec_sub_para = preg_replace('/,/', ";", $row->spec_sub_para);
        $row->spec_sub_sub_para = preg_replace('/,/', ";", $row->spec_sub_sub_para);
        $row->submittal_description = preg_replace('/,/', ";", $row->submittal_description);
        $row->submittal_num = preg_replace('/,/', ";", $row->submittal_num);
        $row->pkg_num = preg_replace('/,/', ";", $row->pkg_num);
        $row->gc_num = preg_replace('/,/', ";", $row->gc_num);
        $row->tag = preg_replace('/,/', ";", $row->tag);
        $row->subcontractor_ref_num = preg_replace('/,/', ";", $row->subcontractor_ref_num);
        $row->status = preg_replace('/,/', ";", $row->status);
        $row->notes = preg_replace('/,/', ";", $row->notes);
        $orig_status->status = preg_replace('/,/', ";", $orig_status->status);
        $current_status->status = preg_replace('/,/', ";", $current_status->status);
        echo "$global_jobinfo->contract_num,$row->spec_section,$row->spec_sub_para,$row->spec_sub_sub_para,$row->submittal_description,$row->submittal_num,$row->pkg_num,$row->gc_num,$row->tag,$row->subcontractor_ref_num,$row->status,$current_status->status,$current_status->document_date,$orig_status->status,$orig_status->document_date,$row->notes\r\n";
    }
    die();
} else {
	error_log("query in submittal [$query_final]");
    $res = @mysql_query($query_final);
}

require("header.php");
fd_navs_header();
echo "<div class='container-fluid'>";
?>
<div class="tablesearcherholder">
    <? ReportTable::doCommonControls('#submittallog'); ?>
    
    <table class='tablesearcher' cellpadding="3" cellspacing="0" border="0">
        <tbody>
            <tr id="filter_col1" data-column="1">
                <td>Spec Section</td>
                <td align="center"><input placeholder='search text' type="text" class="column_filter" id="col1_filter"></td>
            </tr>
            <tr id="filter_col2" data-column="2">
                <td>Submit #</td>
                <td align="center"><input placeholder='search text' type="text" class="column_filter" id="col2_filter"></td>
            </tr>
            <tr id="filter_col3" data-column="3">
                <td>Pkg #</td>
                <td align="center"><input placeholder='search text' type="text" class="column_filter" id="col3_filter"></td>
            </tr>
            <tr id="filter_col4" data-column="4">
                <td>Tag</td>
                <td align="center"><input placeholder='search text' type="text" class="column_filter" id="col4_filter"></td>
            </tr>
            <tr id="filter_col5" data-column="5">
                <td>Description</td>
                <td align="center"><input placeholder='search text' type="text" class="column_filter" id="col5_filter"></td>
            </tr>
            <tr id="filter_col6" data-column="6">
                <td>Subcontractor</td>
                <td align="center"><input placeholder='search text' type="text" class="column_filter" id="col6_filter"></td>
            </tr>
            <tr id="filter_col7" data-column="7">
                <td>Sub Ref #</td>
                <td align="center"><input placeholder='search text' type="text" class="column_filter" id="col7_filter"></td>
            </tr>
            <tr id="filter_col8" data-column="8">
                <td>GC #</td>
                <td align="center"><input placeholder='search text' type="text" class="column_filter" id="col8_filter"></td>
            </tr>
            <tr id="filter_col9" data-column="9">
                <td>Ref DWGs</td>
                <td align="center"><input placeholder='search text' type="text" class="column_filter" id="col9_filter"></td>
            </tr>
            <tr id="filter_col10" data-column="10">
                <td>Status</td>
                <td align="center"><input placeholder='search text' type="text" class="column_filter" id="col10_filter"></td>
            </tr>
            <tr id="filter_col11" data-column="11">
                <td>Change Date</td>
                <td align="center"><input placeholder='search text' type="text" class="column_filter" id="col11_filter"></td>
            </tr>
            <tr id="filter_col12" data-column="12">
                <td>Orig Status</td>
                <td align="center"><input placeholder='search text' type="text" class="column_filter" id="col12_filter"></td>
            </tr>
            <tr id="filter_col13" data-column="13">
                <td>Orig Date</td>
                <td align="center"><input placeholder='search text' type="text" class="column_filter" id="col13_filter"></td>
            </tr>
            <tr id="filter_col14" data-column="14">
                <td>Notes</td>
                <td align="center"><input placeholder='search text' type="text" class="column_filter" id="col14_filter"></td>
            </tr>
        </tbody>
    </table>
</div>
<?php
echo "
<div class='tableheader'>
<b>$dbdescription</b><br>$today<br>
";
if ($write) echo "<a href=$pagename?mode=submittallog_edit>New Submittal</a><br>";
select_section_box();
echo "
<br>
</div>
<div class='clearfix'></div></div>";

$columnHeaders = array (
    array ('name' =>'CSV', 'class' =>''),
    array ('name' =>'Spec Section', 'class' =>''),
    array ('name' =>'Submit #', 'class' =>''),
    array ('name' =>'Pkg #', 'class' => ' '),
    array ('name' =>'Tag', 'class' => ' '),
    array ('name' =>'Description', 'class' => 'description'),
    array ('name' =>'Subcontractor', 'class' => ' '),
    array ('name' =>'Sub Ref #', 'class' => ' '),
    array ('name' =>'GC #', 'class' => ' '),
    array ('name' =>'Ref DWGs', 'class' => ' '),
    array ('name' =>'Status', 'class' => ' '),
    array ('name' =>'Change Date', 'class' => 'nobr'),
    array ('name' =>'Orig Status', 'class' => 'nobr'),
    array ('name' =>'Orig Date', 'class' => 'nobr'),
    array ('name' =>'Notes', 'class' => 'notes'));


ReportTable::generateTableHeader($columnHeaders, 'submittallog', $pagename, $fd_color_4, $fd_color_3);

$count = 0;
while ($row = @mysql_fetch_object($res)) {
    $count++;
    $temp_doc_id = $row->doc_id;
    $cookie_link = batch_this_document($row->doc_id);
    $paperclip_link = webfile_paperclip_view($row->document_file_group_id);
    $bgcolor = "#ffffff";
    if ($row->status == 'Approved') $bgcolor = "#ccffcc";
    if ($row->status == 'Approved as noted') $bgcolor = "#ccffcc";
    if ($row->status == 'No Exceptions Taken') $bgcolor = "#ccffcc";
    $subcontractor_info = $row->display_name;//tbc getoneb("select * from contacts where contacts_id = '$row->subcontractor'");

    if ($row->app_reference == "") $row->app_reference = "?????";
    $current_status = getoneb("select * from submittallog_history where submittallog_id = '$row->submittallog_id' order by document_date desc,create_time desc,last_changed desc limit 1");
    $orig_status = getoneb("select * from submittallog_history where submittallog_id = '$row->submittallog_id' order by document_date,create_time,last_changed limit 1");

    if ($orig_status->history_id == $current_status->history_id) {
        $current_status->document_date = "";
        $current_status->status = "";
    }

    $current_status->document_date = invali_date($current_status->document_date, '/', 'Y');
    $orig_status->document_date = invali_date($orig_status->document_date, '/', 'Y');
    $current_status->status = preg_replace('/ /', '&nbsp;', $current_status->status);
    $orig_status->status = preg_replace('/ /', '&nbsp;', $orig_status->status);
    $ref_text = fd_text_doc_list($temp_doc_id, 'cnstdwglog');
    echo "<tr bgcolor=\"$bgcolor\"><td>
			<table border=0 cellspacing=0 cellpadding=0><tr><td width=20px;>$paperclip_link</td><td>$cookie_link</td></tr></table>
		</td><td>";
    if ($write)
        echo "<a style=\"text-decoration: none;\" href=$pagename?mode=submittallog_edit&submittallog_id=$row->submittallog_id>$row->app_reference</a>";
    else
        echo "$row->app_reference&nbsp;";
    echo "
		</td><td>
			$row->submittal_num
		</td><td>
			$row->pkg_num
		</td><td>
			$row->tag
		</td><td>
			$row->submittal_description
		</td><td>
			$subcontractor_info
		</td><td>
			$row->subcontractor_ref_num
		</td><td>
			$row->gc_num
		</td><td>";
    echo "$ref_text
		</td><td>
			$current_status->status
		</td><td >
			$current_status->document_date
		</td><td >
			$orig_status->status
		</td><td >
			$orig_status->document_date
		</td><td>
			$row->submittal_notes
		</td></tr>
		";
}


ReportTable::closeTable2('#submittallog', 'submittallog');

fd_navs_footer();
?>
