<?
include("../webfile$devel/storage_settings.cfg");

$submittallog_id=addslashes($submittallog_id);
$submittallog_info=getoneb("select * from submittallog where submittallog_id = '$submittallog_id'");
if (!($submittallog_info)) {
	$doc_id=addslashes($doc_id);
	$doc_info=getoneb("select * from documents where doc_id = '$doc_id' and doc_type = 'submittallog'");
	$submittallog_info=getoneb("select * from submittallog where submittallog_id = '$doc_info->app_record_id'");
	if (!($submittallog_info)) die("ERR(2)");
	}
if (!($submittallog_info)) die("ERR(1)");
$job=getoneb("select * from jobinfo where jobinfo_id = '$submittallog_info->jobinfo_id'");

$sequence=ereg_replace("[^0-9]","",$sequence);
//if ($sequence=="") die("Application error! (seq error)");
if ($sequence=="") die("ERR(3)");
$sequence=addslashes($sequence); // Shouldn't really be needed, should always be the same, but why not..
$seq_pretty=sprintf("%'04d",$sequence);



//$latest_full_sheet=getoneb("select * from cnstdwglog_latest_full_sheet where cnstdwglog_id = '$cnstdwglog_info->cnstdwglog_id'");
//$latest_full_sheet=getoneb("select * from cnstdwglog_sheet_history_descending where cnstdwglog_id = '$cnstdwglog_info->cnstdwglog_id' limit 1");






$files_res=@mysql_query("select * from webfile_files where file_group_id = '$submittallog_info->document_file_group_id' and mime_type like '%pdf%'");
$pdf_count=@mysql_num_rows($files_res);
if ($pdf_count<1) die("ERR(3.5 - No PDF to include)");
$file_letter="a";
@mkdir("/tmp/front_desk");
@mkdir("/tmp/front_desk/cook_a_batch");
@mkdir("/tmp/front_desk/cook_a_batch/$global_user->login_name");
@mkdir("/tmp/front_desk/cook_a_batch/$global_user->login_name/$job->contract_num");
@chdir("/tmp/front_desk/cook_a_batch/$global_user->login_name/$job->contract_num");

while ($row=@mysql_fetch_object($files_res)) {
	if ($row->file_group_id==0) die("ERR(99) - No File");
	$submittallog_info->submittallog_num=ereg_replace("[ /]","_",$submittallog_info->submittallog_num);
	$submittallog_info->submittallog_num=ereg_replace("[ /]","_",$submittallog_info->submittallog_num);
	
	//$latest_full_sheet->issuance_name=ereg_replace("[ /]","_",$latest_full_sheet->issuance_name);
	$file_name=$seq_pretty . $file_letter . "-_$job->contract_num_-_submittallog_-_$submittallog_info->submittallog_num.pdf";
	copy("$storage_root$row->file_path",$file_name);
	if (!(is_file($file_name))) die("ERR(4)");
	$file_letter++;
	}
echo "OK";
exit;
?>
