<?
if (!($write)) die_security('In submittal log edit screen without write permissions');
if ($submittallog_id!="")$submittallog_id=addslashes($submittallog_id);
$submittallog_info=getoneb("select * from submittallog where submittallog_id = '$submittallog_id'");
$doc_id=fd_get_doc_id($submittallog_id);

if (!($submittallog_info)) {
	if ($clone_submittallog_id>0) {
		$clone_submittallog_id=addslashes($clone_submittallog_id);
		$submittallog_info=getoneb("select * from submittallog where submittallog_id = '$clone_submittallog_id'");
		$submittallog_info->submittallog_id="";
		$submittallog_info->notes="";
		$submittallog_info->status="";
		$submittallog_info->document_file_group_id="";
		}
	}

include("header.phtml");
fd_navs_header();
load_webfile_javascript();
echo "
<script>
function sd_show_parts() {
	dir_opt=document.getElementById('direction_options');
	out_opt=document.getElementById('outgoing_options');
	in_opt=document.getElementById('incoming_options');
	fb=document.getElementById('webfilebox_container');
	dd=document.getElementById('document_date_container');
	dir_sel=dir_opt.options[dir_opt.selectedIndex].value;
	out_sel=out_opt.options[out_opt.selectedIndex].value;
	in_sel=in_opt.options[in_opt.selectedIndex].value;
	if (dir_sel=='Incoming') {
		in_opt.style.display='inline';
		if (in_sel=='') {
			fb.style.display='none';
			dd.style.display='none';
			} else {
			fb.style.display='inline';
			dd.style.display='inline';
			}			
		} else {
		in_opt.style.display='none';
		}
	if (dir_sel=='Outgoing') {
		out_opt.style.display='inline';
		if (out_sel=='') {
			fb.style.display='none';
			dd.style.display='none';
			} else {
			fb.style.display='inline';
			dd.style.display='inline';
			}			
		} else {
		out_opt.style.display='none';
		}
	
	if (dir_sel=='') {
		fb.style.display='none';
		dd.style.display='none';
		}
	}

function save_subdoc_change() {
	dir_opt=document.getElementById('direction_options');
	out_opt=document.getElementById('outgoing_options');
	in_opt=document.getElementById('incoming_options');
	history_obj=document.getElementById('history_id');
	fb=document.getElementById('webfilebox_container');
	history_sel=history_obj.value;
	dir_sel=dir_opt.options[dir_opt.selectedIndex].value;
	out_sel=out_opt.options[out_opt.selectedIndex].value;
	in_sel=in_opt.options[in_opt.selectedIndex].value;
	webfile_group_id=document.submittal_edit.new_submittal_document.value;
	document_date=urlencode(document.submittal_edit.document_date.value);
	status='error';
	//alert(urlencode(document_date));
	//return(FALSE);
	if (document_date=='') {
		alert('Please fill in the document date!');
		return(FALSE);
		}
	if (dir_sel=='Incoming') {
		status=in_sel;
		}
	if (dir_sel=='Outgoing') {
		status=out_sel;
		}
	if (status=='error') {
		alert('Status error. Please try again or contact your system administrator');
		return (FALSE);
		}
	if (webfile_group_id=='') {
		alert('Attachment error. Failed to find attachment (NULL). Please try again!');
		return (FALSE);
		}
	
	if (webfile_group_id=='0') {
		alert('Attachment error. Failed to find attachment (0). Please try again!');
		return (FALSE);
		}
	ajaxManager('load_page','$pagename?mode=submittal_documents&submittallog_id=$submittallog_info->submittallog_id&webfile_group_id=' + webfile_group_id + '&direction=' + dir_sel + '&status=' + status + '&history_id=' + history_sel + '&document_date=' + document_date,'submittal_documents');
	}

function submittal_history_edit(history_id,submittallog_id) {
	ajaxManager('load_page','$pagename?mode=submittal_documents&history_id=' + history_id + '&submittallog_id=' + submittallog_id,'submittal_documents');
	}

function cancel_subdoc_change() {
	reload_submittal_documents();
	}

function subdoc_delete() {
	if (confirm('Are you sure you want to delete this entry?')) {
		history_obj=document.getElementById('history_id');
		history_id=history_obj.value;
		ajaxManager(\"load_page\",'$pagename?mode=submittal_documents&submittallog_id=$submittallog_info->submittallog_id' + '&history_id_delete=' + history_id,\"submittal_documents\");
		}
	}

function reload_submittal_documents() {
	ajaxManager(\"load_page\",\"$pagename?mode=submittal_documents&submittallog_id=$submittallog_info->submittallog_id\",\"submittal_documents\");
	}
</script>

<form name=submittal_edit method=post action=$pagename>
<input type=hidden name=mode value=submittallog_submit>
<input type=hidden name=submittallog_id value=$submittallog_info->submittallog_id>

<div style=\"float: left;\">
<table border=1 cellspacing=0 cellpadding=4>

<tr><td colspan=4 align=center bgcolor=$fd_color_4>
	<b>Submittal Info</b>
</td></tr>

<tr bgcolor=$fd_color_1><td>
	&nbsp;
</td><td>
	&nbsp;
</td><td>
	Sub Para
</td><td>
	Sub Sub Para
</td></tr>
	

<tr><td>
	<b>Spec Section</b>
</td><td>
	<input size=15 type=text name=spec_section value=\"$submittallog_info->spec_section\">
</td><td>
	<input size=3 type=text name=spec_sub_para value=\"$submittallog_info->spec_sub_para\">
</td><td>
	<input size=3 type=text name=spec_sub_sub_para value=\"$submittallog_info->spec_sub_sub_para\">
</td></tr>

<tr><td>
	<b>Submittal #</b>
</td><td colspan=3>
	<input type=text name=submittal_num value=\"$submittallog_info->submittal_num\">
</td></tr>

<tr><td>
	<b>Package #</b>
</td><td colspan=3>
	<input type=text name=pkg_num value=\"$submittallog_info->pkg_num\">
</td></tr>

<tr><td>
	<b>Tag</b>
</td><td colspan=3>
	<input type=text name=tag value=\"$submittallog_info->tag\">
</td></tr>

<tr><td>
	<b>Description</b>
</td><td colspan=3>
	<input type=text name=submittal_description value=\"$submittallog_info->submittal_description\">
</td></tr>

<tr><td valign=top>
	<b>Submittal(s)</b>
</td><td colspan=3 id=\"submittal_documents\">
</td></tr>
<script>
reload_submittal_documents();
</script>

<tr><td>
	<b>Subcontractor</b>
</td><td colspan=3>
	";contact("select * from contacts where contact_type = 'company' and current = 'Y'",$submittallog_info->subcontractor,'subcontractor');echo"
</td></tr>

<tr><td>
	<b>Subcontractor Ref #</b>
</td><td colspan=3>
	<input text name=subcontractor_ref_num value=\"$submittallog_info->subcontractor_ref_num\">
</td></tr>

<tr><td>
	<b>GC #</b>
</td><td colspan=3>
	<input type=text name=gc_num value=\"$submittallog_info->gc_num\">
</td></tr>

<tr><td>
	<b>Ref DWG</b>
</td><td colspan=3>";
	
	echo "<div style=\"float: left;\">";
	fd_doc_box($submittallog_info->submittallog_id,'cnstdwglog',1);echo "
	</div>";
	
	echo "<div style=\"float: right; border: 1px solid black;\"><table border=0 cellspacing=0 cellpadding=1>";
	$listres=@mysql_query("select * from documents_links left join documents on (documents_links.docb = documents.doc_id) where documents_links.doca = '$doc_id' and documents.doc_type = 'cnstdwglog' order by app_reference, doc_id");
	while ($listrow=@mysql_fetch_object($listres)) {
		$latest_full_sheet=getoneb("select * from cnstdwglog_sheet_history_descending where cnstdwglog_id = '$listrow->app_record_id' limit 1");
		$plink=webfile_paperclip_view($latest_full_sheet->file_group_id);
		echo "<tr><td style=\"border-bottom: 1px solid black;\">cnstdwglog $listrow->app_reference</td><td style=\"border-bottom: 1px solid black;\">$plink</td></tr>";
		}
	echo"</table></div>";
	
	echo"
</td></tr>

<tr><td>
	<b>Notes</b>
</td><td colspan=3>
	<textarea name=notes rows=4 cols=55>$submittallog_info->notes</textarea>
</td></tr>

<tr><td colspan=4 align=right>
	<input type=submit name=action value=Cancel>
	<input type=submit name=action value=Apply>
	<input type=submit name=action value=Save>
	<input type=submit name=action value=\"Save and Clone\">
	<input type=submit name=action value=\"Save and Next\">
</td></tr>



</table>
</div>
<div style=\"padding: 20px; float: left;\">";
pal_box($doc_id);
echo "</div>";
fd_navs_footer();
?>
