<?
if (!($write)) die_security('Trying to write submittal changes without write permissions! Probably actually trying to reverse engineer the system here.. Go disable an account and ask questions later!');
if ($action=="Cancel") {
	forward('main');
	die();
	}
if ($submittallog_id!="") $submittallog_id=addslashes($submittallog_id);
$submittallog_info=getoneb("select * from submittallog where submittallog_id = '$submittallog_id'");

if ($submittallog_info) {
	$query_start="update submittallog set ";
	$query_end="where submittallog_id = '$submittallog_info->submittallog_id'";
	} else { 
	$query_start="insert into submittallog set jobinfo_id = '$global_jobinfo_id', section = '$current_submittallog_section', ";
	$query_end="";
	}


$spec_section=addslashes($spec_section);
$spec_sub_para=addslashes($spec_sub_para);
$spec_sub_sub_para=addslashes($spec_sub_sub_para);
$submittal_description=addslashes($submittal_description);
$tag=addslashes($tag);
$subcontractor=addslashes($subcontractor);
$subcontractor_ref_num=addslashes($subcontractor_ref_num);
$document_file_group_id=addslashes($document_file_group_id);
$status=addslashes($status);
$submittallog_num=addslashes($submittallog_num);
$pkg_num=addslashes($pkg_num);
$gc_num=addslashes($gc_num);
$notes=addslashes($notes);
$query_middle="

spec_section = '$spec_section',
spec_sub_para = '$spec_sub_para',
spec_sub_sub_para = '$spec_sub_sub_para',
submittal_description = '$submittal_description',
tag = '$tag',  
subcontractor = '$subcontractor',
subcontractor_ref_num = '$subcontractor_ref_num',
submittal_num = '$submittal_num',
pkg_num = '$pkg_num',
notes = '$notes',
gc_num = '$gc_num'
";
$query=$query_start . $query_middle . $query_end;
$res=@mysql_query($query);

if (!($res)) {
	die("Application error. Query failed:<hr>$query");
	}

if (!($submittallog_info)) {
	$id=@mysql_insert_id();
	$submittallog_info=getoneb("select * from submittallog where submittallog_id = '$id'");
	}

if ($action=="Apply") {
	forward("submittallog_edit&submittallog_id=$submittallog_info->submittallog_id");
	die();
	}

if ($action=="Save and Clone") {
	forward("submittallog_edit&clone_submittallog_id=$submittallog_info->submittallog_id");
	die();
	}

if ($action=="Save and Next") {
	$list_res=@mysql_query("
	select * from submittallog 
	left join documents on 
	(documents.doc_type = 'submittallog' and 
	documents.app_record_id = submittallog.submittallog_id) 
	where 
	submittallog.jobinfo_id = '$global_jobinfo_id' and 
	submittallog.section = '$current_submittallog_section'
	order by 
	spec_section + 0,
	spec_section,
	spec_sub_para + 0, 
	spec_sub_para,
	spec_sub_sub_para + 0, 
	spec_sub_sub_para,
	submittallog_id   
	");   
	while ($row=@mysql_fetch_object($list_res)) {
		if ($found_it==TRUE) {
			$next_record_info=$row;
			$found_it=FALSE;
			}
		if ($row->submittallog_id==$submittallog_info->submittallog_id) $found_it=TRUE;
		
		}
	if ($next_record_info) {
		forward("submittallog_edit&submittallog_id=$next_record_info->submittallog_id");
		die();
		}
	}
forward('main');
?>
