<?

if ($pal_id!="") {
	$pal_id=addslashes($pal_id);
	$pal_info=getoneb("select * from pal where pal_id = '$pal_id'");
	$query_start="update pal set ";
	$query_end=" where pal_id = '$pal_info->pal_id'";
	} else {
	$max_pal_num=getoneb("select max(pal_num) as total from pal where jobinfo_id = '$global_jobinfo_id'");
	if ($max_pal_num->total<1) $max_pal_num->total=0;
	$newmax=$max_pal_num->total + 1;
	$query_start="insert into pal set jobinfo_id = '$global_jobinfo_id', section = 'default', pal_num = '$newmax', creator_id = '$global_user_id', create_date = now(), ";
	$query_end="";
	}

$short_description=addslashes($short_description);
$full_description=addslashes($full_description);
$due_date=vali_date($due_date);
$priority=addslashes($priority);

$query_middle="
short_description = '$short_description',
full_description = '$full_description',
due_date = '$due_date',
priority = '$priority'

";

$query_full=$query_start . $query_middle . $query_end;

$pal_status=addslashes($pal_status);
$pal_assigned=addslashes($pal_assigned);

//die("<hr>$query_full<hr>");
@mysql_query($query_full);
forward("main&pal_status=$pal_status&pal_assigned=$pal_assigned");








?>
