<?
$today=date('Y-m-d');
if ($section=="") $section=$current_pal_section;
if ($section=="") die('Application error (section)!');

if ($jobinfo_id!="") {
	$jobinfo_id=addslashes($jobinfo_id);
	$job_info=getone("select * from jobinfo where jobinfo_id = '$jobinfo_id'");
	} else {
	die('Application error! Job information is missing or invalid.');
	}

$old_max=getoneb("select max(pal_num) as pal_num from pal where section = '$section' and jobinfo_id = '$job_info->jobinfo_id' limit 1");
$new_max=$old_max->pal_num + 1;
$create_query="
insert into pal set 
jobinfo_id = '$jobinfo_id', 
section = '$section', 
pal_num = '$new_max',
short_description = '',
full_description = '',
creator_id = '$global_user_id',
create_date = '$today'";
@mysql_query($create_query);

$new_doc_ref=@mysql_insert_id();
//$new_doc_info=getone("select * from documents where doc_type = 'pal' and app_record_id = '$new_doc_ref'");

/*
if ($doc_info) {
	/////////////////////////////////////
	// Register the newley added 
	/////////////////////////////////////
	//echo "<hr>call doc_link($doc_info->doc_id,$new_doc_id);<hr>";
	//echo "<hr>call doc_link($doc_info->doc_id,$new_doc_info->doc_id,$global_user_id,'automatic pal');<hr>";
	@mysql_query("call doc_link($doc_info->doc_id,$new_doc_info->doc_id,$global_user_id,'automatic pal');");
	} else {
	$doc_info=getone("select * from documents where doc_type = 'pal' and app_record_id = '$new_doc_id'");
	}
pal_box_filler($doc_info->doc_id);
echo "<div onload=\"pal_id_edit_toggle($new_doc_ref,'true');\"></div>";
exit;
*/

if ($pal_assigned!="") {
	$pal_assigned=addslashes($pal_assigned);
	@mysql_query("insert into pal_assignments set pal_id = '$new_doc_ref', creator_id = '$global_user_id', owner_id = '$pal_assigned', mso = 'N'");
	//die("insert into pal_assignments set pal_id = '$new_doc_ref', creator = '$global_user_id', owner_id = '$pal_assigned', mso = 'N'");
	}
$pal_status=addslashes($pal_status);
forward("pal_edit&pal_id=$new_doc_ref&pal_status=$pal_status&pal_assigned=$pal_assigned");

?>
