<?
require('header.phtml');
include("report_lib.inc");
require("viewpoint_connect_ro.phtml");
require_once("viewpoint_libs.inc");
$report_name="baldwin";
if (!(pm_for_this_job())) check_report_permissions();

echo "
<html>
<body>
<div class=noprint style=\"float: right; cursor: hand; cursor: pointer;\"><font color=blue onclick=\"print();\"><i><u>Print</u></i></font>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>

<font size=-2>

";

if ($detailmode=='h3') {
	$detailmode='h1';
	$sloppy_job=TRUE;
	$sloppy_phase=TRUE;
	}

if ($detailmode=='h2') {
	$detailmode='h1';
	$sloppy_job=TRUE;
	}

if ($detailmode=='c2') {
	$detailmode='c1';
	$sloppy_job=TRUE;
	}

if ($detailmode=='c3') {
	$detailmode='c1';
	$sloppy_phase=TRUE;
	$sloppy_job=TRUE;
	}

if ($detailmode=='h1') {
	$lastphase="";
	$query_add="";
	$job=addslashes($job);
	if ($ct!="") { $ct=addslashes($ct); $query_add=$query_add . "CostType = '$ct' and "; }
	//if ($phase!="") { $phase=addslashes($phase); $query_add=$query_add . "Phase = '$phase' and "; }
	if ($phase!="") { 
		$phase=addslashes($phase);
		if ($sloppy_phase) {
			if ($phase=="25") {
				$query_add=$query_add . "((Phase like '25%') or (Phase like '26%') or (Phase like '29%'))  and "; 
				} else {
				$query_add=$query_add . "Phase like '$phase%' and "; 
				}
			}
		else $query_add=$query_add . "Phase = '$phase' and "; 
		}
	if ($sloppy_job) { $query_add=$query_add . "Job like '$job%' and "; }
	else { $query_add=$query_add . "Job = '$job' and "; }
	$details_query="
		select *
	    from JCCD with (NOLOCK)
		where 
	    JCCo = 1 and 
	    PhaseGroup = 1 and
	    $query_add
	    PostedDate >= '$start_date' and
	    PostedDate <= '$end_date' and 
	    ActualHours != 0
	    order by Job,Phase,ActualDate,PostedDate
	    ";
	$total=0;
	echo "<table width=100% border=1 cellspacing=0 cellpadding=4>";
	//ms_tabledump($details_query);
	$res=@mssql_query($details_query);
		
		while ($row=@mssql_fetch_object($res)) {
		$phase_pretty=ereg_replace("[ -]*$","",$row->Phase);
		if ("$lastphase"!="$phase_pretty") {
			if ($lastphase!="") {
				echo "<tr bgcolor=$fd_color_1><td>Total</td><td>&nbsp;</td><td>&nbsp;</td><td>$total</td><td>&nbsp;</td></tr>";
				$grand_total_hours=$grand_total_hours + $total;
				$total=0;
				}
			echo "<tr><td colspan=5 bgcolor=$fd_color_4 align=center><b>" . ereg_replace("[ -]*$","",$row->Job) . "-$phase_pretty&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$start_date-$end_date</td></tr>";
			$lastphase=$phase_pretty;
			}
		$emp=getoneb("select * from contacts where employee_num = '$row->Employee'");
		$nice_date=date('m/d/y',strtotime($row->ActualDate));
		$nice_post_date=date('m/d/y',strtotime($row->PostedDate));
		$dow=date('D',strtotime($row->ActualDate));
		$multiplier="";
		if ($row->EarnFactor>1) $multiplier="<i>&nbsp;(x$row->EarnFactor)</i>";
		echo "<tr><td>
				$row->Employee
			</td><td>
				$emp->display_name
			</td><td>
				$phase_pretty
			</td><td>
				$row->ActualHours$multiplier
			</td><td>
				$dow - $nice_date&nbsp;&nbsp;**&nbsp;&nbsp;Posted on: $nice_post_date
			</td></tr>";
		$total=$row->ActualHours + $total;
		}
	echo "<tr bgcolor=$fd_color_1><td>Total</td><td>&nbsp;</td><td>&nbsp;</td><td>$total</td><td>&nbsp;</td></tr>";
	echo "</table>";
	$grand_total_hours=$grand_total_hours + $total;
	}

if ($detailmode=='c1') {
	$lastphase="";
	$query_add="";
	$job=addslashes($job);
	if ($ct!="") { $ct=addslashes($ct); $query_add=$query_add . "CostType = '$ct' and "; }
	if ($sloppy_job) { $query_add=$query_add . "Job like '$job%' and "; }
	else { $query_add=$query_add . "Job = '$job' and "; }
	if ($phase!="") { 
		$phase=addslashes($phase);
		if ($sloppy_phase) {
			if ($phase=="25") {
				$query_add=$query_add . "((Phase like '25%') or (Phase like '26%') or (Phase like '29%'))  and "; 
				} else {
				$query_add=$query_add . "Phase like '$phase%' and "; 
				}
			}
		else $query_add=$query_add . "Phase = '$phase' and "; 
		}
	$details_query="
		select *
	    from JCCD with (NOLOCK)
		where 
	    JCCo = 1 and 
	    PhaseGroup = 1 and
	    $query_add
	    PostedDate >= '$start_date' and
	    PostedDate <= '$end_date' and 
	    JCTransType != 'PR' and 
	    ActualCost != 0
	    
	    order by Job,Phase,ActualDate,PostedDate
	    ";
	$total=0;
	echo "<table width=100% border=1 cellspacing=0 cellpadding=4>";
	/////////////////////////////////////////////////////////////////////
	// Payroll line.. 
	/////////////////////////////////////////////////////////////////////
	$payroll_query="
	select sum(ActualHours) as ActualHours, sum(ActualCost) as ActualCost
	from JCCD with (NOLOCK) where 
	JCCo = 1 and PhaseGroup = 1 and 
	$query_add 
	PostedDate >= '$start_date' and 
	PostedDate <= '$end_date' and 
	JCTransType = 'PR'";
	$payroll_info=ms_getoneb($payroll_query);
	if (($payroll_info->ActualHours!=0)||($payroll_info->ActualCost!=0)) {
		echo "<tr><td>PR</td><td>Payroll Entries</td><td>Total from payroll</td><td>" . format_long_decimal($payroll_info->ActualHours) . "</td><td colspan=2>Total Cost: " . format_long_decimal($payroll_info->ActualCost) . "</td></tr>";
		$grand_total_hours=$grand_total_hours + $payroll_info->ActualHours;
		$grand_total_cost=$grand_total_cost + $payroll_info->ActualCost;
		}
	/////////////////////////////////////////////////////////////////////
	$res=@mssql_query($details_query);
	while ($row=@mssql_fetch_object($res)) {
		$phase_pretty=ereg_replace("[ -]*$","",$row->Phase);
		if ("$lastphase"!="$phase_pretty") {
			if ($lastphase!="") {
				echo "<tr bgcolor=$fd_color_1><td>Total</td><td>&nbsp;</td><td>&nbsp;</td><td align=right>" . format_long_decimal($total,2) . "</td><td>&nbsp;</td><td>&nbsp;</td></tr>";
				$grand_total_cost=$grand_total_cost + $total;
				$total=0;
				}
			echo "<tr><td colspan=6 bgcolor=$fd_color_4 align=center><b>" . ereg_replace("[ -]*$","",$row->Job) . "-$phase_pretty&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$start_date-$end_date</td></tr>";
			$lastphase=$phase_pretty;
			}
		//$emp=getoneb("select * from contacts where employee_num = '$row->Employee'");
		$nice_date=date('m/d/y',strtotime($row->ActualDate));
		$nice_posted_date=date('m/d/y',strtotime($row->PostedDate));
		$dow=date('D',strtotime($row->ActualDate));
		$polink="";
		$return_to_url="";
		$vendor_text="";
		if ($row->Vendor>0) {
			$vendor_info=ms_getoneb("select * from APVM with (NOLOCK) where VendorGroup = 1 and Vendor = '$row->Vendor'");
			$vendor_text=$vendor_info->Name;
			}
		if ($row->PO!="") {
			$return_to_url=base64_encode($REQUEST_URI);
			$polink="<a href=\"/global/front_desk$devel/?mode=report_show&report_name=po_show&po_number=$row->PO&return_to_url=$return_to_url\"><font color=blue><i>$row->PO</i></font></a>&nbsp;";
			}
		echo "<tr><td title=\"$row->Source\">
				$row->JCTransType
			</td><td>
				$vendor_text
			</td><td>
				$polink$row->Description
			</td><td>
				$phase_pretty
			</td><td align=right>
				" . format_long_decimal($row->ActualCost,2) . "
			</td><td>
				$dow - $nice_date&nbsp;&nbsp;*&nbsp;&nbsp;$nice_posted_date
			</td></tr>";
		$total=$row->ActualCost + $total;
		//$total=$row->ActualCost + $total;
		}
	echo "<tr bgcolor=$fd_color_1><td>Total</td><td>&nbsp;</td><td>&nbsp;</td><td align=right>" . format_long_decimal($total,2) . "</td><td>&nbsp;</td><td>&nbsp;</td></tr>";
	echo "</table>";
	$grand_total_cost=$grand_total_cost + $total;
	}


echo "</font>
<p>
<table border=1 cellspacing=0 cellpadding=5>
<tr><td colspan=2 bgcolor=$fd_color_4 align=center>
	<b>Grand Totals</b>
</td></tr>
";
if ($grand_total_hours>0) {
	echo "<tr><td><b>Hours</b></td><td>$grand_total_hours</td></tr>";
	}
if ($grand_total_cost>0) {
	echo "<tr><td><b>Costs</b></td><td>$grand_total_cost</td></tr>";
	}

echo "
</table>
</body>
</html>
";

?>
