<?
$employee_group=1;

require("header.phtml");
require_once("viewpoint_connect_ro.phtml");
require_once("viewpoint_libs.inc");
require('mh_lib.inc');
require('report_lib.inc');
$report_name="baldwin";
if (!(pm_for_this_job())) check_report_permissions();

if ($sl=="") die("Application error. Unable to identify subcontract!");
$sl=addslashes($sl);
$query="select * from SLCD with (NOLOCK) where SLCo = 1 and SL = '$sl'";
$res=@mssql_query($query);

$rows=@mssql_num_rows($res);

$grand_total=0;
if ($rows>0) {
	echo "
	<a class=noprint href=javascript:print()><font color=blue><i>Print</i></font></a>
	
	<table border=0 cellspacing=0 cellpadding=6>";
	while ($row=@mssql_fetch_object($res)) {
		$grand_total=$grand_total + $row->ChangeCurCost;
		$pretty_date=date('m/d/y',strtotime($row->ActDate));
		echo "<tr><td>
				$row->SLChangeOrder
			</td><td>
				$row->Description
			</td><td align=right>
				\$" . gap_num($row->ChangeCurCost) . "
			</td><td>
				$pretty_date
			</td></tr>
			";
		}
	echo "
	<tr bgcolor=$fd_color_1><td colspan=2>
		<b>Total</b>
	</td><td align=right>
		\$" . gap_num($grand_total) . "
	</td><td>
		&nbsp;
	</td></tr>
	
	</table>";
	}
?>
