<?
require("header.phtml");
require('mh_lib.inc');
require('report_lib.inc');
include('viewpoint_connect_ro.phtml');
include('viewpoint_libs.inc');
function clean_vp_date($date) {
	$today_unixtime=strtotime("today");
	$date_unixtime=strtotime($date);
	$diff=$today_unixtime - $date_unixtime;
	$years=floor(((($diff/3600)/24)/365));
	$remainder_seconds=($diff - ($years * 365 * 24 * 3600));
	$remainder_days=floor(($remainder_seconds / 3600) / 24);
	$date=ereg_replace("12:00AM$",'',$date );
	$date=$date . " (${years}yrs,${remainder_days}days)";
	return ($date);
	}
                                        
mh_navs_header();
$default_year=date('Y');
if ($year=="") $year=$default_year;
if ($employee!="") {
	$employee=addslashes($employee);
	$employee_info=getoneb("select * from contacts where contacts_id = '$employee'");
	$vp_employee_info=ms_getoneb("select * from HRRM with (NOLOCK) where HRCo = 1 and PREmp = '$employee_info->employee_num'");
	$hire_date=clean_vp_date($vp_employee_info->HireDate);
	} else {
	$employee_info=FALSE;
	}





echo "
<center>
<form name=selectyear method=post action=$pagename>
";contactsbox("select * from contacts where umc_emp = 'Y' and current = 'Y'",$employee,"employee","opener.document.selectyear.submit()");

if ($employee_info) echo "<br>$hire_date";

echo "

<table border=1 cellspacing=0 cellpadding=5>
<tr>
<input type=hidden name=mode value=$mode>
<input type=hidden name=report_name value=\"$report_name\">
<td colspan=4 bgcolor=$fd_color_4 align=center><b><font size=+2>Employee Milestones</font></b><br><input type=text size=6 name=year value=\"$year\" onchange=submit()></td></form></tr>
<tr><td><b>Name</b></td><td><b>Hire&nbsp;Date</b></td><td><b>Years</b></td><td>&nbsp;</td></tr>
";
$res=@mssql_query("select * from HRRM with (NOLOCK) where HRCo = 1 and ActiveYN = 'Y' order by HireDate");
while ($row=@mssql_fetch_object($res)) {
	$hireyear=date('Y',strtotime($row->HireDate));
	$years=$year - $hireyear;
	
	switch ($years) {
		case "5":
		case "10":
		case "15":
		case "20":
		case "25":
		case "30":
		case "35":
		case "40":
		case "45":
		case "50":
		case "55":
		case "60":
		case "65":
		case "70":
		case "75":
		case "80":
		case "85":
		case "90":
		case "95":
		case "100":
					$mark="*";
					break;;
		default: 
					$mark="&nbsp;";
					break;;
		}
	
	if ($mark!="*") continue;
	echo "<tr><td>
			$row->FirstName $row->LastName
		</td><td>
			$row->HireDate
		</td><td>
			$years
		</td><td>
			$mark
		</td></tr>";
	}

echo "</table></center>";

mh_navs_footer();

?>
