<?
require("header.phtml");
require('mh_lib.inc');
mh_navs_header();
check_report_permissions();
$na="<font size=\"-1\" color=gray>n/a</font>";

if ($contact_submit_mode!='') {
	echo "<a href=$pagename?mode=$mode&report_name=$report_name><font color=blue>Main Menu</font></a><br>";
	}

	echo "
	<script>
	function toggle_report_descriptions() {
		obj=document.getElementById('report_descriptions');
		//alert(obj.style.display);
		if (obj.style.display=='none') obj.style.display='block';
		else obj.style.display='none';
		}
	</script>
	<a href=javascript:toggle_report_descriptions()><font color=blue>Show/Hide Report Descriptions</font></a>
	
	<div id=report_descriptions style=\"display: none;\">
	<table border=1 cellspacing=0 cellpadding=4>
	<tr><td colspan=6 align=center bgcolor=$fd_color_4><b>Reports</b></td></tr>
	<tr bgcolor=$fd_color_1><td>
		<b>Nice Name</b>
	</td><td>
		<b>Actual Name</b>
	</td><td>
		<b>Embed</b>
	</td><td title=\"global or job\">
		<b>Type</b>
	</td><td>
		<b>Public</b>
	</td><td>
		<b>Description</b>
	</td></tr>
	";
	
	
	$res=@mysql_query("select * from front_desk_reports order by report_display_name");
	while ($row=@mysql_fetch_object($res)) {
		echo "<tr><td>
				$row->report_display_name
			</td><td>
				$row->report_name
			</td><td>
				$row->can_embed
			</td><td>
				$row->report_type
			</td><td>
				$row->open_to_everyone
			</td><td>
				$row->description
			</td></tr>";
		}
	echo "</table>
	</div>
	";

	echo "<table border=1 cellspacing=0 cellpadding=4>
	<tr><td colspan=5 align=center bgcolor=$fd_color_4><b>Subscribed Users</b></td></tr>";
	if ($adminuser) {
	if ($delete_permission_id!="") {
		$del_perm_info=getoneb("select * from front_desk_reports_permissions where permission_id = '$delete_permission_id'");
		$report_info=getoneb("select * from front_desk_reports where report_id = '$del_perm_info->report_id'");
		security_log_email(
			$del_perm_info->contacts_id,
			0,
			$del_perm_info->only_for_job,
			"deleted report permissions: admin=$del_perm_info->admin_user",
			$report_info->report_display_name
			);
			                        
		@mysql_query("delete from front_desk_reports_permissions where permission_id = '$delete_permission_id'");
		$contact_submit_mode="Search";
		}
	
	
	
	if ($contact_submit_mode=="Add") {
		if ( ($add_user_id!="") && ($report_id!="") && ($add_user_admin!="") ) {
			$add_user_id=addslashes($add_user_id);
			$add_user_admin=addslashes($add_user_admin);
			$report_id=addslashes($report_id);
			$add_jobinfo_id=addslashes($add_jobinfo_id);	
			$report_info=getoneb("select * from front_desk_reports where report_id = '$report_id'");
			//print_r($report_info);
			if ($report_info->report_type!="job") $add_jobinfo_id=0;
			$insert_query="insert into front_desk_reports_permissions set 
				report_id = '$report_id', 
				contacts_id = '$add_user_id',
				admin_user = '$add_user_admin',
				granted_by = '$global_user_id',
				only_for_job = '$add_jobinfo_id'
				";
			
			security_log_email(
				$add_user_id,
				0,
				$add_jobinfo_id,
				"added report permissions: admin=$add_user_admin",
				$report_info->report_display_name
				);
			                        
			$insert_res=@mysql_query($insert_query);
			if(!($insert_res)) {
				die ("Insert error: <hr>$insert_query");
				}	
			}
			$report_id="";
			$add_user_admin="";
			$add_jobinfo_id="";
			$contact_submit_mode="Search";
		}
		$extra_where="";
		if ($add_user_id!="") {
			$add_user_id=addslashes($add_user_id);
			$extra_where=$extra_where . " and contacts.contacts_id = '$add_user_id' ";
			}
		if ($report_id!="") {
			$report_id=addslashes($report_id);
			$extra_where=$extra_where . " and front_desk_reports_permissions.report_id = '$report_id' ";
			}
		if ($add_user_admin!="") {
			$add_user_admin=addslashes($add_user_admin);
			$extra_where=$extra_where . " and front_desk_reports_permissions.admin_user = '$add_user_admin' ";
			}
		if ($add_jobinfo_id!="") {
			$add_jobinfo_id=addslashes($add_jobinfo_id);
			$extra_where=$extra_where . " and front_desk_reports_permissions.only_for_job = '$add_jobinfo_id' ";
			}
	
	
	
			echo "<tr><td colspan=5 bgcolor=$fd_color_3>
					<form name=add_user method=post action=$pagename>
					<input type=hidden name=mode value=\"$mode\">
					<input type=hidden name=report_name value=\"$report_name\">
					<table border=0 cellcpacing=2><tr><td><b>Contact</b></td><td><b>Report</b></td><td><b>Job&nbsp;*</b></td><td><b>Admin</b></td></tr>
					<tr><td valign=top>";
						contactsbox("select * from contacts where umc_emp = 'Y' and current = 'Y'","$add_user_id","add_user_id");echo "
					</td><td>
						";dropbox("select report_id,report_display_name,' (', report_type, ')'  from front_desk_reports order by report_display_name",$report_id,"","",2);echo"
					</td><td>
						";dropbox("select jobinfo_id as add_jobinfo_id,contract_num from jobinfo where active = 'Y' order by contract_num",$add_jobinfo_id,"","",2);echo"
					</td><td>
						<select name=add_user_admin><option>$add_user_admin</option><option>N</option><option>Y</option><option></option></select>
					</td><td>
						<input name=contact_submit_mode type=submit value=Search>
					</td><td>
						<input name=contact_submit_mode type=submit value=Add>
					</td></tr></table>
					</form>
				</td></tr>
			";

		//$contact_submit_mode="Search";
		$report_id="";
		$add_user_admin="";
		$add_jobinfo_id="";
	
	}
	
	
if ($contact_submit_mode!='') {
	//echo "$contact_submit_mode";
	$query="select * from front_desk_reports_permissions natural join contacts natural join front_desk_reports where contacts.current = 'Y' order by alphasort,report_display_name";
	//echo "<hr>$query<hr>";
	if ($contact_submit_mode=="Search") {
		$query="select * from front_desk_reports_permissions natural join contacts natural join front_desk_reports where contacts.current = 'Y' $extra_where order by alphasort,report_display_name";
		}
	
	$res=@mysql_query($query);
	//$res=@mysql_query("select * from front_desk_reports_permissions natural join contacts natural join front_desk_reports order by alphasort,report_display_name");
	
	
	echo "<tr bgcolor=$fd_color_1><td><b>User</b></td><td><b>Report</b></td><td><b>Job</b></td><td><b>Admin</b></td><td>&nbsp;</td></tr>";
	while ($row=@mysql_fetch_object($res)) {
		$row_creator=getoneb("select * from contacts where contacts_id = '$row->granted_by'");
		
		
		if ($row->only_for_job==0) $row->only_for_job="&nbsp;";
		else { 
			$rowjobinfo=getoneb("select contract_num from jobinfo where jobinfo_id = '$row->only_for_job'"); 
			$row->only_for_job=$rowjobinfo->contract_num;
			}
		if ($adminuser) {
			$delete_link="<a href=$pagename?mode=$mode&report_name=$report_name&add_user_id=$add_user_id&delete_permission_id=$row->permission_id><font color=blue><i>Delete</i></font></a>";
			} else {
			$delete_link="&nbsp;";
			}
		echo "<tr><td title=\"Added by $row_creator->display_name @ $row->permission_modified_last\"><a href=$pagename?mode=$mode&report_name=$report_name&report_mode=edit_user><font color=blue>$row->display_name</font></a></td><td>$row->report_display_name</td><td>$row->only_for_job</td><td>$row->admin_user</td><td>$delete_link</td></tr>";
		}
echo "
</table>
&nbsp;<p>	
&nbsp;<p>	
&nbsp;<p>	
&nbsp;<p>	
&nbsp;<p>	
&nbsp;<p>	
&nbsp;<p>	
&nbsp;<p>	
&nbsp;<p>	
&nbsp;<p>	
&nbsp;<p>	
&nbsp;<p>	
&nbsp;<p>	
&nbsp;<p>	
";	
} else {


$query="select * from front_desk_reports order by report_display_name";
echo "<table border=1 cellspacing=0 cellpadding=3>
<tr bgcolor=$fd_color_4><td>
	<b>Application</b>
</td><td>
	<b>Description</b>
</td><td>
	<b>Global Count</b>
</td><td>
	<b>By Job Count</b>
</td></tr>
";

$res=@mysql_query($query);
while ($row=@mysql_fetch_object($res)) {
	$global_list=getoneb("select sum(1) as count from front_desk_reports_permissions where report_id = '$row->report_id' and only_for_job = 0");
	$job_list=getoneb("select sum(1) as count from front_desk_reports_permissions where report_id = '$row->report_id' and only_for_job != 0");
	if ($row->report_type=='global') $job_list->count="$na";
	if ($row->open_to_everyone=='Y') {
		$global_list->count="$na";
		$job_list->count="$na";
		}
	echo "<tr><td>
				<a href=$pagename?mode=$mode&contact_submit_mode=Search&report_name=$report_name&report_id=$row->report_id><font color=blue>$row->report_display_name</font></a>
			</td><td>
				<font size=-1><i>$row->description</i></font>
			</td><td>
				$global_list->count&nbsp;
			</td><td>
				$job_list->count&nbsp;
			</td></tr>";
	
	
	}
echo "</table>";

}
	
	
	
	
	
	
	
	
	
	


mh_navs_footer();
?>
