<?
require("header.phtml");
$report_name="trade_license_manager";
check_report_permissions();
require("mh_lib.inc");
require("report_lib.inc");
require("trade_licenses_lib.inc");
mh_navs_header();
check_for_missing_licenses();

$license_id=addslashes($license_id);
$license_info=getoneb("select * from front_desk_trade_licenses where license_id = '$license_id'");
//print_r($license_info);
echo "
<form name=license_edit method=post action=$pagename>
<input type=hidden name=mode value=report_show>
<input type=hidden name=report_name value=trade_license_submit>
<input type=hidden name=license_id value=\"$license_info->license_id\">

<table border=1 cellspacing=0 cellpadding=4>
<tr bgcolor=$fd_color_4><td colspan=2>
	<center><b>Edit License</b></center>
</td></tr>

<tr><td>
	<b>Employee</b>
</td><td>
	";contact("select * from contacts where umc_emp = 'Y' and current = 'Y'",$license_info->employee_id,"employee_id");echo"
</td></tr>

<tr><td>
	<b>License Type</b>
</td><td>
	";dropbox("select license_type_id,name from front_desk_trade_license_types",$license_info->license_type_id);echo"
</td></tr>

<tr><td>
	<b>License #</b>
</td><td>
	<input type=text size=20 name=license_num value=\"$license_info->license_num\">
</td></tr>

<tr><td>
	<b>Expiration Date</b>
</td><td>
	";datebox($license_info->expiration_date,"expiration_date");echo"
</td></tr>

<tr><td colspan=2 align=right>
	<input type=submit value=\"Submit\">
</td></tr>

</form>
</table>








";










mh_navs_footer();
?>
