<?
if (!($adminuser)) die_security();
$drawing_id=addslashes($drawing_id);
$drawing_info=getoneb("select * from drawinglog where drawing_id = '$drawing_id'");
require("../webfile/storage_settings.cfg");
require("../webfile/local.inc");
delete_webfile_group($drawing_info->submitted_file_group_id);
delete_webfile_group($drawing_info->correction_file_group_id);
delete_webfile_group($drawing_info->returned_file_id);
$revs=@mysql_query("select * from drawinglog_revs where drawing_id = '$drawing_info->drawing_id'");
while ($rev=@mysql_fetch_object($revs)) delete_webfile_group($rev->attached_file_group_id);
@mysql_query("delete from drawinglog_revs where drawing_id = '$drawing_info->drawing_id'");
@mysql_query("delete from drawinglog where drawing_id = '$drawing_id'");
@mysql_query("delete from documents where doc_type = 'drawinglog' and app_record_id = '$drawing_info->drawing_id'");
@mysql_query("delete from drawinglog_history where drawing_id = '$drawing_info->drawing_id'");
@mysql_query("delete from drawinglog_notes where drawing_id = '$drawing_info->drawing_id'");
forward('main');
?>
