<?
if ($dwg_rev_id!="") $dwg_rev_id=addslashes($dwg_rev_id);
else die("Application error. No record specified!");
$rev_info=getone("select * from drawinglog_revs where dwg_rev_id = '$dwg_rev_id'");
$rev_date=vali_date($rev_date);
$sent_to_field_date=vali_date($sent_to_field_date);

$revision=@ereg_replace(" ","",$revision);
if (@ereg("[a-zA-Z]",$revision)) $revision=" " . $revision;

$revision=mysql_real_escape_string($revision);


$rev_description=addslashes($rev_description);


$at_query="select * from drawinglog_revs where 
drawing_id = '$rev_info->drawing_id' and
revision = '$revision' and 
dwg_rev_id != '$rev_info->dwg_rev_id' limit 1";

$already_there=getoneb($at_query);
if ($already_there) {
	$max_rev_info=getoneb("select max(revision) as maxrev from drawinglog_revs where drawing_id = '$rev_info->drawing_id'");
	//tabledump("select max(revision) as maxrev from drawinglog_revs where drawing_id = '$rev_info->drawing_id'");die();
	$new_rev=$max_rev_info->maxrev + 1;
	$revision=$new_rev;
	echo "<script>
	alert('An invalid revision was selected, so a new one was chosen for you! Talk to Curtis if you have a problem with that.');
	</script>
	";
	}

@mysql_query("update drawinglog_revs set rev_date = '$rev_date', sent_to_field_date = '$sent_to_field_date', revision = '$revision', rev_description = '$rev_description' where dwg_rev_id = '$rev_info->dwg_rev_id'");
update_rev($rev_info->drawing_id);

if (($rev_date!="")&&($sent_to_field_date!="")) {
	if ($rev_date>$sent_to_field_date) {
		echo "
		<script>
		alert(\"Hey, those dates don't make any sense!!!\");
		</script>";
		}
	
	}
forward("drawinglog_edit&drawing_id=$rev_info->drawing_id");
?>
