<?php
require_once('classes/ReportTable.php');
use classes\ReportTable\ReportTable;

require('header.php');

fd_navs_header();
//if ($global_user->umc_emp=='Y')
ajax_load("/javascript/calendar.js");
//else echo "<script>function ajaxManager(){ return false; }</script>";
echo "

<style>
	@media print {
	th { font-family: arial; font-size: 8pt; }
	td { font-family: arial; font-size: 8pt; }
	}
</style>


<script>

function toggle_is_current(drawing_id,current_setting) {
	TOGGLE=0;
	if (current_setting=='Y') {
		if (confirm('Mark drawing as not current?')) {
			TOGGLE=1;
			}
		}
	
	if (current_setting!='Y') {
		if (confirm('Mark drawing as current?')) {
			TOGGLE=1;
			}
		}
	
	if (TOGGLE==1) {
		ajaxManager('load_page','$pagename?mode=quick_save_toggle&drawing_id=' + drawing_id,'is_current_' + drawing_id);
		}
	}

function quick_date_form(field,item) {
	if (item.onclick_save==item.onclick) return false;
	item.onclick_save=item.onclick;
	ajaxManager('load_page','$pagename?mode=quick_form&field=' + field + '&drawing_id=' + item.parentNode.id,item.id);
	}
function quick_form(field,item) {
	if (item.onclick_save==item.onclick) return false;
	item.onclick_save=item.onclick;
	ajaxManager('load_form','$pagename?mode=quick_form&field=' + field + '&drawing_id=' + item.parentNode.id,item.id);
	}
function save_data(dwg_id,field,item) {
	item.style.background='yellow';
	document.getElementById(field + '_' + dwg_id).onclick_save='';
	//alert(item.parentNode.parentNode.id);
	ajaxManager('load_page','$pagename?mode=quick_save_data&field=' + field + '&drawing_id=' + dwg_id + '&data=' + item.value,item.parentNode.parentNode.id);
	}

</script>
";

if ($global_jobinfo) {
    $query_search_add= ''; // do it all client side - was query_search_add_text();
	$query="select * from drawinglog where jobinfo_id = '$global_jobinfo->jobinfo_id' and section = '{$_SESSION['current_drawinglog_section']}' $query_search_add order by type,sort_priority,sheet_num";
	$res=@mysql_query($query);
	include("fd_log_paging.php");
    ReportTable::boss_search_filter(1, array(
        'Current', 'Area', 'Sheet #', 'Sheet Title', 'Rev', 'Rev Date', 'Orig Issue', 'Issued for Construction',
        'Sub to Eng', 'Ret from Eng', 'Resubmit Reqd', 'Submittal Status', 'Cur Sub Date', 'Sent to Field', 'Submitted to',
        'Notes', 'Type'
    ), '#sub_application_main_table');
    echo "
    <div class='floating_header'>
    <center>
	<b>Drawings for $global_jobinfo->contract_num - $global_jobinfo->display_name</b>
		<div class=noprint>
			<a href=$pagename?mode=drawinglog_edit&jobinfo_id=$global_jobinfo->jobinfo_id>Add Drawing</a>
			<br>
            $page_page_insert
		</div></center></div>";
	echo "<table class='standard' id='sub_application_main_table' border=1 cellspacing=0 cellpadding=5><thead>";
	$lasttype="";
	
	
	echo "
			<tr valign=top bgcolor=\"$fd_color_4\"><th style='min-width:54px'><span>
				<a target=csv_dl href=\"$pagename?mode=csv_download&query=" . urlencode($query) . "\">CSV</a>
			</span></th><th style='min-width:74px'><span>
				<b>Current</b>
			</span></th><th><span>
				<b>Area</b>
			</span></th><th><span>
				<b>Sheet&nbsp;#</b>
			</span></th><th><span>
				<b>Sheet&nbsp;Title</b>
			</span></th><th style='min-width:47px'><span>
				<b>Rev</b>
			</span></th><th style='min-width:89px'><span>
				<b>Rev&nbsp;Date</b>
			</span></th><th style='min-width:93px'><span>
				<b>Orig&nbsp;Issue</b>
			</span></th><th align=center  style='min-width:115px'><span>
				<b>Issued&nbsp;For<br>Construction</b>
			</span></th><th style='min-width:48px'><span>
				<b>Sub to Eng</b>
			</span></th><th style='min-width:53px'><span>
				<b>Ret from Eng</b>
			</span></th><th><span>
				<b>Resubmit Reqd</b>
			</span></th><th align=center><span>
				<b>Submittal<br>Status</b>
			</span></th><th align=center><span>
				<b>Cur Sub Date</b>
			</span></th><th style='min-width:54px'><span>
				<b>Sent to Field</b>
			</span></th><th style='min-width:115px'><span>
				<b>Submitted&nbsp;to</b>
			</span></th>
			<th><span><b>Notes</b></span></th>
			<th><span><b>Type</b></span></th></tr></thead><tbody>";
	

	
	while($row=@mysql_fetch_object($res)) {
		$temp_doc_id_query="select * from documents where doc_type = 'drawinglog' and section = '$row->section' and app_record_id = '$row->drawing_id'";
		//$temp_doc_id=getoneb("select * from documents where doc_type = 'drawinglog' and section = '$row->section' and app_record_id = '$row->drawinglog_id'");
		$temp_doc_info=getoneb($temp_doc_id_query);
		$temp_doc_id=$temp_doc_info->doc_id;
		//echo "<tr><td>$temp_doc_id</td><td>$temp_doc_id_query</td></tr>";
		$stbg="#ffffff";
		if ($row->submittal_status=='N/A') $stbg="#dddddd";
		if (false && $row->type!=$lasttype) {
			$lasttype=$row->type;
			echo "
			<tr class=floatheader><th colspan=18 align=center bgcolor=$fd_color_4>
				<b>$row->type</b>
			</td></tr>";
        }
		
		$s_sep="";
		$st_text="";
		if ($row->submitted_to_umc=='Y') { $st_text=$st_text . $s_sep . "umc";$s_sep=","; }
		if ($row->submitted_to_gc=='Y') { $st_text=$st_text . $s_sep . "gc";$s_sep=","; }
		if ($row->submitted_to_owner=='Y') { $st_text=$st_text . $s_sep . "owner";$s_sep=","; }
		if ($row->submitted_to_consultant=='Y') { $st_text=$st_text . $s_sep . "consultant";$s_sep=","; }
		if ($st_text=="") $st_text="&nbsp;";
		if (getoneb("select * from drawinglog_notes where drawing_id = '$row->drawing_id' limit 1")) {
			$notesimage="<img src=/images/note.gif>";
			} else {
			$notesimage="&nbsp;";
			}
		$orig_issue=invali_date($row->orig_issue,'/');
		$current_submittal_date=invali_date($row->current_submittal_date,'/');
		$const_issue=invali_date($row->issued_for_construction_date,'/');
		$current_rev_date=invali_date($row->current_rev_date,'/');

		if ($row->submitted_to_eng!="0000-00-00") $ste="X";
		else $ste="&nbsp;";
		
		if ($row->returned_from_eng!="0000-00-00") $rfe="X";
		else $rfe="&nbsp;";
		
		$rr="$row->correction_required";
		if (($rr=="N")||($rr=="")) $rr="N";
		
		$current_rev=getoneb("select * from drawinglog_revs where drawing_id = '$row->drawing_id' order by revision desc,rev_date desc, dwg_rev_id desc limit 1");
		if ($current_rev->sent_to_field_date!="0000-00-00") $stf="X";
		else $stf="&nbsp;";
		
		$file_paperclip=webfile_paperclip_download($current_rev->attached_file_group_id);
		$file_batch=batch_this_document($temp_doc_id);
		
		if ($current_rev_date=="") $current_rev_date="&nbsp;";
		if ($row->sheet_num=="") $row->sheet_num='&lt;?&gt;';
		$bgcolor="#ffffff";
		$note_addendum="";
		if ($row->drawing_is_current=='N') {
			$bgcolor="#ffaaaa";
			$note_addendum="<br>**** Warning, the drawing respresented here is not up to date. Please contact detailing for details ******";
			}
		echo "
		
		<tr bgcolor=$bgcolor id='$row->drawing_id'><td>
				<table border=0 cellspacing=0 cellpadding=0><tr><td>$file_paperclip&nbsp;</td><td>$file_batch</td></tr></table>
			</td><td id=\"is_current_$row->drawing_id\">
				<a href=\"javascript:toggle_is_current($row->drawing_id,'$row->drawing_is_current')\">$row->drawing_is_current</a>
			</td><td id=\"area_$row->drawing_id\">
				$row->area
			</td><td>";
				if (($write)||(($guest)&&($_SESSION['global_user_id']==$row->creator))) {
				echo "<a href=$pagename?mode=drawinglog_edit&drawing_id=$row->drawing_id>$row->sheet_num</a>";
				} else {
				echo "$row->sheet_num";
				}
				echo "
			</td>
			<td id=\"description_$row->drawing_id\" onclick=quick_form('description',this)>
				$row->description
			</td><td>
				$row->revision
			</td><td>
				$current_rev_date
			</td><td>
				$orig_issue
			</td><td>
				$const_issue
			</td><td align=center bgcolor=\"$stbg\">
				$ste
			</td><td align=center bgcolor=\"$stbg\">
				$rfe
			</td><td align=center bgcolor=\"$stbg\">
				$rr
			</td><td>
				$row->submittal_status
			</td><td>
				$current_submittal_date
			</td><td align=center>
				$stf
			</td><td align=center>
				$st_text
			</td><td>$notesimage$note_addendum
			</td><td>$row->type</td></tr>";
		}

    ReportTable::closeTable2('#sub_application_main_table');
	}
echo "</tbody></body>";
fd_navs_footer();
