<?
if ($global_user->umc_emp!='Y') die("ERROR");
//echo "<b>Saved</b>
//<hr>
//Drawing_id: $drawing_id<br>
//Field: $field<br>
//Data: $data<br>
//";

$drawing_id=addslashes($drawing_id);
$field=addslashes($field);
$is_date=false;
switch ($field) {
	case "sort_priority":
	case "cust_1":
	case "cust_2":
	case "cust_3":
	case "cust_4":
	case "cust_5":
	case "description":
			$data=addslashes($data);
			break;;
	case "current_rev_date":
			$is_date=true;
			$data=vali_date($data);
			break;;
	default:
			die("FIELD SUBMIT ERROR");
			break;;
	}

$res=@mysql_query("update drawinglog set $field = '$data' where drawing_id = '$drawing_id'");
if (!($res)) {
	die ("<b><font color=red>ERROR!</font></b>");
	} else {
	if ($is_date) $data=invali_date($data,'/');
	if ($data=="") $data="&nbsp;";
	echo "$data";
	record_history($drawing_id);
	}



?>
