<?
echo "<table border=0><tr bgcolor=#dddddd><td><i>Dwg</i></td><td><i>Grid Ref</i></td></tr>";
if ($gcrfi_id!="") {
	$gcrfi_id=addslashes($gcrfi_id);
	$gcrfi_info=getoneb("select * from gcrfilog where gcrfi_id = '$gcrfi_id'");
	if (!($gcrfi_info)) die('oops');
	if (($dwg!="")||($grid_ref!="")) {
		$dwg=addslashes($dwg);
		$grid_ref=addslashes($grid_ref);
		@mysql_query("insert into gcrfi_dwg_refs set gcrfi_id = '$gcrfi_info->gcrfi_id',dwg = '$dwg', grid_ref = '$grid_ref'");
		}
	
	if ($remove_gcrfi_ref_id!="") {
		//echo "hi";
		$remove_gcrfi_ref_id=addslashes($remove_gcrfi_ref_id);
		$ref_info=getoneb("select * from gcrfi_dwg_refs where gcrfi_ref_id = '$remove_gcrfi_ref_id'");
		if ($ref_info->gcrfi_id != $gcrfi_id) die("Application error: Unable to verify delete intention. Aborting.");
		@mysql_query("delete from gcrfi_dwg_refs where gcrfi_ref_id = '$remove_gcrfi_ref_id'");
		}
	$gcrfi_list=@mysql_query("select * from gcrfi_dwg_refs where gcrfi_id = '$gcrfi_id'");
	while ($row=@mysql_fetch_object($gcrfi_list)) {
		echo "<tr><td>$row->dwg</td><td>$row->grid_ref</td><td><a title=\"Remove dwg/grid ref\"href=\"javascript:rem_dwg_ref($row->gcrfi_ref_id);\"><font color=blue size=+1>-</font></a></td></tr>";
		}
	echo "<tr><td><input title=\"Drawing\" type=text size=10 name=dwg></td><td><input title=\"Grid Ref\" type=text name=grid_ref size=15></td><td><a href=\"javascript:add_dwg_ref();\"><font color=blue size=+1>+</font></a></td></tr>";
	} else {
	echo "<tr><td><input title=\"Drawing\" type=text size=10 name=dwg></td><td><input title=\"Grid Ref\" type=text name=grid_ref size=15></td><td><i><font size=-1>(Save first to add more)</font></i></td></tr>";
	}
echo "</table>";
?>
