<?
require('../webfile/local.inc');
if ($gcrfi_id=="") die("application error");
$gcrfi_info=getoneb("select * from gcrfilog where gcrfi_id = '$gcrfi_id'");

$fd_manager=fd_manager($gcrfi_info->jobinfo_id,$global_user_id);
if ($fd_manager||$adminuser) {
	@mysql_query("delete from gcrfilog where gcrfi_id = '$gcrfi_info->gcrfi_id'");
	delete_webfile_group($gcrfi_info->gcrfi_image_id);
	//die('delete time');
	forward('main');
	exit;
	}
die_security();
?>
