<?
require("header.phtml");


/*
$res=@mysql_query("select * from gcrfilog");
while ($row=@mysql_fetch_object($res)) {
	$doc_info=getone("select * from documents where doc_type = 'gcrfi' and app_record_id = '$row->gcrfi_id'");
	$doc_id=$doc_info->doc_id;
	echo "<br>$doc_id";
	sync_rfi_logs();
	}
*/

if ($global_jobinfo) {
	echo "
	<style type=\"text/css\" media=\"screen\">
	div#printme {
		display: none;
		}
	</style>
	<style type=\"text/css\" media=\"print\">
	img {
		padding: 0;
		border: 0px;
		height: 10;
		}
	
	td  {
		font-size: 10;
		}
	div#noprint {
		display: none;
		}
	a#noprint2 {
		display: none;
		}

	@media print {
		th { font-family: arial; font-size: 8pt; }
		td { font-family: arial; font-size: 8pt; }
		tr.noprint { display: table-row; visibility: hidden; width: 1px; height: 1px; }
		td.noprint { display: table-cell; visibility: hidden; width: 1px; height: 1px; }
		}
	</style>";
fd_navs_header();
	
	$query_search_add=query_search_add_text();
	$query="select * from gcrfilog where jobinfo_id = '$global_jobinfo->jobinfo_id' and section = '$current_gcrfilog_section' $query_search_add order by gcrfi_num + 0 desc, gcrfi_num desc";
	if ($filter_mode!="") {
		session_register('gcrfi_filter_mode');
		if ($filter_mode=="All") $gcrfi_filter_mode="";
		else $gcrfi_filter_mode=$filter_mode;
		}
	
	if ($filter_mode=="") {
		if ($gcrfi_filter_mode!="") $filter_mode=$gcrfi_filter_mode;
		}
	
	if ($filter_mode=='Open') 
		$query="select * from gcrfilog where jobinfo_id = '$global_jobinfo->jobinfo_id' and section = '$current_gcrfilog_section' and pm_complete_date = '0000-00-00' $query_search_add order by gcrfi_num + 0 desc, gcrfi_num desc";
	if ($filter_mode=='Pending') 
		$query="select * from gcrfilog where jobinfo_id = '$global_jobinfo->jobinfo_id' and section = '$current_gcrfilog_section' and reply_date = '0000-00-00' $query_search_add order by gcrfi_num + 0 desc, gcrfi_num desc";
	if ($filter_mode=='Overdue') 
		$query="select * from gcrfilog where jobinfo_id = '$global_jobinfo->jobinfo_id' and section = '$current_gcrfilog_section' and reply_date = '0000-00-00' and response_needed_date < now() $query_search_add order by gcrfi_num + 0 desc, gcrfi_num desc";

	if ($filter_mode=='Detailing Incomplete') 
		$query="select * from gcrfilog where jobinfo_id = '$global_jobinfo->jobinfo_id' and section = '$current_gcrfilog_section' and det_complete_date = '0000-00-00' $query_search_add order by gcrfi_num + 0 desc, gcrfi_num desc";
	if ($filter_mode=='Cad Not Updated') 
		$query="select * from gcrfilog where jobinfo_id = '$global_jobinfo->jobinfo_id' and section = '$current_rfilog_section' and ( det_cfu_ref_files = '' or det_cfu_pp_files = '' or det_cfu_duct_files = '' ) $query_search_add order by gcrfi_num + 0 desc, gcrfi_num desc";
	if ($filter_mode=='Detailing Required') {
		$query="select * from gcrfilog 
			left join documents on (documents.app_record_id = gcrfilog.gcrfi_id and doc_type = 'gcrfi' )
			left join rfi_record_dwg_posting on (documents.doc_id = rfi_record_dwg_posting.doc_id )
			
			where gcrfilog.jobinfo_id = '$global_jobinfo->jobinfo_id' and gcrfilog.section = '$current_rfilog_section' and 
			( 
			arch = '' or struct = '' or mech = '' or other = '' or
			arch is NULL or struct is NULL or mech is NULL or other is NULL or 
			det_cfu_ref_files = '' or det_cfu_pp_files = '' or det_cfu_duct_files = '' or 
			det_complete_date = '0000-00-00'
			) $query_search_add group by gcrfi_num order by gcrfi_num + 0 desc, gcrfi_num desc";
			
		}
	
	//echo "<hr>$query<hr>";
	// list all the record sets, and do this once for each
	//tabledump("select * from front_desk_record_sets where jobinfo_id = '$global_jobinfo->jobinfo_id'");
	$rs_options="";
	$rsres=@mysql_query("select * from front_desk_record_sets where jobinfo_id = '$global_jobinfo->jobinfo_id' order by record_set_id");
	while ($rsrow=@mysql_fetch_object($rsres)) {
		if ($filter_mode=="Postings Incomplete - $rsrow->record_set_name") {
			$query="select * from gcrfilog 
			left join documents on (documents.app_record_id = gcrfilog.gcrfi_id and doc_type = 'gcrfi' )
			left join rfi_record_dwg_posting on (documents.doc_id = rfi_record_dwg_posting.doc_id and record_set_id = '$rsrow->record_set_id' )

			where gcrfilog.jobinfo_id = '$global_jobinfo->jobinfo_id' and gcrfilog.section = '$current_gcrfilog_section' and 
			( 
			arch = '' or struct = '' or mech = '' or other = '' or
			arch is NULL or struct is NULL or mech is NULL or other is NULL 
			
			) $query_search_add group by gcrfi_num order by gcrfi_num desc";
			$fselect="selected";
			} else {
				$fselect="";
			}
		$rs_options=$rs_options . "<option $fselect>Postings Incomplete - $rsrow->record_set_name</option>";
		}
	
	//echo "<hr>$query<hr>";
	$res=@mysql_query($query);
	// Paging stuff..
	include("fd_log_paging.phtml");
	echo "
	<table id='sub_application_main_table' border=1 class=\"printmesmall\" style=\"border: 1px solid grey;\" cellspacing=0 cellpadding=5>
	<thead>
	<tr><td colspan=18>";
		search_div();
		echo "<center>
		<b><font size=+2>GC RFI Log</font><br>Job $global_jobinfo->contract_num:&nbsp;$global_jobinfo->job_name<br>$today</b>

		<div id=\"noprint\">
		<a href=$pagename?mode=gcrfi_edit&jobinfo_id=$global_jobinfo->jobinfo_id><font color=blue>New GC RFI</font></a><p>";
		if ($filter_mode=="") $filter_mode="All";
		echo "
		<form name=filter_select method=post action=\"$pagename\">
		<input type=hidden name=mode value=\"$mode\">
		<select name=filter_mode onchange=submit();>
		<option>All</option>
		<option value=\"Open\" "; if ($filter_mode=="Open") echo "selected"; echo ">UMC Open</option>
		<option ";if($filter_mode=="Pending") echo "selected"; echo ">Pending</option>
		<option ";if($filter_mode=="Overdue") echo "selected"; echo ">Overdue</option>
		<option ";if($filter_mode=="Detailing Incomplete") echo "selected"; echo ">Detailing Incomplete</option>
		<option ";if($filter_mode=="Cad Not Updated") echo "selected"; echo ">Cad Not Updated</option>
		$rs_options
		<option ";if($filter_mode=="Detailing Required") echo "selected"; echo ">Detailing Required</option>
		</select>&nbsp;$current_query_len&nbsp;items
		$search_form_insert
		</form>
		$page_page_insert
		</div>
		<div id=printme>
		Showing: $filter_mode
		</div></center>
	</td></tr>
	
	<tr class=floatheader bgcolor=\"$fd_color_4\"><td class=noprint>
		&nbsp;
	</td><td>
		<b>Init Review</b>
	</td><form name=gc_filter method=post action=\"$pagename\"><td>
		<b>GC #</b>
		<input type=hidden name=mode value=main>
		";
		//if ($global_jobinfo_id==3385) echo "<input title=\"Type something here to filter on just this field\" type=input name=gc_search value=\"$gc_search\" size=5 onchange=submit()>";
		echo "
	</td></form><td>
		<b>UMC #</b>
	</td><td>
		<b>Sub #</b>
	</td><td>
		<b>Bldg</b>
	</td><td>
		<b>Floor</b>
	</td><td>
		<b>Subject</b>
	</td><td>
		<b>Date Sent</b>
	</td><td align=center>
		<b>Response<br>Required</b>
	</td><td align=center>
		<b>Response<br>Date</b>
	</td><td>
		<b>Days Late</b>
	</td><td>
		<b>Created By</b>
	</td><td>
		<b>Det Complete</b>
	</td><td>
		<b>PM Complete</b>
	</td><td>
		<b>Cost/Sched Impact</b>";
	if ($write) {
		echo "
	</td><td>
		<b>Viewed by</b>
	</td><td>
		<b>Notes</b>
		";
		}
	echo "
	</td></tr>
	</thead>
	<tbody class=floatheader>
	";

	while($row=@mysql_fetch_object($res)) {
		$reply_date=invali_date($row->reply_date);
		$temp_doc_id=fd_get_doc_id($row->gcrfi_id);
		$viewers_list_res=@mysql_query("select login_name,display_name from documents_review_history right join contacts on (documents_review_history.contacts_id = contacts.contacts_id) where doc_id = '$temp_doc_id' group by documents_review_history.contacts_id");
		$viewers_list="";
		$vl_sep="";
		while ($vl_user=mysql_fetch_object($viewers_list_res)) {
			$viewers_list=$viewers_list . $vl_sep . "$vl_user->login_name";
			$vl_sep="<br>";
			}
		if ($reply_date=="") {
			$seen_it=getoneb("select * from documents_review_history where doc_id = '$temp_doc_id' and contacts_id = '$global_user_id' limit 1");
		} else {
			$tmp_rp_date=vali_date($reply_date);	
			$seen_it=getoneb("select * from documents_review_history where doc_id = '$temp_doc_id' and contacts_id = '$global_user_id' and review_time > '$tmp_rp_date' limit 1");
		}
		$row_bg_color="#ffffff";
		if (!($seen_it)) $row_bg_color="#ffffaa";
		if ($row->gcrfi_num=="") $row->gcrfi_num="&lt;?&gt;";
		$company_info=getoneb("select * from contacts where contacts_id = '$row->company_id'");
		$site_info=getoneb("select * from contacts where contacts_id = '$row->site_id'");
		$creator_info=getoneb("select * from contacts where contacts_id = '$row->creator'");
		$attention_info=getoneb("select * from contacts where contacts_id = '$row->attention_to_id'");
		$doc_info=getoneb("select * from documents where jobinfo_id = '$row->jobinfo_id' and doc_type = 'gcrfi' and app_record_id = '$row->gcrfi_id' and section = '$row->section' limit 1");
		$row->det_complete_date=invali_date($row->det_complete_date);
		$row->pm_complete_date=invali_date($row->pm_complete_date);
		$row->sent_to_date=invali_date($row->sent_to_date,'/');
		if ($row->sent_to_date=="") $row->sent_to_date='&nbsp;';
		
		if ($reply_date=="") $reply_date=date('Y-m-d');
		else $reply_date=vali_date($reply_date);
		
		$daysqry="select datediff('$reply_date','$row->response_needed_date') as overdue";
		$days=getoneb($daysqry);
		
		$umc_rfi_text=fd_text_doc_list($doc_info->doc_id,'rfi');
		
		$row->response_needed_date=invali_date($row->response_needed_date,'/');
		$row->reply_date=invali_date($row->reply_date);
		if ($row->reply_date=="") $row->reply_date="&nbsp;";
		if ($row->response_needed_date=="") $row->response_needed_date="&nbsp;";
		if ($days->overdue=="") $days->overdue="&nbsp;";
		if ($row->gc_rfi_num=="") $row->gc_rfi_num="&nbsp;";
		if ($row->sub_rfi_num=="") $row->sub_rfi_num="&nbsp;";
		if ($row->key_description=="") $row->key_description="&nbsp;";
		$file_paperclip=webfile_paperclip_view($row->gcrfi_image_id,"&nbsp;");
		$file_batch=batch_this_document($temp_doc_id);
		//$file_paperclip=webfile_paperclip_download($row->gcrfi_image_id,"&nbsp;");
		//if ($row->initial_review_done!='Y') $row_bg_color="#ffff66";
		if ($row->pm_complete_date!="") $row_bg_color=$fd_color_2;
		$creator_info->display_name=ereg_replace(" ","&nbsp;",$creator_info->display_name);
		echo "<tr valign=top bgcolor=\"$row_bg_color\"><td class=noprint>
				";
				if ($file_paperclip!="&nbsp;") {
					if ($write) {
						echo "<table border=0 cellspacing=0 cellpadding=1><tr><td>$file_paperclip</td><td>&nbsp;&nbsp;&nbsp;</td><td>$file_batch</td></tr></table>";
						} else {
							echo "$file_paperclip";
						}
					}
				echo "&nbsp;
			</td><td>
				$row->initial_review_done&nbsp;
			</td><td>";
				if (slow_connection()) {
					$target="target=fd_gcrfi_log";
					} else {
					$target="";
					}
				if ($write) {
					echo "<a $target href=$pagename?mode=gcrfi_edit&gcrfi_id=$row->gcrfi_id><font color=blue>$row->gcrfi_num</font></a>";
					} else {
					//echo "$row->gcrfi_num";
					echo "<a $target href=$pagename?mode=gcrfi_view&gcrfi_id=$row->gcrfi_id><font color=blue>$row->gcrfi_num</font></a>";
					}
			echo "&nbsp;
			</td><td>
				$umc_rfi_text&nbsp;
			</td><td>
				$row->sub_rfi_num&nbsp;
			</td><td>
				$row->bldg&nbsp;
			</td><td>
				$row->floor&nbsp;
			</td><td>
				$row->key_description&nbsp;
			</td><td>
				$row->sent_to_date&nbsp;
			</td><td>
				$row->response_needed_date&nbsp;
			</td><td>
				$row->reply_date&nbsp;
			</td><td>
				$days->overdue&nbsp;
			</td><td>
				$creator_info->display_name&nbsp;
			</td><td>
				$row->det_complete_date&nbsp;
			</td><td>
				$row->pm_complete_date&nbsp;
			</td><td>
				$row->has_cost&nbsp;";
			if ($write) {
				echo "
				</td><td>
					$viewers_list&nbsp;
				</td><td>";
				$row->pm_notes=ereg_replace("\r\n","<p>",substr("$row->pm_notes",0,500));
					echo "$row->pm_notes&nbsp;";
					
				}
			echo "
			</td></tr>
		
		";
		}
	echo "<tr><td colspan=15 height=100%></td></tr></tbody></table>";
	}
//echo "</center></body>";

fd_navs_footer();
?>
