<?
if ($files_id=="") die("no file id.. nothing to do");
else $files_id=addslashes($files_id);
$file_info=getone("select * from webfile_files where files_id = '$files_id'");
$older_version=getoneb("select * from webfile_files where file_group_id = 0 and replaced_by = '$file_info->files_id'");
$download_link=webfile_file_download($file_info->files_id);
$full_preview_link=webfile_image_show($file_info->files_id);
if ($onchange!="") $onchange_decode=base64_decode($onchange);

if ($launching_application_name!="") {
	$launching_application_name=addslashes($launching_application_name);
	$appname_javascript="\"$launching_application_name\"";
	//echo "<script>alert('got the name $launching_application_name into php');</script>";
	} else {
	$appname_javascript="opener.document.${field}_webfile_application_name.value";
	if ($no_name_detect!=1) {
		echo "<script>
			document.location=document.location + '&launching_application_name=' + $appname_javascript + '&no_name_detect=1';
			</script>
			";
		} else {
			$launching_application_name='null';
		}
	}


require('return_to_handler.phtml');
echo "<p align=right>$done_link</p>";

$aurl="$pagename?mode=webfile_permissions_toggle&files_id=$file_info->files_id&launching_application_name=$launching_application_name&return_to=$return_to_this_page";

$imgurl=webfile_medium_image_icon($file_info->files_id);
$viewurl=webfile_view_link($file_info->files_id);
$random=rand();
echo "
<script>

function view_file(url) {
	open(url,'$random','width=900,height=700,resizable=yes,scrollbars=yes,');
	}
function apply_changes() {
	$onchange_decode;
	document.location=\"$return_to_decode\";
	}
</script>

";

//if (($file_info->owner==$global_user_id)||($adminuser)) {
if (($file_info->owner==$global_user_id)||($writable)) {
	echo "
	<script>
	function webdelfile(files_id) {
		if (confirm(\"Permenantly delete file from database?\")) {
			open('$pagename?mode=delete_file_popup&launching_application_name=$launching_application_name&files_id=' + files_id,'webfile_del_pu','width=20,height=20');
			}
		}
	</script>
	";
	}

//$bgcolor="#8caede";
$bgcolor=$umc_standard_blue;
$bluebgcolor=$bgcolor;
$p_version_rows="";
if ($file_info->file_group_id==0) {
	$newer_version=getoneb("select * from webfile_files where files_id = '$file_info->replaced_by'");
	
	$bgcolor="#888888";

	echo "<table border=1 cellpadding=2 cellspacing=0 width=100%>
	<tr bgcolor=\"$bluebgcolor\"><td colspan=4 align=center><b>Newer versions</b></td></tr>";
	while ($newer_version) {
		$image_url=webfile_tiny_image_icon($newer_version->files_id);
		$tools_link="$pagename?mode=webfile_file_tools&files_id=$newer_version->files_id&launching_application_name=$launching_application_name&return_to=$return_to_this_page";
		$p_version_rows="
		<tr><td>
			<table border=1 style=\"border:outset\"cellspacing=0 cellpadding=0><tr><td><a href=\"$tools_link\"><img src=$image_url border=0></a></td></tr></table>
		</td><td>
			$newer_version->file_name&nbsp;
		</td><td>
			$newer_version->upload_date&nbsp;
		</td><td>
			$newer_version->file_size&nbsp;
		</td></tr>
		" . $p_version_rows;
		$newer_version=getoneb("select * from webfile_files where files_id = '$newer_version->replaced_by'");
		}
	echo "$p_version_rows</table>";
	}
$nice_file_name=substr($file_info->file_name,0,15);
echo"	
<table border=1 cellspacing=0 cellpadding=3 width=100%>
<form enctype=\"multipart/form-data\" name=file_info method=post action=$pagename>
<input type=hidden name=files_id value=\"$file_info->files_id\">
<input type=hidden name=return_to value=\"$return_to_this_page\">
<input type=hidden name=mode value=webfile_file_update>
<input type=hidden name=launching_application_name value=\"$launching_application_name\">
<input type=hidden name=onchange value=\"$onchange\">
<input type=hidden name=\"MAX_FILE_SIZE\" value=\"2000000000\">

<tr bgcolor='$bgcolor'><td rowspan=2>
	<img style=\"max-width: 150;\"src=$imgurl>
</td><td colspan=2 align=center>
	<b><i>$nice_file_name</i></b>
</td></tr>


<tr><td colspan=2 valign=top bgcolor=#eeeeee>
<table border=0 cellspacing=0 cellpadding=1>
<tr><td>
	<b>Size:</b>
<td><td width=100%>
	$file_info->file_size
<td><td>
	<a href=\"javascript:view_file('$viewurl')\"><font color=blue>View&nbsp;File</font></a>
</td></tr>
	<tr><td>
	<b>Type:</b>
<td><td>
	<font size=-1>$file_info->mime_type</font>
<td><td>
	<a href=$download_link><font color=blue>Save&nbsp;File</font></a><br>
</td></tr>
	<tr><td>
	<b>Date:</b>
<td><td>
	";$uldate=invali_date($file_info->upload_date);echo"
	$uldate
<td><td>
	<a href=$full_preview_link><font color=blue>Large&nbsp;Preview</font></a>
</td></tr>
	";
if ($file_info->page_count > 0) {
	$pctext="<b>Pages:</b>";
	$pccount=$file_info->page_count;
	} else {
	$pctext="";
	$pccount="";
	}

echo"
<tr><td>
	$pctext
<td><td>
	$pccount
<td><td>";
	if (($writable||($file_info->owner==$global_user_id)) && (!($older_version))) 
	echo "<a href=javascript:webdelfile($file_info->files_id)><font color=blue>Delete</font></a>";
	else echo "&nbsp;";
	echo"
</td></tr>

</table>
</td></tr>

";

if ($writable) {
	echo "
	<tr><td>
		<b>Description</b>
	</td><td colspan=2>
		<input type=text size=30 name=description value=\"$file_info->description\" onchange=submit();>
	</td></tr>
	
	<tr><td>
		<b>New Version</b>
	</td><td colspan=2>
		<input type=file size=30 name=upload_file_1 value=\"Select\" onchange=submit();>
	</td></tr>
	";
	}


if (($file_info->owner==$global_user_id)||($adminuser)) {

echo "
	<tr><td>
		<b>Permissions</b>
	</td><td align=center>
		<b>Read</b>
	</td><td align=center>
		<b>Write</b>
	</td></tr>
	
	<tr><td>
		<b>Public</b>
	</td><td align=center>
		<a href=\"$aurl&permission=access_public\"><font color=blue>
		$file_info->access_public
		</font></a>
	</td><td align=center>
		<a href=\"$aurl&permission=write_public\"><font color=blue>
		$file_info->write_public
		</font></a>
	</td></tr>
	
	<tr><td>
		<b>UMC Network</b>
	</td><td align=center>
		<a href=\"$aurl&permission=access_intranet\"><font color=blue>
		$file_info->access_intranet
		</font></a>
	</td><td align=center>
		<a href=\"$aurl&permission=write_intranet\"><font color=blue>
		$file_info->write_intranet
		</font></a>
	</td></tr>
	
	<tr><td>
		<b>Users</b>
	</td><td align=center>
		<a href=\"$aurl&permission=access_any_user\"><font color=blue>
		$file_info->access_any_user
		</font></a>
	</td><td align=center>
		<a href=\"$aurl&permission=write_any_user\"><font color=blue>
		$file_info->write_any_user
		</font></a>
	</td></tr>
	
	<tr><td>
		<b>Employees</b>
	</td><td align=center>
		<a href=\"$aurl&permission=access_employees\"><font color=blue>
		$file_info->access_employees
		</font></a>
	</td><td align=center>
		<a href=\"$aurl&permission=write_employees\"><font color=blue>
		$file_info->write_employees
		</font></a>
	</td></tr>
	";
	}		
		
//if ($readable) echo "READ";
//if ($writable) echo "WRITE";

echo "</table></form>";
	
if ($older_version) {
	echo "<table border=1 cellpadding=2 cellspacing=0 width=100%>
	<tr bgcolor=#eeeeee><td colspan=4 align=center><b>Older versions</b></td></tr>";
	while ($older_version) {
		$image_url=webfile_tiny_image_icon($older_version->files_id);
		$tools_link="$pagename?mode=webfile_file_tools&files_id=$older_version->files_id&launching_application_name=$launching_application_name&return_to=$return_to_this_page";
		echo "
		<tr><td>
			<table border=1 style=\"border:outset\"cellspacing=0 cellpadding=0><tr><td><a href=\"$tools_link\"><img src=$image_url border=0></a></td></tr></table>
		</td><td>
			$older_version->file_name&nbsp;
		</td><td>
			$older_version->upload_date&nbsp;
		</td><td>
			$older_version->file_size&nbsp;
		</td></tr>
		";
		$older_version=getoneb("select * from webfile_files where file_group_id = 0 and replaced_by = '$older_version->files_id'");
		}
	echo "</table>";
	}
?>
