<?
if ($oiclog_id=="") die("Application error!");
$oiclog_id=addslashes($oiclog_id);
$oiclog_info=getoneb("select * from oiclog where oiclog_id = '$oiclog_id'");
$oiclog_doc_info=getoneb("select * from documents where doc_type = 'oiclog' and app_record_id = '$oiclog_info->oiclog_id'");

if ($selected_section!="") $selected_section=addslashes($selected_section);
ajax_load();
if ($selected_section!='default') $selected_section_text=$selected_section;
echo "
<script>
function toggle_selection(oiclog_doc_id,cnstdwglog_doc_id) {
	element_name=oiclog_doc_id + '-' + cnstdwglog_doc_id;
	//toggle_div=document.getElementById(element_name);
	ajaxManager('load_page','$pagename?mode=cnstdwglog_toggle_selection&oiclog_doc_id=' + oiclog_doc_id + '&cnstdwglog_doc_id=' + cnstdwglog_doc_id,element_name);
	//alert(element_name);
	}

function ajax_trigger() {
	opener.document.reload_cnstdwglog_link=1;
	}

</script>

<style>
	td.u { 
		border-bottom: 1px solid black;
		cursor: pointer;
		cursor: hand;
		}
</style>
                                    


<div onclick=javascript:self.close(); style=\"cursor: pointer; cursor: hand; position: fixed; right: 10px; top: 20px; border: 2px solid black; background: $fd_color_3; padding: 3px;\">Done</div>
<div style=\"width: 100%; border: 1px solid black; background: $fd_color_4\"><center><b>$selected_section_text Construction Drawings</b></center></div>";


// First we see if we have records tieing this to a section already... 
$cnstdwglog_section_info=getoneb("select * from oiclog_purgatory left join documents on (cnstdwglog_doc_id = doc_id) where oiclog_doc_id = '$oiclog_doc_info->doc_id' group by documents.section");
// Next if we're not already tied to a section, we check to see if maybe there's only 1 section, and
// if so, we select that one.. 
if (!($cnstdwglog_section_info)) {
	$cnstdwglog_section_info=getoneb("select * from cnstdwglog_sections where jobinfo_id = '$oiclog_doc_info->jobinfo_id' and active = 'Y'");
	}
// If we still don't have section info, then check to see if they've selected one with the 
// drop box, and if so, we use that from here on out.
if (!($cnstdwglog_section_info)) {
	if ($selected_section!="") {
		//echo "get it";
		//echo "<hr>select * from cnstdwglog_sections where jobinfo_id = '$oiclog_doc_info->jobinfo_id' and section = '$selected_section'<hr>";
		$cnstdwglog_section_info=getoneb("select * from cnstdwglog_sections where jobinfo_id = '$oiclog_doc_info->jobinfo_id' and section = '$selected_section'");
		}
	}
// Still no section info? Then it's time for us to quit.. we don't want to continue without the
// documents coming from a specific section of the construction drawing log.. 
//if (!($cnstdwglog_section_info)) exit('nothing');

if (!($cnstdwglog_section_info)) die('Unrecoverable application error!'); 

//tabledump("select * from cnstdwglog where jobinfo_id = '$oiclog_doc_info->jobinfo_id' and section = '$cnstdwglog_section_info->section' right join documents on (documents.doc_type = 'cnstdwglog' and documents.app_id = cnstdwglog.cnstdwglog_id) order by cnstdwglog.drawing_type,documents.sort_rank,documents.doc_id,cnstdwglog.drawing_num");
$res=@mysql_query("select * from cnstdwglog 
right join documents on (documents.doc_type = 'cnstdwglog' and documents.app_record_id = cnstdwglog.cnstdwglog_id) 
where cnstdwglog.jobinfo_id = '$oiclog_doc_info->jobinfo_id' and cnstdwglog.section = '$cnstdwglog_section_info->section' 
order by cnstdwglog.drawing_type,documents.sort_rank,documents.doc_id,cnstdwglog.drawing_num");
while ($row=@mysql_fetch_object($res)) {
	$selected=getoneb("select * from oiclog_purgatory where oiclog_doc_id = '$oiclog_doc_info->doc_id' and cnstdwglog_doc_id = '$row->doc_id' limit 1");
	$element_onclick="javascript:toggle_selection($oiclog_doc_info->doc_id,$row->doc_id)";
	
	//echo "insert into oiclog_purgatory set oiclog_doc_id = '$oiclog_doc_info->doc_id', cnstdwglog_doc_id = '$row->doc_id', description = 'Automated test for development'<hr>";
	//@mysql_query("insert into oiclog_purgatory set oiclog_doc_id = '$oiclog_doc_info->doc_id', cnstdwglog_doc_id = '$row->doc_id', description = 'Automated test for development'");
	if ($selected) 	echo "<div style=\"cursor: pointer; cursor: hand;\" id=\"$oiclog_doc_info->doc_id-$row->doc_id\" onclick=\"$element_onclick\"><div style=\"width: 100%; border: 1px solid black; background: $fd_color_4;\">$row->drawing_type - $row->drawing_num - $row->description</div></div>";
	else echo "<div style=\"cursor: pointer; cursor: hand;\" id=\"$oiclog_doc_info->doc_id-$row->doc_id\" onclick=\"$element_onclick\"><div style=\"width: 100%; border: 1px solid white;\">$row->drawing_type - $row->drawing_num - $row->description</div></div>";
	}
?>
