<?
$purgatory_id=addslashes($purgatory_id);
$purgatory_info=getoneb("select * from oiclog_purgatory where purgatory_id = '$purgatory_id'");

if (!($purgatory_info)) die("Application error (purgatory_info)! Please contact your system administrator.");
$oiclog_doc_info=getoneb("select * from documents where doc_id = '$purgatory_info->oiclog_doc_id'");
$oiclog_info=getoneb("select * from oiclog where oiclog_id = '$oiclog_doc_info->app_record_id'");
$cnstdwglog_doc_info=getoneb("select * from documents where doc_id = '$purgatory_info->cnstdwglog_doc_id'");
$cnstdwglog_info=getoneb("select * from cnstdwglog where cnstdwglog_id = '$cnstdwglog_doc_info->app_record_id'");
if (!($oiclog_info)) die("Application error (oiclog_info)! Please contact your system administrator.");
if (!($cnstdwglog_info)) die("Application error (cnstdwglog_info)! Please contact your system administrator.");

$query="select * from cnstdwglog_files 
	right join cnstdwglog_issuances on (cnstdwglog_files.issuance_id = cnstdwglog_issuances.issuance_id )
	where cnstdwglog_id = '$cnstdwglog_info->cnstdwglog_id' and issuance_type like 'Constructio%'
	order by issuance_type,sort_priority desc,cnstdwglog_issuances.issuance_id desc,name desc";

//tabledump($query);
$construction_issuances_res=@mysql_query($query);
$full_sheet_status_list="";

echo "
<script>

function check_publish_method() {
	supp=document.getElementById('supp_desc');
	radio_value=validate_radio_button(document.post_file.publish_method);
	if (radio_value=='supplimental') supp.style.display='inline';
	else supp.style.display='none';
	}

function validate_radio_button(button) {
	var cnt = -1;
	for (var i=button.length-1; i > -1; i--) {
		if (button[i].checked) {cnt = i; i = -1;}
		}
	if (cnt > -1) return button[cnt].value;
	else return null;
	}

function validate_select_box(obj) {
	return(obj.options[obj.selectedIndex].value);
	}
	
function check_and_submit() {
	radio_value=validate_radio_button(document.post_file.publish_method);
	select_value=validate_select_box(document.getElementById('issuance_select'));
	
	if (radio_value==null) {
		alert('You need to select full sheet or supplimental');
		return 0;
		}
	if (radio_value=='full_sheet') {
		attachment_status=document.getElementById('as - ' + select_value).value;
		if (attachment_status=='Y') {
			if(!(confirm('Are you sure? There is already a full sheet attached at this location! This action will replace it!'))) return 0;
			}
		}
	
	
	document.post_file.submit();
	
	//alert('confirmed');
	//alert(document.getElementById('');
	//isobj=document.getElementById('issuance_select');
	//alert(isobj.value);
	}

</script>


<form name=post_file method=get action=$pagename>
<input type=hidden name=mode value=cnstdwglog_linker_post_file_submit>
<input type=hidden name=purgatory_id value=\"$purgatory_info->purgatory_id\">

<table border=1 cellspacing=0 cellpadding=4 width=100%>
<tr><td colspan=2 bgcolor=$fd_color_4 align=center>
	<b>Publish to construction drawing log</b>
</td></tr>

<tr><td colspan=2 align=center bgcolor=$fd_color_1>
	<b>Source</b>
</td></tr>

<tr><td colspan=2>
	<font size=-1>Oiclog :: $oiclog_doc_info->section :: $oiclog_doc_info->app_reference :: $oiclog_doc_info->description</font>
</td></tr>

<tr><td colspan=2 align=center bgcolor=$fd_color_1>
	<b>Target</b>
</td></tr>

<tr><td colspan=2>
	<font size=-1>Cnstdwglog :: $cnstdwglog_doc_info->section :: $cnstdwglog_doc_info->app_reference :: $cnstdwglog_doc_info->description</font>
</td></tr>

<tr><td>
	Issuance
</td><td>
	<select id=\"issuance_select\" name=issuance>";

while ($row=@mysql_fetch_object($construction_issuances_res)) { 
	if ($row->name==$oiclog_info->oic_number) $selected="selected"; 
	else $selected="";
	$file_info=getoneb("select * from cnstdwglog_files where issuance_id = '$row->issuance_id' and cnstdwglog_id = '$cnstdwglog_info->cnstdwglog_id'");
	if (!($file_info)) die("Application error! Please contact your system administrator (file info)");
	$attached_full_sheets=getoneb("select * from webfile_groups_and_files where file_group_id = '$file_info->file_group_id' limit 1");
	if ($attached_full_sheets) $atfs='Y';
	else $atfs='N';
	$full_sheet_status_list=$full_sheet_status_list . "<input type=hidden name=name_$row->issuance_id id=\"as - $row->issuance_id\" value='$atfs'>";
	echo "<option value=\"$row->issuance_id\" $selected>$row->name</option>";
	}
echo "</select>
$full_sheet_status_list

</td></tr>

<tr><td valign=top width=150px>
	Type
</td><td>
	<input onchange=\"check_publish_method()\" type=radio name=publish_method value=\"full_sheet\">
	Full&nbsp;Sheet&nbsp;Update<br>
	<input onchange=\"check_publish_method()\" type=radio name=publish_method value=\"supplimental\">
	Supplimental&nbsp;Update<br>
	<div id=supp_desc style=\"display: none;\">Description <input type=text name=supplimental_description></div>
</td></tr>


<tr><td colspan=2 align=center valign=bottom height=80px;>
	<input type=button onclick=\"check_and_submit()\" value=\"Submit\">
</td></tr>
</form>";




?>
