<?
include("../webfile$devel/storage_settings.cfg");
include("../webfile$devel/local.inc");
//include("../cnstdwglog$devel/check_addenda.inc");
include("../cnstdwglog$devel/exported_functions.inc");

$purgatory_id=addslashes($purgatory_id);
$purgatory_info=getoneb("select * from oiclog_purgatory where purgatory_id = '$purgatory_id'");

if (!($purgatory_info)) die("Application error (purgatory_info)! Please contact your system administrator.");
$oiclog_doc_info=getoneb("select * from documents where doc_id = '$purgatory_info->oiclog_doc_id'");
$oiclog_info=getoneb("select * from oiclog where oiclog_id = '$oiclog_doc_info->app_record_id'");
$cnstdwglog_doc_info=getoneb("select * from documents where doc_id = '$purgatory_info->cnstdwglog_doc_id'");
$cnstdwglog_info=getoneb("select * from cnstdwglog where cnstdwglog_id = '$cnstdwglog_doc_info->app_record_id'");
if (!($oiclog_info)) die("Application error (oiclog_info)! Please contact your system administrator.");
if (!($cnstdwglog_info)) die("Application error (cnstdwglog_info)! Please contact your system administrator.");
$issuance_info=getoneb("select * from cnstdwglog_issuances where issuance_id = '" . addslashes($issuance) . "'");
if (!($issuance_info)) die("Application error loading issuance information! Please contact your system administrator.");
$files_info=getoneb("select * from cnstdwglog_files where issuance_id = '$issuance_info->issuance_id' and cnstdwglog_id = '$cnstdwglog_info->cnstdwglog_id'");
if (!($files_info)) die("Application error loading cnstdwglog file information! Please contact your system administrator.");
$file_group_info=getoneb("select * from webfile_groups where file_group_id = '$files_info->file_group_id'");


/*$query="select * from cnstdwglog_files 
	right join cnstdwglog_issuances on (cnstdwglog_files.issuance_id = cnstdwglog_issuances.issuance_id )
	where cnstdwglog_id = '$cnstdwglog_info->cnstdwglog_id' and issuance_type like 'Constructio%'
	order by issuance_type,sort_priority desc,cnstdwglog_issuances.issuance_id desc,name desc";
*/
//$construction_issuances_res=@mysql_query($query);
//$full_sheet_status_list="";


if ($publish_method=="supplimental") {
	$new_file_group_id=copy_webfile_group($purgatory_info->attached_group_id,"cnstdwglog","Published from OIC Log by $global_user->display_name");
	$supplimental_description=addslashes($supplimental_description);
	//echo "sup homey - $purgatory_info->attached_group_id -> $new_file_group_id";
	@mysql_query("insert into cnstdwglog_addenda set files_id = '$files_info->files_id', description = '$supplimental_description',file_groups_id = '$new_file_group_id', required_in_this_issuance = 'Y'");
	$insert_id=@mysql_insert_id();
	@mysql_query("update cnstdwglog_addenda set parent_addenda_id = '$insert_id' where addenda_id = '$insert_id'");
	check_addenda($cnstdwglog_info->cnstdwglog_id);
	@mysql_query("update oiclog_purgatory set posted_to_cnstdwglog = 'Y' where purgatory_id = '$purgatory_info->purgatory_id'");
	include("header.phtml");
	echo "
	<script>
	opener.document.reload_cnstdwglog_link=1;
	self.close();
	</script>
	";
	exit;
	}



if ($publish_method=="full_sheet") {
	//if ($files_info->file_group_id<1) {
	if (!($file_group_info)) {
		// Create new webfile group
		$new_group=create_file_group("Published from OIC log","cnstdwglog");
		@mysql_query("update cnstdwglog_files set file_group_id = '$new_group->file_group_id' where files_id = '$files_info->files_id'");
		$files_info=getoneb("select * from cnstdwglog_files where issuance_id = '$issuance_info->issuance_id' and cnstdwglog_id = '$cnstdwglog_info->cnstdwglog_id'");
		}
	$attached_full_sheet=getoneb("select * from webfile_groups_and_files where file_group_id = '$files_info->file_group_id'");
	$purgatory_attached_full_sheet=getoneb("select * from webfile_groups_and_files where file_group_id = '$purgatory_info->attached_group_id'");
	
	if ($attached_full_sheet && $purgatory_attached_full_sheet) {
		// update existing record in webfile group.
		// Note, not plural, one webfile_file source over the top of one webfile_file target
		copy_webfile_file($purgatory_attached_full_sheet->files_id,$attached_full_sheet->files_id,"cnstdwglog");
		} else {
		//insert new record into webfile group. 
		//$attached_full_sheet=getoneb("select * from webfile_groups_and_files where file_group_id = '$files_info->file_group_id' limit 1");
		//echo "copy webfile group....$purgatory_info->attached_group_id / $files_info->file_group_id<hr>";
		copy_webfile_group($purgatory_info->attached_group_id,"cnstdwglog","Published from OIC Log by $global_user->display_name",$files_info->file_group_id);
		}
	@mysql_query("update oiclog_purgatory set posted_to_cnstdwglog = 'Y' where purgatory_id = '$purgatory_info->purgatory_id'");
	include("header.phtml");
	echo "
	<script>
	opener.document.reload_cnstdwglog_link=1;
	self.close();
	</script>
	";
	exit;
	}





//echo "hi";


die("Application error! Nothing happened, and I really shouldn't have gotten here. Please contact your system administrator..");







?>
