<?

$linker_option_valid=TRUE;

//if ($oiclog_id=="") die("Application error!");
$oiclog_id=addslashes($oiclog_id);
$oiclog_info=getoneb("select * from oiclog where oiclog_id = '$oiclog_id'");
$oiclog_doc_info=getoneb("select * from documents where doc_type = 'oiclog' and app_record_id = '$oiclog_info->oiclog_id'");



if ($selected_section!="") $selected_section=addslashes($selected_section);


// First we see if we have records tieing this to a section already... 
$cnstdwglog_section_info=getoneb("select * from oiclog_purgatory left join documents on (cnstdwglog_doc_id = doc_id) where oiclog_doc_id = '$oiclog_doc_info->doc_id' group by documents.section");
// Next if we're not already tied to a section, we check to see if maybe there's only 1 section, and
// if so, we select that one.. 
if (!($cnstdwglog_section_info)) {
	$cnstdwglog_section_info=getoneb("select * from cnstdwglog_sections where jobinfo_id = '$oiclog_doc_info->jobinfo_id' and active = 'Y'");
	}

// If we can't figure out the section to select on our own, then we put up a drop box...
// (note, we get the drop box even if someone has chosen a section but not added records yet...
// we need a chance to change our mind)
if (!($cnstdwglog_section_info)) {
	$secres=@mysql_query("select * from cnstdwglog_sections where jobinfo_id = '$oiclog_doc_info->jobinfo_id' and active = 'Y' order by section");
	$num_rows=@mysql_num_rows($secres);
	if ($num_rows=="1") {
		$tmp=@mysql_fetch_object($secres);
		$current_section_selection=$tmp->section;
		} else {
		if ($num_rows>1) {
			echo "<div style=\"width: 100%; background: $fd_color_3;\"><center><font size=-1>Cnstdwglog section&nbsp;&nbsp;<select id=\"cnstdwglog_section_select\" onchange=\"cnstdwglog_select_section()\">
			<option>$selected_section</option>";
			while ($option=@mysql_fetch_object($secres)) {
				echo "<option>$option->section</option>";
				}
			echo "<option></option></select></font></center></div>";
			}
		}
	}
// If we still don't have section info, then check to see if they've selected one with the 
// drop box, and if so, we use that from here on out.
if (!($cnstdwglog_section_info)) {
	if ($selected_section!="") {
		//echo "get it";
		//echo "<hr>select * from cnstdwglog_sections where jobinfo_id = '$oiclog_doc_info->jobinfo_id' and section = '$selected_section'<hr>";
		$cnstdwglog_section_info=getoneb("select * from cnstdwglog_sections where jobinfo_id = '$oiclog_doc_info->jobinfo_id' and section = '$selected_section'");
		}
	}
// Still no section info? Then it's time for us to quit.. we don't want to continue without the
// documents coming from a specific section of the construction drawing log.. 
//if (!($cnstdwglog_section_info)) exit('nothing');

if (!($cnstdwglog_section_info)) exit(); 

$current_construction_issuance_info=getoneb("select * from cnstdwglog_issuances where jobinfo_id = '$cnstdwglog_section_info->jobinfo_id' and section = '$cnstdwglog_section_info->section' and issuance_type like 'Constructio%' order by issuance_type,sort_priority desc,issuance_id desc,name desc limit 1");




echo "
<style>
	td.u {
		border-bottom: 1px solid black;
		}
</style>
<div style=\"width: 100%; border-bottom: 1px solid black; background: $fd_color_4\">";

if (($current_construction_issuance_info)) echo "<div style=\"float: left;\"><a href='javascript:cnstdwglog_select_dwg(\"$cnstdwglog_section_info->section\")'><font size=-1 color=blue><i>add/remove</i></font></a></div>";

echo "<center><b>Construction Drawings</b></center></div>";
$res=@mysql_query("select * from oiclog_purgatory left join documents on (documents.doc_id = oiclog_purgatory.cnstdwglog_doc_id) left join cnstdwglog on (documents.doc_type = 'cnstdwglog' and documents.app_record_id = cnstdwglog.cnstdwglog_id) where oiclog_doc_id = '$oiclog_doc_info->doc_id' order by cnstdwglog.drawing_type,documents.sort_rank,documents.doc_id,cnstdwglog.drawing_num");
$purgatory_count=@mysql_num_rows($res);

//if (!($current_construction_issuance_info)) die("catch me test");

if ($purgatory_count>0) {
	$something_posted=getoneb("select * from oiclog_purgatory left join documents on (documents.doc_id = oiclog_purgatory.cnstdwglog_doc_id) left join cnstdwglog on (documents.doc_type = 'cnstdwglog' and documents.app_record_id = cnstdwglog.cnstdwglog_id) where oiclog_doc_id = '$oiclog_doc_info->doc_id' and posted_to_cnstdwglog = 'Y' limit 1");
	} else {
	$something_posted=TRUE;
	}


if ($current_construction_issuance_info->name==$oiclog_info->oic_number) $something_posted=TRUE;



echo "<table width=100% border=0 cellspacing=0 cellpadding=2>";
echo "<tr><td colspan=5 bgcolor=$fd_color_6>";
	if (!($something_posted)) {
		if ($current_construction_issuance_info) echo "<div style=\"float: right;\"><input style=\"font-size: 11px;\" size=10 type=text name=issuance_name id=new_issuance_name value=\"$oiclog_info->oic_number\"><input style=\"font-size: 11px;\" type=button value=\"Add Issuance\" onclick=\"create_cnstdwglog_issuance('$current_construction_issuance_info->jobinfo_id','$current_construction_issuance_info->section')\"></div>";
		}
	echo "<font size=-1>Cndstdwglog::$cnstdwglog_section_info->section::$current_construction_issuance_info->name</font>
</td></tr>";

if (!($current_construction_issuance_info)) {
	echo "<tr><td colspan=5 align=center>No existing construction issuance!</font></td></tr>";
	}


while ($row=@mysql_fetch_object($res)) { 
	echo "<tr>
	
		<td class=u id=\"wf_cell_$row->purgatory_id\" align=center>
			<font size=-1><form name=\"frm_purgatory_$row->purgatory_id\" style=\"display: inline;\">";
			if ($row->posted_to_cnstdwglog=='Y') {
				$link=webfile_paperclip_view($row->attached_group_id);
				echo "$link";
				} else {
				webfilebox2($row->attached_group_id,"wfbox_$row->purgatory_id","cnstdwglog_linker_save_attachment('$row->purgatory_id','--object_element_id--')",array('box_size'=>'5'));
				}
			echo"</form></font>
		</td>

		<td class=u>
			<font size=-1>$row->drawing_type</font>
		</td>
		
		<td class=u>
			<font size=-1>$row->app_reference</font>
		</td>
		
		<td class=u>
			<font size=-1>$row->description</font>
		</td>
		
		
		";if ($oiclog_info->status=="Approved for construction by PM") {
			if ($current_construction_issuance_info) {
				if ($row->posted_to_cnstdwglog=='Y') {
					echo "<td class=u><font size=-1>Published</font></td>";
					} else {
					
					echo "<td class=u>
						<font size=-1 style=\"cursor: pointer; cursor: hand;\" color=blue onclick=\"cnstdwglog_linker_post_file('$row->purgatory_id')\">Publish to Const Dwgs</font>
						</td>";
					}
				}
			}
		echo "
		
		</tr>";
	}
echo "</table>";


?>
