<?
require("header.phtml");
fd_navs_header();
$today=date('m-d-Y');

$query_search_add=query_search_add_text();
$res=@mysql_query("select * from oiclog where jobinfo_id = '$global_jobinfo->jobinfo_id' $query_search_add order by oic_number + 1,oic_number");
search_div();

if ($guest) { comb_webfile_permissions(); }
//if (!($guest)) { comb_webfile_permissions(); }
echo "
<table border=1 cellspacing=0 cellpadding=3>
<tr><td colspan=12 align=center>";
if (!($guest)) echo "<div style=\"float: right;\"><a href=$pagename?mode=main_excel_dump&jobinfo_id=$global_jobinfo->jobinfo_id><font color=blue>Dump log to excel</font></a>&nbsp;&nbsp;&nbsp;</div>";
echo "
<b><font size=+1>$dbdescription</font></b><br>$today<br>";
if ($write) echo "<a href=$pagename?mode=oiclog_edit><font color=blue>Add New Owner Initiated Change</font></a>";
echo "</td></tr>";


if (!($guest)) {
echo "
<tr bgcolor=$fd_color_4><td>
	&nbsp;
</td><td>
	<b>OIC #</b>
</td><td>
	<b>GC Ref #</b>
</td><td>
	<b>UMC COP #</b>
</td><td>
	<b>NTP/Date</b>
</td><td>
	<b>Cost</b>
</td><td>
	<b>Description</b>
</td><td>
	<b>ROM Cost</b>
</td><td>
	<b>Resp Reqd</b>
</td><td>
	<b>Status</b>
</td><td>
	<b>Det Complete</b>
</td><td>
	<b>Notes</b>
</td></tr>
";
} else {
////////////////////////////////////////////////////
// Guests see this view
////////////////////////////////////////////////////
echo "
<tr bgcolor=$fd_color_4><td>
	&nbsp;
</td><td>
	<b>OIC #</b>
</td><td>
	<b>GC Ref #</b>
</td><td>
	<b>UMC COP #</b>
</td><td>
	<b>NTP/Date</b>
</td><td>
	<b>Description</b>
</td><td>
	<b>Resp Reqd</b>
</td><td>
	<b>Status</b>
</td><td>
	<b>Det Complete</b>
</td></tr>
";

}











while ($row=@mysql_fetch_object($res)) {
	//apply_default_file_group_permissions($row->document_file_group_id,"oiclog");
	$link=webfile_paperclip_view($row->document_file_group_id);
	$bgline="#ffffff";
	$temp_doc_id=fd_get_doc_id($row->oiclog_id);
	$file_batch=batch_this_document($temp_doc_id);
	$viewed=getoneb("select * from documents_review_history where contacts_id = '$global_user_id' and doc_id = '$temp_doc_id' limit 1");
	if (!($viewed)) $bgline="#ffffaa";
	if ($row->pm_complete_date!='0000-00-00') $bgline=$fd_color_2;
	$row->det_complete="";
	if ($row->det_complete_date!="0000-00-00") $row->det_complete="X";
	$row->oic_number=ereg_replace(" ","&nbsp;",$row->oic_number);
	if ($row->oic_number=="") $row->oic_number="??????";
	
	if (!($guest)) {
	echo "<tr bgcolor=\"$bgline\"><td>
		<table border=0 cellspacing=0 cellpadding=0><tr><td>$link&nbsp;</td><td>$file_batch</td></tr></table>
	</td><td>
		<a href=$pagename?mode=oiclog_edit&oiclog_id=$row->oiclog_id><font color=blue>$row->oic_number</font></a>
	</td><td>
		$row->gc_ref_num&nbsp;
	</td><td>
		$row->umc_cop_num&nbsp;
	</td><td>";
		if (($row->ntp != "") && ($row->ntp_date!="0000-00-00"))
			echo "$row->ntp/" . invali_date($row->ntp_date);
			else 
			echo "&nbsp;";	
	echo "
	</td><td>
		$row->cost_impact&nbsp;
	</td><td>
		$row->description&nbsp;
	</td><td>
		$row->rom_dollars
	</td><td>
		" . invali_date($row->req_by_date,'/') . "&nbsp;
	</td><td>
		$row->status
	</td><td>
		$row->det_complete&nbsp;
	</td><td>
		$row->notes&nbsp;
	</td></tr>
	";
	} else {
	echo "<tr bgcolor=\"$bgline\"><td>
		<table border=0 cellspacing=0 cellpadding=0><tr><td>$link&nbsp;</td><td>$file_batch</td></tr></table>
	</td><td>
		$row->oic_number
	</td><td>
		$row->gc_ref_num
	</td><td>
		$row->umc_cop_num
	</td><td>";
		if (($row->ntp != "") && ($row->ntp_date!="0000-00-00"))
			echo "$row->ntp/" . invali_date($row->ntp_date);
			else 
			echo "&nbsp;";	
	echo "
	</td><td>
		$row->description
	</td><td>
		" . invali_date($row->req_by_date,'/') . "
	</td><td>
		$row->status
	</td><td>
		$row->det_complete
	</td></tr>
	";
	}

}




echo "</table>";
fd_navs_footer();
?>
