<?
include("../webfile$devel/storage_settings.cfg");

if ($doc_id=="") pdf_generation_error_pdf("ERR(1) - Unable to load OIC information.");
$doc_id=addslashes($doc_id);
$doc_info=getoneb("select * from documents where doc_id = '$doc_id' and doc_type = 'oiclog'");
if (!($doc_info)) pdf_generation_error_pdf("ERR(2) - Unable to load OIC information.");
$oiclog_info=getoneb("select * from oiclog where oiclog_id = '$doc_info->app_record_id'");
if (!($oiclog_info)) die("ERR(3) - Unable to load OIC information");
$job=getoneb("select * from jobinfo where jobinfo_id = '$doc_info->jobinfo_id'");
$files_res=@mysql_query("select * from webfile_files where file_group_id = '$oiclog_info->document_file_group_id' and mime_type like '%pdf%'");

$row=@mysql_fetch_object($files_res);
$oic_number=ereg_replace("[ /]","_",$oiclog_info->oic_number);
pdf_mime_header("OIC_$doc_info->app_reference.pdf");
while ($row=@mysql_fetch_object($files_res)) {
	if ($row->file_group_id==0) continue;
	readfile("$storage_root$row->file_path");
	}
?>
