<?
if (!($doc_id)) die("document_id error!");
$doc_id=addslashes($doc_id);
if (!($oiclog_info)) {
	$doc_info=getoneb("select * from documents where doc_id = '$doc_id'");
	$oiclog_info=getoneb("select * from oiclog where oiclog_id = '$doc_info->app_record_id'");
	}

if ($field !='' ) {
	$field=addslashes($field);
	$set_user_id=$global_user_id;
	if ($value=='') $set_user_id="";
	$value=vali_date($value);
	$field2=addslashes(ereg_replace('_date','_user',$field));
	@mysql_query("update oiclog set $field = '$value',$field2 = '$set_user_id' where oiclog_id = '$oiclog_info->oiclog_id'");
	$oiclog_info=getoneb("select * from oiclog where oiclog_id = '$doc_info->app_record_id'");
	}

$det_user=getoneb("select * from contacts where contacts_id = '$oiclog_info->det_complete_user'");
$foreman_user=getoneb("select * from contacts where contacts_id = '$oiclog_info->foreman_review_user'");
$pm_user=getoneb("select * from contacts where contacts_id = '$oiclog_info->pm_complete_user'");
echo "
<div width=100% style=\"background: $fd_color_4;\">Completion Dates</div>
<table width=100% border=0 cellspacing=0 cellpadding=0>

<tr><td>Detailing Complete:</td><td>";datebox($oiclog_info->det_complete_date,'oiclog_edit.det_complete_date','','comp_date_update(this.name,this.value);');echo"&nbsp;$det_user->login_name</td></tr>
<tr><td>Foreman Complete:</td><td>";datebox($oiclog_info->foreman_review_date,'oiclog_edit.foreman_review_date','','comp_date_update(this.name,this.value);');echo"&nbsp;$foreman_user->login_name</td></tr>
<tr><td>PM Complete:</td><td>";datebox($oiclog_info->pm_complete_date,'oiclog_edit.pm_complete_date','','comp_date_update(this.name,this.value);');echo"&nbsp;$pm_user->login_name</td></tr>

</table>";
?>
