<?
$job_info=getoneb("select * from jobinfo where jobinfo_id = '$dailylog_info->jobinfo_id'");
$creator_info=getoneb("select * from contacts where contacts_id = '$dailylog_info->creator_id'");
$border_right=576;

$fontsize="10";
$standard_gap="16";
$my_loc="710";

$pdf->selectFont("$pdf_font_path/Helvetica.afm");
$pdf->ezSetMargins(36,50,36,36);
////////////////////////////////////////////////////////
// The logo and header/address junk
////////////////////////////////////////////////////////
// GPH MARK - absolute path
$pdf->addPngFromFile('/data/web/pipeline/images/umclogo_wbv2.png',435,710,150,48);
if ($job_info->job_letterhead_address_site!=968) {
	$lhead_site=getoneb("select * from contacts where contacts_id = '$job_info->job_letterhead_address_site'");
	$lhead_site_parts=explode("\r",$lhead_site->address_1);
	$lhead_site_p1=ereg_replace("\n","",$lhead_site_parts[0]);
	$lhead_site_p2=ereg_replace("\n","",$lhead_site_parts[1]);
	$pdf->addText(488,690,8,"$lhead_site_p1");
	$pdf->addText(488,680,8,"$lhead_site_p2");
	$pdf->addText(488,670,8,"$lhead_site->address_city,$lhead_site->address_state");
	$pdf->addText(488,660,8,"$lhead_site->address_zip");
	$pdf->addText(488,640,8,"<b>Phone $lhead_site->phone $lhead_site->phone_ext</b>");
	$pdf->addText(488,630,8,"Fax $lhead_site->phone_fax");
	} else {
	$pdf->addText(488,690,8,"11611 49th Place West");
	$pdf->addText(488,680,8,"P.O. Box 67");
	$pdf->addText(488,670,8,"Mukilteo, Washington");
	$pdf->addText(488,660,8,"98275-4255");
	$pdf->addText(488,640,8,"<b>Phone (206) 364-9900</b>");
	$pdf->addText(488,630,8,"Fax (206) 365-1580");
	}

///////////////////////////////////////////////////////
// Header
$pdf->ezStartPageNumbers(550,35,10,'',"JOB $job_info->contract_num Daily Log $rfi_info->rfi_num, Created By: $creator_info->first_name $creator_info->last_name ($creator_info->email)                                Page {PAGENUM} of {TOTALPAGENUM}");
$pdf->ezText("<i>Daily Report</i>",20);
$pdf->line(36,730,400,730);


// Job find RFI # information
$my_start_y=$my_loc;

$pdf->addText(36,$my_loc,$fontsize,"<b>Project:</b>");
$pdf->addText(95,$my_loc,$fontsize,"$job_info->display_name");
$my_loc=$my_loc - $standard_gap;
 
$pdf->addText(36,$my_loc,$fontsize,"<b>Job #:</b>");
$pdf->addText(95,$my_loc,$fontsize,"$job_info->contract_num");
$my_loc=$my_loc - $standard_gap;

$pdf->addText(36,$my_loc,$fontsize,"<b>Daily #:</b>");
$pdf->addText(95,$my_loc,$fontsize,"$dailylog_info->log_num");
$my_loc=$my_loc - $standard_gap;

$pdf->addText(36,$my_loc,$fontsize,"<b>Date:</b>");
$pdf->addText(95,$my_loc,$fontsize,invali_date($dailylog_info->work_date));
$my_loc=$my_loc - $standard_gap;

//$dailylog_info->weather=ereg_replace("@","QQQ",$dailylog_info->weather);
$dailylog_info->weather=eregi_replace("&deg;",chr(176),$dailylog_info->weather);
$dailylog_info->weather=ereg_replace(chr(194),"",$dailylog_info->weather);

$pdf->addText(36,$my_loc,$fontsize,"<b>Weather:</b>");
$pdf->addText(95,$my_loc,$fontsize,$dailylog_info->weather);
$my_loc=$my_loc - $standard_gap;

if ($dailylog_info->location !="") {
	$pdf->addText(36,$my_loc,$fontsize,"<b>Location:</b>");
	$pdf->addText(95,$my_loc,$fontsize,$dailylog_info->location);
	$my_loc=$my_loc - $standard_gap;
	}



$pdf->setStrokeColor(.3,.3,.3);
$pdf->setLineStyle(.1);

function print_paragraph($title, $text, $rollback="Y") {
	global $my_loc,$pdf,$border_right,$border_left,$fontsize,$standard_gap; // $box_end???
	$start_page=$pdf->ezPageCount;
	$pdf->transaction('start');
	if ($text=="") {
		$my_loc=$my_loc - $standard_gap;
		$pdf->addText(36,$my_loc,$fontsize, "<b>$title:</b> none");
		$pdf->y=$my_loc;
		return 0;
		}
	
	$box_top=$my_loc - 9;
	$pdf->ezSetY($box_top);
	$boxdata=array(36,$box_top,$border_right,$box_top,$border_right,$box_top - 14,36,$box_top - 14);
	$pdf->setColor(.7,.7,.7);
	$pdf->polygon($boxdata,4,1);
	$pdf->setColor(0,0,0);
	$pdf->ezText("<b>$title:</b>\r\n$text\r\n",$fontsize,array('aleft'=>'46','aright'=>'566'));
	$box_end=$pdf->y;
	$my_loc=$pdf->y;
	//$pdf->ezText("<b>$title:</b>\r\n$text\r\n",$fontsize,array('aleft'=>'46','aright'=>'566'));
	
	$pdf->line(36,$box_top,$border_right,$box_top);
	$pdf->line(36,$box_end,$border_right,$box_end);
	$pdf->line(36,$box_top,36,$box_end);
	$pdf->line($border_right,$box_top,$border_right,$box_end);
	$end_page=$pdf->ezPageCount;
	if (($start_page!=$end_page)&&($rollback=="Y")){
		$pdf->transaction('rewind');
		$pdf->ezNewPage();
		print_paragraph($title,$text,"N");
		} else {
		$pdf->transaction('commit');
		}
	
	}


function print_craft_count($craft,$count,$hours=0) {
	global $craft_count_total,$craft_hours_total,$pdf,$fontsize,$my_loc,$standard_gap;
	if ($count < 1) return 0;
	if($craft_count_total=="") $craft_count_total="0";
	
	
	$craft_count_total=$craft_count_total + $count;
	$pdf->addText(36,$pdf->y,$fontsize, "$craft:");
	$pdf->addText(160,$pdf->y,$fontsize, "$count");
	$pdf->addText(160,$pdf->y,$fontsize, "$count");
	if ($hours!=0) {
		$pdf->addText(260,$pdf->y,$fontsize, "Hrs: $hours");
		$craft_hours_total=$craft_hours_total + $hours;
		}
	//$my_loc=($my_loc - $standard_gap) + 4;
	$pdf->ezText(" ");
	
	
	}

print_paragraph("Work Progress",$dailylog_info->work_progress);
print_paragraph("Materials Received",$dailylog_info->materials_received);
print_paragraph("New Hires",$dailylog_info->new_hires);
print_paragraph("New Hire Safety Training",$dailylog_info->new_hire_safety_training);
print_paragraph("Hindrances",$dailylog_info->work_hinderances );
print_paragraph("Accidents, Near Misses & Safety Concerns",$dailylog_info->accidents );
$craft_hours_total=0;
//$my_loc=$my_loc - $standard_gap;
//$pdf->y=$pdf->y - $standard_gap;
//$my_loc=$my_loc - $standard_gap;
//$my_loc=($my_loc - $standard_gap) + 7;
$pdf->y=$pdf->y - $standard_gap;
//$pdf->y=($pdf->y - $standard_gap) + 7;
$pdf->ezText("<b>UMC Personnel</b>",$fonsize);
//$my_loc=($my_loc - $standard_gap) + 4;
$pdf->y=($pdf->y - $standard_gap) + 4;
$pdf->ezText("",$fontsize);
print_craft_count("General Foreman",$dailylog_info->our_general_foreman_count,$dailylog_info->our_general_foreman_hours);
print_craft_count("Plumbing Foreman",$dailylog_info->our_plumbing_foreman_count,$dailylog_info->our_plumbing_foreman_hours);
print_craft_count("Plumbing Journeyman",$dailylog_info->our_plumbing_journeyman_count,$dailylog_info->our_plumbing_journeyman_hours);
print_craft_count("Plumbing Apprentices",$dailylog_info->our_plumbing_apprentice_count,$dailylog_info->our_plumbing_apprentice_hours);
print_craft_count("Steamfitter Foreman",$dailylog_info->our_steamfitter_foreman_count,$dailylog_info->our_steamfitter_foreman_hours);
print_craft_count("Steamfitter Journeyman",$dailylog_info->our_steamfitter_journeyman_count,$dailylog_info->our_steamfitter_journeyman_hours);
print_craft_count("Steamfitter Apprentices",$dailylog_info->our_steamfitter_apprentice_count,$dailylog_info->our_steamfitter_apprentice_hours);
print_craft_count("Laborers",$dailylog_info->our_laborer_count,$dailylog_info->our_laborer_hours);
print_craft_count("Truck Drivers",$dailylog_info->our_truck_driver_count,$dailylog_info->our_truck_driver_hours);
print_craft_count("Operating Engineers",$dailylog_info->our_operating_engineer_count,$dailylog_info->our_operating_engineer_hours);
print_craft_count("Millwrights",$dailylog_info->our_millwright_count,$dailylog_info->our_millwright_hours);
print_craft_count("Carpenters",$dailylog_info->our_carpenter_count,$dailylog_info->our_carpenter_hours);
print_craft_count("Sheetmetal Workers",$dailylog_info->our_sheetmetal_count,$dailylog_info->our_sheetmetal_hours);
print_craft_count("Sheetmetal Foreman",$dailylog_info->our_sheetmetal_foreman_count,$dailylog_info->our_sheetmetal_foreman_hours);
print_craft_count("Sheetmetal Journeyman",$dailylog_info->our_sheetmetal_journeyman_count,$dailylog_info->our_sheetmetal_journeyman_hours);
print_craft_count("Sheetmetal Apprentice",$dailylog_info->our_sheetmetal_apprentice_count,$dailylog_info->our_sheetmetal_apprentice_hours);
print_craft_count("Helpers",$dailylog_info->our_helper_count,$dailylog_info->our_helper_hours);
print_craft_count("Refrigeration",$dailylog_info->our_refrigeration_count,$dailylog_info->our_refrigeration_hours);
$umc_total=$craft_count_total;
$umc_total_hours=$craft_hours_total;
$craft_hours_total=0;
$craft_count_total="";
$pdf->ezText("<b>Subs Personnel</b>",$fontsize);
$pdf->y=($pdf->y - $standard_gap) + 4;

print_craft_count("Temperature Control",$dailylog_info->sub_temperature_control_count,$dailylog_info->sub_temperature_control_hours);
print_craft_count("Insulation",$dailylog_info->sub_insulation_count,$dailylog_info->sub_insulation_hours);
print_craft_count("Painters",$dailylog_info->sub_painter_count,$dailylog_info->sub_painter_hours);
print_craft_count("Sewer Men",$dailylog_info->sub_sewer_men_count,$dailylog_info->sub_sewer_men_hours);
print_craft_count("Electrician",$dailylog_info->sub_electrician_count,$dailylog_info->sub_electrician_hours);
print_craft_count("Refrigeration",$dailylog_info->sub_refrigeration_count,$dailylog_info->sub_refrigeration_hours);
print_craft_count("Air Balance",$dailylog_info->sub_air_balance_count,$dailylog_info->sub_air_balance_hours);
print_craft_count("Sheetmetal Workers",$dailylog_info->sub_sheet_metal_count,$dailylog_info->sub_sheet_metal_hours);
print_craft_count("Core Drillers",$dailylog_info->sub_core_drill_count,$dailylog_info->sub_core_drill_hours);
print_craft_count("Fire Caulkers",$dailylog_info->sub_fire_caulk_count,$dailylog_info->sub_fire_caulk_hours);
print_craft_count("Fire Protection",$dailylog_info->sub_fire_protection_count,$dailylog_info->sub_fire_protection_hours);
print_craft_count("Chemical Treatment",$dailylog_info->sub_chemical_treatment_count,$dailylog_info->sub_chemical_treatment_hours);
print_craft_count("Fuel Tank Install/Piping",$dailylog_info->sub_fuel_tank_install_and_piping_count,$dailylog_info->sub_fuel_tank_install_and_piping_hours);
print_craft_count("Excavation",$dailylog_info->sub_excavation_count,$dailylog_info->sub_excavation_hours);
$sub_total=$craft_count_total;
$sub_total_hours=$craft_hours_total;
$total_total=$umc_total + $sub_total;
$total_total_hours=$umc_total_hours + $sub_total_hours;
$pdf->y=($pdf->y - $standard_gap) + 7;
$pdf->ezText("<b>Total Personnel:</b> $total_total",$fontsize);
if ($total_total_hours!=0) {
	$pdf->ezText("<b>Total Hours:</b> $total_total_hours",$fontsize);
	}
$pdf->y=($pdf->y - $standard_gap) + 4;
?>
