<?
require("header.phtml");
fd_navs_header();
$today=date('m-d-Y');

echo "
<script>
function create_new_dailylog() {
	if(confirm('Create new log now?')) {
		document.location='$pagename?mode=create_log';
		}
	}

</script>

<table id='sub_application_main_table' border=1 cellspacing=0 cellpadding=3>
<thead>
<tr><td colspan=8>";
//<div class=noprint style=\"position: absolute; border: 2px solid black;\"><form name=search method=post action=$pagename>Search:&nbsp;<input type=text name=search_text value=\"$search_text\">";
//dropbox_search($search_array);
//echo"<input type=submit value='Go'></form></div>
search_div();
echo"<center><b><font size=+1>Daily Log</font></b><br>$today";

$query_search_add=query_search_add_text();
$query="select * from dailylog where jobinfo_id = '$global_jobinfo_id' and section = '$current_dailylog_section' $query_search_add order by work_date desc, dailylog_id desc";
$res=@mysql_query($query);
include("fd_log_paging.phtml");



echo "<br>
<a href=javascript:create_new_dailylog()><font color=blue>Create New Daily Log</font></a><br>$page_page_insert
</center>
</td></tr>

<tr class=floatheader><td>
	&nbsp;
</td><td>
	<b>Log #</b>
</td><td>
	<b>Weekday</b>
</td><td>
	<b>Date</b>
</td><td>
	<b>Created By</b>
</td><td>
	<b>Status</b>
</td><td>
	<b>Weather</b>
</td><td>
	<b>Hindrances</b>
</td></tr>
</thead><tbody class=floatheader>
";



while ($row=@mysql_fetch_object($res)) {
	$temp_doc_id_query="select * from documents where doc_type = 'dailylog' and section = '$row->section' and app_record_id = '$row->dailylog_id'";
	$temp_doc_info=getoneb($temp_doc_id_query);
	$temp_doc_id=$temp_doc_info->doc_id;
	$file_batch=batch_this_document($temp_doc_id);

	$weekday=date("D",strtotime($row->work_date));
	if ($row->work_hinderances=="") $hind="&nbsp;";
	else $hind='*';
	
	$creator_info=getoneb("select * from contacts where contacts_id = '$row->creator_id'");
	$date=invali_date($row->work_date,'/');
	echo "<tr><td>
			$file_batch
		</td><td>
			<a href=$pagename?mode=dailylog_edit&dailylog_id=$row->dailylog_id><font color=blue>$row->log_num</font></a>
		</td><td align=center>
			$weekday
		</td><td>
			$date
		</td><td>
			$creator_info->first_name $creator_info->last_name
		</td><td>
			$row->status
		</td><td>
			$row->weather
		</td><td>
			$hind
		</td></tr>
		";
	}
echo "<tr><td colspan=15 height=100%></td></tr></tbody></table>";
fd_navs_footer();
?>
