<?PHP
global $fd_color_1, $fd_color_2, $global_user, $pagename_up, $devel, $fd_color_4, $my_home_color, $global_jobinfo_id;
$GLOBALS['contact_view_js'] = 'Y';
$jobinfo_id = $global_jobinfo_id;
require_once("header.phtml");
$today=date('m-d-Y');
$jobinfo_id=addslashes($jobinfo_id);
$jobinfo=getone("select * from jobinfo where jobinfo_id = '$jobinfo_id'");


require_once("header.phtml");
require_once("frontdesk_pageheader.phtml");
require_once("frontdesk_secondary_nav.phtml");
require_once("frontdesk_tabs.phtml");

?>




<div style="background: <? echo $watermark;?>; background-repeat: repeat; vertical-align: top; text-align: left;">
<table id="sub_application_main_table" cellpadding=3>
	<thead>
		<tr>
			<td colspan=8>
				<?php
					search_div();
				?>
				<center><b><font size=+1>Daily Log</font></b><br>
				
				<?php
					echo $today;
					$query_search_add=query_search_add_text();
					$query="select
										*,
										(SELECT COUNT(*) FROM dailylog_entries WHERE work_hinderances <> '' AND dailylog_entries.dailylog_id = dailylog.dailylog_id) AS hinderance_count
									from
										dailylog 
									where
										jobinfo_id = '$global_jobinfo_id' and
										section = '$current_dailylog_section'
										$query_search_add
									order by
										work_date desc,
										dailylog_id desc
										";
										
					$res=@mysql_query($query);

					include("fd_log_paging.phtml");

					echo "<br>
					<a href=javascript:create_new_dailylog('$pagename')><font color=blue>Create New Daily Log</font></a><br>$page_page_insert
					</center>
					</td></tr>
					
					<tr class=floatheader><td>
						&nbsp;
					</td><td>
						<b>Log #</b>
					</td><td>
						<b>Weekday</b>
					</td><td>
						<b>Date</b>
					</td><td>
						<b>Created By</b>
					</td><td>
						<b>Status</b>
					</td><td>
						<b>Weather</b>
					</td><td>
						<b>Hindrances</b>
					</td></tr>
					</thead><tbody class=floatheader>
					";

while ($row=@mysql_fetch_object($res)) {
	$temp_doc_id_query="select * from documents where doc_type = 'dailylog' and section = '$row->section' and app_record_id = '$row->dailylog_id'";
	$temp_doc_info=getoneb($temp_doc_id_query);
	$temp_doc_id=$temp_doc_info->doc_id;
	$file_batch=batch_this_document($temp_doc_id);

	$weekday=date("D",strtotime($row->work_date));
	if ($row->work_hinderances=="" && $row->hinderance_count < 1) $hind="&nbsp;";
	else $hind='*';
	
	$creator_info=getoneb("select * from contacts where contacts_id = '$row->creator_id'");
	$date=invali_date($row->work_date,'/');
	echo "<tr><td>
			$file_batch
		</td><td>
			<a href=$pagename?mode=dailylog_view&dailylog_id=$row->dailylog_id><font color=blue>$row->log_num</font></a>
		</td><td align=center>
			$weekday
		</td><td>
			$date
		</td><td>
			$creator_info->first_name $creator_info->last_name
		</td><td>
			$row->status
		</td><td>
			$row->weather
		</td><td>
			$hind
		</td></tr>
		";
	}
echo "<tr><td colspan=15 height=100%></td></tr></tbody></table>";
?>	
</div>
<script>
    setTimeout("ajaxManager('load_page','/global/front_desk?mode=my_jobs_menu','my_jobs_drop')",100);
	setTimeout("ajaxManager('load_page','/global/front_desk?mode=recent_jobs_menu','recent_jobs_drop')",200);
</script>