<?
include("../webfile$devel/storage_settings.cfg");


if ($doc_id=="") die("ERR(1)");
$doc_id=addslashes($doc_id);
$doc_info=getoneb("select * from documents where doc_id = '$doc_id' and doc_type = 'dailylog'");
if (!($doc_info)) die("ERR(2)");
$dailylog_info=getoneb("select * from dailylog where dailylog_id = '$doc_info->app_record_id'");
if (!($dailylog_info)) die("ERR(3)");
$dailylog_id=$dailylog_info->dailylog_id;

$job=getoneb("select * from jobinfo where jobinfo_id = '$doc_info->jobinfo_id'");
$sequence=ereg_replace("[^0-9]","",$sequence);
if ($sequence=="") die("ERR(4)");
$sequence=addslashes($sequence); // Shouldn't really be needed, should always be the same, but why not..
$seq_pretty=sprintf("%'04d",$sequence);
$contract_num=$job->contract_num;


$file_letter="a";
@mkdir("/tmp/front_desk");
@mkdir("/tmp/front_desk/cook_a_batch");
@mkdir("/tmp/front_desk/cook_a_batch/$global_user->login_name");
@mkdir("/tmp/front_desk/cook_a_batch/$global_user->login_name/$job->contract_num");
@chdir("/tmp/front_desk/cook_a_batch/$global_user->login_name/$job->contract_num");


require_once('pdf_lib2.inc');
$pdf=&new Cezpdf("$global_user->pref_paper_size","portrait");
//$number=$job->fd_rfi_template_number;
require("dailylog_render_pdf.phtml");

$file_contents=$pdf->ezOutput();
$output_file_name=$seq_pretty . $file_letter . "_-_${contract_num}_-_daily_-_$dailylog_info->log_num_-_$dailylog->work_date.pdf";
file_put_contents($output_file_name,$file_contents);
if (!(is_file($output_file_name))) die("ERR(5)");

echo "OK";
exit;
?>
