<?
require('querylib.inc');
require('header.phtml');
if ($bidlist_id=="") {
	include("lead_create.phtml");
	exit;
	} 
$bidlist_id=escapeshellcmd($bidlist_id);
$bid_info=load_proposal_info($bidlist_id);
$form_mode="edit";
$dropboxmode="";
$dropboxvaradd="";
$dropboxsize="1";

echo "
<form name=bidlist_edit method=get action=$pagename>
<input type=hidden name=mode value=proposal_submit>
<input type=hidden name=bidlist_id value='$bidlist_id'>
<input type=hidden name=target value=main>
<input type=hidden name=targetmode value=lead>";

include("proposal_edit_header.phtml");



////////////////////////////////////////////////////////////////////////////
////////////////////	Top Section - Mandatory Items	////////////////////
////////////////////////////////////////////////////////////////////////////
echo "
<div id=\"proposal_form_table\">

<table border=0 cellspacing=0 cellpadding=0>
<tr><td valign=top>


<table border=0 cellspacing=0 cellpadding=$main_table_padding>
<tr><td width=100% colspan=4>
	";include("proposal_edit_form_required.phtml");echo"
</td></tr>

<tr><td width=100% colspan=4>
	";include("proposal_edit_form_owner.phtml");echo"
</td></tr>

<tr><td valign=top>";
	include('proposal_edit_form_tracking.phtml');
	echo"
</td><td valign=top align=center>
	";
	include("proposal_edit_form_lead_logs.phtml");
	echo"
</td><td valign=top align=left>
	";include("proposal_edit_form_project_data.phtml");echo"
</td></tr>

<tr><td colspan=3>";
	if ($adminuser) {
		echo "
		<a href=javascript:apply_go_down();><font color=blue>&lt;--Prev--</font></a>&nbsp;&nbsp;&nbsp;<a href=javascript:apply_go_up();><font color=blue>--Next--&gt;</font></a>
		";
		}
echo"</td></tr>

<tr><td colspan=3>
	";
	show_bidlist_log($bidlist_id,'lead_comments','Lead Notes Log');
	echo"
</td></tr>

</table>

</td><td valign=top>
	";
	include("proposal_edit_form_associated.phtml");
	echo"
	<b>Files:</b><br>
	";
	webfilebox($bid_info->attached_files,"attached_files","opener.apply_changes()");
	webfile_group_vert_preview($bid_info->attached_files);
	echo "
</td></tr></table>
</form>

</div>
</p>

<script>
function apply_changes() {
	document.bidlist_edit.target.value='reload';
	document.bidlist_edit.submit();
	}
function save_and_search() {
	document.bidlist_edit.target.value='searchpage';
	document.bidlist_edit.submit();
	}
function apply_go_down() {
	document.bidlist_edit.target.value='go_down';
	document.bidlist_edit.submit();
	}
function apply_go_up() {
	document.bidlist_edit.target.value='go_up';
	document.bidlist_edit.submit();
	}
</script>
";


?>
