<?

require("header.phtml");

echo "
<a href=$pagename?mode=main><font color=blue>Cancel</font></a><br>
<center><h3>Create <u>OLD</u> proposal</h3></center><hr>

Create Proposal for the year: 
<form name=new_old_prop>
<input type=hidden name=mode value=proposal_edit>
<input type=hidden name=old_prop value=true>
<select name=proposal_year>
<option value=''></option>
<option value='1980'>1980</option>
<option value='1981'>1981</option>
<option value='1982'>1982</option>
<option value='1983'>1983</option>
<option value='1984'>1984</option>
<option value='1985'>1985</option>
<option value='1986'>1986</option>
<option value='1987'>1987</option>
<option value='1988'>1988</option>
<option value='1989'>1989</option>
<option value='1990'>1990</option>
<option value='1991'>1991</option>
<option value='1992'>1992</option>
<option value='1993'>1993</option>
<option value='1994'>1994</option>
<option value='1995'>1995</option>
<option value='1996'>1996</option>
<option value='1997'>1997</option>
<option value='1998'>1998</option>
<option value='1999'>1999</option>
<option value='2000'>2000</option>
<option value='2001'>2001</option>
<option value='2002'>2002</option>
<option value='2003'>2003</option>
</select>
&nbsp;&nbsp;&nbsp;Seq&nbsp;#&nbsp;<i>(optional)</i>&nbsp;<input type=text size=4 name=override_sequence_num>
<br><input type=submit value=Create>
</form>
";


?>
