<?
require_once('querylib.inc');
$query="select * from contacts where current = 'Y' and umc_emp = 'Y' order by last_name,first_name,employee_num";

echo "
<html><body bgcolor=white>
<a href=$pagename?mode=notifications><font color=blue>Return to notifications</font></a>
<h3>Select User to Add</h3><hr>";
$res=@mysql_query($query);

while($row=@mysql_fetch_object($res)) {
	if (!(getoneb("select * from bidlist_notifications where contacts_id = '$row->contacts_id'")))
	echo "<a href=$pagename?mode=notifications_add_submit&contacts_id=$row->contacts_id><font color=blue>$row->last_name, $row->first_name</font></a><br>";
	
	}






?>
