<?
require_once('querylib.inc');
if (!($adminuser)) die("ERROR: Security Violation! The authorities have been notified!!!");

$query="select * from bidlist_notifications,contacts where bidlist_notifications.contacts_id = contacts.contacts_id order by last_name,first_name,employee_num";

$res=@mysql_query($query);


echo "
<html><body bgcolor=white>

<a href=$pagename?mode=notifications_add><font color=blue>Add</font></a><p>
<a href=$pagename?mode=main_bidlist><font color=blue>Return to bidlist</font></a><p>


<table border=1 cellpadding=0 cellspacing=0><tr><td>
<table border=0 cellspacing=0 cellpadding=6>

<tr bgcolor=#dddddd><td>
	<font size=+1>Name</font>
</td><td>
	<font size=+1>E-mail</font>
</td><td>
	&nbsp;
</td></tr>
";
	
while($row=@mysql_fetch_object($res)) {
	echo "
	<tr><td>
		$row->last_name, $row->first_name
	</td><td>
		$row->email
	</td><td>
		<a href=$pagename?mode=notifications_remove&notify_id=$row->notify_id><font color=blue><i>remove</i></a>
	</td></tr>
	
	";
	}

echo "</table>
</td></tr></table>
";

?>
