<?
if ($bidlist_id!="") $bidlist_id=escapeshellcmd($bidlist_id);
else die("ERROR: No bidlist_id specified. Please contact you system administrator");

echo "<html><head><title>$application_name - add reference</title></head>
<body bgcolor=#ffffff>
<form name=reference_add method=post action=$pagename>
<input type=hidden name=mode value=reference_submit>
<input type=hidden name=bidlist_id value=\"$bidlist_id\">
<table border=0>

<tr><td>
	Reference: 
</td><td>
	";contactbox("select * from contacts where umc_emp = 'N' order by alphasort");echo"
</td></tr>

<tr><td>
	Type: 
</td><td>
	<input type=text name=type>
</td></tr>

<tr><td>
	Notes:
</td><td>
	<textarea name=notes rows=5 cols=35></textarea>
</td></tr>

<tr><td>
	Sorting Priority: 
</td><td>
	<input type=text name=sort_priority size=4 value=10>
</td></tr>

<tr><td colspan=2 align=right>
	<input type=submit value=Add>
</td></tr>



</form>
</body>";
?>
