<?

if ($oiclog_doc_id=="") die("Application error!");
if ($cnstdwglog_doc_id=="") die("Application error!");

$oiclog_doc_id=addslashes($oiclog_doc_id);
$cnstdwglog_doc_id=addslashes($cnstdwglog_doc_id);



$oiclog_doc_info=getoneb("select * from documents where doc_id = '$oiclog_doc_id'");
$cnstdwglog_doc_info=getoneb("select * from documents where doc_id = '$cnstdwglog_doc_id'");
$cnstdwglog_info=getoneb("select * from cnstdwglog where cnstdwglog_id = '$cnstdwglog_doc_info->app_record_id'");
$link_text="$cnstdwglog_info->drawing_type - $cnstdwglog_info->drawing_num - $cnstdwglog_info->description";

$purgatory_info=getoneb("select * from oiclog_purgatory where oiclog_doc_id = '$oiclog_doc_info->doc_id' and cnstdwglog_doc_id = '$cnstdwglog_doc_info->doc_id' limit 1");


if (!($purgatory_info)) {
	@mysql_query("insert into oiclog_purgatory set oiclog_doc_id = '$oiclog_doc_info->doc_id', cnstdwglog_doc_id = '$cnstdwglog_doc_info->doc_id'");
	//echo "needs to be linked";
	} else {
	$attachment_info=getoneb("select * from oiclog_purgatory right join webfile_groups_and_files on (oiclog_purgatory.attached_group_id = webfile_groups_and_files.file_group_id and webfile_groups_and_files.files_id > 0 ) where oiclog_doc_id = '$oiclog_doc_info->doc_id' and cnstdwglog_doc_id = '$cnstdwglog_doc_info->doc_id' limit 1");
	if ($attachment_info) {
		die("<div style=\"border: 1px solid black; width: 100%; color: white; background: red;\">$link_text - ERR: File attached!</div>");
		}
	@mysql_query("delete from oiclog_purgatory where oiclog_doc_id = '$oiclog_doc_info->doc_id' and cnstdwglog_doc_id = '$cnstdwglog_doc_info->doc_id'");
	}


$purgatory_info=getoneb("select * from oiclog_purgatory where oiclog_doc_id = '$oiclog_doc_info->doc_id' and cnstdwglog_doc_id = '$cnstdwglog_doc_info->doc_id' limit 1");

if ($purgatory_info) {
	echo "<div style=\"width: 100%; background: $fd_color_4; border: 1px solid black;\">$link_text</div>";
	} else {
	echo "<div style=\"width: 100%; border: 1px solid white;\">$link_text</div>";
	}



//$url=$GLOBALS['REQUEST_URI'];
//echo "toggle me baby!!!!!!!!!<HR>$url";





?>
