<?
//////////////////////////////////////////////////////////////////////
// We need to keep track of a few things so we can exit to the right
// spot again for most any scenario:
// #1) doc_id - this is the document that opened us
// #2) doc_edit_id - this is the document we're editing
// #3) $doc_type, but from here it is fixed 
//
//	Anything else that we load off of, should probably get overriden 
//  by the above data (IE: if we know we're load a particular 
//  doc_edit_id, we don't care about the edit text that is for
//  trying to locate it.
//////////////////////////////////////////////////////////////////////

$doc_type="oiclog";
include ('fd_document_box_header.phtml');
fd_document_box_header_print($doc_id,$doc_type,$doc_edit_id);

///////////////////////////////////////////////////////////////////////////////////////////////////
//	This is the end of the generics section
//	...now on to the app specific stuff
///////////////////////////////////////////////////////////////////////////////////////////////////
if ($doc_edit_info) {
	$oiclog_info=getoneb("select * from oiclog where oiclog_id = '$doc_edit_info->app_record_id'");
	//$gcrfi_num_text=htmlspecialchars($gcrfi_info->gcrfi_num);
	$oic_number_text=htmlspecialchars($oiclog_info->oic_number);
	} else {
	$oic_number_text=htmlspecialchars($load_text);
	//$gcrfi_num_text=htmlspecialchars($load_text);
	
	}

echo "<table border=0 cellspacing=0 cellpadding=1>";
if (!($oiclog_info)) {
	echo "
	<tr><td>
			<font size=-2>OIC #:</font>
	</td><td>
		<input type=text size=8 name=oic_number id=doc_box_oic_number value=\"$oic_number_text\">
	</td></tr>
	
	<tr><td colspan=2 align=center>
		<input type=button onclick=create_new_oiclog($doc_info->doc_id) value=Create>
	</td></tr>
	</table>
	";
	exit;
	}
echo "
<tr><td>
		<font size=-2>OIC #:</font>
</td><td id=fd_document_box_oic_number_cell>
	<input type=text size=8 name=oic_number id=doc_box_oic_number value=\"$oic_number_text\" onchange=fd_doc_change_oic_number('$doc_info->doc_id','$doc_edit_info->doc_id')>
</td></tr>

<tr><td>
	<font size=-2>Subject:</font>
</td><td id=fd_document_box_description_cell>
	<input type=text size=13 name=description id=doc_box_description value=\"$oiclog_info->description\" onchange=fd_doc_change_description('$doc_info->doc_id','$doc_edit_info->doc_id')>
</td></tr>

</table>
";
?>
