<?

include ('fd_document_box_header.phtml');
$oic_number=addslashes($oic_number);
$oic_info=getoneb("select * from oiclog where oiclog_id = '$doc_edit_info->app_record_id'");
$oic_dupe=getoneb("select * from oiclog where jobinfo_id = '$oic_info->jobinfo_id' and section = '$oic_info->section' and oic_number = '$oic_number' limit 1");
if (!($gcrfi_dupe)) {
	@mysql_query("update oiclog set oic_number = '$oic_number' where oiclog_id = '$doc_edit_info->app_record_id'");
	$input_style="";
	} else {
	$input_style='style="background: red; color: white; font-weight: bold;"';
	$oic_number=htmlspecialchars($oic_info->oic_number);
	}
echo "<input $input_style type=text size=8 name=oic_number id=doc_box_oic_number value=\"$oic_number\" onchange=fd_doc_change_oic_number('$doc_info->doc_id','$doc_edit_info->doc_id')>";
?>
