<?
if ($guest) die_security("Guest in oiclog edit form");

if ($oiclog_id!="") {
	$oiclog_id=addslashes($oiclog_id);
	$oiclog_info=getoneb("select * from oiclog where oiclog_id = '$oiclog_id'");
	$doc_id=fd_get_doc_id($oiclog_info->oiclog_id);
	}
require("header.phtml");
fd_navs_header();

if ($global_jobinfo->oic_prefix=="") $global_jobinfo->oic_prefix="OIC";

if ($doc_id) {
	if (pm_for_this_job()) {
		echo "
		<script>
		function delete_oiclog_record(doc_id) {
			if (confirm('Permanently delete this record and all attachments?')) {
				document.location='$pagename?mode=oiclog_delete&doc_id=' + doc_id;
				}
			}
		</script>
		<div style=\"float: right;\"><i><a href=javascript:delete_oiclog_record($doc_id)>delete</a></i></div>
		";
		}
	}


echo "
<script>
function explode_file() {
	if (confirm('Explode the contents of this file into the construction drawings section below?')) {
		alert('webfile_files_id error! Unabled to load file information.');
		}
	}

</script>


<form name=oiclog_edit method=post action=$pagename>
<input type=hidden name=mode value=oiclog_submit>
<input type=hidden name=oiclog_id value=\"$oiclog_id\">
<table style=\"border-collapse: collapse; border: 1px solid black;\" border=0 cellspacing=0 cellpadding=5>

<tr><td style=\"border: 1px solid black; background: $fd_color_4;\" colspan=2 align=center>
	<b><font size=+2>OIC LOG</font></b>
</td><td valign=top style=\"border: 1px solid black;\" rowspan=16>
";
	if ($oiclog_id!="") {
		echo"
		<div style=\"border: 2px solid black;\" width=100% id=record_dwg_posting></div>
		<div style=\"border: 2px solid black;\" width=100% id=det_cfu_box>";include("det_cfu_box.phtml");echo"</div>
		<div style=\"border: 2px solid black;\" width=100% id=todo_completion_dates>";include("todo_completion_dates.phtml");echo"</div>
		<div style=\"border: 2px solid black;\" width=100%>";pal_box($doc_id,294);echo"</div>
		
		<div style=\"border: 2px solid black;\" width=100%>";fd_attachments_in_body();echo "</div>
		<script>ajaxManager('load_page','$pagename?mode=oic_record_dwg_posting&doc_id=$doc_id','record_dwg_posting');</script>";
		}
	echo"
</td></tr>




<tr><td>
	OIC Number:
</td><td>
	<input type=text name=oic_number size=10 value=\"$oiclog_info->oic_number\">
</td></tr>

<tr><td>
	UMC COP#:
</td><td>
	<input type=text size=10 name=umc_cop_num value=\"$oiclog_info->umc_cop_num\">
</td></tr>

<tr><td>
	GC Ref#:
</td><td>
	<input type=text size=10 name=gc_ref_num value=\"$oiclog_info->gc_ref_num\">
</td></tr>

<tr><td>
	Description:
</td><td>
	<input type=text name=description size=50 value=\"$oiclog_info->description\">
</td></tr>

<tr><td>
	Req By:
</td><td>
	";datebox2($oiclog_info->req_by_date,'oiclog_edit.req_by_date');echo "
</td></tr>

<tr><td>
	Cost Impact:
</td><td>
	<select name=cost_impact>
	<option>$oiclog_info->cost_impact</option>
	<option>Y</option>
	<option>N</option>
	</select>
	UMC&nbsp;Resp&nbsp;Date:&nbsp;";datebox2($oiclog_info->cost_impact_response_date,'oiclog_edit.cost_impact_response_date');echo"
</td></tr>

<tr><td>
	Shop DWG Status:
</td><td>
	<select name=shop_dwg_status>
	<option>$oiclog_info->shop_dwg_status</option>
	<option>Incorporated into dwg</option>
	<option>Not Incorporated into dwg</option>
	<option>No revisions required</option>
	<option></option>
	</select>
</td></tr>

<tr><td>
	ROM Dollars:
</td><td>
	<input type=text size=15 name=rom_dollars value=\"$oiclog_info->rom_dollars\">
</td></tr>

<tr><td>
	Actual Dollars:
</td><td>
	<input type=text size=15 name=actual_dollars value=\"$oiclog_info->actual_dollars\">
</td></tr>

<tr><td title=\"Notice to proceed\">
	NTP
</td><td>
	<select name=ntp>
	<option>$oiclog_info->ntp</option>
	<option>Y</option>
	<option>N</option>
	</select>
	";datebox2($oiclog_info->ntp_date,'oiclog_edit.ntp_date');echo "
</td></tr>
	
<tr><td>
	Status:
</td><td>";
	if (fd_manager($global_jobinfo_id)||pm_for_this_job()) {
		echo "<select name=\"status\">
			<option>$oiclog_info->status</option>
			<option>Pending release for construction</option>
			<option>Approved for construction by PM</option>
			</select>";
		} else {
		echo "<input type=hidden name=\"status\" value=\"$oiclog_info->status\">$oiclog_info->status";
		}
	echo"
</td></tr>

<tr><td>
	Scanned Doc:
</td><td>
	";
	webfilebox($oiclog_info->document_file_group_id,"document_file_group_id");
	
	echo"
	<input type=button onclick=explode_file() value=Explode>
	</td></tr>

<tr><td valign=top>
	Notes:
</td><td>
	<textarea name=notes rows=5 cols=50>$oiclog_info->notes</textarea>
</td></tr>

<tr><td colspan=2>
</td></tr>

<tr><td colspan=2 align=right>
	<input type=submit value=Save>
</td></tr>
</table>
</form>
";




/////////////////////////////////////////////////////////////////////////
// Construction DWG Log integration here.. 
/////////////////////////////////////////////////////////////////////////
//echo "<div id=mgmtofdwg>";
//include("dwg_mgmt.phtml");
//echo "</div>";
/*
echo "<div id=dwg_mgmt>
<table border=1 cellspacing=0 cellpadding=4>
<tr><form name=dwg_add><td>
	<input type=hidden name=file_id_test value='tora tora tora!'>
	";webfilebox2("","file_group_id","add_new_dwg()");echo "
</td></form></tr>

</table>
</div>
";
*/
/////////////////////////////////////////////////////////////////////////

contact_popup_javascript();
load_webfile_javascript();

echo "
<script>


function update_posting_item(posting_id,field_name,field_value) {
	ajaxManager('load_page','$pagename?mode=oic_record_dwg_posting&doc_id=$doc_id&selected_tab=' + posting_id + '&update_field_name=' + field_name + '&update_field_value=' + field_value,'record_dwg_posting');
	}

function box_little(obj) { obj.rows=2; }
function box_big(obj) { obj.rows=10; }

function update_assigned_to(posting_id,contact_id) {
	if (contact_id=='') contact_id='0';
	ajaxManager('load_page','$pagename?mode=oic_record_dwg_posting&doc_id=$doc_id&selected_tab=' + posting_id + '&assigned_to_set=' + contact_id,'record_dwg_posting');
	}

function cfu_select_update(field) {
	eval ('fieldval=document.oiclog_edit.' + field + '.value;');
	ajaxManager('load_page','$pagename?mode=det_cfu_box&doc_id=$doc_id&field=' + field + '&fieldval=' + fieldval,'det_cfu_box');
	}

function cfu_hours_update(field) {
	eval ('fieldval=document.oiclog_edit.' + field + '.value;');
	ajaxManager('load_page','$pagename?mode=det_cfu_box&doc_id=$doc_id&hoursfield=' + field + '&hoursfieldval=' + fieldval,'det_cfu_box');
	}

function comp_date_update(field,value) {
	eval('document.oiclog_edit.' + field + '.style.background=\"yellow\"');
	ajaxManager('load_page','$pagename?mode=todo_completion_dates&doc_id=$doc_id&field='+ field + '&value=' + value,'todo_completion_dates');
	}

function fill_response_date() {
	if (document.oiclog_edit.hidden_reply.value=='') {
		if (document.oiclog_edit.reply_date.value=='') document.oiclog_edit.reply_date.value='$today';
		}
	}

document.reload_cnstdwglog_link=1;

function cnstdwglog_select_section() {
	obj=document.getElementById('cnstdwglog_section_select');
	obj.style.background='yellow';
	ajaxManager('load_page','$pagename?mode=cnstdwglog_linker&oiclog_id=$oiclog_info->oiclog_id&selected_section=' + obj.value,'cnstdwglog_linker_div');
	}

function cnstdwglog_linker_watch() {
	if (document.reload_cnstdwglog_link!=0) {
		document.reload_cnstdwglog_link=0;
		ajaxManager('load_page','$pagename?mode=cnstdwglog_linker&oiclog_id=$oiclog_info->oiclog_id','cnstdwglog_linker_div');
		//alert(\"not zero\");
		} 
		//else {
		//document.append(\"zero<br>\");
		//}
	window.setTimeout('cnstdwglog_linker_watch()',1000);
	}

function cnstdwglog_select_dwg(section) {
	open('$pagename?mode=cnstdwglog_linker_popup&oiclog_id=$oiclog_info->oiclog_id&selected_section=' + section,'cnstdwglog_linker_pu','width=500,height=500,scrollbars=1');
	}

function ajax_trigger() {
	document.reload_cnstdwglog_link=1;
	}

function cnstdwglog_linker_save_attachment(purgatory_id,webfile_object_id) {
	wo=document.getElementById(webfile_object_id);
	value=wo.value;
	cell_id='wf_cell_' + purgatory_id;
	ajaxManager('load_page','$pagename?mode=cnstdwglog_linker_save_attachment&purgatory_id=' + purgatory_id + '&attached_group_id=' + value,cell_id);
	}

function create_cnstdwglog_issuance(jobinfo_id,section) {
	if (confirm('Are you sure you want to create a new issuance in the construction drawing log?')) {
		//alert('create it');
		issuance=document.getElementById('new_issuance_name');
		//alert(issuance.value);
		ajaxManager('load_page','$pagename?mode=cnstdwglog_linker_new_issuance&issuance_jobinfo_id=' + jobinfo_id + '&section=' + section + '&new_issuance_name=' + issuance.value + '&oiclog_id=$oiclog_info->oiclog_id','cnstdwglog_linker_div');
		}
	}

function cnstdwglog_linker_post_file(purgatory_id) {
	//alert(purgatory_id);
	open('$pagename?mode=cnstdwglog_linker_post_file_popup&purgatory_id=' + purgatory_id,'cnstdwglog_post_file_pu','width=600,height=400,scrollbars=1');
	}



</script>

<div style=\"border: 2px solid black; width: 600px;\" id=\"cnstdwglog_linker_div\">
&nbsp;
</div>

<script>
document.getElementById('cnstdwglog_linker_div').ajax_trigger='never';
cnstdwglog_linker_watch();
</script>

<input type=button onclick=\"document.reload_cnstdwglog_link=1\" value=Reload>
";









//fd_doc_box_with_attachments(array('show_types'=>'cnstdwglog,rfi,gcrfi,dailylog','show_attachments'=>'Y'));
//echo "<p>";
//oiclog_doc_box(array('show_types'=>'cnstdwglog,rfi,gcrfi,dailylog','show_attachments'=>'Y','onchange'=>"alert('--object_element_id--')"));
//oiclog_doc_box(array('show_types'=>'cnstdwglog,rfi,gcrfi,dailylog','show_attachments'=>'Y','onchange'=>""));
//oiclog_doc_box(array('show_types'=>'cnstdwglog,rfi,gcrfi,dailylog','show_attachments'=>'Y'));

fd_navs_footer();
?>
