<?

$doc_id=addslashes($doc_id);
$doc_info=getoneb("select * from documents where doc_id = '$doc_id'");
if (!(pm_for_this_job($doc_info->jobinfo_id))) {
	die_security();
	}
if ($doc_info->doc_type!="oiclog") die_security();
$oic_info=getoneb("select * from oiclog where oiclog_id = '$doc_info->app_record_id'");
include("../webfile/storage_settings.cfg");
include("../webfile/local.inc");


delete_webfile_group($oic_info->document_file_group_id);
@mysql_query("delete from oiclog where oiclog_id = '$oic_info->oiclog_id'");
forward('main');
?>
