<?
include("../webfile$devel/storage_settings.cfg");

if ($doc_id=="") die("ERR(1)");
$doc_id=addslashes($doc_id);
$doc_info=getoneb("select * from documents where doc_id = '$doc_id' and doc_type = 'oiclog'");
if (!($doc_info)) die("ERR(1.5)");
$oiclog_info=getoneb("select * from oiclog where oiclog_id = '$doc_info->app_record_id'");
if (!($oiclog_info)) die("ERR(2)");
$job=getoneb("select * from jobinfo where jobinfo_id = '$doc_info->jobinfo_id'");
$sequence=ereg_replace("[^0-9]","",$sequence);
if ($sequence=="") die("ERR(3)");
$sequence=addslashes($sequence); // Shouldn't really be needed, should always be the same, but why not..
$seq_pretty=sprintf("%'04d",$sequence);

$files_res=@mysql_query("select * from webfile_files where file_group_id = '$oiclog_info->document_file_group_id' and mime_type like '%pdf%'");

$file_letter="a";
@mkdir("/tmp/front_desk");
@mkdir("/tmp/front_desk/cook_a_batch");
@mkdir("/tmp/front_desk/cook_a_batch/$global_user->login_name");
@mkdir("/tmp/front_desk/cook_a_batch/$global_user->login_name/$job->contract_num");
@chdir("/tmp/front_desk/cook_a_batch/$global_user->login_name/$job->contract_num");

while ($row=@mysql_fetch_object($files_res)) {
	$oic_number=ereg_replace("[ /]","_",$oiclog_info->oic_number);
	$file_name=$seq_pretty . $file_letter . "-_$job->contract_num_-_oic_-_$oic_number.pdf";
	copy("$storage_root$row->file_path",$file_name);
	if (!(is_file($file_name))) die("ERR(5)");
	$file_letter++;
	}
echo "OK";
exit;
?>
