<?


echo "
<input type=hidden name=jobinfo_form_main value=true>
<table border=1 cellpadding=0 cellspacing=0>
<tr><td bgcolor=#dddddd colspan=2 align=center>
	<b>Marketing Data</b>
</td></tr>

<tr><td>
	Goal Meeting Methods
</td><td>
	<textarea name=mkt_goal_notes rows=5 cols=50>$jobinfo->mkt_goal_notes</textarea>
</td></tr>

<tr><td>
	Contract Value Notes
</td><td>
	<input type=text name=mkt_contract_value_notes size=50 value=\"$jobinfo->mkt_contract_value_notes\">
</td></tr>

</table>
";






?>
