<?
require('header.phtml');
echo "<a href=$pagename?mode=proposal_search><font color=blue>Return to Search Options</font></a><br>";

$create_date_1=vali_date($create_date_1);
$create_date_2=vali_date($create_date_2);

if ($create_date_1=='') die ('ERROR: You must specify both dates for the range');
if ($create_date_2=='') die ('ERROR: You must specify both dates for the range');

$query="select * from bidlist where create_date > '$create_date_1' and create_date < '$create_date_2' order by bidlist_id";
proposal_search_output_1($query);





?>
