<?
echo "
<input type=hidden name=proposal_form_lead_logs value=true>

<table border=1 cellspacing=0 cellpadding=2 width=10% class=\"tableobj\">
<tr><td bgcolor=$table_dark align=center><b>Project Description</b></td></tr>
<tr><td><textarea cols=35 rows=5 name=lead_project_description>$bid_info->lead_project_description</textarea>

<tr><td bgcolor=$table_dark align=center><b>New Lead Note</b></td></tr>
<tr><td><textarea cols=35 rows=5 name=lead_note></textarea><pre></pre></td></tr>
</table>
";
?>
