<?
require('header.phtml');

echo "
<a href=$pagename?mode=reports><font color=blue>Return to reports</font></a><br>

<h2>Please select which groups to run this report for:</h2><hr>

<table border=0 cellspacing=0 cellpadding=5>
<form name=report_1_form method=post action=$pagename>
<input type=hidden name=mode value=reports_output_1b

<tr><td>
	<b>Commercial</b>
</td><td>
	<input type=checkbox name=commercial checked>
</td></tr>

<tr><td>
	<b>Industrial</b>
</td><td>
	<input type=checkbox name=industrial checked>
</td></tr>

<tr><td>
	<b>Service</b>
</td><td>
	<input type=checkbox name=service checked>
</td></tr>

<tr><td>
	<b>Special Projects</b>
</td><td>
	<input type=checkbox name=special_projects checked>
</td></tr>

<tr><td>
	<b>Southern WA</b>
</td><td>
	<input type=checkbox name=southern_wa checked>
</td></tr>


<tr><td colspan=2 align=right>
	<input type=submit value='Go'>
</td></tr>

</table>
";

?>
