<?
require('querylib.inc');
require('header.phtml');
echo "<a href=$pagename?mode=main><font color=blue>Cancel</font></a>";

if ($jobinfo_id != "") {
	$new=0;
	$jobinfo_id=addslashes($jobinfo_id);
	$jobinfo=getone("select * from jobinfo where jobinfo_id = '$jobinfo_id'");
	} else {
	$new=1;
	}

echo "<center>";

include("jobinfo_edit_tabs_start.phtml");

$jobinfo->job_name=ereg_replace(" ","&nbsp;",$jobinfo->job_name);
echo "
<table width=100% bgcolor=#ffffff border=1 cellspacing=0 cellpadding=3 style=\"font-variant: small-caps; font-size: small; font-weight: bold;\">

<tr><td colspan=4 align=center bgcolor=#eeeeee width=100%>
	<i>$jobinfo->contract_num&nbsp;-&nbsp;<i>$jobinfo->job_name</i>
</td></tr>

<tr><td colspan=4 align=center>
	<a href=$pagename?mode=get_vp_job_info&job_num=$jobinfo->contract_num><font color=blue>Sync&nbsp;From&nbsp;Viewpoint</font></a>
</td></tr>

</table>";
include("jobinfo_edit_tabs_end.phtml");

echo "</center>";
?>
