<?
require("header.phtml");
fd_navs_header();
if ($parent_tree_id!="") $parent_tree_id=addslashes($parent_tree_id);
$parent_tree_info=getoneb("select * from file_cabinet_tree where tree_id = '$parent_tree_id'");
if (!($parent_tree_info)) die("Application error: Invalid parent object!");
$parent_tree_template_info=getoneb("select * from file_cabinet_templates where template_id = '$parent_tree_info->template_id'");
//tabledump("select * from file_cabinet_templates where template_id = '$parent_tree_info->template_id'");
//echo "<hr>select * from file_cabinet_templates where template_id = '$parent_tree_info->template_id'<hr>";
//echo "<hr>select * from file_cabinet_templates where template_id = '$parent_tree_info->template_id'<hr>";
if (!($parent_tree_template_info)) die("Application error: Invalid parent template information!");

echo "
<script>
function add_folder(folder_parent,template_id) {
	document.location='$pagename?mode=add_folder_submit&folder_parent=' + folder_parent + '&template_id=' + template_id;
	}
</script>
<a href=$pagename?mode=main&current_folder=$parent_tree_info->tree_id><font color=blue>Cancel</font></a>
<h2>Available Folders</h2><hr>
";
$res=@mysql_query("select * from file_cabinet_templates where folder_parent = '$parent_tree_template_info->template_id' and folder_parent != template_id order by sort_priority, folder_name");
//$total_count=@mysql_num_rows($res);

$folders_list="";
$total_count=0;
while ($row=@mysql_fetch_object($res)) {
	$exists=getoneb("select * from file_cabinet_tree where 
	jobinfo_id = '$global_jobinfo_id' and
	parent_id = '$parent_tree_info->tree_id' and
	folder_name = '$row->folder_name'");
	if ($exists) continue;
	$total_count++;
	$folders_list=$folders_list . "<a href=\"javascript:add_folder('$parent_tree_info->tree_id','$row->template_id')\"><font colur=blue>$row->folder_name</font></a><br>";
	}


//tabledump("





if ($total_count<1) {
	echo "<b>No additional folders available...</b>";
	}
echo "$folders_list";
fd_navs_footer();
?>
