<?
if ($new_folder_name!="") $new_folder_name=addslashes($new_folder_name);
else $new_folder_name="????";
if ($current_folder_id!="") $current_folder_id=addslashes($current_folder_id);
else die("Application error!");
$cfi=getoneb("select * from file_cabinet_tree where tree_id = '$current_folder_id'");
if (!($cfi)) die("Application error looking up folder info");
$query="insert into file_cabinet_tree set jobinfo_id = '$cfi->jobinfo_id', parent_id = '$cfi->tree_id', template_id = '$cfi->template_id', sort_priority = '$cfi->sort_priority', folder_name = '$new_folder_name', folder_description = '$new_folder_name', folder_creator = '$global_user_id', free_for_all = '$cfi->free_for_all', correspondence_children = '$cfi->correspondence_children'";
$res=mysql_query($query);
if (!($res)) die("Query error:<hr>$query");
$id=@mysql_insert_id();
forward("main&current_folder=$id");
?>
