<?
include("../webfile/local.inc");
if ($file_cabinet_id!="") {
	$file_cabinet_id=addslashes($file_cabinet_id);
	} else {
	die("Application error!");
	}
$file_cabinet_info=getoneb("select * from file_cabinet where file_cabinet_id = '$file_cabinet_id'");
if (!($file_cabinet_info)) die ("Application error!");

if (($file_cabinet_info->creator==$global_user_id) || (member_of_global_group_named("IT"))) {
	//echo "<a href=javascript:delete_this_record()><b>Delete</b></a>";
	delete_webfile_group($file_cabinet_info->file_group_id);
	@mysql_query("delete from file_cabinet where file_cabinet_id = '$file_cabinet_info->file_cabinet_id'");
	} else {
	die_security();
	}
forward("main&current_folder=$file_cabinet_info->tree_id");
?>
