<?

if ($tree_id!="") {
	$tree_id=addslashes($tree_id);
	} else {
	die("Application error!");
	}
$tree_info=getoneb("select * from file_cabinet_tree where tree_id = '$tree_id'");
if (!($tree_info)) die("Application error. Directory information error!");
if ($tree_info->free_for_all!="Y") die_security();

$child_trees=getoneb("select * from file_cabinet_tree where parent_id = '$tree_info->tree_id' limit 1");
$child_files=getoneb("select * from file_cabinet where tree_id = '$tree_info->tree_id' limit 1");
if ($child_trees) die("Application error. Item has children that would be orphaned!");
if ($child_files) die("Application error. Item has children that would be orphaned!");



@mysql_query("delete from file_cabinet_tree where tree_id = '$tree_info->tree_id'");
forward("main&current_folder=$tree_info->parent_id");
/*
*/
?>
