<?
require("header.phtml");
fd_navs_header();


if ($kwl!="") {
	$kwl=addslashes($kwl);
	$kwl_form=htmlspecialchars($kwl);
	}

echo "

<a href=$pagename?mode=main><font color=blue>Cancel</font></a>

<form name=file_cabinet_search method=post action=$pagename>
<input type=hidden name=mode value=\"$mode\">

<table border=1 cellspacing=0 cellpadding=5>
<tr><td colspan=2 bgcolor=$fd_color_4 align=center>
	<b>Search Criteria</b>
</td></tr>

<tr><td>
	<b>Keywords</b>
</td><td>
	<input type=text size=20 name=kwl value=\"$kwl_form\">
</td></tr>

<tr><td valign=top>
	<i>examples</i>
</td><td><font size=-1>
	<table border=0 cellspacing=0 cellpadding=2>
	<tr><td>
		\"this that\"
	</td><td>
		=
	</td><td>
		find with \"this\" or \"that\"
	</td></tr>
	
	<tr><td>
		\"this +that\"
	</td><td>
		=
	</td><td>
		find with \"this\" and \"that\"
	</td></tr>
	
	<tr><td>
		\"this -that\"
	</td><td>
		=
	</td><td>
		find with \"this\" but not \"that\"
	</td></tr>
	</table>
	</font>
</td></tr>

<tr><td colspan=2 align=center>
	<input type=button onclick=submit() value=\"Search\">
</td></tr>
</table>
</form>

<script>
document.file_cabinet_search.kwl.focus();
</script>
";




if ($kwl!="") {
	file_search($kwl);
	
	}
















fd_navs_footer();
?>
