<?
$today=date('m-d-Y');
$page_width="700";

$cart_count=getoneb("select sum(quantity) as items from costore_cart where status = 'new' and contacts_id = '$global_user_id'");
if ($cart_count->items>0) $cart_text="&nbsp;($cart_count->items items)";
else $cart_text="";
	

echo "
<html>
<head><title>$dbdescription</title><link rel='stylesheet' type='text/css' href='umcstore.css'>
&nbsp;<br>
&nbsp;&nbsp;&nbsp;<font class='logo'>UMC EMPLOYEE STORE&nbsp;</font>
<span class='tagline'>| CLOTHING, EQUIPMENT, ETC.</span>

<div valign=middle style=\"height: 36px; width: 100%; background: #2a4a93;\">

<div class='adminLinks' style=\"float: right;\"><a class='adminLinks' href='/intra/'>Exit</a></div>
<div class=adminLinks>&nbsp;</div>";
//<div class='adminLinks' style=\"float: right;\"><a class='adminLinks' href='$pagename_up'>Exit</a></div>
// Orig line eyeballed by me probably (Jeff)
// <div valign=middle style=\"height: 36px; width: 100%; background: #003399;\">
// Sniffed from the logo from Gail K
//<div valign=middle style=\"height: 36px; width: 100%; background: #2a4a93;\">

$orders_admin=FALSE;
if (!($adminuser)) {
	$pmjobinfo=("select * from costore_cart_invoice left join jobinfo on (costore_cart_invoice.billing_jobinfo_id = jobinfo.jobinfo_id) where project_manager_id = '$global_user_id' and cart_status = 'PM Approval' limit 1");
	if ($pmjobinfo) $orders_admin=TRUE;
	} else {
	$orders_admin=TRUE;
	}

if($orders_admin) {
	echo "
	<div class='adminLinks'><a href='$pagename?mode=orders_admin' class=adminLinks>ORDERS ADMINISTRATION</a></div>
	<div class='adminLinks'>|</div>";
	}
if ($sum->total>0) $items="&nbsp;($sum->total&nbsp;items)";
echo "<div class='adminLinks'><a class='adminLinks' href='$pagename'>CATALOG</a></div>
<div class='adminLinks'> | </div>
<div class='adminLinks'><a class='adminLinks' href='$pagename?mode=shopping_cart'>SHOPPING&nbsp;CART$cart_text</a></div>
</div></head>

<body bgcolor=\"#0099cc\">
<div width=100% style=\"background: white;\">
<table style=\"width: ${page_width}px; border: 0px solid black;\"><tr><td>
<IMG align='right' SRC='/images/umc_logo_286.png'></td></tr><tr><td>
";


?>
