<?

if ($references_history_id!="") {
	$references_history_id=addslashes($references_history_id);
	$query_start="update ";
	$query_end=" where references_history_id = '$references_history_id'";
	} else {
	$query_start="insert into ";
	$query_end="";
	}

if ($name!="") {
	$application_id=addslashes($application_id);
	$name=addslashes($name);
	$company_title=addslashes($company_title);
	$phone=addslashes($phone);
	$years_known=addslashes($years_known);

	$query_middle="
	hr_applications_references_history set 
	application_id = '$application_id',
	name = '$name',
	company_title = '$company_title',
	phone = '$phone',
	years_known = '$years_known'
	";

	$query_full=$query_start . $query_middle . $query_end;
	$res=@mysql_query($query_full);
	if (!($res)) die("ERROR: Query failed.<br>Failed query:<hr>$query_full");
	}
include("app_forward_mode.phtml");
?>
