<p style="color: black; text-indent: 0mm; line-height: 4.16mm; background-color: white; text-align: left;"><font size="1">UMC Copyright&nbsp;&copy;&nbsp;2004. All rights reserved.</font></p></span></td>

        </tr>
      </table>
      <p>&nbsp;</p>
      </TD>
    <TD WIDTH=214 HEIGHT=153 valign="top" bgcolor="#FFFFFF"> <a href=http://www.umci.com/><IMG SRC="images_umc/home_umclogo.png" WIDTH=214 border=0></TD>
  </TR>
</TABLE>
</BODY>
</HTML></TD>
                    </TR>
                  </TABLE></td>
              </tr>
            </table></td>
        </tr>
      </table></td>
  </tr>
  <tr>
    <td valign="top"><br>
    </td>
  </tr>
</table>
<p>&nbsp; </p>
<p>&nbsp; </p>
</BODY>
</HTML>
