<HTML>
<HEAD>
<TITLE>UMC Employment Opportunities</TITLE>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<SCRIPT LANGUAGE="Javascript" src="http://www.umci.com/umci_javascripts.js" type="text/javascript"></SCRIPT>
<link rel="stylesheet" href="stylesheet.css" type="text/css">
<link href="umci_stylesheet.css" rel="stylesheet" type="text/css">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}
//-->
</script>
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_reloadPage(init) {  //reloads the window if Nav4 resized
  if (init==true) with (navigator) {if ((appName=="Netscape")&&(parseInt(appVersion)==4)) {
    document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}
  else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();
}
MM_reloadPage(true);
//-->
</script>
</HEAD>
<BODY BGCOLOR=#FFFFFF onLoad="MM_preloadImages('images_umc/home_button_over_placeholder.gif','images_umc/_buttons/return_roll.gif')">
<table width="750" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr> 
    <td><table width="750" border="0" align="center" cellpadding="1" cellspacing="0" bgcolor="#333333">
        <tr> 
          <td><table width="100%" border="0" align="center" cellpadding="1" cellspacing="0" bordercolor="#000000">
              <tr> 
                <td valign="top"><TABLE WIDTH=100% BORDER=0 CELLPADDING=0 CELLSPACING=0>
                    <TR> 
                      <TD WIDTH=100% HEIGHT=34 align="right" valign="top" bgcolor="#666666"> 
                        
                        <div align="right">
                        <?if (FALSE) echo "<a href=\"https://pipeline.umci.com/\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage('intranet','','images_umc/_buttons/intranet_roll.gif',1)\"><img src=\"images_umc/_buttons/intranet.gif\" name=\"intranet\" width=\"87\" height=\"35\" border=\"0\"></a>";?>
                        <a href="http://www.umci.com/" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('contact','','images_umc/_buttons/return_roll.gif',1)"><img src="images_umc/_buttons/return.gif" name="contact" width="87" height="35" border="0"></a>
                        </div></TD>
                    
                    </TR>
                    <TR> 
                      <TD WIDTH=743 HEIGHT=200 valign="top" bgcolor="#CCCCCC">
                      <? $image_num=rand(1,5); ?>
                      <img src="images_umc/employment_main_<?echo"$image_num";?>.jpg" width="750" height="200" border="0">
                      </TD>
                    </TR>
                    <TR> 
                      <TD WIDTH=743 HEIGHT=49 valign="top" bgcolor="#999999"><a href="" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('p1','','images_umc/home_button_over_placeholder.gif',1)"><img src="images_umc/home_button_placeholder.gif" name="p1" width="125" height="49" border="0" align="top"></a><a href="" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('p2','','images_umc/home_button_over_placeholder.gif',1)"><img src="images_umc/home_button_placeholder.gif" name="p2" width="137" height="49" border="0" align="top"></a><a href="" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('p3','','images_umc/home_button_over_placeholder.gif',1)"><img src="images_umc/home_button_placeholder.gif" name="p3" width="158" height="49" border="0" align="top"></a></TD>
                    </TR>
                    <TR> 
                      <TD WIDTH=100% HEIGHT=214 valign="top" bgcolor="#FFFFFF"><HTML>
<HEAD>
<TITLE>home_inner01</TITLE>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
</HEAD>
<BODY BGCOLOR=#FFFFFF>
<TABLE WIDTH=743 BORDER=0 CELLPADDING=0 CELLSPACING=0>
  <TR> 
    <TD WIDTH=101 rowspan="3" valign="top" bgcolor="#FFFFFF">&nbsp; </TD>
    <TD HEIGHT=45 colspan="2" valign="top" bgcolor="#FFFFFF">&nbsp; </TD>
  </TR>
  <TR> 
    <TD WIDTH=428 HEIGHT=16 valign="top"> <IMG SRC="images_umc/home_employment_opportunities.gif" WIDTH=428 HEIGHT=16></TD>
    <TD WIDTH=214 HEIGHT=16 bgcolor="#FFFFFF">&nbsp; </TD>
  </TR>
  <TR> 
    <TD WIDTH=428 HEIGHT=153 valign="top" bgcolor="#FFFFFF"><table width="71%" border="0" cellpadding="0">
        <tr>
          <td><span class="body">
