<?
if ($batch_number!="") $batch_number=addslashes($batch_number);
else die("Error: Invalid batch number! (Application error?)");

$batch_info=getoneb("select * from positivepay_batch_history where batch_number = '$batch_number'");
log_batch_activity($batch_info->batch_id,"Batch posted");


@mysql_query("update positivepay_trans_history set status = 'posted', post_date = now() where batch_number = '$batch_number'");
forward('batch_mgmt');
?>
