<?
require('header.phtml');

echo "
<h3>Positive Pay Options</h3>
<a href=$pagename?mode=download_form><font color=blue>Start a new batch</font></a><br>
<a href=$pagename?mode=batch_mgmt><font color=blue>View/manage old batches</font></a>
<p>
<a href=$pagename?mode=account_list><font color=blue>Manage Accounts</font></a><p>

<a href=$pagename_up><font color=blue>Exit</font></a>
<hr>
<a href=$pagename?mode=401k_menu><font color=blue>401k Download</font></a>
";





?>
