<?
require_once('querylib.inc');
if ($hr_opening_bullets_id!="") {
	$hr_opening_bullets_id=addslashes($hr_opening_bullets_id);
	$bullet_info=getone("select * from hr_opening_bullets where hr_opening_bullets_id = '$hr_opening_bullets_id'");
	$bullet_category=$bullet_info->bullet_category;
	$hr_openings_id=$bullet_info->hr_openings_id;
	$allow_responses=checkbreak($bullet_info->allow_responses);
	} else {
	$bullet_category=addslashes($bullet_category);
	$hr_openings_id=addslashes($hr_openings_id);
	}
if ($bullet_category=="") die("Application Error: Bullet category not set. Please contact your system administrator");
if ($hr_openings_id=="") die("Application Error: HR openings id not set. Please contact your system administrator.");

//echo "$bullet_category<hr>";
//echo "hi";
require('header.phtml');
echo "
<form name=bullet_edit method=post action=$pagename>
<input type=hidden name=mode value=bullet_submit>
<input type=hidden name=bullet_category value=\"$bullet_category\">
<input type=hidden name=hr_openings_id value=\"$hr_openings_id\">
<input type=hidden name=hr_opening_bullets_id value=\"$hr_opening_bullets_id\">

<h3>Bullet edit</h3><hr>
<table border=0>
<tr><td valign=top>
	<b>Bullet Text:</b>
</td><td>
	<textarea name=bullet_text rows=5 cols=40>$bullet_info->bullet_text</textarea>
</td></tr>

<tr><td valign=top>
	<b>Sort Priority:</b>
</td><td>
	<input type=text size=2 name=sort_priority value=\"$bullet_info->sort_priority\">
</td></tr>


";

switch ($bullet_category) {
	
	///////////////////////////////////////////////////////////////
	case "requirements":
		echo "
		<tr><td>
			<b>Allow Responses?</b>
		</td><td>
			<input type=checkbox name=allow_responses $allow_responses>
		</td></tr>";
		break;
	///////////////////////////////////////////////////////////////
	case "questions":
		echo "<input type=hidden name=allow_responses value=\"on\">";
		break;
	///////////////////////////////////////////////////////////////
	default:
		echo "<input type=hidden name=allow_responses value=\"\">";
		break;
	///////////////////////////////////////////////////////////////
	
	}
echo "
<tr><td colspan=2 align=right><input type=submit value=\"Save\"></td></tr>	
</table>
</form>
";

if ($hr_opening_bullets_id!="") echo "<a href=$pagename?mode=bullet_delete&hr_opening_bullets_id=$hr_opening_bullets_id><font color=blue>DELETE</font></a>";



?>
