<?
require('header.phtml');
echo "

<table border=0 cellspacing=0 cellpadding=4>
<tr><td valign=top>
	<b>Asian</b>
</td><td>
	Persons having origins in any of the original peoples of the Far east, Southeast Asia, the Indian Subcontinent, or the Pacific Islands.
</td></tr>

<tr><td valign=top>
	<b>Black</b>
</td><td>
	Persons having origins in any of the Black African racial groups not of Hispanic origin.
</td></tr>

<tr><td valign=top>
	<b>Hispanic</b>
</td><td>
	Persons of Mexican, Puerto Rican, Cuban, Central or South American or other Spanish Culture or origin, regardless of race.
</td></tr>

<tr><td valign=top>
	<b>Native American</b>
</td><td>
	Persons having origins in any of the original peoples of North America and maintaining identifieable tribal affiliations through membership and participation or community identification.
</td></tr>

<tr><td valign=top>
	<b>White</b>
</td><td>
	Persons having origins in any of the original peoples of Europe, North Africa, and the Middle East who are not of Hispanic origin.
</td></tr>



";
?>
