<?
require('header.phtml');
echo "
<font size=+1>
<table border=0 cellspacing=0 cellpadding=4>
<tr><td valign=top>
	<b>*Special Disabled Veteran</b>
</td><td>
	Entitled to disability compensation for a disability rated at 30@ or more; a disability rate at less than 30@, but have been determined to hav a serious employment disability; or discharged or released from active duty because of a service-connected disability.
</td></tr>

<tr><td valign=top>
	<b>Other Eligable Veteran</b>
</td><td>
	Served in the military, ground, haval or air servies of the United States on active duty during a war or in a campaign or expedition for which a campaign badge has been authorized.
</td></tr>

<tr><td colspan=2>
	<b>*If you are a person with a disability, you can assist us by describing accommodations that may be needed to enable you to safely perform the essential functions of the job. Requests for reasonable accommodations should be discussed with Human Resources of your immediate supervisor.</b>
</td></tr>




</font>


";
?>
