<?

if ($service_id!="") {
	$service_id=addslashes($service_id);
	$service_info=getone("select * from access_servers_services where service_id = '$service_id'");
	$server_id=$service_info->server_id;
	} else {
	$service_info->active='Y';
	}
$service_info->active=checkbreak($service_info->active);

if (($server_id=="") || ($server_id <1)) {
	die("Failed to detect server information! Please contact your system administrator (is that you?)");
	} else {
	$server_id=addslashes($server_id);
	$server_info=getone("select * from access_servers where server_id = '$server_id'");
	}
require('header.phtml');


echo "
<form name=services_edit action=$pagename method=post>
<input type=hidden name=mode value=servers_services_submit>
<input type=hidden name=server_id value=\"$server_info->server_id\">
<input type=hidden name=service_id value=\"$service_info->service_id\">

<table border=1 cellspacing=0 cellpadding=4>
<tr><td colspan=2 align=center bgcolor=#dddddd>
	<b>Edit service for \"$server_info->name\"</b>
</td></tr>


<tr><td>
	<b>Service Type</b>
</td><td>
	";dropbox("select service_type_id,name from access_service_types order by name",$service_info->service_type_id,"","",1);echo"
</td></tr>

<tr><td>
	<b>Active</b>
</td><td>
	<input type=checkbox name=active $service_info->active>
</td></tr>

<tr><td valign=top>
	<b>Configuration Details</b>
</td><td>
	<textarea name=config_details rows=10 cols=50>$service_info->config_details</textarea>
</td></tr>

<tr><td colspan=2 align=right>
	<input type=submit value=Save>
</td></tr>

</table>
</form>
";





?>
