<?
if (!($admin_check)) die("ERROR: not an admin!");



echo "
<a href=$pagename><font color=blue>Return to Main Menu</font></a><p>

<a href=$pagename?mode=admin_reports_mileage_form><font color=blue>Mileage report</font></a><br>
<a href=$pagename?mode=admin_reports_user_timesheets_form><font color=blue>Print Series for specific user</font></a><br>
<a href=$pagename?mode=admin_reports_timesheets_by_contract_form><font color=blue>Timesheets by Contract</font></a><br>
<a href=$pagename?mode=admin_reports_overview_form><font color=blue>Timesheet Summaries</font></a><br>
<a href=$pagename?mode=admin_user_selection><font color=blue>Timesheet History by Employee</font></a>






";











?>
