<?
if ($group_id=="") die("ERROR: No Group Specified.. Please contact your administrator or try again/start over.<br>");
$group_info=getone("select * from timesheet_foreman_groups where group_id = '$group_id'");

if ($group_info->foreman_id!=$global_user->contacts_id) die("ERROR: Security Violation! The authorities have been notified!");
	
require('header.phtml');
echo "
<a href=$pagename?mode=foreman_group_edit&group_id=$group_info->group_id><font color=blue>Return to <u>$group_info->group_name</u> properties
<br>
<h2><center>Available to add to $group_info->group_name</center></h2><hr>";


echo "<table border=0>";
$query="select * from contacts where employee_group = '1' and current = 'Y' order by last_name, first_name, employee_num";
$res=@mysql_query($query);
while ($row=@mysql_fetch_object($res)) {
	if (!(getoneb("select * from timesheet_group_members where group_id = '$group_id' and employee_id = '$row->contacts_id'"))) {
		echo "<tr><td>
				$row->last_name, $row->first_name ($row->employee_num)
			</td><td>
				<a href=$pagename?mode=foreman_group_membership_add&group_id=$group_id&employee_id=$row->contacts_id><font color=blue>Add</font</a>
			</td></tr>";
		}
	}
echo "</table>";







?>
