<?
if ($group_id!="") $group_id=escapeshellcmd($group_id);
	else die ("ERROR: Missing group_id. Please contact your administrator, or try again (start over).");
if ($employee_id!="") $employee_id=escapeshellcmd($employee_id);
	else die ("ERROR: Missing employee_id. Please contact your administrator, or try again (start over).");

$contact_info=getone("select * from contacts where contacts_id = '$employee_id'");
if ($contact_info->employee_group!=1) die("ERROR: Security Violation!!! The authorities have been notified!");

$group_info=getone("select * from timesheet_foreman_groups where group_id = '$group_id'");
if ($group_info->foreman_id!=$global_user->contacts_id) die ("ERROR: Security Violation! The authorities have been notified!");

$query="insert into timesheet_group_members set group_id = '$group_id', employee_id = '$employee_id'";
$res=@mysql_query($query);
//if (!($res)) die ("ERROR: Update Failed. Please contact your system administrator or try again.<p>Failed Query:<hr>$query");
forward("foreman_group_edit&group_id=$group_id");
?>
