<?

$ts_id=escapeshellcmd($ts_id);
//echo "<hr>select * from timesheet_index where timesheet_id = '$ts_id'<hr>";
$timesheet_info=getone("select * from timesheet_index where timesheet_id = '$ts_id'");
$timesheet_dates=date_info(invali_date($timesheet_info->week_ending));

if (!(i_have_underlings($global_user->employee_num)))  die("ERROR: Security violation! The authorities are being notified!");

$query="update timesheet_index set reviewed = 'Y', reviewer_id = '$global_user->contacts_id' where timesheet_id = '$ts_id'";

$res=@mysql_query($query);
if (!($res)) die("fatal error: first stage mark for process. Please contact your system administrator.");

if ($all==1) 
	forward('supervisor_unapproved_selection');
else
	forward('supervisor_timesheet_selection');

?>
