<?
//if (!($payroll_check)) die("ERROR: Security violation! The authorities are being notified!");

$ts_id=escapeshellcmd($ts_id);
$timesheet_info=getone("select * from timesheet_index where timesheet_id = '$ts_id'");
$timesheet_dates=date_info(invali_date($timesheet_info->week_ending));

if (!($timesheet_info->employee_id == $current_user_id))  die("ERROR: Security violation! The authorities are being notified!");

$query="update timesheet_index set status = 'new' where timesheet_id = '$ts_id'";
$query2="update timesheet_time set timesheet_status = 'new' where employee_id = '$timesheet_info->employee_id' and employee_num = '$timesheet_info->employee_num' and workday >= '$timesheet_dates->week_start_mysql' and workday <= '$timesheet_dates->week_end_mysql'";

$res=@mysql_query($query);
if (!($res)) die("fatal error: first stage mark for process. Please contact your system administrator.");
$res=@mysql_query($query2);
if (!($res)) die("fatal error: second stage mark for process. Please contact your system administrator.");

forward('main');

?>
