<?
//require('timesheet_libs.inc');
//require('timesheet_include.inc');

echo "<body bgcolor=white>
<script>
window.focus();
</script>
";

if ($job_num=="") {
	echo "Error: You must first specify a job number.<p>
	<a href=javascript:self.close();><font color=blue>CLOSE</font></a>";
	exit;
	}

$job_info=is_valid_viewpoint_job(escapeshellcmd($job_num));

if (!($job_info)) {
	echo "Error: Invalid job specified. Please change your job, and try again.<p>
	<a href=javascript:self.close();><font color=blue>CLOSE</font></a>";
	exit;
	}
	
$plquery="select * from JCJM with (NOLOCK) where JCCo = 1 and Job = '$job_info->job' and LockPhases = 'Y'";
//$plquery="select * from JCJM where JCCo = 1 and Job like '$job_info->job%' and LockPhases = 'Y'";
//echo "<hr>$plquery<hr>";
//ms_tabledump($plquery);
$phases_locked=ms_getoneb($plquery);
//$phases_locked=TRUE;
//$phases_locked=FALSE;
if ($phases_locked) {
	$query="select * from JCJP with (NOLOCK) INNER JOIN JCCH with (NOLOCK) on JCJP.JCCo = JCCH.JCCo and JCJP.Job = JCCH.Job and JCJP.Phase = JCCH.Phase where JCJP.Job = '$job_info->job' and JCJP.JCCo = 1 and JCJP.ActiveYN = 'Y' and JCCH.CostType = '8' and JCJP.Phase not like 'YYYYY%'";
	} else { 
	
	echo "<B>Warning, this job seems to have unlocked phases set. Unless this is a service job this is most
	likely an error. Please contact the jobs contract administrator to have
	the problem corrected!</b>";
	//$query="select * from bJCPC,bJCPM where bJCPC.Phase = bJCPM.Phase and bJCPC.CostType = 8 and bJCPC.PhaseGroup = '1' and bJCPM.PhaseGroup = 8 and bJCPC.Phase not like 'YYYYY%'";
	//$query="select * from bJCPC,bJCPM where 
	//bJCPC.Phase = bJCPM.Phase and 
	//bJCPC.CostType = 8 and 
	//bJCPC.PhaseGroup = '1' and 
	//bJCPM.PhaseGroup = 8 and 
	//bJCPC.Phase not like 'YYYYY%'";
	
	//$query="select * from bJCPM,bJCPC where bJCPM.Phase = bJCPM.Phase and bJCPC.PhaseGroup = 1 and CostType = 8";
	$query="select * from JCPC with (NOLOCK) left join JCPM with (NOLOCK) on (JCPC.Phase = JCPM.Phase and JCPC.JCCo = JCPM.JCCo ) where JCPC.JCCo = 1 and JCPC.PhaseGroup = 1 and JCPC.CostType = 8 and JCPC.Phase not like 'YYYYY%' and ud2003phase = 'Y'";
	$query="select * from JCPM with (NOLOCK) left outer join JCPC with (NOLOCK) on JCPM.PhaseGroup = JCPC.PhaseGroup and JCPM.Phase = JCPC.Phase 
		where JCPC.CostType = 8 and JCPM.PhaseGroup = 1 and JCPM.Phase not like 'YYYY%'";
	
	//ms_tabledump($query);
	//echo "<hr>$query<hr>";
	}

echo "<table border=0>
<script>
function setvalue(phase) {
	opener.document.add_time.phase.value=phase;
	self.close();
	}
</script>
";
$res=@mssql_query($query);
while($row=@mssql_fetch_object($res)) {
	$row->Phase=ereg_replace(" *","",$row->Phase);
	$row->Phase=ereg_replace("-*$","",$row->Phase);

	echo "<tr><td>
			<a href=javascript:setvalue('$row->Phase');><font color=blue>$row->Phase</a>
		</td><td>
			$row->Description
		</td></tr>";
	}
echo "</table></body>";
?>
