<?
require("timesheet_header.phtml");
require("timesheet_footer.phtml");

if ($timesheet_summary_showalldays_set!="") {
	if ($timesheet_summary_showalldays==1) $timesheet_summary_showalldays=0;
	else $timesheet_summary_showalldays=1;
	}
if ($timesheet_summary_showalldays=="") {
	session_register('timesheet_summary_showalldays');
	$timesheet_summary_showalldays=0;
	}
if ($timesheet_summary_showalldays==0) $showalldays_text="Show All Days";
	else $showalldays_text="Hide Empty Days";

echo "
<table border=0 cellpadding=4><tr><td>
<form name=changejobview method=post action=$pagename>
<input type=hidden name=mode value=timesheet_edit>
<input type=hidden name=timesheet_mode_new value=timesheet_summary_by_job>
<input type=submit value=\"View By Job\">
</form></td>

<td>
<form name=showpdf method=get action=$pagename>
<input type=hidden name=mode value=timesheet_summary_pdf>
<input type=button value='Download PDF' onclick=document.location=\"$pagename?mode=timesheet_summary_pdf&blah=blah/timesheet.pdf\";>
</form>
</td>
";

if ($timesheet_info->status=="new") {
	echo "
	<td>
	<form name=togglesumview method=post action=$pagename>
	<input type=hidden name=mode value=timesheet_edit>
	<input type=hidden name=timesheet_summary_showalldays_set value=toggle>
	<input type=submit value=\"$showalldays_text\">
	</form></td>
	
	<td>
	<form name=timesheet_confirm_form method=get onsubmit=\"return confirm('You\'re sure you\'re done?')\" action=$pagename>
	<input type=hidden name=mode value=timesheet_submit>
	<input type=hidden name=employee_num value=\"$current_user->employee_num\">
	<input type=hidden name=week_ending value=$timesheet_info->week_ending>
	<input type=submit value=\"Submit Timesheet\" style=\"background: yellow\">
	</form></td>
	
	<script>

	function confirm_timesheet() {
	if (confirm('You\'re sure you\'re done?')) document.timesheet_confirm_form.submit();
	}
	
	</script>
	";
	}

echo "</tr></table>";

$counter=0;
if ($timesheet_info->status=="new") $noedit=0;
	else $noedit=1;

$total_weeks_hours=0;
$total_st_hours=0;
$total_ot_hours=0;
$total_dt_hours=0;
$total_v_hours=0;
$total_s_hours=0;
$total_h_hours=0;
$total_subs=0;
$total_park=0;
$total_trav=0;
$total_exps=0;

while ($counter < 7) {
	$tmp=print_day("$current_user->contacts_id",$week_info[$counter]->date,$timesheet_summary_showalldays,"timesheet_summary",$noedit);
	$total_weeks_hours=$tmp->total_hours + $total_weeks_hours;
	$total_st_hours=$total_st_hours + $tmp->sum_st;
	$total_ot_hours=$total_ot_hours + $tmp->sum_ot;
	$total_dt_hours=$total_dt_hours + $tmp->sum_dt;
	$total_v_hours=$total_v_hours + $tmp->sum_v;
	$total_s_hours=$total_s_hours + $tmp->sum_s;
	$total_h_hours=$total_h_hours + $tmp->sum_h;
	$total_subs=$total_subs + $tmp->subs;
	$total_park=$total_park + $tmp->park;
	$total_trav=$total_trav + $tmp->trav;
	$total_exps=$total_exps + $tmp->exps;

	$counter++;
	}
echo "<table border=0>";

$total_subs=sprintf('%.2f',$total_subs);
$total_park=sprintf('%.2f',$total_park);
$total_trav=sprintf('%.2f',$total_trav);
$total_exps=sprintf('%.2f',$total_exps);

if ($total_subs!=0) echo "<tr><td align=right>Subsistence</td><td align=right>\$$total_subs</td></tr>";
if ($total_park!=0) echo "<tr><td align=right>Parking</td><td align=right>\$$total_park</td></tr>";
if ($total_trav!=0) echo "<tr><td align=right>Travel</td><td align=right>\$$total_trav</td></tr>";
if ($total_exps!=0) echo "<tr><td align=right>Total&nbsp;S/P/T</td><td align=right>&nbsp;&nbsp;\$$total_exps</td></tr>";

if ($total_st_hours!=0) echo "<tr><td align=right>Straight&nbsp;Time&nbsp;Hours</td><td align=right>$total_st_hours</td></tr>";
if ($total_ot_hours!=0) echo "<tr><td align=right>Overtime&nbsp;Hours</td><td align=right>$total_ot_hours</td></tr>";
if ($total_dt_hours!=0) echo "<tr><td align=right>Doubletime&nbsp;Hours</td><td align=right>$total_dt_hours</td></tr>";
if ($total_v_hours!=0) echo "<tr><td align=right>Vacation&nbsp;Hours</td><td align=right>$total_v_hours</td></tr>";
if ($total_s_hours!=0) echo "<tr><td align=right>Sick&nbsp;Hours</td><td align=right>$total_s_hours</td></tr>";
if ($total_h_hours!=0) echo "<tr><td align=right>Holiday&nbsp;Hours</td><td align=right>$total_h_hours</td></tr>";

echo "<tr><td align=right>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Total Hours:</td><td align=right>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$total_weeks_hours</td></tr></table>";

$sick_avail=employee_sick_hours($current_user->employee_num);
$sick_avail_rounded=round($sick_avail,2);
$vac_avail=employee_vacation_hours($current_user->employee_num);

if (($total_st_hours > 40) && ($current_user->overtime_exempt=="N")) 
	echo "<h2><font color=red>THE SHANE WARNING: YOU'RE NOT OVERTIME EXEMPT, BUT YOU HAVE MORE THAN 40 HOURS OF STANDARD TIME. ANYTHING OVER 40 HOURS SHOULD BE OVERTIME!!!!!!!!! PLEASE CORRECT THIS!</font></H1>
	<script>
	alert('TOO MANY STANDARD TIME HOURS! (Shane, is that you?)');
	</script>
	";

if (($total_v_hours > $vac_avail)&&($timesheet_info->status!="posted"))
	echo "<h2><font color=red>VACATION WARNING: YOU'VE EXCEEDED YOUR CURRENTLY AVAILABLE VACATION HOURS.<br>Current Vacation Time Balance is $vac_avail.</font></H1>
	<script>
	alert('YOU HAVE EXCEEDED YOUR CURRENTLY AVAILABLE VACATION HOURS. Current Vacation Balance: $vac_avail');
	</script>
	";

if (($total_s_hours > $sick_avail)&&($timesheet_info->status!="posted"))
	echo "<h2><font color=red>SICK TIME WARNING: YOU'VE EXCEEDED YOUR CURRENTLY AVAILABLE SICK TIME HOURS.<br>Current Available Sick Time Balance is approximately $sick_avail_rounded hours.</font></H1>
	<script>
	alert('YOU HAVE EXCEEDED YOUR CURRENTLY AVAILABLE SICK TIME HOURS. Current Sick Time Balance: $sick_avail_rounded');
	</script>
	";


?>
