<?
require('header.phtml');
fd_navs_header();
ajax_load();

$today=date('m/d/Y');

$query_search_add=query_search_add_text();
$query="select * from sketchlog where jobinfo_id = '$global_jobinfo->jobinfo_id' and section = '$current_sketchlog_section' $query_search_add order by sort_priority,sketch_num desc";
/*
if ($search_text!="") {
	$search_text=addslashes($search_text);
	$query="select * from sketchlog where jobinfo_id = '$global_jobinfo->jobinfo_id' and section = '$current_sketchlog_section' and 
	( 
	sketch_num like '%$search_text%' or 
	dwg_title like '%$search_text%' or 
	floor like '%$search_text%' or 
	area like '%$search_text%' ) 
	order by sort_priority,sketch_num desc";
	}
*/

echo "
<style>  
	@media print { 
	th { font-family: arial; font-size: 8pt; }
	td { font-family: arial; font-size: 8pt; }
	}
</style>
                                

<script>
function quick_form(field,item) {
	if (item.onclick_save==item.onclick) return false;
	item.onclick_save=item.onclick;
	ajaxManager('load_form','$pagename?mode=quick_form&field=' + field + '&sketchlog_id=' + item.parentNode.id,item.id);
	}
function save_data(sketch_id,field,item) {
	item.style.background='yellow';
	document.getElementById(field + '_' + sketch_id).onclick_save='';
	ajaxManager('load_page','$pagename?mode=quick_save_data&field=' + field + '&sketchlog_id=' + sketch_id + '&data=' + item.value,item.parentNode.parentNode.id);
	}
</script>
";

if ($global_jobinfo) {
	echo "
	<script>
	function sketch_new() {
	if (confirm('Create new sketch. Are you sure?')) document.location='$pagename?mode=sketchlog_edit&jobinfo_id=$global_jobinfo->jobinfo_id';
	}
	</script>
	<table id='sub_application_main_table' border=1 cellspacing=0 cellpadding=5>
	<thead>
	<tr><td colspan=10>";search_div();echo "<center>
	<b><font size=+2>Sketchlog</font><br>Job $global_jobinfo->contract_num:&nbsp;$global_jobinfo->display_name<br>$today</b>";
	echo "<br class=noprint><a class=noprint href=\"javascript:sketch_new()\"><font class=noprint color=blue>Add Sketch</font></a>";

	
	$res=@mysql_query($query);
	include("fd_log_paging.phtml");

	
	echo "<br>$page_page_insert</center></td></tr>
	<tr class=floatheader bgcolor=\"$fd_color_4\"><td>
		&nbsp;
	</td><td>
		<b>Sketch&nbsp;#</b>
	</td><td>
		<b>Description</b>
	</td><td>
		<b>Rev</b>
	</td><td>
		<b>Rev&nbsp;Date</b>
	</td><td>
		<b>Orig&nbsp;Issue</b>
	</td><td>
		<b>Sent&nbsp;to&nbsp;Field</b>
	</td><td>
		<b>Submitted&nbsp;to</b>
	</td>";
	if ($global_jobinfo->fd_dwg_cust_1_used=='Y') echo "<td><b>$global_jobinfo->fd_dwg_cust_1_name</b></td>";
	if ($global_jobinfo->fd_dwg_cust_2_used=='Y') echo "<td><b>$global_jobinfo->fd_dwg_cust_2_name</b></td>";
	if ($global_jobinfo->fd_dwg_cust_3_used=='Y') echo "<td><b>$global_jobinfo->fd_dwg_cust_3_name</b></td>";
	if ($global_jobinfo->fd_dwg_cust_4_used=='Y') echo "<td><b>$global_jobinfo->fd_dwg_cust_4_name</b></td>";
	if ($global_jobinfo->fd_dwg_cust_5_used=='Y') echo "<td><b>$global_jobinfo->fd_dwg_cust_5_name</b></td>";
	echo"<td><b>Notes</b></td></tr></thead><tbody "; if ($global_browser!='IE') echo "class=floatheader";echo">";

	while($row=@mysql_fetch_object($res)) {
		$temp_doc_id_query="select * from documents where doc_type = 'sketchlog' and section = '$row->section' and app_record_id = '$row->sketchlog_id'";
		$temp_doc_info=getoneb($temp_doc_id_query);
		$temp_doc_id=$temp_doc_info->doc_id;
		$file_batch=batch_this_document($temp_doc_id);
		$s_sep="";
		$st_text="";
		if ($row->submitted_to_umc=='Y') { $st_text=$st_text . $s_sep . "umc";$s_sep=","; }
		if ($row->submitted_to_gc=='Y') { $st_text=$st_text . $s_sep . "gc";$s_sep=","; }
		if ($row->submitted_to_owner=='Y') { $st_text=$st_text . $s_sep . "owner";$s_sep=","; }
		if ($row->submitted_to_consultant=='Y') { $st_text=$st_text . $s_sep . "consultant";$s_sep=","; }
		if ($st_text=="") $st_text="&nbsp;";
		if (getoneb("select * from sketchlog_notes where sketchlog_id = '$row->sketchlog_id' limit 1")) {
			$notesimage="<img src=/images/note.png>";
			} else {
			$notesimage="&nbsp;";
			}
		$orig_issue=invali_date($row->orig_issue,'/');
		$current_rev_date=invali_date($row->current_rev_date,'/');

		$current_rev=getoneb("select * from sketchlog_revs where sketchlog_id = '$row->sketchlog_id' order by revision desc,rev_date desc, sketch_rev_id desc limit 1");
		if ($current_rev->sent_to_field_date!="0000-00-00") $stf="X";
		else $stf="&nbsp;";
		
		$file_paperclip=webfile_paperclip_download($current_rev->attached_file_group_id,"&nbsp;");
		$file_batch=batch_this_document($temp_doc_id);

		if ($current_rev_date=="") $current_rev_date="&nbsp;";
		echo "<tr id='$row->sketchlog_id'><td style=\"padding: 0; padding-left: 5; padding-right: 5;\"><table border=0 cellspacing=0 cellpadding=0><tr><td>$file_paperclip&nbsp;</td><td>$file_batch</td></tr></table></td>
			<td>";
				if (($write)||(($guest)&&($global_user_id==$row->creator))) {
					echo "<a href=$pagename?mode=sketchlog_edit&sketchlog_id=$row->sketchlog_id><font color=blue>$row->sketch_num</font></a>";
					} else {
					echo "$row->sketch_num";
					}
				echo "
			</td>
			<td id=\"dwg_title_$row->sketchlog_id\" onclick=quick_form('dwg_title',this)>
				$row->dwg_title
			</td><td>
				$row->revision
			</td><td>
				$current_rev_date
			</td><td>
				$orig_issue&nbsp;
			</td><td align=center>
				$stf
			</td><td align=center>
				$st_text
			</td>";
			if ($global_jobinfo->fd_dwg_cust_1_used=='Y') echo "<td id=\"cust_1_$row->drawing_id\" onclick=quick_form('cust_1',this)>$row->cust_1&nbsp;</td>";
			if ($global_jobinfo->fd_dwg_cust_2_used=='Y') echo "<td id=\"cust_2_$row->drawing_id\" onclick=quick_form('cust_2',this)>$row->cust_2&nbsp;</td>";
			if ($global_jobinfo->fd_dwg_cust_3_used=='Y') echo "<td id=\"cust_3_$row->drawing_id\" onclick=quick_form('cust_3',this)>$row->cust_3&nbsp;</td>";
			if ($global_jobinfo->fd_dwg_cust_4_used=='Y') echo "<td id=\"cust_4_$row->drawing_id\" onclick=quick_form('cust_4',this)>$row->cust_4&nbsp;</td>";
			if ($global_jobinfo->fd_dwg_cust_5_used=='Y') echo "<td id=\"cust_5_$row->drawing_id\" onclick=quick_form('cust_5',this)>$row->cust_5&nbsp;</td>";
			echo "<td>$notesimage</td></tr>";
		}
	echo "<tr><td colspan=10 height=100%></td></tr></table>";
	}
fd_navs_footer();
?>
