<?
include("../webfile$devel/storage_settings.cfg");

//die("fooberry");
if ($doc_id=="") die("ERR(1)");
$doc_id=addslashes($doc_id);
$doc_info=getoneb("select * from documents where doc_id = '$doc_id' and doc_type = 'sketchlog'");
if (!($doc_info)) die("ERR(1.5)");
$sketch_info=getoneb("select * from sketchlog where sketchlog_id = '$doc_info->app_record_id'");
if (!($sketch_info)) die("ERR(2)");

$job=getoneb("select * from jobinfo where jobinfo_id = '$doc_info->jobinfo_id'");
$sequence=ereg_replace("[^0-9]","",$sequence);
if ($sequence=="") die("ERR(3)");
$sequence=addslashes($sequence); // Shouldn't really be needed, should always be the same, but why not..
$seq_pretty=sprintf("%'04d",$sequence);




$rev=getoneb("select * from sketchlog_revs where sketchlog_id = '$sketch_info->sketchlog_id' order by revision desc limit 1");
//tabledump("select * from drawinglog_revs where drawing_id = '$drawing_info->drawing_id' order by revision desc limit 1");

if (!($rev)) die("ERR(4)");

$files_res=@mysql_query("select * from webfile_files where file_group_id = '$rev->attached_file_group_id' and mime_type like '%pdf%'");

$file_letter="a";
@mkdir("/tmp/front_desk");
@mkdir("/tmp/front_desk/cook_a_batch");
@mkdir("/tmp/front_desk/cook_a_batch/$global_user->login_name");
@mkdir("/tmp/front_desk/cook_a_batch/$global_user->login_name/$job->contract_num");
@chdir("/tmp/front_desk/cook_a_batch/$global_user->login_name/$job->contract_num");

//die("fooberry");
while ($row=@mysql_fetch_object($files_res)) {
	if ($row->file_group_id==0) die("ERR(99) - No File");
	//$sketch_num=ereg_replace("[ /]","_",$drawing_info->sheet_num);
	$file_name=$seq_pretty . $file_letter . "-_$job->contract_num_-_sketch_-_$sketch_info->sketch_num.pdf";
	copy("$storage_root$row->file_path","$file_name");
		//die("copy(\"$storage_root$row->file_path\",\"$file_name\")");
	//	}
	if (!(is_file($file_name))) die("ERR(5)");
	//echo "<hr>$file_name<hr>";
	$file_letter++;
	}
echo "OK";
exit;
?>
