<?
require('header.phtml');
fd_navs_header();
if ($sketchlog_id!="") {
	$sketchlog_id=addslashes($sketchlog_id);
	$sketchlog_info=getone("select * from sketchlog where sketchlog_id = '$sketchlog_id'");
	$jobinfo_id=$sketchlog_info->jobinfo_id;
	$sketchlog_info->submitted_to_umc=checkbreak($sketchlog_info->submitted_to_umc);
	$sketchlog_info->submitted_to_gc=checkbreak($sketchlog_info->submitted_to_gc);
	$sketchlog_info->submitted_to_owner=checkbreak($sketchlog_info->submitted_to_owner);
	$sketchlog_info->submitted_to_consultant=checkbreak($sketchlog_info->submitted_to_consultant);
	$sketchlog_info->lead_engineer_notify=checkbreak($sketchlog_info->lead_engineer_notify);
	if($sketchlog_info) $sketchlog_info->not_new=TRUE;
	if ($load_mode=="clone") {
		$sketchlog_id="";
		$sketchlog_info->sketchlog_id="";
		}
	$ref_shop_dwg=getoneb("select * from drawinglog where drawing_id = '$sketchlog_info->ref_shop_dwg'");
	$sketchlog_info->ref_shop_dwg_text=$ref_shop_dwg->sheet_num;
	$doc_id=fd_get_doc_id($sketchlog_info->sketchlog_id);
	}

if ($jobinfo_id=="") $jobinfo_id=$global_jobinfo_id;
$jobinfo_id=addslashes($jobinfo_id);
$jobinfo=getone("select * from jobinfo where jobinfo_id = '$jobinfo_id'");
if (!($jobinfo)) die("ERROR: No job information! Please contact your system administrator!");

if ($sketchlog_id=="") {
	$maxnum=getoneb("select max(sketch_num) as max_sketch from sketchlog where jobinfo_id = '$jobinfo->jobinfo_id' and section = '$current_sketchlog_section'");
	if ($maxnum->max_sketch<1) $new_num=1;
	else $new_num=$maxnum->max_sketch + 1;
	
	$new_sketch_query="insert into sketchlog set jobinfo_id = '$jobinfo->jobinfo_id', sketch_num = '$new_num', section = '$current_sketchlog_section', creator = '$global_user_id'";
	$res=@mysql_query($new_sketch_query);
	$new_id=@mysql_insert_id();
	//die("anything?<hr>$new_sketch_query");
	forward("sketchlog_edit&sketchlog_id=$new_id");
	exit;
	}
$sketchlog_info->dwg_title=htmlspecialchars($sketchlog_info->dwg_title);


if (!($write)) {
	if (!(($guest)&&($sketchlog_info->creator==$global_user_id))) die_security();
	}


require('header.phtml');
if (($adminuser)&&($sketchlog_info)) {
	echo "<div style=\"float: right;\"><a href=javascript:mega_warning($sketchlog_info->sketchlog_id)><font color=blue><i>Delete entire sketch</i></font></a></div>";
	}

echo "
<script>
ref_shop_dwg_string='$sketchlog_info->ref_shop_dwg';
ref_shop_dwg_array=ref_shop_dwg_string.split(',');
var ref_shop_dwg_array_static=new Array();

function ajax_trigger() {
	apply_changes();
	}
";

$dwglistqry="select drawing_id,type,sheet_num,description from drawinglog where jobinfo_id = '$sketchlog_info->jobinfo_id' order by type, sort_priority,sheet_num,description";
$dwglistres=@mysql_query($dwglistqry);
while ($dwglistrow=@mysql_fetch_object($dwglistres)) {
	echo "ref_shop_dwg_array_static[$dwglistrow->drawing_id]='$dwglistrow->sheet_num';";
	}

echo "
function objsetcolor(drawing_id,anchor_object) {
	if (is_in_array(drawing_id,ref_shop_dwg_array)) {
		anchor_object.style.background='$fd_color_4';
		} else {
		anchor_object.style.background='white';
		}
	}
function is_in_array(data,testarray) {
	count=0;
	while (count <= testarray.length) {
		if (data==testarray[count]) return true;
		count++;
		}
	return false;
	}

function refresh_mod_shop_dwg_form() {
	document.sketch_rev__edit.mod_shop_dwg.value=mod_shop_dwg_array.toString();
	count=0;
	sep=''; 
	newtext='';
	while (count < mod_shop_dwg_array.length) {
		id=mod_shop_dwg_array[count];
		to_add=mod_shop_dwg_array_static[id];
		if (to_add) {
			newtext=newtext + sep + to_add;
			sep=',';
			}
		count++;
		}
	document.sketch_rev_edit.mod_shop_dwg_text.value=newtext;
	}

function refresh_ref_shop_dwg_form() {
	document.sketchlog_edit.ref_shop_dwg.value=ref_shop_dwg_array.toString();
	count=0;
	sep=''; 
	newtext='';
	while (count < ref_shop_dwg_array.length) {
		id=ref_shop_dwg_array[count];
		to_add=ref_shop_dwg_array_static[id];
		if (to_add) {
			newtext=newtext + sep + to_add;
			sep=',';
			}
		count++;
		}
	document.sketchlog_edit.ref_shop_dwg_text.value=newtext;
	}

function mod_shop_dwg_toggle(mod_shop_dwg,screen_object) {
	if (is_in_array(mod_shop_dwg,mod_shop_dwg_array)) {
		count=0;
		while (count <= mod_shop_dwg_array.length) {
			if (mod_shop_dwg==mod_shop_dwg_array[count]) {
				mod_shop_dwg_array.splice(count,1);
				}
			count++;
			}
		} else {
		mod_shop_dwg_array.push(mod_shop_dwg);
		}
	refresh_mod_shop_dwg_form();
	objsetcolor(mod_shop_dwg,screen_object);
	}

function ref_shop_dwg_toggle(ref_shop_dwg,screen_object) {
	if (is_in_array(ref_shop_dwg,ref_shop_dwg_array)) {
		count=0;
		while (count <= ref_shop_dwg_array.length) {
			if (ref_shop_dwg==ref_shop_dwg_array[count]) {
				ref_shop_dwg_array.splice(count,1);
				}
			count++;
			}
		} else {
		ref_shop_dwg_array.push(ref_shop_dwg);
		}
	refresh_ref_shop_dwg_form();
	objsetcolor(ref_shop_dwg,screen_object);
	}
function dwg_popup(sketchlog_id) {
	document.getElementById('dwg_select').style.display='block';
	}
function apply_changes() {
	document.sketchlog_edit.savemode.value='apply';
	document.sketchlog_edit.submit();
	}
function save_and_clone() {
	document.sketchlog_edit.savemode.value='clone';
	document.sketchlog_edit.submit();
	}
function save_and_next() {
	document.sketchlog_edit.savemode.value='next';
	document.sketchlog_edit.submit();
	}
function del_rev(rev) {
	if(confirm('Are you sure you want to delete this revision?')) 
		document.location='$pagename?mode=sketch_rev_delete&sketch_rev_id=' + rev;
	}
";

if (($adminuser)&&($sketchlog_info)) {
	echo "
	function mega_warning() {
		if (confirm('Warning the ENTIRE sketch will be deleted!'))
			if (confirm(\"...All it's history.. EVERYTHING DELETED!\"))
				if (confirm('Are you sure?'))
					document.location='$pagename?mode=sketchlog_delete&sketchlog_id=$sketchlog_info->sketchlog_id';
		}
	";
	}

echo "
</script>
<table border=0 cellspacing=0 cellpadding=5><tr><td valign=top>
<form name=sketchlog_edit method=post action=$pagename>
<input type=hidden name=mode value=sketchlog_submit>
<input type=hidden name=sketchlog_id value=\"$sketchlog_info->sketchlog_id\">
<input type=hidden name=jobinfo_id value=\"$jobinfo_id\">
<input type=hidden name=savemode value='normal'>

<table border=1 cellspacing=0 cellpadding=3>

<tr><td colspan=4 align=center bgcolor=$fd_color_4>
	<b>$sketchlog_info->sheet_num Sketch Record</b>
</td></tr>
<tr bgcolor=\"$fd_color_1\"><td colspan=2 align=center>
	<b>Sketch Info</b>
</td></tr>

<tr><td>
	<b>Sketch Number:</b>&nbsp;
</td><td>
	<input type=hidden name=sketch_num value=\"$sketchlog_info->sketch_num\">$sketchlog_info->sketch_num
</td></tr>

<tr><td>
	<b>Sketch Description</b>
</td><td>
	<input type=text name=dwg_title value=\"$sketchlog_info->dwg_title\">
</td></tr>

<tr><td>
	<b>RFI&nbsp;#</b>
</td><td>
	<input disabled size=1 type=text name=rfi_num value=\"$sketchlog_info->rfi_num\">";
	fd_doc_box2($doc_id,"rfi");
	echo"
</td></tr>

<tr><td>
	<b>Ref&nbsp;Shop&nbsp;DWG</b>
</td><td>
	";fd_doc_box2($doc_id,"drawinglog");echo"
	<input type=hidden name=ref_shop_dwg value=\"\">
	<input type=text name=ref_shop_dwg_text value=\"$sketchlog_info->ref_shop_dwg_text\" size=4>
</td></tr>

<tr><td>
	<b>Submitted to:</b>
</td><td>
	<i><input type=checkbox name=submitted_to_umc $sketchlog_info->submitted_to_umc>UMC&nbsp;&nbsp;<input type=checkbox name=submitted_to_gc $sketchlog_info->submitted_to_gc>GC&nbsp;&nbsp;<input type=checkbox name=submitted_to_owner $sketchlog_info->submitted_to_owner>Owner&nbsp;&nbsp;<input type=checkbox name=submitted_to_consultant $sketchlog_info->submitted_to_consultant>Consultant</i>
</td></tr>

<tr><td>
	<b>Floor/Area:</b>
</td><td>
	<input type=text size=10 name=floor value=\"$sketchlog_info->floor\">
	<input type=text size=5 name=area value=\"$sketchlog_info->area\">
</td></tr>

<tr><td>
	<b>Issued for:</b>
</td><td>
	";if ($sketchlog_info->issued_for!="") $extra_issue_for="<option></option>";
	else $extra_issue_for="";
	echo"
	<select name=issued_for>
	<option selected>$sketchlog_info->issued_for</option>$extra_issue_for
	<option>Approval</option>
	<option>Coordination</option>
	<option>Field use/Construction</option>
	<option>For their use</option>
	<option>Returned for review</option>
	<option>UMC review or coordination</option>
	</select>
</td></tr>

<tr><td>
	<b>Orig&nbsp;Issue</b>
</td><td>
	";
	if (($sketchlog_info->orig_issue=="")||($adminuser)) {
		datebox2($sketchlog_info->orig_issue,"sketchlog_edit.orig_issue");
		} else {
		echo "$sketchlog_info->orig_issue
		<input type=hidden name=orig_issue value=\"$sketchlog_info->orig_issue\">
		";
		}	
	echo "
</td></tr>

<tr><td>
	<b>Originator:</b>
</td><td>
	";contactsbox("select * from contacts where ( contact_type = 'company' or contact_type = 'contact') ",$sketchlog_info->originator,"originator");echo"
</td></tr>
<input type=hidden name=sort_priority value=\"$sketchlog_info->sort_priority\">
";



$udcount=0;
$extra_fields="";
if ($jobinfo->fd_sketch_cust_1_used=='Y') {
	if ($jobinfo->fd_sketch_cust_1_size>45) $maxsize=80;
	else $maxsize=$jobinfo->fd_sketch_cust_1_size;
	
	$sketchlog_info->cust_1=htmlspecialchars($sketchlog_info->cust_1);
	$extra_fields=$extra_fields . "
	<tr bgcolor=#dddddd><td>
		<b>* $jobinfo->fd_sketch_cust_1_name</b>:
	</td><td colspan=3>
		<input type=text size=\"$maxsize\" name=cust_1 value=\"$sketchlog_info->cust_1\">
	</td></tr>
	";
	} else $udcount++;

if ($jobinfo->fd_sketch_cust_2_used=='Y') {
	if ($jobinfo->fd_sketch_cust_2_size>45) $maxsize=45;
	else $maxsize=$jobinfo->fd_sketch_cust_2_size;
	
	$sketchlog_info->cust_2=htmlspecialchars($sketchlog_info->cust_2);
	$extra_fields=$extra_fields . "
	<tr bgcolor=#dddddd><td>
		<b>* $jobinfo->fd_sketch_cust_2_name</b>:
	</td><td colspan=3>
		<input type=text size=\"$maxsize\" name=cust_2 value=\"$sketchlog_info->cust_2\">
	</td></tr>
	";
	} else $udcount++;

if ($jobinfo->fd_sketch_cust_3_used=='Y') {
	if ($jobinfo->fd_sketch_cust_3_size>45) $maxsize=45;
	else $maxsize=$jobinfo->fd_sketch_cust_3_size;
	
	$sketchlog_info->cust_3=htmlspecialchars($sketchlog_info->cust_3);
	$extra_fields=$extra_fields . "
	<tr bgcolor=#dddddd><td>
		<b>* $jobinfo->fd_sketch_cust_3_name</b>:
	</td><td colspan=3>
		<input type=text size=\"$maxsize\" name=cust_3 value=\"$sketchlog_info->cust_3\">
	</td></tr>
	";
	} else $udcount++;

if ($jobinfo->fd_sketch_cust_4_used=='Y') {
	if ($jobinfo->fd_sketch_cust_4_size>45) $maxsize=45;
	else $maxsize=$jobinfo->fd_sketch_cust_4_size;
	
	$sketchlog_info->cust_4=htmlspecialchars($sketchlog_info->cust_4);
	$extra_fields=$extra_fields . "
	<tr bgcolor=#dddddd><td>
		<b>* $jobinfo->fd_sketch_cust_4_name</b>:
	</td><td colspan=3>
		<input type=text size=\"$maxsize\" name=cust_4 value=\"$sketchlog_info->cust_4\">
	</td></tr>
	";
	} else $udcount++;

if ($jobinfo->fd_sketch_cust_5_used=='Y') {
	if ($jobinfo->fd_sketch_cust_5_size>45) $maxsize=45;
	else $maxsize=$jobinfo->fd_sketch_cust_5_size;
	
	$sketchlog_info->cust_5=htmlspecialchars($sketchlog_info->cust_5);
	$extra_fields=$extra_fields . "
	<tr bgcolor=#dddddd><td>
		<b>* $jobinfo->fd_sketch_cust_5_name</b>:
	</td><td colspan=3>
		<input type=text size=\"$maxsize\" name=cust_5 value=\"$sketchlog_info->cust_5\">
	</td></tr>
	";
	} else $udcount++;
//echo "<tr bgcolor=$fd_color_1><td colspan=2 align=center><b>$udcount unused custom fields (*)</b></td></tr>";

/*
echo "
$extra_fields
*/

echo "

<tr><td colspan=4>
	<table border=0 cellspacing=0 cellpadding=0 width=100% align=center>
	<tr><td>
		<input type=button onclick=save_and_next() value=\"Save and Next\">
	</td><td>
		<input type=button onclick=save_and_clone() value=\"Save and Clone\">
	</td><td>
		<input type=submit value=Save>
	</td><td>
		<input type=button onclick=apply_changes() value=Apply>
	</td><td>
		<input type=button onclick=document.location=\"$pagename\" value=\"Cancel\">
	</td></tr>
	</table>
</td></tr>
</table>
</form>
</td><td valign=top>";


if ($sketchlog_info->not_new) {
$doc_id=fd_get_doc_id($sketchlog_info->sketchlog_id);
pal_box($doc_id);

echo "<table border=1 cellspacing=0 cellpadding=4>
<tr bgcolor=\"$fd_color_4\"><td align=center>
	<b>Sketch&nbsp;Notes</b>
</td></tr>
<tr><td align=center>
	<i>**Note: Once added notes can not be modified or deleted</i>
</td></tr>

<tr><td>
	asdf
	<b>Add:</b><br><form name=sketchlog_add_notes method=post action=$pagename>
	<input type=hidden name=mode value=sketchlog_add_notes>
	<input type=hidden name=sketchlog_id value=\"$sketchlog_info->sketchlog_id\">
	<textarea name=notes rows=4 cols=50></textarea><br>
	<input type=submit value=\"Save Note\">
	</form>
</td></tr>
";
$notes_query="select * from sketchlog_notes where sketchlog_id = '$sketchlog_info->sketchlog_id' order by note_date desc, sketchlog_note_id";
$notes_res=@mysql_query($notes_query);
while ($note=@mysql_fetch_object($notes_res)) {
	$poster=getone("select * from contacts where contacts_id = '$note->creator'");
	$ondate=invali_date($note->note_date);
	$note->notes=ereg_replace("\n",'<p>',$note->notes);
	echo "<tr bgcolor=$fd_color_4><td><b>Posted by: $poster->display_name on $ondate</b></td></tr>
	<tr><td>$note->notes</td></tr>";
	}
echo"</table>";
}




echo "</td></tr></table>";



$rev_query="select * from sketchlog_revs where sketchlog_id = '$sketchlog_info->sketchlog_id' order by revision";
$rev_query_res=@mysql_query($rev_query);
$rev_query_count=@mysql_num_rows($rev_query_res);
if (($rev_query_count<1)&&($sketchlog_info)) {
	$query="insert into sketchlog_revs set sketchlog_id = '$sketchlog_info->sketchlog_id',revision = '0',rev_date = now(),rev_description = 'Original Issue',sent_to_field_date = '',creator = '$global_user->contacts_id'";
	@mysql_query($query);
	update_rev($sketchlog_info->sketchlog_id);
	$rev_query_res=@mysql_query($rev_query);
	$rev_query_count=@mysql_num_rows($rev_query_res);
	}

if ($rev_query_count > 0) {
	echo "<table border=1 cellspacing=0 cellpadding=4 id=\"ajax_target\">
	
	<tr><td colspan=8 align=center bgcolor=$fd_color_4>
		<b>Sketch Revisions</b>
	</td></tr>
	
	<tr><td>
		<b>Revision</b>
	</td><td>
		<b>Description</b>
	</td><td>
		<b>Rev Date</b>
	</td><td>
		<b>Sent to Field</b>
	</td><td>
		<b>Created by</b>
	</td><td>
		<b>File</b>
	</td><td colspan=2>&nbsp;
	</td></tr>
	
	<script>
	function apply_webfile_change(sketch_rev_id) {
		eval('value=document.add_rev_file' + sketch_rev_id + '.attached_file_group_id.value;');
		ajaxManager('load_page','$pagename?mode=rev_file_submit&attached_file_group_id=' + value + '&sketch_rev_id=' + sketch_rev_id,'ajax_target');
		}
	</script>
	";
	
	while ($revrow=@mysql_fetch_object($rev_query_res)) {
		$revdate=invali_date($revrow->rev_date);
		$stfdate=invali_date($revrow->sent_to_field_date);
		$creator=getoneb("select * from contacts where contacts_id = '$revrow->creator'");
		echo "
		<tr><td>
			$revrow->revision&nbsp;
		</td><td>
			$revrow->rev_description
		</td><td>
			$revdate
		</td><td>
			$stfdate&nbsp;
		</td><td>
			$creator->display_name
		</td><form name=\"add_rev_file$revrow->sketch_rev_id\" method=get target=_temp_save_win action=$pagename><td>
			<input type=hidden name=mode value=rev_file_submit>
			<input type=hidden name=sketch_rev_id value=\"$revrow->sketch_rev_id\">
			";webfilebox($revrow->attached_file_group_id,'attached_file_group_id',"opener.apply_webfile_change($revrow->sketch_rev_id);");echo"
		</td></form><td>
			<a href=$pagename?mode=sketch_rev_edit&sketch_rev_id=$revrow->sketch_rev_id><font color=blue>Edit</font></a>
		";
		if ($adminuser) {
			echo "</td><td><a href=\"javascript:del_rev('$revrow->sketch_rev_id');\"><font color=blue>Delete</font></a>";
			}
		
		echo "</td></tr>";
		}
	$max_rev_info=getoneb("select max(revision) as maxrev from sketchlog_revs where sketchlog_id = '$sketchlog_info->sketchlog_id'");
	$new_rev=$max_rev_info->maxrev + 1;
	echo "
	<script>
		function show_newrev_form() {
			document.getElementById('newrev_button').style.display='none';
			";
			if ($global_browser=="IE") { 
				echo "document.getElementById('newrev_form').style.display='inline';";
			} else {
				echo "document.getElementById('newrev_form').style.display='table-row';";
				}
			echo"
			}
	</script>
	<form name=sketch_rev_edit method=get action=\"$pagename\">
	<input type=hidden name=mode value=\"sketch_rev_add\">
	<input type=hidden name=sketchlog_id value=\"$sketchlog_info->sketchlog_id\">
	
	<tr style=\"display: none\" id=\"newrev_form\"><td>
		<input type=text size=3 name=revision value=\"$new_rev\">
	</td><td>
		<input type=text size=40 name=rev_description value=\"\">
	</td><td>
		";datebox2("",'sketch_rev_edit.rev_date');echo"
	</td><td>
		";datebox2("",'sketch_rev_edit.sent_to_field_date');echo"
	</td><td colspan=3 align=center>
		<input type=submit value=\"Save\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	</td></tr>
	
	
	
	<tr id=\"newrev_button\"><td colspan=7 align=center>
		<a href=javascript:show_newrev_form();><font color=blue>Add</font></a>
	</td></tr>

	</table>
	</form>
	";
	}

echo"
<script>
refresh_ref_shop_dwg_form();
</script>
";
fd_navs_footer();
?>
