<?

if ($sketchlog_id=="") die("Application error: no drawing specified for note");
else $sketchlog_id=addslashes($sketchlog_id);

$creator=$global_user_id;
$notes=addslashes($notes);
$query="insert into sketchlog_notes set
sketchlog_id = '$sketchlog_id',
creator = '$creator',
note_date = now(),
notes = '$notes'";

//echo "<hr>$query<hr>";exit;
@mysql_query($query);
forward("sketchlog_edit&sketchlog_id=$sketchlog_id");
?>
