<?
if ($sketch_rev_id!="") $sketch_rev_id=addslashes($sketch_rev_id);
else die('oops.. No rev set to modify');

$rev_info=getone("select * from sketchlog_revs where sketch_rev_id = '$sketch_rev_id'");

if (!($rev_info)) die("Error loading revision info. Please contact your system adminsitrator!");

include('header.phtml');

echo "
<form name=sketch_rev_edit method=post action=$pagename>
<table border=1 cellspacing=0 cellpadding=3>
<input type=hidden name=mode value=\"sketch_rev_submit\">
<input type=hidden name=sketch_rev_id value=\"$rev_info->sketch_rev_id\">
<tr><td> 
	Revision:
</td><td>
	<input type=text name=revision value=\"$rev_info->revision\">
</td></tr>

<tr><td>
	Revision Date:
</td><td>
	";datebox2($rev_info->rev_date,'sketch_rev_edit.rev_date');echo "
</td></tr>

<tr><td>
	Description:
</td><td>
	<input size=80 type=text name=rev_description value=\"$rev_info->rev_description\">
</td></tr>

<tr><td>
	Sent to Field:
</td><td>
	";datebox2($rev_info->sent_to_field_date,'sketch_rev_edit.sent_to_field_date');echo "
</td></tr>

<tr><td colspan=2 align=right>
	<input type=submit value=Save>
</td></tr>

</table>
</form>
";
?>
