<?
if ($sketch_rev_id!="") $sketch_rev_id=addslashes($sketch_rev_id);
else die("Application error. No record specified!");
$rev_info=getone("select * from sketchlog_revs where sketch_rev_id = '$sketch_rev_id'");
$rev_date=vali_date($rev_date);
$sent_to_field_date=vali_date($sent_to_field_date);
$revision=addslashes($revision);
$rev_description=addslashes($rev_description);

@mysql_query("update sketchlog_revs set rev_date = '$rev_date', sent_to_field_date = '$sent_to_field_date', revision = '$revision', rev_description = '$rev_description' where sketch_rev_id = '$rev_info->sketch_rev_id'");
update_rev($rev_info->drawing_id);

if (($rev_date!="")&&($sent_to_field_date!="")) {
	if ($rev_date>$sent_to_field_date) {
		echo "
		<script>
		alert(\"Hey, those dates don't make any sense!!!\");
		</script>";
		}
	
	}
forward("sketchlog_edit&sketchlog_id=$rev_info->sketchlog_id");
//echo "<script>self.close();</script>";
?>
