<?


$contact->current=checkbreak($contact->current);
$contact->owner=checkbreak($contact->owner);
$contact->consultant=checkbreak($contact->consultant);
$contact->mechanical_contractor=checkbreak($contact->mechanical_contractor);
$contact->manufacturer=checkbreak($contact->manufacturer);
$contact->is_general=checkbreak($contact->is_general);
$contact->is_reprographics_firm=checkbreak($contact->is_reprographics_firm);

$cancel_link="$pagename?mode=$contacts_last_main_mode";

if ($return_to!="") {
	//$return_to=addslashes($return_to);
	//$abort_url=base64_decode($return_to);
	//$cancel_link=$abort_url;
	$cancel_link=get_return_to_link($return_to);
	}

echo "
<table border=0 cellspacing=0 cellpadding=0>

<a href=$cancel_link><font color=blue>Cancel</font></a><br>

<form name=standardform method=get action=$pagename>
<input type=hidden name=mode value=contacts_submit>
<input type=hidden name=contacts_id value=\"$contact->contacts_id\">
<input type=hidden name=contact_type value=\"$contact->contact_type\">
<input type=hidden name=exit_target value=\"$contacts_last_main_mode\">
<input type=hidden name=return_to value=\"$return_to\">
<input type=hidden name=is_company value=\"Y\">

<tr><td>
	Company Name:
</td><td>
	<input type=text size=40 name=company value=\"$contact->company\">
</td></tr>

<tr><td>
	Picture
</td><td>
	";webfilebox($contact->photo_file_group_id,'photo_file_group_id',"",1);echo"
</td></tr>

<tr><td>
	<font title=\"Client Account Manager\">CAM
</td><td>
	";contactsbox("select * from contacts where current = 'Y' and umc_emp = 'Y'","$contact->cam_id","cam_id","",2,"contact_cam_popup");echo "
</td></tr>

<tr><td>
	E-mail:
</td><td>
	<input type=text name=email value='$contact->email'>*
</td></tr>

<tr><td>
	Address:
</td><td>
	<textarea rows=5 cols=40 scroll=auto wrap=soft name=address_1>$contact->address_1</textarea>
</td></tr>

<tr><td>
	City:
</td><td>
	<input type=text name=address_city value='$contact->address_city'>
</td></tr>

<tr><td>
	State:
</td><td>
	<input type=text name=address_state size=3 value='$contact->address_state'>
</td></tr>

<tr><td>
	Zip Code:
</td><td>
	<input type=text name=address_zip size=10 value='$contact->address_zip'>
</td></tr>

<tr><td>
	Phone:
</td><td>
	<input type=text name=phone value='$contact->phone'>
</td></tr>

<tr><td>
	Phone Extension:
</td><td>
	<input type=text name=phone_ext value='$contact->phone_ext'>
</td></tr>

<tr><td>
	Fax:
</td><td>
	<input type=text name=phone_fax value='$contact->phone_fax'>
</td></tr>


<tr><td colspan=2>
	<b>Contact Categories</b> <br>
	<font size=-2><i>(check all that apply)</i><b>:</b></font>
</td></tr>

<tr><td>
	Current:
</td><td>
	<input type=checkbox name=current $contact->current><br>
</td></tr>

<tr><td>
	Owner (customer):
</td><td>
	<input type=checkbox name=owner $contact->owner><br>
</td></tr>

<tr><td>
	Consultant:
</td><td>
	<input type=checkbox name=consultant $contact->consultant><br>
</td></tr>

<tr><td>
	Mechanical Contractor:
</td><td>
	<input type=checkbox name=mechanical_contractor $contact->mechanical_contractor><br>
</td></tr>

<tr><td>
	Manufacturer:
</td><td>
	<input type=checkbox name=manufacturer $contact->manufacturer><br>
</td></tr>

<tr><td>
	General Contractor:
</td><td>
	<input type=checkbox name=is_general $contact->is_general><br>
</td></tr>

<tr><td>
	Reprographics Firm:
</td><td>
	<input type=checkbox name=is_reprographics_firm $contact->is_reprographics_firm><br>
</td></tr>

<tr><td></td><td>
	<input type=button value=Apply onclick=apply_changes();>
	<input type=button value=Finish onclick=submit();>
</td></tr>
</table>
</form>
<script>
function apply_changes() {
	document.standardform.exit_target.value='contact_edit';
	document.standardform.submit();
	}
</script>

";


if ($new!="1") {
	echo "<hr>Sites for this company&nbsp<a href=$pagename?mode=contacts_edit&contact_type=site&company_id=$contact->contacts_id><font color=blue>(Add)</font></a><p>";
	contact_table("select * from contacts where company_id = '$contact->contacts_id' and contact_type = 'site' order by alphasort");

	echo "<hr>Contacts for this company&nbsp<a href=$pagename?mode=contacts_edit&contact_type=contact&company_id=$contact->contacts_id><font color=blue>(Add)</font></a><p>";
	contact_table("select * from contacts where company_id = '$contact->contacts_id' and contact_type = 'contact' order by alphasort");
	}



require('footer.phtml');
?>
