<?
echo "<table border=0><tr bgcolor=#dddddd><td><i>Dwg</i></td><td><i>Grid Ref</i></td></tr>";
if ($rfi_id!="") {
	$rfi_id=addslashes($rfi_id);
	//$rfi_info=getoneb("select * from rfilog where rfi_id = '$rfi_info->rfi_id'");
	$rfi_info=getoneb("select * from rfilog where rfi_id = '$rfi_id'");
	if (!($rfi_info)) die('oops');
	if (($dwg!="")||($grid_ref!="")) {
		$dwg=addslashes($dwg);
		$grid_ref=addslashes($grid_ref);
		@mysql_query("insert into rfi_dwg_refs set rfi_id = '$rfi_info->rfi_id',dwg = '$dwg', grid_ref = '$grid_ref'");
		}
	
	if ($remove_rfi_ref_id!="") {
		//echo "hi";
		$remove_rfi_ref_id=addslashes($remove_rfi_ref_id);
		$ref_info=getoneb("select * from rfi_dwg_refs where rfi_ref_id = '$remove_rfi_ref_id'");
		if ($ref_info->rfi_id != $rfi_id) die("Application error: Unable to verify delete intention. Aborting.");
		//echo "<script>alert($remove_rfi_ref_id);</script>";
		@mysql_query("delete from rfi_dwg_refs where rfi_ref_id = '$remove_rfi_ref_id'");
		}
	$rfi_list=@mysql_query("select * from rfi_dwg_refs where rfi_id = '$rfi_id'");
	//tabledump($rfi_list);
	while ($row=@mysql_fetch_object($rfi_list)) {
		echo "<tr><td>$row->dwg</td><td>$row->grid_ref</td><td><a title=\"Remove dwg/grid ref\"href=\"javascript:rem_dwg_ref($row->rfi_ref_id);\"><font color=blue size=+1>-</font></a></td></tr>";
		}
	echo "<tr><td><input title=\"Drawing\" type=text size=10 name=dwg></td><td><input title=\"Grid Ref\" type=text name=grid_ref size=15></td><td><a href=\"javascript:add_dwg_ref();\"><font color=blue size=+1>+</font></a></td></tr>";
	} else {
	echo "<tr><td><input title=\"Drawing\" type=text size=10 name=dwg></td><td><input title=\"Grid Ref\" type=text name=grid_ref size=15></td><td><i><font size=-1>(Save first to add more)</font></i></td></tr>";
	}
echo "</table>";
?>
