<?
if ($rfi_id=="") die("Application or user error");
else $rfi_id=addslashes($rfi_id);

$rfi_info=getone("select * from rfilog where rfi_id = '$rfi_id'");


$rfi_num=round($rfi_info->rfi_num);
$rfi_num_next=$rfi_num + 1;
$query="select * from rfilog where section = '$rfi_info->section' and jobinfo_id = '$rfi_info->jobinfo_id' and rfi_num >= '$rfi_info->rfi_num' and rfi_num < '$rfi_num_next' order by rfi_num desc limit 1";
$last_rfi_info=getoneb($query);
$new_rfi_num=$last_rfi_info->rfi_num + .01;

$ins_query="insert into rfilog set section = '$rfi_info->section', jobinfo_id = '$rfi_info->jobinfo_id', rfi_num = '$new_rfi_num', creator = '$global_user_id',rfi_date = now()";

$res=@mysql_query($ins_query);
if (!($res)) die ("Error with query...<hr>$ins_query");
$insert_id=@mysql_insert_id();
forward("rfi_edit&rfi_id=$insert_id");
?>
