<?
$doc_id=addslashes($doc_id);
$doc_info=getoneb("select * from documents where doc_id = '$doc_id'");
if (!($doc_info)) die("Application error: Invalid document_id. Please contact your system administrator!");


$query="select * from front_desk_record_sets where jobinfo_id = '$doc_info->jobinfo_id' order by sort_priority,record_set_name";
//tabledump($query);
$res=@mysql_query($query);
$count=@mysql_num_rows($res);

echo "<table width=100% border=0 cellspacing=0 cellpadding=1>
<tr bgcolor=$fd_color_4><td style=\"border-bottom: 2px solid white;\" colspan=$count>
	Record Dwg Posting
</td></tr>
<tr>";

while ($row=@mysql_fetch_object($res)) {
	$rs_done="Y";
	$rs_query="select * from rfi_record_dwg_posting where record_set_id = '$row->record_set_id' and doc_id = '$doc_info->doc_id'";
	$rs_info=getoneb($rs_query);
	if ($selected_tab=="") $selected_tab=$rs_info->posting_id;
	if (!($rs_info)) {
		@mysql_query("insert into rfi_record_dwg_posting set doc_id = '$doc_info->doc_id', record_set_id = '$row->record_set_id'");
		$rs_info=getoneb($rs_query);
		if (!($rs_info)) die("Application Error: Unable to initialize rfi_record_dwg_posting entry!");
		}
	if ($rs_info->arch=="") $rs_done='N';
	if ($rs_info->struct=="") $rs_done='N';
	if ($rs_info->mech=="") $rs_done='N';
	if ($rs_info->specs=="") $rs_done='N';
	if ($rs_info->other=="") $rs_done='N';
	
	if ($rs_done=="Y") {
		$rs_css="text-decoration: line-through;";
		} else {
		$rs_css="";
		}

	if ($rs_info->posting_id==$selected_tab) {
		$selected_info=$rs_info;
		echo "<td align=center id=\"posting_name_$rs_info->posting_id\" style=\"border: 2px solid black; -moz-border-radius: 15px 15px 0px 0px; border-bottom: 0px solid white;\" bgcolor=white><font style=\"$rs_css\" size=-1>$row->record_set_name</font></td>";
		} else {
		echo "
		<td bgcolor=$fd_color_3 align=center onclick=\"ajaxManager('load_page','$pagename?mode=rfi_record_dwg_posting&doc_id=$doc_info->doc_id&selected_tab=$rs_info->posting_id','record_dwg_posting');\" style=\"cursor: hand; cursor: pointer; border: 2px solid black; border-left: 1px solid black; -moz-border-radius: 15px 15px 0px 0px;\">
		<bgcolor=#dddddd><font style=\"$rs_css\" size=-1>$row->record_set_name</font></td>";
		}
	}

if ($update_field_name!="") {
	$update_field_name=addslashes($update_field_name);
	$update_field_value=addslashes($update_field_value);
	$updater=$global_user_id;
	$update_field_value=ereg_replace('^ *$','',$update_field_value);
	if ($update_field_value=='') $updater=0;
	$posting_id=addslashes($posting_id);
	$today=date('Y-m-d');
	$update_query="update rfi_record_dwg_posting set $update_field_name = '$update_field_value', ${update_field_name}er = '$updater', ${update_field_name}_date = '$today' where posting_id = '$selected_tab'";
	@mysql_query($update_query);
	$selected_info=getoneb("select * from rfi_record_dwg_posting where posting_id = '$selected_tab'");
	}

if ($assigned_to_set!="") {
	$assigned_to_set=addslashes($assigned_to_set);
	@mysql_query("update rfi_record_dwg_posting set assigned_to = '$assigned_to_set' where posting_id = '$selected_tab'");
	$selected_info=getoneb("select * from rfi_record_dwg_posting where posting_id = '$selected_tab'");
	}

echo "

<tr><td colspan=10 width=100%>
	<table border=0 cellspacing=0 cellpadding=0 width=100%>
		
		<tr><td></td><td>
			<font size=-1><i>Completed</i></font>
		</td></tr>

		<tr><td>
			Arch
		</td><td>
			<select name=arch onchange=\"update_posting_item('$selected_info->posting_id',this.name,this.value);\"><option>$selected_info->arch</option><option>Y</option><option>N</option><option>n/a</option><option> </option></select>
		</td><td>";
			$updater=getoneb("select * from contacts where contacts_id = '$selected_info->archer'");
			echo"$updater->display_name
		</td></tr>

		<tr><td>
			Struct
		</td><td>
			<select name=struct onchange=\"update_posting_item('$selected_info->posting_id',this.name,this.value);\"><option>$selected_info->struct</option><option>Y</option><option>N</option><option>n/a<option> </option></select>
		</td><td>";
			$updater=getoneb("select * from contacts where contacts_id = '$selected_info->structer'");
			echo"$updater->display_name
		</td></tr>

		<tr><td>
			<font title=\"Includes Plumb, Pipe and Sheet Metal\">Mech</font>
		</td><td>
			<select name=mech onchange=\"update_posting_item('$selected_info->posting_id',this.name,this.value);\"><option>$selected_info->mech</option><option>Y</option><option>N</option><option>n/a</option><option> </option></select>
		</td><td>";
			$updater=getoneb("select * from contacts where contacts_id = '$selected_info->mecher'");
			echo"$updater->display_name
		</td></tr>

		<tr><td>
			<font title=\"Everyone forgets specs eh..\">Specs</font>
		</td><td>
			<select name=specs onchange=\"update_posting_item('$selected_info->posting_id',this.name,this.value);\"><option>$selected_info->specs</option><option>Y</option><option>N</option><option>n/a</option><option></option></select>
		</td><td>";
			$updater=getoneb("select * from contacts where contacts_id = '$selected_info->specser'");
			echo"$updater->display_name
		</td></tr>

		<tr><td>
			Other
		</td><td>
			<select name=other onchange=\"update_posting_item('$selected_info->posting_id',this.name,this.value);\"><option>$selected_info->other</option><option>Y</option><option>N</option><option>n/a</option><option> </option></select>
		</td><td>";
			$updater=getoneb("select * from contacts where contacts_id = '$selected_info->otherer'");
			echo"$updater->display_name
		</td></tr>

		<tr><form><td colspan=3><font size=-1><i>Assigned to:<br></font></i>";contactsbox("select * from contacts where umc_emp = 'Y' and current = 'Y'",$selected_info->assigned_to,'selected_assigned_to',"opener.update_assigned_to($selected_info->posting_id)",0);echo"</td></tr>

	</table>
</td></tr>

";


?>
