<?
if ($submitval=='Cancel') {
	echo "<font size=+2>Changes discarded.....</font><hr>";
	forward('main');
	exit;
	}

$jobinfo_id=addslashes($global_jobinfo_id);
$creator=addslashes($global_user->contacts_id);
$saved_by=addslashes($global_user->contacts_id);

if ($rfi_id!="") {
	$rfi_id=addslashes($rfi_id);
	$rfi_info=getoneb("select * from rfilog where rfi_id = '$rfi_id'");
	if ($rfi_info) {
		if (!($write)) {
			if (!(($guest)&&($rfi_info->creator==$global_user_id))) die_security();
			}
		}
	$rfi_num=$rfi_info->rfi_num;
	$jobinfo_id=$rfi_info->jobinfo_id;
	$query_start="update";
	$query_end="where rfi_id = '$rfi_info->rfi_id'";
	$creator=$rfi_info->creator;
	} else {
	$query_start="insert into";
	$rfi_info->rfi_date=date('Y-m-d');
	$query_end=",creator = '$creator'";
	$max_num=getoneb("select max(rfi_num) as max_num from rfilog where jobinfo_id = '$jobinfo_id' and section = '$current_rfilog_section'");
	$rfi_num=round($max_num->max_num + 1);
	$jobinfo_id=$global_jobinfo_id;
	if ($global_jobinfo_id=="") die("ERROR: Why aren't we in a specific job?!?!?!");
	}

$section=addslashes($current_rfilog_section);
$key_description=addslashes(pasted_text_decoder($key_description));
$gc_rfi_num=addslashes($gc_rfi_num);
$sub_rfi_num=addslashes($sub_rfi_num);
$cpm_schedule_id=addslashes($cpm_schedule_id);
$question=addslashes(pasted_text_decoder($question));
$solution=addslashes(pasted_text_decoder($solution));
$response_needed_date=vali_date($response_needed_date);
$reply=addslashes(pasted_text_decoder($reply));
$reply_from=addslashes($reply_from);
$reply_date=vali_date($reply_date);
$rep_id=addslashes($rep_id);
$sent_to_id=addslashes($sent_to_id);
$sent_to_date=vali_date($sent_to_date);
$pm_review_done=checkfix($pm_review_done);
$attached_sheets=checkfix($attached_sheets);
$sent=checkfix($sent);
$attached_sheet_name=addslashes($attached_sheet_name);
$spec=addslashes($spec);
$bldg=addslashes($bldg);
$floor=addslashes($floor);
$has_cost=addslashes($has_cost);
$pm_notes=addslashes($pm_notes);
$sub_id=addslashes($sub_id);
$reply_file_group_id=addslashes($reply_file_group_id);

$query_middle=" rfilog set
jobinfo_id = '$jobinfo_id',
section = '$current_rfilog_section',
rfi_num = '$rfi_num',
gc_rfi_num = '$gc_rfi_num',
sub_rfi_num = '$sub_rfi_num', 
cpm_schedule_id = '$cpm_schedule_id', 
rfi_date = '$rfi_info->rfi_date',
key_description = '$key_description',
question = '$question',
solution = '$solution',
response_needed_date = '$response_needed_date',
pm_review_done = '$pm_review_done',
sent = '$sent',
attached_sheets = '$attached_sheets',
attached_sheet_name = '$attached_sheet_name',
reply = '$reply',
reply_from = '$reply_from',
reply_date = '$reply_date',
has_cost = '$has_cost',
rep_id = '$rep_id',
sent_to_id = '$sent_to_id',
sent_to_date = '$sent_to_date',
spec = '$spec',
bldg = '$bldg',
floor = '$floor',
saved_by = '$saved_by',
pm_notes = '$pm_notes',
reply_file_group_id = '$reply_file_group_id',
sub_id = '$sub_id'
";
//echo "$query_middle";exit;
$query=$query_start . $query_middle . $query_end;
$res=@mysql_query($query);
if (!($res)) die("ERROR: Database update failed. Debug information:<hr>$query");
if ($rfi_id=="") {
	$rfi_info->rfi_id=@mysql_insert_id();
	}

$doc_id=fd_get_doc_id($rfi_info->rfi_id);
sync_rfi_logs();

if (($dwg!="")||($grid_ref!="")) {
	$dwg=addslashes($dwg);
	$grid_ref=addslashes($grid_ref);
	@mysql_query("insert into rfi_dwg_refs set rfi_id = '$rfi_info->rfi_id',dwg = '$dwg', grid_ref = '$grid_ref'");
	}


//die($submitval);


if ($submitval=="OK") forward("main");
if ($submitval=="Print") {
	forward("rfi_display_pdf&rfi_id=$rfi_info->rfi_id&blah=blah/pdf_download/rfi.pdf");
	exit;
	}
if (($submitval=="Save and Add Files")||($submitval=="Apply")) {
	forward("rfi_edit&rfi_id=$rfi_info->rfi_id");
	exit;
	}
if ($submitval=="Prev") {
	$prev_rfi_num=round($rfi_info->rfi_num - 1);
	//if ($prev_rfi_num<1) $prev_rfi_num=1;
	$new_rfi_info=getoneb("select * from rfilog where jobinfo_id = '$rfi_info->jobinfo_id' and section = '$rfi_info->section' and rfi_num = $prev_rfi_num");
	}
if ($submitval=="Next") {
	$next_rfi_num=round($rfi_info->rfi_num + 1);
	//if ($next_rfi_num<1) $next_rfi_num=1;
	$new_rfi_info=getoneb("select * from rfilog where jobinfo_id = '$rfi_info->jobinfo_id' and section = '$rfi_info->section' and rfi_num = $next_rfi_num");
	}
if ($new_rfi_info) {
	forward("rfi_edit&rfi_id=$new_rfi_info->rfi_id");
	exit;
	}
forward('main');
exit;
?>
