<?
$today=date('m-d-Y');
$submit_text="OK";

if (!($write)) die_security();

if ($gcrfi_id!="") {
	$new=0;
	$gcrfi_id=addslashes($gcrfi_id);
	$gcrfi_info=getoneb("select * from gcrfilog where gcrfi_id = '$gcrfi_id'");
	$jobinfo_id=$gcrfi_info->jobinfo_id;
	$creator_info=getoneb("select * from contacts where contacts_id = '$gcrfi_info->creator'");
	$gcrfi_info->gcrfi_date=invali_date($gcrfi_info->gcrfi_date,'/');
	$gcrfi_info->sent_to_date=invali_date($gcrfi_info->sent_to_date,'/');
	$gcrfi_info->key_description=htmlspecialchars($gcrfi_info->key_description);
	$gcrfi_info->question=htmlspecialchars($gcrfi_info->question);
	$gcrfi_info->solution=htmlspecialchars($gcrfi_info->solution);
	$gcrfi_info->response=htmlspecialchars($gcrfi_info->response);
	if (($global_user_id!=$gcrfi_info->creator)&&($gcrfi_info->initial_review_done=='N')) {
		//echo "trying to fix the initial review by field";
		$gcrfi_info->initial_review_done='Y';
		$gcrfi_info->initial_review_by=$global_user_id;
		@mysql_query("update gcrfilog set initial_review_done = 'Y', initial_review_by = '$global_user_id' where gcrfi_id = '$gcrfi_info->gcrfi_id'");
		}
	$irvd_bg='#ffffff';
	if ($gcrfi_info->initial_review_done!='Y') $irvd_bg='yellow';
	$gcrfi_info->initial_review_done=checkbreak($gcrfi_info->initial_review_done);
	} else {
	$new=1;
	$gcrfi_info->gcrfi_date=$today;
	$submit_text="Save and Add Files";
	$creator_info=getoneb("select * from contacts where contacts_id = '$global_user_id'");
	$gcrfi_info->rep_id=$creator_info->contacts_id;
	}
$gcrfi_info->attached_sheets=checkbreak($gcrfi_info->attached_sheets);
ajax_load();
require('header.phtml');
fd_navs_header();
if ($jobinfo_id!="") $jobinfo_id=addslashes($jobinfo_id);
$jobinfo=getoneb("select * from jobinfo where jobinfo_id = '$jobinfo_id'");

if ($gcrfi_id!="") {
	$fd_manager=fd_manager($gcrfi_info->jobinfo_id,$global_user_id);
	if ($fd_manager||$adminuser) {
		echo "<script>
			function delete_gcrfi(gcrfi_id) {
				if (confirm('Permanently delete this gcrfi?'))
					document.location='$pagename?mode=gcrfi_delete&gcrfi_id=$gcrfi_info->gcrfi_id';
					}
			</script>";
		}
	}

if ($global_browser!='IE') {
	$row_display="table-row";
	$row_hide="none";
	} else {
	$row_display="inline";
	$row_hide="none";
	}

$data_display="";
$onsubmit="";
$image_link=webfile_possible_view_link($gcrfi_info->gcrfi_image_id);

//if (fast_connection()) {
if ($image_link) {
	$data_display=$row_hide;
	$onsubmit="show_data();";
	}
//}
echo"
<p>
<form onsubmit=\"$onsubmit\" name=gcrfi_edit method=post action=\"$pagename\">
<input type=hidden name=mode value=gcrfi_submit>
<input type=hidden name=gcrfi_id value=\"$gcrfi_info->gcrfi_id\">
<input type=hidden name=submitvalalt value=\"\">
<table border=0 cellspacing=0 cellpadding=4 style=\"border-left: 2px solid black;\">

<tr><td colspan=2 style=\"border-bottom: 2px solid; border-top: 2px solid;\">
	<font size=+2><b>GC&nbsp;RFI&nbsp;-&nbsp;Request&nbsp;For&nbsp;Information</b></font>
</td><td style=\"border-left: 2px solid black;border-right: 2px solid black;border-top: 2px solid black;\" align=center valign=top>
	<img src=/images/home_umclogo.png>
</td></tr>

<tr><td colspan=2 align=center>
	<table border=0 cellspacing=0 cellpadding=0 width=100%>
	<tr><td align=center>";
		if ($new!="1") echo "<input name=submitval type=submit value=\"Prev\">";
		else echo "&nbsp;";
		echo "
	</td><td align=center>
		<input name=submitval type=submit value=\"Cancel\">
	</td><td align=center>
		<input name=submitval type=submit value=\"Apply\">
	</td><td align=center>
		<input name=submitval type=submit value=\"$submit_text\">
	</td><td align=center>";
		if ($new!="1") echo "<input name=submitval type=submit value=\"Next\">";
		else echo "&nbsp;";
		echo "
	</td></tr>
	</table>
	</td><td style=\"border-left: 2px solid black; border-right: 2px solid black; border-bottom: 2px solid black;\" rowspan=25 valign=top>
	<div style=\"border: 1px solid black; float: right; background: $irvd_bg;\">&nbsp;Initial&nbsp;Review&nbsp;Done&nbsp;<input type=checkbox name=initial_review_done $gcrfi_info->initial_review_done>&nbsp;</div><font size=+1>&nbsp;</font>
	";
	
	if ($gcrfi_id!="") $doc_id=fd_get_doc_id($gcrfi_info->gcrfi_id);
	pal_box($doc_id);
	echo"
	<table style=\"border: 0px solid black;\" width=100%>
	<tr><td>
		Cost/Sched Impact&nbsp;
	</td><td>
		<select name=has_cost>
		<option>$gcrfi_info->has_cost</option>
		<option>Y</option>
		<option>N</option>
		<option> </option>
		</select>
	</td></tr>
	<tr><td>
		UMC COP #
	</td><td>
		<i>disabled</i>
	</td></tr>
	</table>
	";
	if ($gcrfi_id!="") {
		echo"
		<div style=\"border: 2px solid black;\" width=100% id=record_dwg_posting></div>
		<div style=\"border: 2px solid black;\" width=100% id=det_cfu_box>";include("det_cfu_box.phtml");echo"</div>
		<div style=\"border: 2px solid black;\" width=100% id=todo_completion_dates>";include("todo_completion_dates.phtml");echo"</div>
		<script>ajaxManager('load_page','$pagename?mode=rfi_record_dwg_posting&doc_id=$doc_id','record_dwg_posting');</script>
		";
	}
	echo"
	<div style=\"border: 2px solid black\" width=100% id=various_notes>
	<div width=100% style=\"background: $fd_color_4;\">Notes</div>
	<textarea onfocus=\"box_big(this)\" name=pm_notes rows=2 cols=40>$gcrfi_info->pm_notes</textarea><br>

</td></tr>

<tr><td width=200>
	<b>Job #:</b>
</td><td width=600>
	$jobinfo->contract_num
</td></tr>

<tr><td>
	<b>Job Name:</b>
</td><td>
	$jobinfo->display_name
</td></tr>

<tr><td>
	<b>GC RFI #:</b>
</td><td><table width=100% border=0 cellspacing=0 cellpadding=0><tr><td width=100%><input type=text size=12 name=gcrfi_num value=\"$gcrfi_info->gcrfi_num\"></td><td align=right><b>Sent&nbsp;Date:</b></td><td>&nbsp;&nbsp;$gcrfi_info->sent_to_date&nbsp;&nbsp;&nbsp;&nbsp;</td></tr></table>
</td></tr>

<tr><td valign=top>
	<b>UMC RFI #:</b>
</td><td>
	";fd_document_box(array('limit_to_type'=>'rfi'));echo"
</td></tr>

<tr><td>
	<b>Subject:</b>
</td><td>
	<input type=text name=key_description maxlength=85 size=40 value=\"$gcrfi_info->key_description\">
</td></tr>

<tr bgcolor=#ffffaa id=d10><td>
	<b>Date Sent</b>
</td><td>
	";datebox2($gcrfi_info->sent_to_date,'gcrfi_edit.sent_to_date','','0','U');echo"
</td></tr>

<tr bgcolor=#ffffaa id=d8><td>
	<b>Response Required</b>
</td><td>
	";datebox2($gcrfi_info->response_needed_date,'gcrfi_edit.response_needed_date','','0','U');echo"
</td></tr>

<tr bgcolor=#ffffaa id=d14><td>
	<b>Response Date</b>
</td><td>
	";datebox2($gcrfi_info->reply_date,'gcrfi_edit.reply_date','','0','U');echo"
	<input type=hidden name=hidden_reply value=\"$gcrfi_info->reply\">
</td></tr>







";

$unselected_color=$fd_color_3;
$selected_color="#ffffff";

if ($image_link && fast_connection()) {
	$data_display=$row_hide;
	$data_row_display=$row_hide;
	$image_row_display=$row_display;
	} else {
	$data_row_display=$row_display;
	$image_row_display=$row_hide;
	$data_display=$row_display;
	} 

echo "
<tr id=image2 style=\"display: $image_row_display;\"><td colspan=2>
	<table width=100% border=0 cellspacing=0 cellpadding=5><tr>
	<td style=\"cursor: hand; cursor: pointer; border: 2px solid black; border-right: 1px solid black; -moz-border-radius: 15px 15px 0px 0px;\" width=150px bgcolor=$unselected_color onclick=show_data();><b>Show Data</b></td>
	<td style=\"cursor: hand; cursor: pointer; border: 2px solid black; border-left: 1px solid black; border-bottom: 0px solid $unselected_color; -moz-border-radius: 15px 15px 0px 0px;\" width=150px onclick=show_image() bgcolor=$selected_color><font color=blue>Refresh Image(s)</font></td>
	<td style=\"border-bottom: 2px solid black;\">&nbsp;</td>
	</table></td></tr>

	
<tr id=d15 style=\"display: $data_row_display;\"><td colspan=2>
	<table width=100% border=0 cellspacing=0 cellpadding=5><tr>
	<td style=\"border: 2px solid black; border-bottom: 0px solid $unselected_color; -moz-border-radius: 15px 15px 0px 0px;\" width=150px bgcolor=$selected_color><b>Show Data</b></td>
";

	if ($image_link) {
		echo "<td style=\"cursor: hand; cursor: pointer; border: 2px solid black; border-left: 1px solid black; -moz-border-radius: 15px 15px 0px 0px;\" width=150px onclick=\"show_image();\" bgcolor=$unselected_color>Show Image</td>";
		} else {
		echo "<td align=center style=\"border: 2px solid black; border-left: 1px solid black; -moz-border-radius: 15px 15px 0px 0px;\" width=280px bgcolor=$unselected_color><b>Attach File:&nbsp;</b>";webfilebox($gcrfi_info->gcrfi_image_id,'gcrfi_image_id','',8);echo"</td>";
		}

echo"
	<td style=\"border-bottom: 2px solid black;\">&nbsp;</td>
	</table>
</td></tr>
<tr bgcolor=#cccccc style=\"display: $image_row_display;\" id=image><td colspan=2 style=\"border: 2px solid black; border-top: 0px solid black;\"><iframe id=\"image_iframe\" style=\"displays:none;\" width=800 height=600 src=$image_link></iframe></td></tr>
";

echo "
<tr id=d16 style=\"display: $data_display;\"><td>
	<b>CPM Sched ID</b>
</td><td>
	<input type=text size=10 name=cpm_schedule_id value=\"$gcrfi_info->cpm_schedule_id\">
</td></tr>

<tr id=d1 style=\"display: $data_display;\"><td>
	<b>Spec</b>
</td><td>
	<input type=text size=10 name=spec value=\"$gcrfi_info->spec\">
</td></tr>

<tr id=d2 style=\"display: $data_display;\"><td>
	<b>Bldg / Floor</b>
</td><td>
	<input type=text size=15 name=bldg value=\"$gcrfi_info->bldg\"> / <input type=text name=floor size=8 value=\"$gcrfi_info->floor\">
</td></tr>


<tr id=d3 style=\"display: $data_display;\"><td valign=top>
	<b>Location</b>
</td><td id=dwg_ref_list>
	<b><i>Loading...</i></b>
</td></tr>

<tr id=d4 style=\"display: $data_display;\"><td valign=top>
	<b>Question</b>
</td><td>
	<textarea onfocus=\"box_big(this)\" name=question rows=2 cols=50>$gcrfi_info->question</textarea>
</td></tr>

<tr id=d5 style=\"display: $data_display;\"><td valign=top>
	<b>Recommended<br>Solution</b>
</td><td>
	<textarea onfocus=\"box_big(this)\" name=solution rows=2 cols=50>$gcrfi_info->solution</textarea>
</td></tr>

<tr id=d6 style=\"display: $data_display;\"><td>
	<b>Additional Cost</b>
</td><td>
	<input type=checkbox name=has_cost $gcrfi_info->has_cost>
</td></tr>

<tr id=d7 style=\"display: $data_display;\"><td>
	<b>UMC Rep</b>
</td><td>
	";contactsbox("select * from contacts where umc_emp = 'Y' and current = 'Y'",$gcrfi_info->rep_id,'rep_id');echo"
</td></tr>

<tr id=d9 style=\"display: $data_display;\"><td>
	<b>Attached Sheets</b>
</td><td>
	<input type=checkbox name=attached_sheets $gcrfi_info->attached_sheets>&nbsp;<input name=attached_sheet_name value=\"$gcrfi_info->attached_sheet_name\">
</td></tr>

";

if ($image_link) {
echo "<tr bgcolor=#cccccc id=d11 style=\"display: $data_display;\"><td>
	<b>GC RFI Image/file</b>
</td><td>
	";
	webfilebox($gcrfi_info->gcrfi_image_id,'gcrfi_image_id');
	echo "
</td></tr>";
} else {
echo "<div id=d11>";
}

echo "
<tr bgcolor=#cccccc id=d12 style=\"display: $data_display;\"><td valign=top>
	<b>Response</b>
</td><td>
	<textarea onchange=\"fill_response_date()\" onfocus=\"box_big(this)\" onblur=\"box_little(this)\" name=reply rows=2 cols=50>$gcrfi_info->reply</textarea>
</td></tr>

<tr bgcolor=#cccccc id=d13 style=\"display: $data_display;\"><td>
	<b>Response from</b>
</td><td>
	";contactsbox("select * from contacts where current = 'Y'",$gcrfi_info->reply_from,'reply_from');echo"
</td></tr>

</table>	



</form>

<script>

function update_posting_item(posting_id,field_name,field_value) {
	ajaxManager('load_page','$pagename?mode=rfi_record_dwg_posting&doc_id=$doc_id&selected_tab=' + posting_id + '&update_field_name=' + field_name + '&update_field_value=' + field_value,'record_dwg_posting');
	}

function show_image() {
	hide_data();
	document.getElementById('image').style.display='$row_display';
	document.getElementById('image2').style.display='$row_display';
	document.getElementById('image_iframe').src='$image_link';
	}

function show_data() {
	hide_image();
	document.getElementById('d1').style.display='$row_display';
	document.getElementById('d2').style.display='$row_display';
	document.getElementById('d3').style.display='$row_display';
	document.getElementById('d4').style.display='$row_display';
	document.getElementById('d5').style.display='$row_display';
	document.getElementById('d6').style.display='$row_display';
	document.getElementById('d7').style.display='$row_display';
	document.getElementById('d9').style.display='$row_display';
	document.getElementById('d11').style.display='$row_display';
	document.getElementById('d12').style.display='$row_display';
	document.getElementById('d13').style.display='$row_display';
	document.getElementById('d15').style.display='$row_display';
	document.getElementById('d16').style.display='$row_display';
	}

function hide_image() {
	document.getElementById('image').style.display='$row_hide';
	document.getElementById('image2').style.display='$row_hide';
	}

function hide_data() {
	document.getElementById('d1').style.display='$row_hide';
	document.getElementById('d2').style.display='$row_hide';
	document.getElementById('d3').style.display='$row_hide';
	document.getElementById('d4').style.display='$row_hide';
	document.getElementById('d5').style.display='$row_hide';
	document.getElementById('d6').style.display='$row_hide';
	document.getElementById('d7').style.display='$row_hide';
	document.getElementById('d9').style.display='$row_hide';
	document.getElementById('d11').style.display='$row_hide';
	document.getElementById('d12').style.display='$row_hide';
	document.getElementById('d13').style.display='$row_hide';
	document.getElementById('d15').style.display='$row_hide';
	document.getElementById('d16').style.display='$row_hide';
	}

function rem_dwg_ref(gcrfi_ref_id) {
	if ('$gcrfi_info->gcrfi_id'=='') return FALSE;
	loadurl='$pagename?mode=dwg_ref_list&gcrfi_id=$gcrfi_info->gcrfi_id&remove_gcrfi_ref_id=' + gcrfi_ref_id;
	ajaxManager('load_page',loadurl,'dwg_ref_list');
	}
	
function add_dwg_ref() {
	if ('$gcrfi_info->gcrfi_id'=='') return FALSE;
	loadurl='$pagename?mode=dwg_ref_list&gcrfi_id=$gcrfi_info->gcrfi_id&dwg=' + document.gcrfi_edit.dwg.value + '&grid_ref=' + document.gcrfi_edit.grid_ref.value;
	ajaxManager('load_page',loadurl,'dwg_ref_list');
	}

function box_little(obj) { obj.rows=2; }
function box_big(obj) { obj.rows=10; }

function update_assigned_to(posting_id) {
	/////////////////////////////////////////////////////////////
	// This function does work, but will cause errors to show up
	// in the browser javascript output because it was launched in
	// a different window. When the update launched by the other 
	// window is done it tries to write the results to a named
	// object id's innerHTML, but can't find the object with the
	// correct id.  The launching window also closes itself, so
	// there is no id available to write back to over there either.
	//
	// I tried to kill the error, by writing back to a special 'null'
	// id which aborts any write backs, but there is still an error
	// because the callback object disappears mid-stream with the
	// window that launched it.
	/////////////////////////////////////////////////////////////
	obj=document.getElementById('hidden_contactsbox_selected_assigned_to');
	if (obj.value=='') obj.value='0';
	ajaxManager('load_page','$pagename?mode=rfi_record_dwg_posting&doc_id=$doc_id&selected_tab=' + posting_id + '&assigned_to_set=' + obj.value,'verynull');
	}

function cfu_select_update(field) {
	eval ('fieldval=document.gcrfi_edit.' + field + '.value;');
	ajaxManager('load_page','$pagename?mode=det_cfu_box&doc_id=$doc_id&field=' + field + '&fieldval=' + fieldval,'det_cfu_box');
	}

function cfu_hours_update(field) {
	eval ('fieldval=document.gcrfi_edit.' + field + '.value;');
	ajaxManager('load_page','$pagename?mode=det_cfu_box&doc_id=$doc_id&hoursfield=' + field + '&hoursfieldval=' + fieldval,'det_cfu_box');
	}

function comp_date_update(field,value) {
	eval('document.gcrfi_edit.' + field + '.style.background=\"yellow\"');
	ajaxManager('load_page','$pagename?mode=todo_completion_dates&doc_id=$doc_id&field='+ field + '&value=' + value,'todo_completion_dates');
	}

function apply_changes() {
	document.gcrfi_edit.submitval.value='Apply';
	document.gcrfi_edit.submitvalalt.value='Apply';
	document.gcrfi_edit.submit();
	}

function fill_response_date() {
	if (document.gcrfi_edit.hidden_reply.value=='') {
		if (document.gcrfi_edit.reply_date.value=='') document.gcrfi_edit.reply_date.value='$today';
		}
	}

ajaxManager('load_page','$pagename?mode=dwg_ref_list&gcrfi_id=$gcrfi_info->gcrfi_id','dwg_ref_list');
</script>
";
fd_navs_footer();
?>
