<?

$gcrfi_info->gcrfi_date=invali_date($gcrfi_info->gcrfi_date);
//$gcrfi_info->gcrfi_num=ereg_replace('.00$','',"$gcrfi_info->gcrfi_num");

$job_info=getoneb("select * from jobinfo where jobinfo_id = '$gcrfi_info->jobinfo_id'");
$creator_info=getoneb("select * from contacts where contacts_id = '$gcrfi_info->creator'");
$border_right=576;

$fontsize="10";
$standard_gap="16";
$my_loc="710";

$pdf->selectFont("$pdf_font_path/Helvetica.afm");
$pdf->ezSetMargins(36,36,36,36);
////////////////////////////////////////////////////////
// The logo and header/address junk
////////////////////////////////////////////////////////
//$pdf->addPngFromFile('/home/web/pipeline.umci.com/images/umc_logo_med_res.png',435,700,150,56);
// GPH MARK - absolute path
$pdf->addPngFromFile('/data/web/pipeline/images/umclogo_wbv2.png',435,710,150,48);
$pdf->addText(488,690,8,"11611 49th Place West");
$pdf->addText(488,680,8,"P.O. Box 67");
$pdf->addText(488,670,8,"Mukilteo, Washington");
$pdf->addText(488,660,8,"98275-4255");
$pdf->addText(488,640,8,"<b>Phone (206) 364-9900</b>");
$pdf->addText(488,630,8,"Fax (206) 365-1580");
///////////////////////////////////////////////////////

// Header
$pdf->ezStartPageNumbers(550,35,10,'',"JOB $job_info->contract_num GCRFI $gcrfi_info->gcrfi_num, Created By: $creator_info->first_name $creator_info->last_name                                      Page {PAGENUM} of {TOTALPAGENUM}");
$pdf->ezText("(GC) RFI - REQUEST FOR INFORMATION",20);
$pdf->line(36,730,400,730);


// Job find RFI # information
$my_start_y=$my_loc;
$pdf->addText(36,$my_loc,$fontsize,"<b>Date:</b>");
$pdf->addText(95,$my_loc,$fontsize,"$gcrfi_info->gcrfi_date");
$my_loc=$my_loc - $standard_gap;
$pdf->addText(36,$my_loc,$fontsize,"<b>Job #:</b>");
$pdf->addText(95,$my_loc,$fontsize,"$job_info->contract_num");
$my_loc=$my_loc - $standard_gap;
$pdf->addText(36,$my_loc,$fontsize,"<b>Project:</b>");
$pdf->addText(95,$my_loc,$fontsize,"$job_info->display_name");
$my_loc=$my_start_y;
$pdf->addText(316,$my_loc,$fontsize,"<b>GC RFI #:</b>");
$pdf->addText(375,$my_loc,$fontsize,"$gcrfi_info->gcrfi_num");
$my_loc=$my_loc - $standard_gap;
$pdf->addText(316,$my_loc,$fontsize,"<b>UMC RFI #:</b>");
$pdf->addText(375,$my_loc,$fontsize,"xxxxxx");
$my_loc=$my_loc - $standard_gap;
if ($gcrfi_info->sub_rfi_num!="") {	
	$pdf->addText(316,$my_loc,$fontsize,"<b>Sub RFI #:</b>");
	$pdf->addText(375,$my_loc,$fontsize,"$gcrfi_info->sub_rfi_num");
	}

$pdf->setStrokeColor(.3,.3,.3);
$pdf->setLineStyle(.1);

$my_loc=$my_loc - ($standard_gap /2);
// Main description stuff
$box_top=$my_loc;
$my_loc=$my_loc - $standard_gap;
$pdf->addText (40,$my_loc,$fontsize,"Subject: " . substr($gcrfi_info->key_description,0,65));
$pdf->line(79,$my_loc - 1,379,$my_loc - 1);
$pdf->addText (382,$my_loc,$fontsize,"Spec: $gcrfi_info->spec");
$pdf->line(411,$my_loc - 1,460,$my_loc - 1);
$my_loc=$my_loc - $standard_gap;
$pdf->addText (315,$my_loc,$fontsize,"Bldg: $gcrfi_info->bldg");
$pdf->line(341,$my_loc - 1,380,$my_loc - 1);
$pdf->addText (382,$my_loc,$fontsize,"Floor: $gcrfi_info->floor");
$pdf->line(411,$my_loc - 1,460,$my_loc - 1);
$count=1;

$grres=@mysql_query("select * from gcrfi_dwg_refs where gcrfi_id = '$gcrfi_info->gcrfi_id'");
$bump='yes';

while ($grrow=@mysql_fetch_object($grres)) {
	$pdf->addText (40,$my_loc,$fontsize,"Dwg:");
	$pdf->addText (68,$my_loc,$fontsize,$grrow->dwg);
	$pdf->line(66,$my_loc - 1,122,$my_loc - 1);
	$pdf->addText (125,$my_loc,$fontsize, "Grid Ref:");
	$pdf->addText (169,$my_loc,$fontsize,$grrow->grid_ref);
	$pdf->line(167,$my_loc - 1,250,$my_loc - 1);
	$my_loc = $my_loc - $standard_gap;
	$count++;
	$bump='no';
	}
if ( $bump == 'yes' ) $my_loc=$my_loc - $standard_gap;
$box_end=$my_loc+($standard_gap / 2);

// Box for the main description stuff
//$box_end=630;
$pdf->line(36,$box_top,465,$box_top);
$pdf->line(36,$box_end,465,$box_end);
$pdf->line(36,$box_top,36,$box_end);
$pdf->line(465,$box_top,465,$box_end);

// Box for the question
$box_top=$box_end - 9;
$pdf->ezSetY($box_top);
$boxdata=array(36,$box_top,$border_right,$box_top,$border_right,$box_top - 14,36,$box_top - 14);
$pdf->setColor(.7,.7,.7);
$pdf->polygon($boxdata,4,1);
$pdf->setColor(0,0,0);

$pdf->ezText("<b>Question:</b>\r\n$gcrfi_info->question\r\n",$fontsize,array('aleft'=>'46','aright'=>'566'));
$box_end=$pdf->y;
$pdf->line(36,$box_top,$border_right,$box_top);
$pdf->line(36,$box_end,$border_right,$box_end);
$pdf->line(36,$box_top,36,$box_end);
$pdf->line($border_right,$box_top,$border_right,$box_end);


////////////////////////////////////////////////////////////
// Box for the solution
// Note, much of this is done twice, because we roll back a
// transaction if we end up on a new page.
////////////////////////////////////////////////////////////
$page=$pdf->ezPageCount;
$pdf->transaction('start');
$pdf->ezSetY($box_top);
$box_top=$box_end - 9;
$pdf->ezSetY($box_top);
$boxdata=array(36,$box_top,$border_right,$box_top,$border_right,$box_top - 14,36,$box_top - 14);
$pdf->setColor(.7,.7,.7);
$pdf->polygon($boxdata,4,1);
$pdf->setColor(0,0,0);

$pdf->ezText("<b>Recommended Solution:</b>\r\n$gcrfi_info->solution\r\n",$fontsize,array('aleft'=>'46','aright'=>'566'));
$box_end=$pdf->y;
$border_right=576;
if ($pdf->ezPageCount!=$page) {
	$pdf->transaction('rewind');
	$pdf->ezNewPage();
	$box_top=$pdf->y;
	
	$boxdata=array(36,$box_top,$border_right,$box_top,$border_right,$box_top - 14,36,$box_top - 14);
	$pdf->setColor(.7,.7,.7);
	$pdf->polygon($boxdata,4,1);
	$pdf->setColor(0,0,0);

	$pdf->ezText("<b>Solution:</b>\r\n$gcrfi_info->solution\r\n",$fontsize,array('aleft'=>'46','aright'=>'566'));
	$box_end=$pdf->y;
	$border_right=576;
	$pdf->line(36,$box_top,$border_right,$box_top);
	} else {
	$pdf->transaction('commit');
	}
$pdf->line(36,$box_top,$border_right,$box_top);
$pdf->line(36,$box_end,$border_right,$box_end);
$pdf->line(36,$box_top,36,$box_end);
$pdf->line($border_right,$box_top,$border_right,$box_end);
////////////////////////////////////////////////////////////

$rep_info=getoneb("select * from contacts where contacts_id = '$gcrfi_info->rep_id'");
if (!($rep_info)) $rep_info=getoneb("select * from contacts where contacts_id = '$gcrfi_info->creator'");


$pdf->ezText("<b>Additional Cost: </b> $gcrfi_info->has_cost");
$pdf->ezText("<b>UMC Rep: </b> $rep_info->display_name");
$pdf->ezText("<b>Response Needed by: </b> " . invali_date($gcrfi_info->response_needed_date));

if (($gcrfi_info->attached_sheets=='Y')&&($gcrfi_info->attached_sheet_name!="")) $gcrfi_info->attached_sheets=$gcrfi_info->attached_sheet_name;
$pdf->ezText("<b>Attached Sheets: </b> $gcrfi_info->attached_sheets");
$sent_to_info=getoneb("select * from contacts where contacts_id = '$gcrfi_info->sent_to_id'");
$pdf->ezText("<b>Sent to: </b> $sent_to_info->display_name <i>(" . invali_date($gcrfi_info->sent_to_date) . ")</i>");









$box_end= $pdf->y;
////////////////////////////////////////////////////////////
// Box for the Reply
// Note, much of this is done twice, because we roll back a
// transaction if we end up on a new page.
////////////////////////////////////////////////////////////
$page=$pdf->ezPageCount;
$pdf->transaction('start');
$box_top=$box_end-9;
$pdf->ezSetY($box_top);
$boxdata=array(36,$box_top,$border_right,$box_top,$border_right,$box_top - 14,36,$box_top - 14);
$pdf->setColor(.7,.7,.7);
$pdf->polygon($boxdata,4,1);
$pdf->setColor(0,0,0);

$reply_from_info=getoneb("select * from contacts where contacts_id = '$gcrfi_info->reply_from'");
if ($reply_from_info->contact_type=="contact") {
	$reply_comp_info=getoneb("select * from contacts where contacts_id = '$reply_from_info->company_id'");
	$reply_from_text="$reply_from_info->first_name $reply_from_info->last_name of $reply_comp_info->display_name";
	} else {
	$reply_from_text="$reply_from_info->display_name";
	}	


$reply_date_text=invali_date($gcrfi_info->reply_date);
$pdf->ezText("<b>Response               </b>  From: $reply_from_text on $reply_date_text\r\n$gcrfi_info->reply\r\n",$fontsize,array('aleft'=>'46','aright'=>'566'));
$box_end=$pdf->y;
$border_right=576;
if ($pdf->ezPageCount!=$page) {
	$pdf->transaction('rewind');
	$pdf->ezNewPage();
	$box_top=$pdf->y;
	$boxdata=array(36,$box_top,$border_right,$box_top,$border_right,$box_top - 14,36,$box_top - 14);
	$pdf->setColor(.7,.7,.7);
	$pdf->polygon($boxdata,4,1);
	$pdf->setColor(0,0,0);

	$pdf->ezText("<b>Response               </b>  From: $reply_from_text on $reply_date_text\r\n$gcrfi_info->reply\r\n",$fontsize,array('aleft'=>'46','aright'=>'566'));
	//$pdf->ezText("<b>Reply:</b>\r\n$gcrfi_info->reply\r\n",$fontsize,array('aleft'=>'46','aright'=>'566'));
	$box_end=$pdf->y;
	$border_right=576;
	$pdf->line(36,$box_top,$border_right,$box_top);
	} else {
	$pdf->transaction('commit');
	}
$pdf->line(36,$box_top,$border_right,$box_top);
$pdf->line(36,$box_end,$border_right,$box_end);
$pdf->line(36,$box_top,36,$box_end);
$pdf->line($border_right,$box_top,$border_right,$box_end);
////////////////////////////////////////////////////////////

?>
