<?
include("../webfile$devel/storage_settings.cfg");

$gcrfi_id=addslashes($gcrfi_id);
$gcrfi_info=getoneb("select * from gcrfilog where gcrfi_id = '$gcrfi_id'");
if (!($gcrfi_info)) {
	$doc_id=addslashes($doc_id);
	$doc_info=getoneb("select * from documents where doc_id = '$doc_id' and doc_type = 'gcrfi'");
	$gcrfi_info=getoneb("select * from gcrfilog where gcrfi_id = '$doc_info->app_record_id'");
	if (!($gcrfi_info)) pdf_generation_error_pdf("ERR(2) - Unable to load GCRFI information.");
	}
if (!($gcrfi_info)) pdf_generation_error_pdf("ERR(1) - Unable to load GCRFI information.");
$job=getoneb("select * from jobinfo where jobinfo_id = '$gcrfi_info->jobinfo_id'");

$files_res=@mysql_query("select * from webfile_files where file_group_id = '$gcrfi_info->gcrfi_image_id' and mime_type like '%pdf%'");
$file_letter="a";

$row=@mysql_fetch_object($files_res);
if ($row->file_group_id==0) pdf_generation_error_pdf("ERR(99) - Unable to find a pdf to show.");
pdf_mime_header("GCRFI_$doc_info->app_reference.pdf");
readfile("$storage_root$row->file_path");

?>
