<?
if (!($adminuser)) die_security();
require('header.phtml');
$section_id=addslashes($section_id);
$section_info=getoneb("select * from gcrfi_sections where section_id = '$section_id'");
if (!($section_info)) die("Application Error: Invalid section specified. Please contact your system administrator!");

echo "
<form name=section_name method=post action=$pagename>
<input type=hidden name=mode value=section_change_name_submit>
<input type=hidden name=section_id value=\"$section_info->section_id\">
<table border=1 cellspacing=0 cellpadding=4>
<tr><td>
	<b>Name</b>
</td><td>
	<input type=text name=section value=\"$section_info->section\">
</td></tr>

<tr><td colspan=2 align=right>
	<input type=submit value=Submit>
</td></tr>
</table>
";
?>
