<?
$rfi_id=addslashes($rfi_id);
$document_info=getone("select * from documents where app_record_id = '$rfi_id' and doc_type = 'rfi' limit 1");
$semi_rand = md5(time()); 
$mime_boundary = "==Multipart_Boundary_x{$semi_rand}x";  

$recipient=addslashes($recipient);
$contact_info=getoneb("select * from contacts where contacts_id = '$recipient'");
$rfi_info=getone("select * from rfilog where rfi_id = '$rfi_id'");


require_once('pdf_lib2.inc');
$pdf=&new Cezpdf("$global_user->pref_paper_size","portrait");
require('rfi_render_pdf.phtml');

$pdf_data=$pdf->ezOutput();
$send_result=send_email_now(
	$global_user_id ,
	$recipient ,
	$document_info->doc_id ,
	"UMC RFI # $rfi_info->rfi_num",
	$message ,
	$pdf_data,
	"umc_rfi_$rfi_info->rfi_num.pdf",
	"application/pdf"
	);

//mail('jeffb@umci.com',
//	'PDF For you', 
//	$full_message , 
//	"From: UMC Web Server <webmaster@umci.com>\r\nContent-type: multipart/mixed;\r\n  boundary=\"$mime_boundary\"");

echo "RFI (id $rfi_id) sent to:<br>$contact_info->display_name<p>";
sleep (.1);
?>
