<?
include("../webfile$devel/storage_settings.cfg");

if ($doc_id=="") pdf_generation_error_pdf("ERR(1) - Unable to load document information.");
$doc_id=addslashes($doc_id);
$doc_info=getoneb("select * from documents where doc_id = '$doc_id' and doc_type = 'sketchlog'");
if (!($doc_info)) pdf_generation_error_pdf("ERR(2) - Unable to load document information.");
$sketch_info=getoneb("select * from sketchlog where sketchlog_id = '$doc_info->app_record_id'");
if (!($sketch_info)) pdf_generation_error_pdf("ERR(3) - Unable to load sketch information.");

$job=getoneb("select * from jobinfo where jobinfo_id = '$doc_info->jobinfo_id'");
$rev=getoneb("select * from sketchlog_revs where sketchlog_id = '$sketch_info->sketchlog_id' order by revision desc limit 1");

if (!($rev)) pdf_generation_error_pdf("ERR(4) - Unable to load document revision.");

$files_res=@mysql_query("select * from webfile_files where file_group_id = '$rev->attached_file_group_id' and mime_type like '%pdf%'");

pdf_mime_header("Sketch_-_$doc_info->app_reference.pdf");
while ($row=@mysql_fetch_object($files_res)) {
	if ($row->file_group_id==0) continue;
	readfile("$storage_root$row->file_path");
	}
?>
