<?
if ($sketch_rev_id=="") die("Application Error: No sketch_rev_id specified! Please contact your system administrator!");
else $sketch_rev_id=addslashes($sketch_rev_id);

if ($attached_file_group_id=="") die("Application Error: No attached_file_group_id specified! Please contact your system administrator!");
else $attached_file_group_id=addslashes($attached_file_group_id);

$query="update sketchlog_revs set attached_file_group_id = '$attached_file_group_id' where sketch_rev_id = '$sketch_rev_id'";
@mysql_query($query);
echo "booya!!!!!!!!!!!!";
?>
