<?
//if ($section_id=="") die("Application error. No section specified.");
//else 
$section_id=addslashes($section_id);

$section_info=getoneb("select * from sketchlog_sections where section_id = '$section_id'");
if (!($section_info)) die("Application error. Section invalid.");


if ($section_info->active=='Y') $section_info->active='N';
else $section_info->active='Y';

@mysql_query("update sketchlog_sections set active = '$section_info->active' where section_id = '$section_info->section_id'");
forward('manage_sections');






?>
