<?
if (!($adminuser)) die_security();
require("../webfile/storage_settings.cfg");
require("../webfile/local.inc");
$sketchlog_id=addslashes($sketchlog_id);
$sketchlog_info=getoneb("select * from sketchlog where sketchlog_id = '$sketchlog_id'");
$revs=@mysql_query("select * from sketchlog_revs where sketchlog_id = '$sketchlog_info->sketchlog_id'");
while($rev=@mysql_fetch_object($revs)) delete_webfile_group($rev->attached_file_group_id);
@mysql_query("delete from sketchlog_revs where sketchlog_id = '$sketchlog_info->sketchlog_id'");
@mysql_query("delete from sketchlog where sketchlog_id = '$sketchlog_id'");
@mysql_query("delete from documents where doc_type = 'sketchlog' and app_record_id = '$sketchlog_info->sketchlog_id'");
@mysql_query("delete from sketchlog_history where sketchlog_id = '$sketchlog_info->sketchlog_id'");
@mysql_query("delete from sketchlog_notes where sketchlog_id = '$sketchlog_info->sketchlog_id'");
forward('main');
?>
