<?

if (!($issue_res_admin)) 
	die ("You don't have permissions to be here, so go away!!!!!!!!!");

if ($issue_res_category_rights_id=="")
	die ("You didn't give me enough information to work with. Please contact your system administrator for help or something!!!!");


$issue_res_category_rights_id=escapeshellcmd($issue_res_category_rights_id);

$query="delete from issue_res_category_rights where issue_res_category_rights_id = '$issue_res_category_rights_id'";
$res=@mysql_query($query);

if (!($res))
	die("Error with query. DB update failed. Please contact your system administrator!<p>Failed query: <hr>$query");

forward('admin_category');

?>
