<?

if (!($issue_res_admin))
	die ("Fatal Error: Invalid Permissions. You shouldn't be here, so go away now or we'll be sending the cops soon!");

if ($issue_res_users_id=="") 
	die ("Fatal Error: Invalid information supplied, can not continue. Please contact your system administrator for assistence.");

$issue_res_contacts_id=escapeshellcmd($issue_res_contacts_id);

$entry_info=getone("select * from issue_res_users where issue_res_users_id = '$issue_res_users_id'");


////////////////////////////////////////////////////////////////////////////////////////
//	Eliminate the notifications for this user in this job
////////////////////////////////////////////////////////////////////////////////////////
$to_delete_query="select issue_res_notify.issue_res_notify_id as notify_id from issue_res_issues,issue_res_category,issue_res_application,issue_res_notify
where issue_res_issues.issue_res_category_id = issue_res_category.issue_res_category_id
and issue_res_category.issue_res_application_id = issue_res_application.issue_res_application_id
and issue_res_application.jobinfo_id = '$entry_info->jobinfo_id'
and issue_res_issues.problem_id = issue_res_notify.problem_id
and issue_res_notify.contacts_id = '$entry_info->contacts_id'";

$res=@mysql_query($to_delete_query);
while($row=@mysql_fetch_object($res)) @mysql_query("delete from issue_res_notify where issue_res_notify_id = '$row->notify_id'");
////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////

$issue_res_users_info=getoneb("select * from issue_res_users where issue_res_users_id = '$issue_res_users_id'");
$query="delete from issue_res_users where issue_res_users_id = '$issue_res_users_id'";
$res=@mysql_query($query);
security_log_email(
	$issue_res_users_info->contacts_id,
	0,
	$issue_res_users_info->jobinfo_id,
	"removed from job",
	$application_name);
if (!($res))
	die ("Fatal Error: Invalid information supplied, can not continue. Please contact your system administrator for assistence.");

////////////////////////////////////////////////////////////////////////////////////////
//	Check to see if there are any other jobs the user is set up for, and if not,
//	then delete the user from the global "access" table..
////////////////////////////////////////////////////////////////////////////////////////

//echo "select * from issue_res_users where contacts_id = '$entry_info->contacts_id' limit 1 <hr>";
//tabledump("select * from issue_res_users where contacts_id = '$entry_info->contacts_id' limit 1");
if (!(getoneb("select * from issue_res_users where contacts_id = '$entry_info->contacts_id' limit 1"))) {
	//echo "<b>That was the last entry. User should be deleted from the access table</b><hr>";
	$query="delete from access where application_name = '$application_name' and contacts_id = '$entry_info->contacts_id' and type = 'read_only' and rightsmode = 'grant'";
	//echo "<hr>$query<hr>";
	mysql_query($query);
	}

////////////////////////////////////////////////////////////////////////////////////////

forward('admin_users');
//echo "<a href=$pagename?mode=admin_users><font color=blue>continue</font></a>";
?>
