<?

$query="select * from issue_res_application where jobinfo_id = '$global_jobinfo_id' order by issue_res_application_name";
//tabledump($query);

echo "
<html>
<body bgcolor=#ffffff>
<a href=$pagename?mode=main><font color=blue>Cancel</font></a><hr>

<table border=1 cellpadding=4 width=60%>
	<tr bgcolor=$tableheadbgcolor><td>
		Log Name
	</td><td>
		Log Descripiton
	</td><td>
		Active
	</td><td>
		&nbsp;
	</td><td>
		&nbsp;
	</td></tr>";

$res=@mysql_query($query);

while($row=@mysql_fetch_object($res))
	echo "<tr><td>
			$row->issue_res_application_name&nbsp;
		</td><td>
			$row->issue_res_application_description&nbsp;
		</td><td>
			$row->issue_res_application_active&nbsp;
		</td><td>
			<a href=$pagename?mode=app_edit&issue_res_edit_application_id=$row->issue_res_application_id><font color=blue><i>Edit</i></font>
		</td><td>
			<a href=$pagename?mode=app_delete&issue_res_edit_application_id=$row->issue_res_application_id><font color=blue><i>Delete</i></font>
		</td></tr>";

echo "</table>

<form name=application_add method=post action=$pagename>
<input type=hidden name=mode value=app_edit_submit>

<table border=1 cellpadding=4>

<tr bgcolor=$tableheadbgcolor><td>
	New Log:
</td><td>
	Log Description:
</td><td>
	Active:
</td><td>
	&nbsp;
</td></tr>

<tr><td>	
	<input type=text name=issue_res_application_name size=30>
</td><td>
	<input type=text size=50 name=issue_res_application_description>
</td><td>
	<select name=issue_res_application_active>
		<option value=Y>Y</option>
		<option vlaue=N>N</option>
	</select>
</td><td>
	<input type=button value=\"Create\" onclick=submit();>
</td></tr>
</form>
</table>";






?>
