<?
if ($issue_res_edit_application_id=="")
	die("Error: Not enough information passed!!!!! Invalid function useage. Please contact your system administrator for help.<p>");
$issue_res_edit_application_id=escapeshellcmd($issue_res_edit_application_id);

$appeditinfo=getone("select * from issue_res_application where issue_res_application_id = '$issue_res_edit_application_id'");

echo"
<a href=$pagename?mode=app_edit_list><font color=blue>Cancel</font></a><hr>
<form name=application_edit method=post action=$pagename>
<input type=hidden name=mode value=app_edit_submit>
<input type=hidden name=issue_res_edit_application_id value=\"$issue_res_edit_application_id\">
<table border=1 cellpadding=5>
<tr bgcolor=$tableheadbgcolor><td>
	Log Name
</td><td>
	Log Description
</td><td>
	Active
</td><td>
	&nbsp;
</td></tr>

<tr><td valign=top>
	<input type=text size=30 name=issue_res_application_name value=\"$appeditinfo->issue_res_application_name\">
</td><td>
	<input type=text size=50 name=issue_res_application_description value=\"$appeditinfo->issue_res_application_description\">
</td><td>
	<select name=issue_res_application_active>
		<option value=$appeditinfo->issue_res_application_active>$appeditinfo->issue_res_application_active</option>
		<option value=Y>Y</option>
		<option value=N>N</option>
	</select>
</td><td>
	<input type=button value=\"Save\" onclick=submit();>
</td></tr>
</form>
</table>";







?>
