<?
require("header2.phtml");
	//<a href=$pagename?mode=job_selection_win><img border=0 src=up_arrow.png title=\"Up one level\"></a>

echo "
<script>
function app_set(issue_res_application_id){
opener.document.location='$pagename?mode=main&issue_res_application_id_set=' + issue_res_application_id ;
self.close();
}
</script>";


	if ($issue_res_admin) require("header_job_setup.phtml");
	echo "</center><font size=+1><b>Please select which issue log:</b></font><br>";
	$issue_res_app_query="select * from issue_res_application where jobinfo_id = '$global_jobinfo->jobinfo_id' order by issue_res_application_name";
	$applist_res=@mysql_query($issue_res_app_query);
	while($app_entry=@mysql_fetch_object($applist_res)) {
		if ($mode!="app_selection_win")
			echo "<ul><a href=$pagename?mode=main&issue_res_application_id_set=$app_entry->issue_res_application_id>";
		else 
			echo "<ul><a href=javascript:app_set('$app_entry->issue_res_application_id');>";
		
		echo "<font color=blue size=+1>
		$app_entry->issue_res_application_name
		</font>
		</a>
			<ul><li><i>$app_entry->issue_res_application_description</i></li></ul>
		</ul>";
		}

require("footer.phtml");
fd_navs_footer();
exit;

?>
