<?

if (!($issue_res_admin))
	die("Error: you shouldn't be here, so go away now!!!!");

require("header2.phtml");

$query="select * from issue_res_category left join issue_res_category_template on (issue_res_category.category_template_id = issue_res_category_template.category_template_id) where issue_res_application_id = '$issue_res_application_id' order by category_name";
//tabledump($query);
$res=@mysql_query($query);

echo "

<a href=$pagname?mode=main><font color=blue>Exit</font></a><hr>


<table border=1 cellpadding=3>
<tr bgcolor='$tableheadbgcolor'><td>
	Category Name
</td><td>
	Category Template
</td><td>
	Category Status
</td><td>
	&nbsp;
</td><td>
	&nbsp;
</td></tr>";


while($row=@mysql_fetch_object($res))
	echo "
	<tr><td>
		$row->category_name
	</td><td>
		$row->category_template_name
	</td><td>
		$row->category_status
	</td><td>
		<a href=$pagename?mode=category_edit&issue_res_edit_category_id=$row->issue_res_category_id>
		<font color=blue><i>Edit</i></font></a>	
	</td><td>
		<a href=javascript:cat_delete($row->issue_res_category_id)>
		<font color=blue><i>Delete</i></font></a>	
	</td></tr>
	";



echo"
</table>
<form name=category_create method=post action=$pagename>
<input type=hidden name=mode value=category_edit_submit>
<input type=hidden name=category_status value='active'><p>
New Category: <br><input type=text size=30 name=category_name>
";dropbox("select * from issue_res_category_template",$catinfo->category_template_id);echo"
<input type=button value='Add' onclick=submit();>
</form>

<script>
function cat_delete(category_id) {
	if (confirm('Are you sure you want to delete this category!?!'))
		document.location='$pagename?mode=category_edit_delete&category_edit_delete_id=' + category_id
	}
document.category_create.category_name.focus();
</script>


";

?>
