<?

switch ($issue_res_category_info->category_template_id)	{
	case 1:
				$category_template_text->conflict_id='Conflict ID';
				$category_template_text->bld_floor='Building/floor';
				$category_template_text->bld_floor_short='Bldg/flr';
				$category_template_text->grid='Grid';
				$category_template_text->grid_short='Grid';
				$category_template_text->summary='Summary';
				$category_template_text->solution='Proposed Solution';
				$category_template_text->actual_solution='Actual Solution';
				$category_template_text->responsibility='Trade Responsibility';
				$category_template_text->completed_by='Completed by';
				$category_template_text->due_date='Due Date';
				$category_template_text->last_action='Last Action'; // Obsolete in basic template view I think
				$category_template_text->completed='Completed date';
				$category_template_text->approved='Approved';
			break;
	case 2:
				$category_template_text->conflict_id='Task ID';
				$category_template_text->bld_floor='Group';
				$category_template_text->bld_floor_short='Group';
				$category_template_text->grid='Priority (1-5)';
				$category_template_text->grid_short='Priority';
				$category_template_text->summary='Task';
				$category_template_text->solution='Proposed Solution';
				$category_template_text->actual_solution='Actual Solution';
				$category_template_text->responsibility='Responsible';
				$category_template_text->completed_by='Completed by';
				$category_template_text->due_date='Due Date';
				$category_template_text->last_action='Last Action';
				$category_template_text->completed='Completed date';
				$category_template_text->approved='Approved';
			break;
	case 3:
				$category_template_text->conflict_id='Task ID';
				$category_template_text->bld_floor='Group';
				$category_template_text->bld_floor_short='Group';
				$category_template_text->grid='Priority (1-5)';
				$category_template_text->grid_short='Priority';
				$category_template_text->summary='Task';
				$category_template_text->solution='Proposed Solution';
				$category_template_text->actual_solution='Actual Solution';
				$category_template_text->responsibility='Responsible';
				$category_template_text->completed_by='Completed by';
				$category_template_text->due_date='Due Date';
				$category_template_text->last_action='Last Action';
				$category_template_text->completed='Completed date';
				$category_template_text->approved='Approved';
			break;
	case 4:
				$category_template_text->conflict_id='Issue #';
				$category_template_text->bld_floor='Equipment Tag';
				$category_template_text->bld_floor_short='Equip Tag';
				$category_template_text->grid='BMS Screen';
				$category_template_text->grid_short='BMS';
				$category_template_text->summary='Issue';
				$category_template_text->solution='Proposed Solution';
				$category_template_text->actual_solution='Current Status';
				$category_template_text->responsibility='Action By';
				$category_template_text->completed_by='Completed by';
				$category_template_text->due_date='Due Date';
				$category_template_text->last_action='Last Action';
				$category_template_text->completed='Completed date';
				$category_template_text->approved='Approved';
			break;
	default:
				$category_template_text->conflict_id='Task ID';
				$category_template_text->bld_floor='Group';
				$category_template_text->grid='Priority (1-5)';
				$category_template_text->summary='Task';
				$category_template_text->solution='Proposed Solution';
				$category_template_text->actual_solution='Actual Solution';
				$category_template_text->responsibility='Responsible';
				$category_template_text->completed_by='Completed by';
				$category_template_text->due_date='Due Date';
				$category_template_text->last_action='Last Action';
				$category_template_text->completed='Completed date';
				$category_template_text->approved='Approved';
			break;
	}				




?>
