<?
require("header3.phtml");
if ($issue_res_edit_category_id=="")
	die("Error: Missing category information. Improper call to this function!<p>");

$issue_res_edit_category_id=escapeshellcmd($issue_res_edit_category_id);

$catinfo=getone("select * from issue_res_category where issue_res_category_id = '$issue_res_edit_category_id'");

$catinfo->strict_parents=checkbreak($catinfo->strict_parents);

echo "
<form name=category_edit method=post action=$pagename>
<input type=hidden name=mode value=category_edit_submit>
<input type=hidden name=issue_res_edit_category_id value=\"$issue_res_edit_category_id\">
<table border=1 cellpadding=5>
<tr bgcolor=$tableheadbgcolor><td>
	Category Name
</td><td>
	&nbsp;
</td><td>
	&nbsp;
</td><td>
	Strict Parents
</td><td>
	&nbsp;
</td></tr>

<tr><td>
	<input type=text size=25 name=category_name value=\"$catinfo->category_name\">
</td><td>
	";dropbox("select * from issue_res_category_template",$catinfo->category_template_id);echo"
</td><td>
	<select name=category_status>
		<option value=\"$catinfo->category_status\">$catinfo->category_status</option>
		<option value=\"active\">active</option>
		<option value=\"inactive\">inactive</option>
	</select>
</td><td>
	<input type=checkbox name=strict_parents $catinfo->strict_parents>
</td><td>
	<input type=button value=\"Save\" onclick=submit();>
</td></tr>
</table>
</form>
";

?>
