<?
echo "
</center>
	<body bgcolor=#ffffff>
";
if ($issue_res_admin) {
	include("admin_jobs.phtml");
	}


echo "
	<font size=+1><b>Please select which job:</b></font><p>";
	$issue_res_joblist_query="select * from jobinfo where issue_res_tracking = 'Y' order by job_name";
	$issue_res_joblist_res=@mysql_query($issue_res_joblist_query);
	while($joblist_entry=@mysql_fetch_object($issue_res_joblist_res)) {
		$textcolor="blue";
		if (($issue_res_admin)||(getoneb("select * from issue_res_users where jobinfo_id = '$joblist_entry->jobinfo_id' and contacts_id = '$global_user_id' limit 1"))) {
			if (($joblist_entry->active=='N')&&($joblist_entry->jobinfo_id!='1782')) $textcolor="gray";
			echo "<ul>
			<a href=$pagename?mode=main&global_jobinfo_id_set=$joblist_entry->jobinfo_id>
			<font color=$textcolor size=+1>
			$joblist_entry->job_name ($joblist_entry->contract_num)
			</font>
			</a>
			</ul>";
		}
		}

require("job_hotlist.phtml");
require("footer.phtml");
?>
