<?

echo "<html><head><title>$dbdescription:$mode</title></head>
<body bgcolor=#ffffff text=#333333 onunload=check_exit();>
";

$new=0;


if ("$problem_id" != "") {
	$problem=getone("select * from issue_res_issues where problem_id = '$problem_id'");
	}

if ("$problem_id" == "") {
	$new=1;
	$problem=new bsclass;
	$cfidtemp=getoneb("select max(conflict_id) as conflict_id from issue_res_issues where issue_res_category_id = '$issue_res_category_id'");

	$cfidtemp->conflict_id++;
	$problem->conflict_id=$cfidtemp->conflict_id;	
	$problem->issue_parent=escapeshellcmd($issue_parent);
	}

$problem->due_date=invali_date("$problem->due_date");
$problem->completed=invali_date("$problem->completed");

if ($new)
	$problem->due_date=$last_due_date;


//////////////////////////////////////////////////
//////////// Dealing with issue trees ////////////
//////////////////////////////////////////////////
if ($problem->issue_parent>0) {
	$problem->issue_parent=escapeshellcmd($problem->issue_parent);
	$problem_parent_info=getone("select * from issue_res_issues where problem_id = '$problem->issue_parent'");
	$problem->conflict_id=$problem_parent_info->conflict_id;
	echo "<h3><i>Editting a sub-issue:</i></h3>";

	///////////////////////////////////////////////
	///////// Go Find out which subitem I am....
	///////////////////////////////////////////////
	
	$my_rev=a;
	$my_parents_parent=$problem->issue_parent;
	while ($my_parents_parent!=0) {
		$my_rev++;
		$tmp_info=getone("select issue_parent from issue_res_issues where problem_id = '$my_parents_parent'");
		$my_parents_parent=$tmp_info->issue_parent;		
		}

	}

if (!($new)) {
echo "
<script>

function box_little(obj) { obj.rows=2; }
function box_big(obj) { obj.rows=10; }

function confirm_sub_new() {
	if(confirm(\"Create new sub-issue?\"))
		document.subissuecreate.submit();
	}
</script>
<table border=1><tr>";


if ($problem->issue_parent) {
	echo "
	<td>
	<form name=parentissueload method=post action=$pagename>
	<input type=hidden name=mode value=problem_edit>
	<input type=hidden name=problem_id value=\"$problem->issue_parent\">
	<input type=button value=\"Open Parent-issue\" onclick=submit();>
	</form>
	</td>
	";
	}


if (!($problem->issue_child)) { 
	echo "
	<td>
	<form name=subissuecreate method=post action=$pagename>
	<input type=hidden name=mode value=problem_edit>
	<input type=hidden name=issue_parent value=\"$problem->problem_id\">
	<input type=button value=\"Create a sub-issue\" onclick=confirm_sub_new();>
	</form>
	</td>
	";
	} else {
	echo "
	<td>
	<form name=subissueload method=post action=$pagename>
	<input type=hidden name=mode value=problem_edit>
	<input type=hidden name=problem_id value=\"$problem->issue_child\">
	<input type=button value=\"Open sub-issue\" onclick=submit();>
	</form>
	</td>
	";
	}
echo "</tr></table>";
}
//////////////////////////////////////////////////


////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////	Notifications Select Box Code
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////

$notify_select_height=20;
$notifyselect="";
$notquery="select contacts.contacts_id as contacts_id, first_name,last_name, email  from issue_res_users,contacts where issue_res_users.contacts_id = contacts.contacts_id and jobinfo_id = '$global_jobinfo_id' order by last_name,first_name,company";
$notres=@mysql_query($notquery);
$notify_select_count=@mysql_num_rows($notres);
if ($notify_select_count<$notify_select_height)
	$notify_select_height=$notify_select_count;

if ($issue_res_full) {
	$notifyselect="$notifyselect<select size=$notify_select_height multiple name='issue_res_notification_id[]' onchange=set_modified();>";

	while($notrow=@mysql_fetch_object($notres)) {
		if (getoneb("select * from issue_res_notify where contacts_id = '$notrow->contacts_id' and problem_id = '$problem_id'"))
			$selected=" selected";
		else
			$selected="";		
		$notifyselect="$notifyselect<option value='$notrow->contacts_id'$selected>$notrow->last_name, $notrow->first_name ($notrow->email)</option>";
		}
	$notifyselect="$notifyselect</select>";
} else {
	$notifyselect="<table border=1><tr><td>";
	while($notrow=@mysql_fetch_object($notres))
		if (getoneb("select * from issue_res_notify where contacts_id = '$notrow->contacts_id' and problem_id = '$problem_id'"))
		$notifyselect="$notifyselect $notrow->last_name, $notrow->last_name ($notrow->email)<br>";
	$notifyselect="$notifyselect</td></tr></table>";
}
////////////////////////////////////////////////////////////


echo "
<form name=problem_edit method=post action=$pagename>
<input type=hidden name=mode value=problem_submit>
<input type=hidden name=problem_id value=\"$problem_id\">
<input type=hidden name=issue_parent value=\"$problem->issue_parent\">
<input type=hidden name=problem_modified value=no>

<table border=0>

<tr><td>	
	$category_template_text->conflict_id:	
</td><td>";
	if ($problem->issue_parent>0) {
	echo "<b>$problem->conflict_id$my_rev</b>
	<input type=hidden name=conflict_id value=\"$problem->conflict_id\">
	";
	
	} else {
	echo "<input type=text name=conflict_id value=\"$problem->conflict_id\" onchange=set_modified();>$my_rev";
	}
	echo "
</td><td>	
	$category_template_text->bld_floor:	
</td><td>	
	<input type=text name=bld_floor value=\"$problem->bld_floor\" onchange=set_modified();>
</td><td rowspan=8 valign=top>
	Notifications List:<hr>Retransmit Notifications <input type=checkbox name=retransmit_notifications onchange=set_modified();><br>$notifyselect
</td></tr>

<tr><td>	
	$category_template_text->grid:
</td><td>	
	<input type=text name=grid value=\"$problem->grid\" onchange=set_modified();>
</td><td>
	&nbsp;
</td><td>
	&nbsp;
</td></tr>

<tr><td>	
	$category_template_text->summary:
</td><td colspan=3>	
	<textarea rows=3 onfocus=box_big(this) onblur=box_little(this) cols=50 name=summary wrap=no onchange=set_modified();>$problem->summary</textarea>
</td></tr>

<tr><td>	
	$category_template_text->solution:	
</td><td colspan=3>	
	<textarea rows=3 onfocus=box_big(this) onblur=box_little(this) cols=50 name=solution wrap=no onchange=set_modified();>$problem->solution</textarea>
</td></tr>

<tr><td>	
	$category_template_text->actual_solution:
</td><td colspan=3>	
	<textarea rows=3 onfocus=box_big(this) onblur=box_little(this) cols=50 name=actual_solution wrap=no onchange=set_modified();>$problem->actual_solution</textarea>
</td></tr>

<tr><td>	
	$category_template_text->due_date:
</td><td>	
	";datebox($problem->due_date,"problem_edit.due_date","","set_modified()");echo"
</td></tr>

<tr><td>	
	<font color=red><b>$category_template_text->completed:</b></font>
</td><td>
	";datebox($problem->completed,"problem_edit.completed","","set_modified()");echo"
</td><td>	
	<font color=red><b>$category_template_text->completed_by:</b></font>
</td><td>	
	<input type=text name=completed_by value=\"$problem->completed_by\" onchange=set_modified();>
</td></tr>


<tr><td>	
	$category_template_text->responsibility:
</td><td>	
	<input size=13 type=text name=responsibility value=\"$problem->responsibility\" onchange=set_modified();>
</td><td>
	Approved:	
</td><td>	
	<input type=text name=approved value=\"$problem->approved\" onchange=set_modified();>
</td></tr>

<tr><td>
	File(s):
</td><td>
	";webfilebox($problem->attached_files,"attached_files");echo"
</td></tr>
</table>

<table border=0>
<tr><td>
	<input type=hidden name=save_action value=default>
	<input type=hidden name=submitting value=no>

	<table width=300px border=1><tr><td colspan=3 align=center><b>Save Options:</b></td></tr>
	
	<tr><td>
		<input type=button value='New Item' onclick=save_and_new(); onmouseover=focus();>
	</td><td>
		<input type=button value='Cancel' onclick=check_modified(); onmouseover=focus();>
	</td><td>
		<input type=button value='Show Log' onclick=save_and_show_log(); onmouseover=focus();>
	</td></tr>
	
	<tr align=center><td>
		<input type=button value='<-Prev-' onclick=save_and_prev(); onmouseover=focus();>
	</td><td>
		<input name=save_button type=button value='Print' onclick=save_or_print(); onmouseover=focus();>
	</td><td>
		<input type=button value='-Next->' onclick=save_and_next(); onmouseover=focus();>
	</td></tr>

	<tr><td colspan=2>
		<input type=button value='Load Conflict: ' onclick=save_and_load_conflict(); onmouseover=focus();>
		<input type=text size=4 name=load_conflict_id onmouseover=focus();>
	</td><td>
		<input type=button value='Clone' onclick=save_and_clone(); onmouseover=focus();>
	</td></tr>
	
	";
	if ($global_user->umc_emp=='Y') {
	echo "
	<tr><td colspan=3 align=center>
		<input type=button onclick=sign_off_by_umc() value=\"UMC Signoff\">
	</td></tr>
	";
	}
	
	echo "
</table>
</td>
</form>


";

if ($new != 1) {
	echo "<td width=100% align=right>
<form method=post action=$pagename name=problem_delete>
<input type=hidden name=mode value=problem_delete>
<input type=hidden name=problem_id value=$problem_id>
<input type=button value=Delete onclick=areyousure();>
</td>
</form>

<script> 
function areyousure () {
    if (confirm(\"You sure? This will destroy this record!\")) {
        document.problem_delete.submit();
        }
}

</script>	
";
}


echo "
</tr></table>
<script>
document.date_today=\"" . date('m/d/Y') . "\"

function sign_off_by_umc() {
	document.problem_edit.completed.value=document.date_today;
	document.problem_edit.completed_by.value='UMC';
	document.problem_edit.approved.value='UMC';
	if (document.problem_edit.actual_solution.value=='') {
		document.problem_edit.actual_solution.value='completed';
		}
	document.problem_edit.problem_modified.value='yes';
	save_and();
	save_and_show_log();
	}

function save_and() {
	document.problem_edit.submitting.value='yes';
	}

function save_and_load_conflict() {
	if (document.problem_edit.load_conflict_id.value>0) {
		if (document.problem_edit.problem_modified.value=='no') {
		document.location='$pagename?mode=problem_quickload&conflict_id=' + document.problem_edit.load_conflict_id.value;
		} else {
		save_and();
		document.problem_edit.save_action.value='save_and_load_conflict';
		document.problem_edit.submit();
		}
	} else {
	alert('No Conflict ID Specified.');
	}
}

function apply_changes() {
	set_modified();
	save_or_print();
	}

function save_and_next() {
	if (document.problem_edit.problem_modified.value=='no') {
	document.location='$pagename?mode=problem_load_next&problem_id=$problem_id';
	} else {
	save_and();
	document.problem_edit.save_action.value='save_and_next';
	document.problem_edit.submit();
	}
}

function save_and_clone() {
	save_and();
	document.problem_edit.save_action.value='save_and_clone';
	document.problem_edit.submit();
}

function save_and_prev() {
	if (document.problem_edit.problem_modified.value=='no') {
	document.location='$pagename?mode=problem_load_prev&problem_id=$problem_id';
	} else {
	save_and();
	document.problem_edit.save_action.value='save_and_prev';
	document.problem_edit.submit();
	}
}

function save_and_new() {
	if (document.problem_edit.problem_modified.value=='no') {
	document.location='$pagename?mode=problem_edit';
	} else {
	save_and();
	document.problem_edit.save_action.value='save_and_new';
	document.problem_edit.submit();
	}
}

function save_and_show_log() {
	if (document.problem_edit.problem_modified.value=='no') {
	document.location='$pagename?mode=main';
	} else {
	save_and();
	document.problem_edit.save_action.value='save_and_show_log';
	document.problem_edit.submit();
	}
}

function save_or_print() {
	if (document.problem_edit.problem_modified.value=='no') {
	open(\"$pagename?mode=problem_print&problem_id=$problem_id\",\"problem_print_win\",\"width=800,height=600\");
	} else {
	save_and();
	document.problem_edit.save_action.value='just_save';
	document.problem_edit.submit();
	}
}

function set_modified() {
	document.problem_edit.problem_modified.value='yes';
	document.problem_edit.save_button.value='Save';
	window.status='Modified';
	}

function check_modified() {
	if (document.problem_edit.problem_modified.value=='yes') {
	   if (confirm('Are you sure? Changes haven\'t been save.'))
	   document.location='$pagename';
	   }
	else document.location='$pagename';
	}
	
function check_exit() {
	document.problem_edit.save_button.focus();
	if ((document.problem_edit.problem_modified.value=='yes')&&(document.problem_edit.submitting.value!='yes')) {
	   if (confirm('Save changes?'))
		save_or_print();
	   }
	}
	
function check_modified() {
	if (document.problem_edit.problem_modified.value=='yes') {
	   if (confirm('Are you sure? Modifications not saved yet.'))
	   document.location='$pagename';
	   }
	else document.location='$pagename';
	}
	
function catmoveconfirm() {
	if (confirm(\"Are you sure? you can lose/destroy items easily with this option!!!!\"))
		document.dangerdanger.submit();
	}

</script>
";

if ($issue_res_admin&&($problem->issue_parent==0)) {
echo "
<p>
<hr>
<form name=dangerdanger method=post action=$pagename>
<input type=hidden name=mode value=problem_new_category_set>
<input type=hidden name=problem_id value=\"$problem_id\">
<input type=text size=6 name=issue_res_problem_new_category value=\"$issue_res_problem_last_new_category\">
<input type=button value=\"Move to new category\" onclick=catmoveconfirm();>
<input type=button value=Browse onclick=open('$pagename?mode=problem_move_browse&category_id_set=$problem->issue_res_category_id','problem_move_browse','width=500,height=300');>
</form>";

}

?>
