<?
$PRINTED_SOMETHING="";

if ($category_id_set!="") {
	session_register('category_id');
	$category_id=escapeshellcmd($category_id_set);
	$browse_category_id=$category_id;
	}



if ($browse_category_id > 0) { 
	$query="
	select * from 
		issue_res_category,
		issue_res_application,
		jobinfo
	where
		issue_res_category.issue_res_category_id = '$browse_category_id' and
		issue_res_application.issue_res_application_id = issue_res_category.issue_res_application_id and
		jobinfo.jobinfo_id = issue_res_application.jobinfo_id
	";
	$path_info=getone($query);
	//tabledump($query);
	echo "<a href=$pagename?mode=problem_move_browse&browse_category_id=0&browse_application_id=$path_info->issue_res_application_id><font color=blue>UP</font></a><br><ul>$path_info->job_name<ul>$path_info->issue_res_application_name<ul>$path_info->category_name</ul></ul></ul><hr>";
	$PRINTED_SOMETHING="1";
	}

if ($browse_application_id > 0) {
	$browse_application_id=escapeshellcmd($browse_application_id);
	//echo "Application ID: $browse_application_id";
	$query="
	select * from 
		issue_res_application,
		jobinfo
	where
		issue_res_application.issue_res_application_id = '$browse_application_id' and
		jobinfo.jobinfo_id = issue_res_application.jobinfo_id
	";
	$path_info=getone($query);
	echo "<a href=$pagename?mode=problem_move_browse&browse_application_id=0&browse_jobinfo_id=$path_info->jobinfo_id><font color=blue>UP</font></a><br><ul>$path_info->job_name<ul>$path_info->issue_res_application_name</ul></ul><hr>";
	$qry="select * from issue_res_category where issue_res_application_id = '$browse_application_id' order by category_name";
	$res=@mysql_query($qry);
	while($row=@mysql_fetch_object($res)) {
		if ($row->issue_res_category_id==$category_id) {
			echo "<b>$row->category_name</b><br>";
			} else {
			echo "<a href=$pagename?mode=problem_move_browse&browse_category_id=$row->issue_res_category_id><font color=blue>$row->category_name</font></a><br>";
			}
		}
	$PRINTED_SOMETHING="1";

	}
	
if ($browse_jobinfo_id > 0) {
	$browse_jobinfo_id=escapeshellcmd($browse_jobinfo_id);
	//echo "Jobinfo ID: $browse_jobinfo_id";
	$query="
	select * from 
		jobinfo
	where
		jobinfo_id = '$browse_jobinfo_id'
	";
	$path_info=getone($query);
	echo "<a href=$pagename?mode=problem_move_browse&browse_jobinfo_id=0><font color=blue>UP</font></a><br><ul>$path_info->job_name</ul><hr>";

	$qry="select * from issue_res_application where jobinfo_id = '$browse_jobinfo_id' order by issue_res_application_name";
	$res=@mysql_query($qry);
	while($row=@mysql_fetch_object($res))
		echo "<a href=$pagename?mode=problem_move_browse&browse_application_id=$row->issue_res_application_id><font color=blue>$row->issue_res_application_name</font></a><br>";
	$PRINTED_SOMETHING="1";
	}
	
if ($PRINTED_SOMETHING!="1") {
	$qry="select * from jobinfo where issue_res_tracking = 'Y' order by job_name";
	$res=@mysql_query($qry);
	while($row=@mysql_fetch_object($res))
		echo "<a href=$pagename?mode=problem_move_browse&browse_jobinfo_id=$row->jobinfo_id><font color=blue>$row->job_name ($row->contract_num)</font></a><p>";
	
	
	}

















//if (($browse_category_id != 0)) {
if (($category_id != $browse_category_id) && ($browse_category_id != 0)) {
	echo "<a href=javascript:set_id();><font color=blue>MOVE ITEM TO THIS CATEGORY</font></a>

	<script>
	function set_id() {
		opener.document.dangerdanger.issue_res_problem_new_category.value = '$browse_category_id';
		opener.document.dangerdanger.submit();
		self.close();
		}
	</script>
	";
	}
?>
