<?
//require('querylib.inc');

if ($issue_res_admin) {
	$problem_id=escapeshellcmd($problem_id);
	$problem_info=getone("select * from issue_res_issues where problem_id = '$problem_id'");

	$query="delete from issue_res_issues where problem_id = '$problem_id'";
	$query2="delete from issue_res_notify where problem_id = '$problem_id'";
	mysql_query($query);
	mysql_query($query2);

	if ($problem_info->issue_parent>0) {
		$query3="update issue_res_issues set issue_child = 0 where problem_id = '$problem_info->issue_parent' and issue_child = '$problem_id'";
		mysql_query($query3);
		}

	forward('main');
	} else { 
	echo "PERMISSION DENIED. Please contact your system administrator (or (s)he may contact you).<p>";
	exit;
	}

?>
