<?

$issue_res_read_only=false;
$issue_res_read_write=false;
$issue_res_full=false;
$issue_res_admin=false;


if ($adminuser) {
$issue_res_read_only=1;
$issue_res_read_write=1;
$issue_res_full=1;
$issue_res_admin=1;
}

if ($issue_res_application_id) {
	$issue_res_app_rights=getoneb("select * from issue_res_application_rights where contacts_id = '$global_user_id' and issue_res_application_id = '$issue_res_application_id'");
	if ($issue_res_app_rights->user_type=="read_only") {
		$issue_res_read_only=1;
		}
	if ($issue_res_app_rights->user_type=="read_write") {
		$issue_res_read_only=1;
		$issue_res_read_write=1;
		}
	if ($issue_res_app_rights->user_type=="full") {
		$issue_res_read_only=1;
		$issue_res_read_write=1;
		$issue_res_full=1;
		}
	if ($issue_res_app_rights->user_type=="admin") {
		$issue_res_read_only=1;
		$issue_res_read_write=1;
		$issue_res_full=1;
		$issue_res_admin=1;
		}
	}



$issue_res_cat_rights=getoneb("select * from issue_res_category_rights where contacts_id = '$global_user_id' and issue_res_category_id = '$issue_res_category_id'");


if ($issue_res_cat_rights->user_type=="read_only") {
	$issue_res_read_only=1;
	}

if ($issue_res_cat_rights->user_type=="read_write") {
	$issue_res_read_only=1;
	$issue_res_read_write=1;
	}

if ($issue_res_cat_rights->user_type=="full") {
	$issue_res_read_only=1;
	$issue_res_read_write=1;
	$issue_res_full=1;
	}

if ($issue_res_cat_rights->user_type=="admin") {
	$issue_res_read_only=1;
	$issue_res_read_write=1;
	$issue_res_full=1;
	$issue_res_admin=1;
	}

?>
