<?
include("../webfile$devel/storage_settings.cfg");

$doc_id=addslashes($doc_id);
$doc_info=getoneb("select * from documents where doc_id = '$doc_id' and doc_type = 'rfi'");

$rfi_info=getoneb("select * from rfilog where rfi_id = '$doc_info->app_record_id'");

if ($doc_id=="") pdf_generation_error_pdf("ERR(1) - No document id.");
if (!($doc_info)) pdf_generation_error_pdf("ERR(2) - Invalid document id.");
if (!($rfi_info)) pdf_generation_error_pdf("ERR(3) Invalid/unable to load RFI information.");
$rfi_id=$rfi_info->rfi_id;

$global_jobinfo=getoneb("select * from jobinfo where jobinfo_id = '$doc_info->jobinfo_id'");
require_once('pdf_lib2.inc');
$pdf=&new Cezpdf("$global_user->pref_paper_size","portrait");
$number=$global_jobinfo->fd_rfi_template_number;
require("rfi_render_pdf${number}.phtml");

$file_contents=$pdf->ezOutput();
if ($pdf_mime_header_registered!='Y') {
	$pdf_mime_header_registered='Y';
	pdf_mime_header();
	}
echo $file_contents;

?>
