<?
$today=date('m-d-Y');
$submit_text="OK";

if ($rfi_id!="") {
	$new=0;
	$rfi_id=addslashes($rfi_id);
	$rfi_info=getone("select * from rfilog where rfi_id = '$rfi_id'");

	if ($rfi_info) {
		if (!($write)) {
			if (!(($guest)&&($rfi_info->creator==$global_user_id))) die_security();
			}
		}
	
	$jobinfo_id=$rfi_info->jobinfo_id;
	$creator_info=getoneb("select * from contacts where contacts_id = '$rfi_info->creator'");
	$saved_by_info=getoneb("select * from contacts where contacts_id = '$rfi_info->saved_by'");
	$rfi_info->rfi_date=invali_date($rfi_info->rfi_date,'/');
	$rfi_info->key_description=htmlspecialchars($rfi_info->key_description);
	$rfi_info->question=htmlspecialchars($rfi_info->question);
	$rfi_info->solution=htmlspecialchars($rfi_info->solution);
	$rfi_info->response=htmlspecialchars($rfi_info->response);
	$doc_info=getoneb("select * from documents where jobinfo_id = '$rfi_info->jobinfo_id' and section = '$rfi_info->section' and doc_type = 'rfi' and app_record_id = '$rfi_info->rfi_id' limit 1");
	$rfi_info->sent=checkbreak($rfi_info->sent);
	$rfi_info->pm_review_done=checkbreak($rfi_info->pm_review_done);
	} else {
	$new=1;
	$rfi_info->rfi_date=$today;
	$rfi_info->rfi_num='<i>(auto)</i>';
	$rfi_info->sent_to_id=$global_jobinfo->default_gc_recipient;
	$jobinfo_id=$rfi_info->jobinfo_id;
	$submit_text="Save and Add Files";
	$creator_info=getoneb("select * from contacts where contacts_id = '$global_user_id'");
	$rfi_info->rep_id=$creator_info->contacts_id;
	}
$rfi_info->attached_sheets=checkbreak($rfi_info->attached_sheets);


////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////
//	Get a paperlip link for an attached gcrfi if we can.
////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////
$gc_paperclip="";
$gc_doc_info=getoneb("select * from documents_links left join documents on (documents_links.docb = documents.doc_id) where doc_type = 'gcrfi' and doca = '$doc_info->doc_id'");
if ($gc_doc_info) {
$gc_doc_info=getoneb("select * from gcrfilog where gcrfi_id = '$gc_doc_info->app_record_id'");
	if ($gc_doc_info) {
		$gc_paperclip=webfile_paperclip_view($gc_doc_info->gcrfi_image_id);
	}
}
////////////////////////////////////////////////////////////////


require('header.phtml');
fd_navs_header();
$jobinfo=getoneb("select * from jobinfo where jobinfo_id = '$jobinfo_id'");
$rfi_info->rfi_num=ereg_replace('.00$','',"$rfi_info->rfi_num");

if ($rfi_id!="") {
	$fd_manager=fd_manager($rfi_info->jobinfo_id,$global_user_id);
	if ($fd_manager||$adminuser) {
		echo "<script>
			function delete_rfi(rfi_id) {
				if (confirm('Permanently delete this rfi?'))
					document.location='$pagename?mode=rfi_delete&rfi_id=$rfi_info->rfi_id';
					}
			</script>";
		}
	echo "
	<script>
	function new_sub_rfi() {
		if(confirm('Create a new revision of this RFI?'))
			document.location='$pagename?mode=new_sub_rfi&rfi_id=$rfi_info->rfi_id';
		}
	</script>
	";
	}

echo"
<form name=rfi_edit method=post action=\"$pagename\">
<input type=hidden name=mode value=rfi_submit>
<input type=hidden name=rfi_id value=\"$rfi_info->rfi_id\">
<table style=\"border: 2px solid black;\" cellspacing=0 cellpadding=4>

<tr><td colspan=2 valign=center style=\"border-bottom: 2px solid black;\">
	<div style=\"float: right;\"><input name=submitval type=submit value=\"Print\">&nbsp;&nbsp;&nbsp;</div>
	<font size=+2><b>RFI&nbsp;-&nbsp;Request&nbsp;For&nbsp;Information</b></font>
</td><td style=\"border-left: 2px solid black;\" align=center valign=top>
	<img src=/images/home_umclogo.png>
</td></tr>

<tr><td colspan=2 align=center>
	<table border=0 cellspacing=0 cellpadding=0 width=100%>
	<tr><td align=center>";
		if ($new!="1") echo "<input name=submitval type=submit value=\"Prev\">";
		else echo "&nbsp;";
		echo "
	</td><td align=center>
		<input name=submitval type=submit value=\"Cancel\">
	</td><td align=center>
		<input name=submitval type=submit value=\"Apply\">
	</td><td align=center>
		<input name=submitval type=submit value=\"$submit_text\">
	</td><td align=center>";
		if ($new!="1") echo "<input name=submitval type=submit value=\"Next\">";
		else echo "&nbsp;";
		echo "
	</td></tr>
	</table>
</td><td rowspan=20 valign=top style=\"border-left: 2px solid black;\">
	";
	////////////////////////////////////////////////////////////////////
	////////////////////////////////////////////////////////////////////
	// OK, starting here, we're going down the right hand side...
	////////////////////////////////////////////////////////////////////
	////////////////////////////////////////////////////////////////////
	if ($new==0) {
	echo "
	<div style=\"float: right;\"><font size=+1>&nbsp;Submitted&nbsp;<input type=checkbox name=sent $rfi_info->sent>&nbsp;&nbsp;&nbsp;&nbsp;</font></div>
	<div><font size=+1>PM&nbsp;Review&nbsp;Done&nbsp;<input type=checkbox name=pm_review_done $rfi_info->pm_review_done></font></div>
	";
	
	if ($rfi_id!="") $doc_id=fd_get_doc_id($rfi_info->rfi_id);
		
		
		pal_box($doc_id);
		$this_rfi_num=round($rfi_info->rfi_num);
		$next_rfi_num=$this_rfi_num + 1;
		$subsquery="select * from rfilog where jobinfo_id = '$rfi_info->jobinfo_id' and section = '$rfi_info->section' and rfi_num >= '$this_rfi_num' and rfi_num < '$next_rfi_num' order by rfi_num desc";
		$subsres=@mysql_query($subsquery);
		$subscount=mysql_num_rows($subsres);
		//if ($subscount>1) {
			echo "<br><table width=100% border=1 cellspacing=0 cellpadding=1><tr bgcolor=\"$fd_color_4\"><td colspan=2><div style=\"float: right;\"><a href=\"javascript:new_sub_rfi();\"><font color=blue>New&nbsp;Revision</font></a></div>RFI Revisions</td></tr>";
			while ($subrow=@mysql_fetch_object($subsres)) {
					if ($subrow->key_description=="") $subrow->key_description='&nbsp;';
					if ($subrow->rfi_num==$rfi_info->rfi_num) {
						echo "<tr bgcolor=#dddddd><td>
								$subrow->rfi_num
							</td><td>
								$subrow->key_description
							</td></tr>
							";
						} else {
						echo "<tr bgcolor=#ffffff><td>
								<a href=$pagename?mode=rfi_edit&rfi_id=$subrow->rfi_id><font color=blue>$subrow->rfi_num</font></a>
							</td><td>
								$subrow->key_description
							</td></tr>
							";
						}
				}
			echo "</table>";
		//	}
		
		}
	if ($global_jobinfo->front_desk_hide_rfilog_posting!='Y') {
	echo "
	<table border=0 width=100%>
	<tr><td>
	Cost/Sched Impact&nbsp;
	</td><td>
		<select name=has_cost>
		<option>$rfi_info->has_cost</option>
		<option>Y</option>
		<option>N</option>
		<option> </option>
	</select>
	</td></tr>
	<tr><td>     
		UMC COP #
	</td><td>
		<i>disabled</i>
	</td></tr>
	</table>
	";
	}

if ($rfi_id!="") {
//$doc_id=fd_get_doc_id($rfi_info->rfi_id);
	
	
	if ($global_jobinfo->front_desk_hide_rfilog_posting!='Y') {
		echo"
		<div style=\"border: 2px solid black;\" id=record_dwg_posting></div>
		<div style=\"border: 2px solid black;\" id=det_cfu_box>";include("det_cfu_box.phtml");echo"</div>
		<div style=\"border: 2px solid black;\" id=todo_completion_dates>";include("todo_completion_dates.phtml");echo"</div>
		<script>ajaxManager('load_page','$pagename?mode=rfi_record_dwg_posting&doc_id=$doc_id','record_dwg_posting');</script>";
		}
	}
	echo "<div style=\"border: 2px solid black\" width=100% id=various_notes>
	<div width=100% style=\"background: $fd_color_4;\">Notes</div>
	<textarea onfocus=\"box_big(this)\" onblur=\"box_little(this)\" name=pm_notes rows=2 cols=40>$rfi_info->pm_notes</textarea><br>
	<b>All Linked Documents:</b><br>
	";
	fd_document_box();
	echo "
</td></tr>

<tr><td>
	<b>Job #:</b>
</td><td>
	$jobinfo->contract_num
	<script>
	document.send_rfi_confirmed='no';
	function send_rfi_to(contact_id) {
		if ((document.rfi_edit.email_text.value=='')&&(document.send_rfi_confirmed=='no')) {
			document.send_rfi_confirmed='yes';
			if (!(confirm('There is no message included. Are you sure?'))) {
				return false;
				}
			}
		message=urlencode(document.rfi_edit.email_text.value);
		ajaxManager('load_page','$pagename?mode=send_rfi_to&rfi_id=$rfi_info->rfi_id&recipient=' + contact_id+ '&message=' + message,'project_team');
		return true;
		}
	</script>
</td></tr>

<tr><td>
	<b>Job Name:</b>
</td><td>
	$jobinfo->display_name
</td></tr>

<tr><td>
	<b>UMC RFI #:</b>
</td><td><table width=100% border=0 cellspacing=0 cellpadding=0><tr><td width=100%>$rfi_info->rfi_num</td><td align=right><b>Input&nbsp;Date:</b></td><td>&nbsp;&nbsp;$rfi_info->rfi_date&nbsp;&nbsp;&nbsp;&nbsp;</td></tr></table>
</td></tr>


<tr><td>
	<b>GC RFI#</b>
</td><td>
	<div style=\"float: left;\">";
	//fd_document_box($rfi_info->rfi_id,'gcrfi',1);
	fd_doc_box($rfi_info->rfi_id,'gcrfi',1);
	//fd_document_box();
	echo"</div><div width=100%>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$gc_paperclip</div>
</td></tr>

<tr><td>
	<b>Sub</b>
</td><td>
	";contactsbox("select * from contacts where contact_type = 'company'",$rfi_info->sub_id,'sub_id');echo"
</td></tr>

<tr><td>
	<b>Sub RFI#</b>
</td><td>
	<input type=text size=10 name=sub_rfi_num value=\"$rfi_info->sub_rfi_num\">
</td></tr>

<tr><td>
	<b>CPM Sched ID</b>
</td><td>
	<input type=text size=10 name=cpm_schedule_id value=\"$rfi_info->cpm_schedule_id\">
</td></tr>

<tr><td>
	<b>Subject:</b>
</td><td>
	<input type=text name=key_description maxlength=77 size=40 value=\"$rfi_info->key_description\">
</td></tr>

<tr><td>
	<b>Spec:</b>
</td><td>
	<input type=text size=10 name=spec value=\"$rfi_info->spec\">
</td></tr>

<tr><td>
	<b>Bldg / Floor:</b>
</td><td>
	<input type=text size=15 name=bldg value=\"$rfi_info->bldg\"> / <input type=text name=floor size=8 value=\"$rfi_info->floor\">
</td></tr>


<tr><td valign=top>
	<b>Location</b>
</td><td id=dwg_ref_list>
	<b><i>Loading...</i></b>
</td></tr>

<tr><td valign=top>
	<b>Question</b>
</td><td>
	<textarea onfocus=\"box_big(this)\" onblur=\"box_little(this)\" name=question rows=3 cols=50>$rfi_info->question</textarea>
</td></tr>

<tr><td valign=top>
	<b>Recommended<br>Solution</b>
</td><td>
	<textarea onfocus=\"box_big(this)\" onblur=\"box_little(this)\" name=solution rows=3 cols=50>$rfi_info->solution</textarea>
</td></tr>

<tr><td>
	<b>UMC Rep</b>
</td><td>
	";contactsbox("select * from contacts where umc_emp = 'Y' and current = 'Y'",$rfi_info->rep_id,'rep_id');echo"
</td></tr>

<tr><td>
	<b>Response Needed</b>
</td><td>
	";datebox($rfi_info->response_needed_date,'rfi_edit.response_needed_date');echo"
</td></tr>

<tr><td>
	<b>Attached Sheets</b>
</td><td>
	<input type=checkbox name=attached_sheets $rfi_info->attached_sheets>&nbsp;<input name=attached_sheet_name value=\"$rfi_info->attached_sheet_name\">
</td></tr>

<tr><td>
	<b>Submitted to (GC)</b>
</td><td>
	";contactsbox("select * from contacts where 1 = 1 and current = 'Y'",$rfi_info->sent_to_id,'sent_to_id');echo"&nbsp;<b>on</b>&nbsp;
	";datebox($rfi_info->sent_to_date,'rfi_edit.sent_to_date');echo"
</td></tr>

<tr bgcolor=#cccccc><td valign=top>
	<b>Response</b>
</td><td>
	<textarea onfocus=\"box_big(this)\" onblur=\"box_little(this)\" name=reply rows=3 cols=50>$rfi_info->reply</textarea>
	";
	//if ($rfi_id!="") $doc_id=fd_get_doc_id($rfi_info->rfi_id);
		if ($rfi_info->reply == "") {
			//tabledump("select * from rfilog_notifications where contacts_id = '$global_user->contacts_id' and notification_sent = 'N' and rfi_id = '$rfi_info->rfi_id' and expires > now() limit 1");
			if ($rfi_info->rfi_id>0) {
				echo "<script>
				function notify_of_rfi_reponse_toggle (rfi_id) {
					ajaxManager('load_page','$pagename?mode=rfi_response_notify_toggle&rfi_id=' + rfi_id,'rfi_response_notify');
					}
				</script>";
				if (!(getoneb("select * from rfilog_notifications where contacts_id = '$global_user->contacts_id' and notification_sent = 'N' and rfi_id = '$rfi_info->rfi_id' and expires > now() limit 1"))) {
					echo "<div id=rfi_response_notify><a href=javascript:notify_of_rfi_reponse_toggle($rfi_info->rfi_id)><font color=blue><i>Notify me when there's a response</i></font></a></div>";
					} else {
					echo "<div id=rfi_response_notify><a href=javascript:notify_of_rfi_reponse_toggle($rfi_info->rfi_id)><font color=blue><i title=\"You're currently going to be notified when a response comes in.\">Cancel response notification</i></font></a></div>";
					}
				}
			}
		
echo "
</td></tr>

<tr bgcolor=#cccccc><td>
	<b>Response from</b>
</td><td>
	";contactsbox("select * from contacts where current = 'Y'",$rfi_info->reply_from,'reply_from');echo"
</td></tr>

<tr bgcolor=#cccccc><td>
	<b>Response Date</b>
</td><td>
	<table border=0 cellspacing=0 cellpadding=1><tr><td>";datebox($rfi_info->reply_date,'rfi_edit.reply_date');echo"</td><td style=\"border: 1px solid black; background: $fd_color_3;\">&nbsp;&nbsp;<b>Attach&nbsp;Reply</b>&nbsp;";webfilebox($rfi_info->reply_file_group_id,'reply_file_group_id','');echo"</td></tr></table>
</td></tr>

</table>	
</form>
<b>Created by:</b> <i>$creator_info->first_name&nbsp;$creator_info->last_name</i><br>
<b>Last saved by:</b> <i>$saved_by_info->first_name&nbsp;$saved_by_info->last_name</i>

<script>

function box_little(obj) {
	obj.rows=2;
	}

function box_big(obj) {
	obj.rows=10;
	}

function update_assigned_to(posting_id) {
	/////////////////////////////////////////////////////////////
	// This function does work, but will cause errors to show up
	// in the browser javascript output because it was launched in
	// a different window. When the update launched by the other 
	// window is done it tries to write the results to a named
	// object id's innerHTML, but can't find the object with the
	// correct id.  The launching window also closes itself, so
	// there is no id available to write back to over there either.
	//
	// I tried to kill the error, by writing back to a special 'null'
	// id which aborts any write backs, but there is still an error
	// because the callback object disappears mid-stream with the
	// window that launched it.
	/////////////////////////////////////////////////////////////
	obj=document.getElementById('hidden_contactsbox_selected_assigned_to');
	if (obj.value=='') obj.value='0';
	ajaxManager('load_page','$pagename?mode=rfi_record_dwg_posting&doc_id=$doc_id&selected_tab=' + posting_id + '&assigned_to_set=' + obj.value,'verynull');
	}

function update_posting_item(posting_id,field_name,field_value) {
	ajaxManager('load_page','$pagename?mode=rfi_record_dwg_posting&doc_id=$doc_id&selected_tab=' + posting_id + '&update_field_name=' + field_name + '&update_field_value=' + field_value,'record_dwg_posting');
	}

function cfu_select_update(field) {
	eval ('fieldval=document.rfi_edit.' + field + '.value;');
	ajaxManager('load_page','$pagename?mode=det_cfu_box&doc_id=$doc_id&field=' + field + '&fieldval=' + fieldval,'det_cfu_box');
	}

function cfu_hours_update(field) {
	eval ('fieldval=document.rfi_edit.' + field + '.value;');
	ajaxManager('load_page','$pagename?mode=det_cfu_box&doc_id=$doc_id&hoursfield=' + field + '&hoursfieldval=' + fieldval,'det_cfu_box');
	}

function comp_date_update(field,value) {
	eval('document.rfi_edit.' + field + '.style.background=\"yellow\"');
	ajaxManager('load_page','$pagename?mode=todo_completion_dates&doc_id=$doc_id&field='+ field + '&value=' + value,'todo_completion_dates');
	}



function rem_dwg_ref(rfi_ref_id) {
	if ('$rfi_info->rfi_id'=='') return FALSE;
	loadurl='$pagename?mode=dwg_ref_list&rfi_id=$rfi_info->rfi_id&remove_rfi_ref_id=' + rfi_ref_id;
	ajaxManager('load_page',loadurl,'dwg_ref_list');
	}
	
function add_dwg_ref() {
	if ('$rfi_info->rfi_id'=='') return FALSE;
	loadurl='$pagename?mode=dwg_ref_list&rfi_id=$rfi_info->rfi_id&dwg=' + document.rfi_edit.dwg.value + '&grid_ref=' + document.rfi_edit.grid_ref.value;
	//alert(loadurl);
	ajaxManager('load_page',loadurl,'dwg_ref_list');
	}
ajaxManager('load_page','$pagename?mode=dwg_ref_list&rfi_id=$rfi_info->rfi_id','dwg_ref_list');
</script>
";
fd_navs_footer();
?>
