<?
$section_id=addslashes($section_id);
$section_info=getoneb("select * from rfi_sections where section_id = '$section_id'");
if (!($section_info)) die("Application error: Bad section info. Please contact your system administrator!");

if ($section=="") $section="&nbsp;";
else $section=addslashes($section);
@mysql_query("update rfi_sections set section = '$section' where section_id = '$section_info->section_id'");
@mysql_query("update rfilog set section = '$section' where section = '$section_info->section' and jobinfo_id = '$section_info->jobinfo_id'");
forward('manage_sections');
?>
