<?

echo "<style>

td.b {
	border-top: 1px solid black;
	vertical-align: top;
	}
</style>
<table style=\"font-size: 9pt;\" border=0 cellspacing=0 cellpadding=2>
<thead>
<tr><td colspan=15 align=center>
	
	<div class=noprint style=\"position: absolute; border: 2px solid black;\"><form name=search method=post action=$pagename>Search:&nbsp;<input type=text name=search_text value=\"$search_text\">";dropbox_search($search_array);echo"<input type=submit value='Go'></form></div>
	<b><font size=+2>UMC RFI Log</font><br>Job $global_jobinfo->contract_num:&nbsp;$global_jobinfo->job_name<br>$today</b>
		<div id=\"noprint\">
	<a href=$pagename?mode=rfi_edit&jobinfo_id=$global_jobinfo->jobinfo_id><font color=blue>New RFI</font></a><br>
	<a href=$pagename?mode=$mode&filter_mode=$filter_mode&view=normal><font color=blue>Normal View</font></a>
	
	<p>";
	if ($filter_mode=="") $filter_mode="All";
	
	echo "
	<form name=filter_select method=post action=\"$pagename\">
	<input type=hidden name=mode value=\"$mode\">
	Showing:&nbsp;<select name=filter_mode onchange=submit();>
	<option>All</option>
	<option value=\"Open\" ";if ($filter_mode=="Open") echo "selected"; echo ">UMC Open</option>
	<option ";if($filter_mode=="Pending") echo "selected"; echo ">Pending</option>
	<option ";if($filter_mode=="Overdue") echo "selected"; echo ">Overdue</option>";
	
	if ($global_jobinfo->front_desk_hide_rfilog_posting!='Y') {
	echo "
	<option ";if($filter_mode=="Detailing Incomplete") echo "selected"; echo ">Detailing Incomplete</option>
	<option ";if($filter_mode=="Cad Not Updated") echo "selected"; echo ">Cad Not Updated</option>
	$rs_options
	<option ";if($filter_mode=="Detailing Required") echo "selected"; echo ">Detailing Required</option>";
	}
	echo "
	</select>&nbsp;$current_query_len&nbsp;items
	</form>
	$page_page_insert
	</div>
	<div id=printme>Showing: $filter_mode</div>
</td></tr>


<tr bgcolor=\"$fd_color_4\"><td>
	<b>UMC #</b>
</td><td>
	<b>GC #</b>
</td><td>
	<b>Subject</b>
</td><td>
	<b>Bldg/flr</b>
</td><td>
	<b>Question</b>
</td><td style=\"min-width: 300px;\">
	<b>Response</b>
</td><td>
	<b>Submitted</b>
</td><td>
	<b>Resp Reqd</b>
</td><td>
	<b>Received</b>
</td><td>
	<b>Days Late</b>
</td><td>
	<b>Notes</b>
</td></tr>
</thead>

<tbody "; if ($global_browser!='IE') echo "class=floatheader";echo">
";
	while($row=@mysql_fetch_object($res)) {
	$rowbgcolor="#ffffff";
	//// jbmarkif ($row->pm_complete_date=='N') $rowbgcolor='#ffff66';
	$company_info=getoneb("select * from contacts where contacts_id = '$row->company_id'");
	$site_info=getoneb("select * from contacts where contacts_id = '$row->site_id'");
	$creator_info=getoneb("select * from contacts where contacts_id = '$row->creator'");
	$attention_info=getoneb("select * from contacts where contacts_id = '$row->attention_to_id'");
	
	$row->rfi_date=invali_date($row->rfi_date,'/');
	$reply_date=invali_date($row->reply_date);
	
	if ($reply_date=="") $reply_date=date('Y-m-d');
	else $reply_date=vali_date($reply_date);
	
	$daysqry="select datediff('$reply_date','$row->response_needed_date') as overdue";
	$days=getoneb($daysqry);
	
	$row->response_needed_date=invali_date($row->response_needed_date,'/');
	$row->reply_date=invali_date($row->reply_date);
	if ($row->reply_date=="") $row->reply_date="&nbsp;";
	if ($row->response_needed_date=="") $row->response_needed_date="&nbsp;";
	if ($days->overdue=="") $days->overdue="&nbsp;";
	if ($row->sub_rfi_num=="") $row->sub_rfi_num="&nbsp;";
	if ($row->key_description=="") $row->key_description="&nbsp;";
	
	$gcrfi_text=fd_text_doc_list(fd_get_doc_id($row->rfi_id),'gcrfi');
	$row->det_complete_date=invali_date($row->det_complete_date);
	$row->pm_complete_date=invali_date($row->pm_complete_date);
	if ($row->pm_complete_date!="") $rowbgcolor=$fd_color_2;
	$row->rfi_num=ereg_replace('.00$','',"$row->rfi_num");
	$gc_paperclip="";
echo "<tr bgcolor=\"$rowbgcolor\"><td class=b>";
				if (($write)||(($guest)&&($global_user_id==$row->creator))) {
					echo "<a href=$pagename?mode=rfi_edit&rfi_id=$row->rfi_id><font color=blue>$row->rfi_num</font></a>";
					//echo "<a href=$pagename?mode=rfi_edit&rfi_id=$row->rfi_id><font color=blue>$row->rfi_num</font></a>";
				} else {
					echo "<a href=$pagename?mode=rfi_display_pdf&rfi_id=$row->rfi_id&blah=blah/pdf_download/rfi.pdf><font color=blue>$row->rfi_num</font></a>";
				}
		echo "</td><td class=b>";
		if ($gcrfi_text!="&nbsp;") {
			$temp_doc_info=getoneb("select * from documents where doc_type = 'rfi' and app_record_id = '$row->rfi_id'");
			$gc_doc_info=getoneb("select * from documents_links left join documents on (documents_links.docb = documents.doc_id) where doc_type = 'gcrfi' and doca = '$temp_doc_info->doc_id'");
			if ($gc_doc_info) {
				$gc_doc_info=getoneb("select * from gcrfilog where gcrfi_id = '$gc_doc_info->app_record_id'");
				if ($gc_doc_info) {
					$gc_paperclip=webfile_paperclip_view($gc_doc_info->gcrfi_image_id);
					}
				}
			}
		$row->sent_to_date=invali_date($row->sent_to_date,'/');
		$row->sent_to_date=ereg_replace("/200","/0",$row->sent_to_date);
		$row->response_needed_date=ereg_replace("/200","/0",$row->response_needed_date);
		$row->reply_date=ereg_replace("-","/",$row->reply_date);
		$row->reply_date=ereg_replace("/200","/0",$row->reply_date);
		$bldgflr="";
		if ("$row->bldg$row->floor"!="") $bldgflr="$row->bldg<br>$row->floor";
		echo "
			<table width=100% border=0 cellspacing=0 cellpadding=2>
				<tr><td>$gcrfi_text</td><td>$gc_paperclip</td></tr>
			</table>
		</td><td class=b>
			$row->key_description
		</td><td class=b>
			<font size=-1>$bldgflr&nbsp;</font>
		</td><td class=b>
			<div style=\"min-width: 200px;\">$row->question</div>
		</td><td class=b>
			<div style=\"min-width: 200px;\">$row->reply&nbsp;</div>
		</td><td class=b>
			$row->sent_to_date&nbsp;
		</td><td class=b>
			$row->response_needed_date
		</td><td class=b>
			$row->reply_date&nbsp;
		</td><td class=b>
			$days->overdue&nbsp;
		</td><td class=b>
			$row->pm_notes&nbsp;
		</td></tr>
	";
	}
echo "</tbody></table>";
?>
