<?
if ($transmittal_id!="") $transmittal_id=addslashes($transmittal_id);
else die("what'chu talk'n 'bout Willis (transmittal_id)");

$doc_date=vali_date($doc_date);
$description=addslashes($description);
$quantity=addslashes($quantity);
$doc_id=addslashes($doc_id);

$query="insert into transmittal_documents set transmittal_id = '$transmittal_id', quantity='$quantity', description='$description', doc_date = '$doc_date', doc_id = '$doc_id'";
@mysql_query($query);
forward("transmittal_edit&transmittal_id=$transmittal_id&focus_add_form=true");
?>
