<?
require("header.phtml");
fd_navs_header();

if ($global_jobinfo) {
	$query="select * from transmittals where jobinfo_id = '$global_jobinfo->jobinfo_id' and section = '$current_transmittals_section'  order by transmittal_num desc";
	if ($search_text!="") {
		$search_text=addslashes($search_text);
		$query="select * from transmittals where jobinfo_id = '$global_jobinfo->jobinfo_id' and section = '$current_transmittals_section' and ( transmittal_num like '%$search_text%' or subject like '%$search_text%' or comments like '%$search_text%' or transmitted_via like '%$search_text%' ) order by transmittal_num desc";
		//die("fooberry");
		}
	$res=@mysql_query($query);
	include("fd_log_paging.phtml");
	echo "
	<style>
	@media print {
		th { font-family: arial; font-size: 8pt; }
		td { font-family: arial; font-size: 8pt; }
		}
	</style>
	
	<table id='sub_application_main_table' border=1 cellspacing=0 cellpadding=5>
	<thead>
	<tr><td colspan=9>";
	//<div class=noprint style=\"position: absolute; border: 2px solid black;\"><form name=search method=post action=$pagename>Search:&nbsp;<input type=text name=search_text value=\"$search_text\"><input type=submit value='Go'></form></div>
	search_div();
	echo"
	<center>
	<b><font size=+2>Transmittal Log</font><br>Job $global_jobinfo->contract_num:&nbsp;$global_jobinfo->display_name<br>$today</b>
	<div class=noprint><br><a href=$pagename?mode=transmittal_edit&jobinfo_id=$global_jobinfo->jobinfo_id><font color=blue>New Transmittal</font></a><br>$page_page_insert</div>
	</center>
	</td></tr>
	<tr class=floatheader><th>
		<b>#</b>
	</th><th>
		<b>Sent</b>
	</th><th>
		<b>Date</b>
	</th><th>
		<b>Company</b>
	</th><th>
		<b>Site</b>
	</th><th>
		<b>Attention</b>
	</th><th>
		<b>Sent by</b>
	</th><th>
		<b>Subject</b>
	</th><th>
		<b>Pages</b>
	</th></tr></thead>
	<tbody "; if ($global_browser!='IE') echo "class=floatheader";echo">
	";

	while($row=@mysql_fetch_object($res)) {
		$company_info=getoneb("select * from contacts where contacts_id = '$row->company_id'");
		$site_info=getoneb("select * from contacts where contacts_id = '$row->site_id'");
		$creator_info=getoneb("select * from contacts where contacts_id = '$row->creator'");
		$attention_info=getoneb("select * from contacts where contacts_id = '$row->attention_to_id'");
		$row->transmittal_date=invali_date($row->transmittal_date,'/');
		echo "<tr><td>
				<a href=$pagename?mode=transmittal_edit&transmittal_id=$row->transmittal_id><font color=blue>$row->transmittal_num</font></a>
			</td><td>
				$row->sent
			</td><td>
				$row->transmittal_date
			</td><td>
				$company_info->display_name
			</td><td>
				$site_info->display_name
			</td><td>
				$attention_info->display_name
			</td><td>
				$creator_info->display_name
			</td><td>
				$row->subject
			</td><td>
				$row->pages
			</td></tr>
		
		";
		}
	echo "<tr><td colspan=15 height=100%></td></tr></tbody></table>";
	}
fd_navs_footer();
?>
