<?

if ($transmittal_id=="") exit;
else $transmittal_id=addslashes($transmittal_id);

//tabledump("select * from transmittal_recipients where transmittal_id = '$transmittal_id'");

//echo "Hello to more recipients";
if ($add_recipient_id!="") {
	$add_recipient_id=addslashes($add_recipient_id);
	@mysql_query("insert into transmittal_recipients set transmittal_id = '$transmittal_id', recipient_id = '$add_recipient_id'");
	}

if ($delete_recipient_id!="") {
	$delete_recipient_id=addslashes($delete_recipient_id);
	@mysql_query("delete from transmittal_recipients where transmittal_id = '$transmittal_id' and recipient_id = '$delete_recipient_id'");
	}

contactsbox("select * from contacts where contact_type = 'contact' and current = 'Y'","",'recipient_id','');
$res=@mysql_query("select * from transmittal_recipients right join contacts on (transmittal_recipients.recipient_id = contacts.contacts_id) where transmittal_id = '$transmittal_id' order by alphasort");
echo "<table border=0 cellspacing=0 cellpadding=3>";
while ($row=@mysql_fetch_object($res)) {
	echo "
	<tr><td>
		$row->display_name
	</td><td>
		<a href=javascript:delete_recipient($row->recipient_id)><font color=blue><i>Delete</i></font></a>
	</td></tr>
	";
	}
echo "</table>";
?>
