<?
require_once('pdf_lib2.inc');
$transmittal_id=addslashes($transmittal_id);
$t_info=getone("select * from transmittals where transmittal_id = '$transmittal_id'");
$t_info->transmittal_date=invali_date($t_info->transmittal_date);
$attn_info=getoneb("select * from contacts where contacts_id = '$t_info->attention_to_id'");
$company_info=getoneb("select * from contacts where contacts_id = '$t_info->company_id'");
$site_info=getoneb("select * from contacts where contacts_id = '$t_info->site_id'");
$job_info=getoneb("select * from jobinfo where jobinfo_id = '$t_info->jobinfo_id'");
$d_info=getoneb("select * from transmittal_methods where transmitted_via = '$t_info->transmitted_via'");
$fontsize="10";
$standard_gap="15";
$my_loc="710";
$creator_info=getoneb("select * from contacts where contacts_id = '$t_info->creator'");
$cc_info=getoneb("select * from contacts where contacts_id = '$t_info->cc_to_id'");
// Stack up the phone information so it's ready to print
if ($site_info->phone=="") $site_info->phone=$company_info->phone;
if ($attn_info->phone=="") $attn_info->phone=$site_info->phone;
if ($site_info->phone_fax=="") $site_info->phone_fax=$company_info->phone_fax;
if ($attn_info->phone_fax=="") $attn_info->phone_fax=$site_info->phone_fax;
if ($site_info->display_name=="") $site_info->display_name=$company_info->display_name;

$pdf=&new Cezpdf("$global_user->pref_paper_size","portrait");
$pdf->selectFont("$pdf_font_path/Helvetica.afm");
////////////////////////////////////////////////////////
// The logo and header/address junk
////////////////////////////////////////////////////////
$pdf->addPngFromFile('/data/web/pipeline/images/umclogo_wbv2.png',435,710,150,48);

if ($job_info->job_letterhead_address_site!=968) {
	$lhead_site=getoneb("select * from contacts where contacts_id = '$job_info->job_letterhead_address_site'");
	$lhead_site_parts=explode("\r",$lhead_site->address_1);
	$lhead_site_p1=ereg_replace("\n","",$lhead_site_parts[0]);
	$lhead_site_p2=ereg_replace("\n","",$lhead_site_parts[1]);
	if ($lhead_site->address_state=='WA') $lhead_site->address_state='Washington';
	$pdf->addText(488,690,8,"$lhead_site_p1");
	$pdf->addText(488,680,8,"$lhead_site_p2");
	$pdf->addText(488,670,8,"$lhead_site->address_city,$lhead_site->address_state");
	$pdf->addText(488,660,8,"$lhead_site->address_zip");
	$pdf->addText(488,640,8,"<b>Phone $lhead_site->phone $lhead_site->phone_ext</b>");
	$pdf->addText(488,630,8,"Fax $lhead_site->phone_fax");
	} else {
	$pdf->addText(488,690,8,"11611 49th Place West");
	$pdf->addText(488,680,8,"P.O. Box 67");
	$pdf->addText(488,670,8,"Mukilteo, Washington");
	$pdf->addText(488,660,8,"98275-4255");
	$pdf->addText(488,640,8,"<b>Phone (206) 364-9900</b>");
	$pdf->addText(488,630,8,"Fax (206) 365-1580");
	}



///////////////////////////////////////////////////////

$pdf->ezText("Transmittal Cover Sheet" ,25);
$pdf->line(36,730,400,730);


$pdf->addText(36,$my_loc,$fontsize,"<b>UMC Job #:</b>");
$pdf->addText(115,$my_loc,$fontsize,"$job_info->contract_num");

$my_loc=$my_loc - $standard_gap;
$pdf->addText(36,$my_loc,$fontsize,"<b>Project:</b>");
$pdf->addText(115,$my_loc,$fontsize,"$job_info->display_name");

$my_loc=$my_loc - $standard_gap;
$pdf->addText(36,$my_loc,$fontsize,"<b>Date:</b>");
$pdf->addText(115,$my_loc,$fontsize,"$t_info->transmittal_date");

$my_loc=$my_loc - $standard_gap; // Old phone location gap
$my_loc=$my_loc - $standard_gap; // Old fax location gap



$my_loc=$my_loc - $standard_gap;
$my_loc=$my_loc - ($standard_gap/2);
$pdf->addText(36,$my_loc,$fontsize, "<b>Attn:</b>");

if ($attn_info->first_name . $attn_info->last_name != "") 
	$pdf->addText(115,$my_loc,$fontsize, "<b>$attn_info->first_name $attn_info->last_name</b>");
else 
	$pdf->addText(115,$my_loc,$fontsize, "<b>$attn_info->display_name</b>");

$moreattn=getoneb("select * from transmittal_recipients where transmittal_id = '$t_info->transmittal_id' limit 1");
//echo ("select * from transmittal_recipients where transmittal_id = '$t_info->transmittal_id' limit 1");exit;

//$my_loc=$my_loc - $standard_gap;
//$my_loc=$my_loc - ($standard_gap/2);
//$pdf->addText(115,$my_loc,$fontsize, "<b>hi</b>");
$addcount=0;
if ($moreattn) {
	$morelistres=@mysql_query("select * from transmittal_recipients right join contacts on (transmittal_recipients.recipient_id = contacts.contacts_id ) where transmittal_id = '$t_info->transmittal_id' order by alphasort");
	$morelist="";
	$moresep="";
	while ($morerow=@mysql_fetch_object($morelistres)) {
		if ($addcount==5) {
			$addcount=0;
			$my_loc=$my_loc - $standard_gap;
			$pdf->addText(115,$my_loc,$fontsize, "$morelist");
			$morelist="";
			$moresep="";
			}
		if($morerow->contact_type=='contact') {
			$moreadd=$morerow->first_name . " " . $morerow->last_name;
			} else {
			$moreadd=$morerow->display_name;
			}
		
		$addcount++;
		$morelist=$morelist . $moresep . $moreadd;
		$moresep=", ";
		}
	$my_loc=$my_loc - $standard_gap;
	//$my_loc=$my_loc - ($standard_gap/2);
	$pdf->addText(115,$my_loc,$fontsize, "$morelist");
	}

if ($cc_info) {
	$my_loc=$my_loc - $standard_gap;
	$pdf->addText(36,$my_loc,$fontsize, "<b>CC:</b>");
	$pdf->addText(115,$my_loc,$fontsize, "<b>$cc_info->display_name</b>");
	}

$my_loc=$my_loc - $standard_gap;
$pdf->addText(36,$my_loc,$fontsize, "<b>Send to:</b>");
$pdf->addText(115,$my_loc,$fontsize, "$site_info->display_name");

if($site_info->address_1=="") {
	$site_info->address_1=$company_info->address_1;
	$site_info->address_city=$company_info->address_city;
	$site_info->address_state=$company_info->address_state;
	$site_info->address_zip=$company_info->address_zip;
	}

if ($t_info->use_contact_addr_when_available=='Y') {
	if ($attn_info->address_1!="") {
		$site_info->address_1=$attn_info->address_1;
		$site_info->address_city=$attn_info->address_city;
		$site_info->address_stata=$attn_info->address_state;
		$site_info->address_zip=$attn_info->address_zip;
		}
	if ($attn_info->phone_fax!="") $site_info->phone_fax=$attn_info->phone_fax;
	}

$my_loc=$my_loc - $standard_gap;
$pdf->addText(36,$my_loc,$fontsize, "<b>Address:</b>");
$pdf->addText(115,$my_loc,$fontsize, "$site_info->address_1");
$my_loc=$my_loc - $standard_gap;
$pdf->addText(115,$my_loc,$fontsize, "$site_info->address_city, $site_info->address_state $site_info->address_zip");

$my_loc=$my_loc - ($standard_gap/2);

$my_loc=$my_loc - $standard_gap;
$pdf->addText(36,$my_loc,$fontsize, "<b>Phone:</b>");
$pdf->addText(115,$my_loc,$fontsize, "$site_info->phone");

$my_loc=$my_loc - $standard_gap;
$pdf->addText(36,$my_loc,$fontsize, "<b>Fax:</b>");
//if ($site_info->phone_fax!="") $company_info->phone_fax=$site_info->phone_fax;
$pdf->addText(115,$my_loc,$fontsize, "$site_info->phone_fax");

///////////////////////////////////////////////////////////////////////////////
// The block that seperates the page
///////////////////////////////////////////////////////////////////////////////
$my_loc=$my_loc - ($standard_gap/2);
$pdf->setStrokeColor(.5,.5,.5);
$pdf->line(36,$my_loc,576,$my_loc);
$pdf->line(36,$my_loc - 20, 576, $my_loc - 20);
$pdf->line(36,$my_loc,36,$my_loc - 20);
//$pdf->addText(40,$my_loc - 13, $fontsize,"<b>Pages:</b>  $t_info->pages");
//$pdf->line(126,$my_loc,126,$my_loc - 20);
$pdf->addText(40,$my_loc - 13, $fontsize, "<b>VIA:</b>  $d_info->name");
$pdf->line(150,$my_loc,150,$my_loc - 20);
$pdf->addText(154,$my_loc - 13, $fontsize, "<b>Transmitted:</b>  $t_info->transmitted");
$pdf->line(395,$my_loc,395,$my_loc - 20);
$pdf->addText(400,$my_loc - 13, $fontsize, "<b>Transmittal ID:</b>  $t_info->transmittal_num");
$pdf->line(576,$my_loc,576,$my_loc - 20);
$pdf->setStrokeColor(0,0,0);
///////////////////////////////////////////////////////////////////////////////

$my_loc=$my_loc - 40;
$pdf->addText(36,$my_loc,$fontsize, "<b>SUBJECT:</b>");
$pdf->addText(150,$my_loc,$fontsize, "<b>$t_info->subject</b>");
$pdf->setStrokeColor(.3,.3,.3);
$pdf->setLineStyle(.1);
$pdf->line(150,$my_loc- 3 ,576,$my_loc - 3);

$my_loc=$my_loc - 20;
$pdf->addText(36,$my_loc,$fontsize, "<b>COMMENTS:</b>");

$pdf->ezSetY($my_loc - 8);
$comments=array(array('comment'=>"$t_info->comments"));
$pdf->ezTable($comments,'','',array('showLines'=>1,'showHeadings'=>0,'width'=>540,'lineCol'=>array(.5,.5,.5)));




/////////////////////////////////////////////////////////////////////////////
// Finally, the list of documents.. 
/////////////////////////////////////////////////////////////////////////////
$pdf->ezSetDy(-10);
$query="select * from transmittal_documents where transmittal_id = '$t_info->transmittal_id' order by trans_doc_id";
$pdf->ezTableDumpStart();
$pdf->ezTableDumpAdd("<b>Qty</b>","<b>Description</b>","<b>Date</b>");
$res=@mysql_query($query);
while ($row=@mysql_fetch_object($res)) {
	$pdf->ezTableDUmpAdd("$row->quantity","$row->description",invali_date($row->doc_date,'/'));
	}
$pdf->ezTableDumpPrint(1,array(
'width'=>'540',
'rowGap'=>.25,
'lineCol'=>array(.5,.5,.5),
'cols'=>array('0'=>array('width'=>'28'),'2'=>array('width'=>'64'))
));


$pdf->addText(36,60,$fontsize, "<b>From:</b>   $creator_info->first_name $creator_info->last_name");
$pdf->setStrokeColor(.3,.3,.3);
$pdf->setLineStyle(.1);
$pdf->line(70,58,300,58);
$pdf->ezStartPageNumbers(550,35,10,'','{PAGENUM} of {TOTALPAGENUM} transmittal cover');
$pdf->ezStream();
?>
