<?
$trans_doc_id=addslashes($trans_doc_id);
$trans_doc_info=getone("select * from transmittal_documents where trans_doc_id = '$trans_doc_id'");

$quantity=addslashes($quantity);
$description=addslashes($description);
$doc_date=vali_date($doc_date);

//echo "$description<hr>$quantity<hr>select * from transmittal_documents where trans_doc_id = '$trans_doc_id'";
$query="update transmittal_documents set quantity = '$quantity', description = '$description', doc_date = '$doc_date' where trans_doc_id = '$trans_doc_info->trans_doc_id'";
@mysql_query($query);
forward("transmittal_edit&transmittal_id=$trans_doc_info->transmittal_id");
?>
