<?
if (!($admin_check)) die("ERROR: Security Violation! The authorities are being notified!");

$contacts_id=escapeshellcmd($contacts_id);
$contact_type=escapeshellcmd($contact_type);

$query="insert into timesheet_types (contacts_id,contact_type) values ('$contacts_id','$contact_type')";

$res=@mysql_query($query);

if (!($res)) die("Operation Failed: The operation could not be completed for some reason. Please contact your system administrator.<br>Failing query:<hr>$query<hr>");

forward('admin_timesheet_types_modify');


?>
