<?
$CONTRACTOR=FALSE;
if ($global_user->contacts_id != "2090") {
$viewpoint_user_info=ms_getoneb("select udusername,PREmp from HRRM with (NOLOCK) where HRCo = 1 and udusername = '$current_user->login_name'");

//echo "$global_user->contacts_id";exit;

if ($contractor_warned=="") {
	session_register('contractor_warned');
	$contractor_warned="no";
	}

if (!($viewpoint_user_info)) {
	if ($contractor_warned!="yes") {
		echo "Error getting employee number from viewpoint! No matched login name for \"$current_user->login_name\".<br>
		<b>If you are not a contract employee, then this is an error with your account!<br>
		<font color=red>You will not be allowed to create a timesheet for yourself at this point.</font></b><br>";
		//else
		//echo "Grabbed employee number record from viewpoint<p>";
		$contractor_warned="yes";
		}
	}

$viewpoint_group_info=ms_getoneb("select PRGroup from PREH with (NOLOCK) where PRCo = 1 and Employee = $viewpoint_user_info->PREmp");
if (!($viewpoint_group_info)&&($contractor_warned!="yes"))
	echo "Error getting employee group (1/3) from viewpoint! No matched login name for \"$current_user->login_name\"???";
	//else
	//echo "Grabbed employee group record from viewpoint<p>";


$update_red_query="update contacts set employee_num = '$viewpoint_user_info->PREmp',employee_group = '$viewpoint_group_info->PRGroup' where contacts_id = '$current_user->contacts_id' and umc_emp = 'Y'";
@mysql_query($update_red_query);
}
?>
