<?
if (!($payroll_check)) die("ERROR: Security violation! The authorities are being notified!");

$mark_week_ending=vali_date($mark_week_ending);

$query="update timesheet_index,contacts set timesheet_index.status = 'processing' where contacts.contacts_id = timesheet_index.employee_id and contacts.timesheet_payroll_sequence_num = '$payroll_seq' and timesheet_index.status = 'complete' and timesheet_index.week_ending = '$mark_week_ending'";
$query2="update timesheet_time,contacts set timesheet_status = 'processing' where contacts.contacts_id = timesheet_time.employee_id and contacts.timesheet_payroll_sequence_num = '$payroll_seq' and timesheet_status = 'complete' and week_ending = '$mark_week_ending'";

$res=@mysql_query($query);
if (!($res)) die("fatal error1: first stage mark all processing. Please contact your system administrator.");
$res=@mysql_query($query2);
if (!($res)) die("fatal error2: second stage mark all processing. Please contact your system administrator.");

forward('payroll_timesheet_selection');

?>
