<?
if (!($payroll_check)) die("ERROR: Security violation! The authorities are being notified!");
require_once('pdf_lib2.inc');
require_once('timesheet_libs_pdf.inc');
//-----------------------------------------------------------------------------------
//	Document Setup...
//-----------------------------------------------------------------------------------
$pdf=&new Cezpdf("$global_user->pref_paper_size","portrait");
$pdf->selectFont("$pdf_font_path/Helvetica.afm");
//-----------------------------------------------------------------------------------
//	Page Printing
//-----------------------------------------------------------------------------------
$query="select * from timesheet_index,contacts where timesheet_index.employee_id = contacts.contacts_id and timesheet_index.status = 'processing' and contacts.timesheet_payroll_sequence_num = '$payroll_seq' order by week_ending desc,last_name";
//tabledump($query);exit;
$res=@mysql_query($query);
while($row=@mysql_fetch_object($res)) {
	$pdf=pdf_timesheet_2($pdf,$row->timesheet_id);
	}
$pdf->ezStream();
?>
