<?
require_once("querylib.inc");
require_once("timesheet_include.inc");

$mileage_rate = get_mileage_rate($workday);

echo "

<body bgcolor=white>

<table border=1><tr><td colspan=2 bgcolor=#dddddd>
Add Mileage:
</td></tr>

<form name=add_time method=post action=$pagename>
<input type=hidden name=mode value='timesheet_edit_add_spt_verify'>
<input type=hidden name=employee_num value='$current_user->employee_num'>
<input type=hidden name=earnings_code value=7>
<input type=hidden name=comments>

<tr><td>
	Date:
</td><td>
	<b>$workday</b>&nbsp;
	<input type=hidden name=workday value=\"$workday\">
</td></tr>

<tr><td valign=top>
	<a href=javascript:job_help();><font color=black>Job:</font></a>
</td><td>
	<input type=text name=job_num><br>
	";recent_jobs($current_user->contacts_id,1);echo"
</td></tr>

<tr><td valign=top>
	<a href=javascript:phase_help();><font color=black>Phase:</font></a>
</td><td>
	<input type=text name=phase><br>
</td></tr>

<tr><td>
	Miles:
</td><td>
	<input type=text name=miles>
	<input type=hidden name=dollars>
</td></tr>

<tr><td colspan=2 align=right>
	<input type=button onclick=calc_miles(); value=Add>
</td</tr>
<tr><td colspan=2>
	Notes<br>
	<textarea name=notes2 row=4 cols=40></textarea>
</td></tr>
</form>
</table>

<script>
function job_help() {
	open('$pagename?mode=timesheet_job_popup','timesheet_popup','height=400,width=400,scrollbars=yes,resizable=yes');
	}

function phase_help() {
	if (document.add_time.job_num.value=='') {
		alert('Error: Please enter a job number first');
	} else {
		open ('$pagename?mode=timesheet_phase_spt_popup&job_num=' + document.add_time.job_num.value,'timesheet_popup','height=400,width=500,scrollbars=yes,resizable=yes');
	}
}

function calc_miles() {
	document.add_time.dollars.value=(Math.round(document.add_time.miles.value * $mileage_rate)/100);
	document.add_time.comments.value=document.add_time.miles.value + ' miles';
	document.add_time.submit();
}
document.add_time.job_num.focus();
</script>            




";









echo "</body>";
?>
