<?

if ($service_type_id!="") {
	$service_type_id=addslashes($service_type_id);
	$service_type_info=getone("select * from access_service_types where service_type_id = '$service_type_id'");
	}

require('header.phtml');
echo "
<form name=service_type_edit method=post action=$pagename>
<input type=hidden name=mode value=service_type_submit>
<input type=hidden name=service_type_id value=\"$service_type_info->service_type_id\">
<table border=1 cellspacing=0 cellpadding=4><tr><td colspan=2 bgcolor=#dddddd align=center><b>Service Type Info</b></td></tr>
<tr><td>
	<b>Service Name:</b>
</td><td>
	<input type=text maxlength=100 name=name value=\"$service_type_info->name\">
</td></tr>

<tr><td valign=top>
	<b>Description:</b>
</td><td>
	<textarea name=description rows=5 cols=40>$service_type_info->description</textarea>
</td></tr>

<tr><td colspan=2 align=right>
	<input type=submit value=Save>
</td></tr>
</form>










";











?>
