<?
if ($service_type_id!="") {
	$service_type_id=addslashes($service_type_id);
	$query_start="update access_service_types set ";
	$query_end=" where service_type_id = '$service_type_id'";
	} else {
	$query_start="insert into access_service_types set ";
	$query_end="";
	}

$name=addslashes($name);
$description=addslashes($description);
$query_middle="
name = '$name',
description = '$description'
";
$query_full=$query_start . $query_middle . $query_end;
$res=@mysql_query($query_full);
if (!($res)) die("Update failed! Failed query:<hr>$query_full");
forward('server_lookups');
?>
