<?

echo "
<hr>
<table border=0 cellpadding=2 cellspacing=0>

<tr><td>
	<a href=$pagename_up><font color=blue>Exit</font></a>
</td><td>
	<a href=$pagename><font color=blue>Main Menu</font></a>
</td><td>
	<a href=$pagename?mode=product_search_result><font color=blue>Last Search Results</font></a>
</td><td>
	<a href=$pagename?mode=product_edit><font color=blue>New Entry</font></a>
</td></tr>

</table>


";





?>
