<?
//////////////////////////////////////////////////////////////////////
// We need to keep track of a few things so we can exit to the right
// spot again for most any scenario:
// #1) doc_id - this is the document that opened us
// #2) doc_edit_id - this is the document we're editing
// #3) $doc_type, but from here it is fixed 
//
//	Anything else that we load off of, should probably get overriden 
//  by the above data (IE: if we know we're load a particular 
//  doc_edit_id, we don't care about the edit text that is for
//  trying to locate it.
//////////////////////////////////////////////////////////////////////

$doc_type="oiclog";
include ('fd_document_box_header.phtml');
fd_document_box_header_print($doc_id,$doc_type,$doc_edit_id);

///////////////////////////////////////////////////////////////////////////////////////////////////
//	This is the end of the generics section
//	...now on to the app specific stuff
///////////////////////////////////////////////////////////////////////////////////////////////////
echo "boo";
if ($doc_edit_info) {
	$oiclog_info=getoneb("select * from oiclog where oiclog_id = '$doc_edit_info->app_record_id'");
	//$gcrfi_num_text=htmlspecialchars($gcrfi_info->gcrfi_num);
	
	} else {
	//$gcrfi_num_text=htmlspecialchars($load_text);
	
	}

echo "<table border=0 cellspacing=0 cellpadding=1>";
if (!($oiclog_info)) {
	echo "
	<tr><td>
			<font size=-2>OIC Num:</font>
	</td><td>
		<input type=text size=8 name=oic_number id=doc_box_oic_number value=\"$oic_number_text\">
	</td></tr>
	
	<tr><td colspan=2 align=center>
		<input type=button onclick=create_new_oiclog($doc_info->doc_id) value=Create>
	</td></tr>
	</table>
	";
	exit;
	}
echo "
<tr><td>
		<font size=-2>GCRFI #:</font>
</td><td id=fd_document_box_gcrfi_num_cell>
	<input type=text size=8 name=gcrfi_num id=doc_box_gcrfi_num value=\"$gcrfi_num_text\" onchange=fd_doc_change_gcrfi_num('$doc_info->doc_id','$doc_edit_info->doc_id')>
</td></tr>

<tr><td>
	<font size=-2>Subject:</font>
</td><td id=fd_document_box_key_description_cell>
	<input type=text size=13 name=key_description id=doc_box_key_description value=\"$gcrfi_info->key_description\" onchange=fd_doc_change_key_description('$doc_info->doc_id','$doc_edit_info->doc_id')>
</td></tr>

<tr><td valign=top>
	<font size=-2>Resp&nbsp;Reqd:</font>
</td><td id='fd_document_box_resp_reqd_cell'>
	";datebox2($gcrfi_info->response_needed_date,'form1.response_needed_date',"fd_doc_gcrfi_change_resp_reqd_date(this.id,$doc_info->doc_id,$doc_edit_info->doc_id)");echo"
</td></tr>

<tr><td>
	<font size=-2>Resp&nbsp;From:</font>
</td><td id='fd_document_box_reply_from_cell'>
	";contact("select * from contacts where contact_type = 'contact' and umc_emp != 'Y' and current = 'Y'",$gcrfi_info->reply_from,'reply_from',"ajaxManager('load_page','/global$devel/gcrfilog$devel/?mode=mini_edit_update_reply_from&doc_id=$doc_info->doc_id&doc_edit_id=$doc_edit_info->doc_id&reply_from=' + document.contact_changed_value,'fd_document_box_reply_from_cell');",array('hidden_input'=>'N','input_size'=>'10','jobinfo_id'=>"$global_jobinfo->jobinfo_id"));echo"
</td></tr>

<tr><td valign=top>
	<font size=-2>Recv&nbsp;Date:</font>
</td><td id='fd_document_box_reply_cell'>
	";datebox2($gcrfi_info->reply_date,'form1.reply_date',"fd_doc_gcrfi_change_reply_date(this.id,$doc_info->doc_id,$doc_edit_info->doc_id)");echo"
</td></tr>

<tr><td valign=top>
	<font size=-2>PM&nbsp;Complete:</font>
</td><td id='fd_document_box_pm_complete_cell'>
	";datebox2($gcrfi_info->pm_complete_date,'form1.pm_complete_date',"fd_doc_gcrfi_change_pm_complete_date(this.id,$doc_info->doc_id,$doc_edit_info->doc_id)");echo"
</td></tr>

<tr><td colspan=2 id='fd_document_box_has_cost_cell'>
	<font size=-2>Cost/Sched&nbsp;Impact:</font>
	<select id=\"doc_box_has_cost\" name=has_cost onchange=fd_doc_change_has_cost($doc_info->doc_id,$doc_edit_info->doc_id)>
	<option>$gcrfi_info->has_cost</option>
	<option>Y</option>
	<option>N</option>
	<option></option>
	</select>
</td></tr>
</table>
";
?>
