<?

require('intra-pw.inc');

@mysql_connect(localhost,"globalread","qazxsw");
@mysql_select_db("global");

session_register('print_size');
if ($print_size=="") $print_size="8";
if ($print_size_set!="") $print_size=addslashes($print_size_set);
$print_size_big=$print_size + 2;

$query="select contract_num, job_name, project_manager_id, job_cost, contract_type, contract_admin from jobinfo where active = 'Y' and job_type like '%special%' order by contract_num";

$result=@mysql_query($query);

echo "

<style type=\"text/css\" media=\"print\">
th {
	font-size: $print_size_big
	}
td {
	font-size: $print_size
	}

div#printsize {
	display: none;
	}

</style>


<div id=\"printsize\">
<a href=$pagename_up><font color=blue>Exit</font></a>
<form name=printsize method=post action=$pagename>
<table border=1 cellspacing=0 cellpadding=3><tr><td bgcolor=#dddddd>Print Size: <input size=2 type=text name=print_size_set value=\"$print_size\" onchange=submit()></td></tr></table>
</form>
</div>


<center>
<h2>Active Special Projects Jobs</h2>
<table border=1 cellspacing=0 cellpadding=3>
<thead>
	<tr bgcolor=#dddddd><th>
	Job Number
	</th><th>
	Name
	</th><th>
	Project Manager
	</th><th>
	Job Cost
	</th><th>
	Contract Type
	</th><th>
	Contract Admin
	</th></tr>
</thead>
	";

while($row=@mysql_fetch_object($result)) {
	$con_ad=getoneb("select * from contacts where contacts_id = '$row->contract_admin'");
	if ($con_ad) {
		$contract_admin="$con_ad->last_name, $con_ad->first_name";
		} else {
		$contract_admin="";
		}

	$mgr=getoneb("select * from contacts where contacts_id = '$row->project_manager_id'");
	if ($mgr) {
		$manager="$mgr->last_name, $mgr->first_name";
		} else {
		$manager="";
		}


	echo "<tr><td>
			$row->contract_num
		</td><td>
			$row->job_name
		</td><td>
			$manager&nbsp;
		</td><td>
			$row->job_cost&nbsp;
		</td><td>
			$row->contract_type&nbsp;
		</td><td>
			$contract_admin&nbsp;
		</td></tr>
		";
		//<tr><td colspan=5><font size=-3><hr></font></td></tr>
		
		}

echo "</table></center>";
	
















?>
