<?
require('header.phtml');

if ($sharelist_id!="") {
	$sharelist_id=addslashes($sharelist_id);
	$share_info=getone("select * from access_jupiter_sharelist where sharelist_id = '$sharelist_id'");
	}

echo "
<form name=sharelist method=post action=$pagename>
<input type=hidden name=mode value=access_jupiter_share_submit>
<input type=hidden name=sharelist_id value=\"$share_info->sharelist_id\">
<table border=1 cellspacing=0 cellpadding=0><tr><td>
<table border=0>
<tr><td colspan=2 bgcolor=#dddddd align=center>
	<b>Share Info</b>
</td></tr>

<tr><td>
	Share Path/Name:
</td><td>
	<input type=text name=share_path value=\"$share_info->share_path\">
</td></tr>

<tr><td>
	Share Device:
</td><td>
	";dropbox("select device_id,device_description from access_jupiter_devices order by device_description desc","$share_info->device_id");echo"
</td></tr>

<tr><td>
	Share Owner:
</td><td>
	";contactsbox("select * from contacts where umc_emp = 'Y' and current = 'Y'","$share_info->share_owner","share_owner");echo"
</td></tr>

<tr><td colspan=2 align=right>
	<input type=submit value=Save>
</td></tr>

</form>
</table>
</td></tr></table>
";




?>
