<?
require_once('classes/Authorization/AccessControl.php');

use classes\Authorization\AccessControl;

$uri_encode=base64_encode($REQUEST_URI);
$bgcolor="white";

//$bgcolor="#8caede";
$bgcolor=$umc_standard_blue;
echo "<html><head><title>UMC Contacts</title></head><body bgcolor=\"$bgcolor\">";
if ($global_user_id!="") {
	$global_user_info=getoneb("select * from contacts where contacts_id = '$global_user_id'");
	$global_user_id=addslashes($global_user_id);
	}

if ($display_name=="") $no_auto_select=TRUE;
else $no_auto_select=FALSE;

function color_print() {
	global $shaded;
	if ($shaded=="no") {
		$shaded="yes";
		echo " bgcolor=#ffffff ";
		} else {
		$shaded="no";
		echo " bgcolor=#eeeeee ";
		}
	}
////////////////////////////////////////////////////////
// Read in the settings passes as a bitmask from the
// javascript on the other page.
////////////////////////////////////////////////////////
$settings=escapeshellcmd($settings);
$readonly=bit_info($settings,0);
$locked=bit_info($settings,1);
$allow_add=bit_info($settings,2);
$hide_image=bit_info($settings,3);
$show_no_details_in_popup=bit_info($settings,4);
$show_phone_in_form=bit_info($settings,5);
                    
$query=escapeshellcmd($query);
$query_next=$query;
$query=base64_decode($query);
$field=escapeshellcmd($field);
$field_next=$field;
$onchange=escapeshellcmd($onchange);
$onchange_next=$onchange;
$onchange=base64_decode($onchange);
$contacts_id=escapeshellcmd($contacts_id);
$contacts_id_next=$contacts_id;
if ($display_name!="") {
	$display_name=addslashes($display_name);
	$display_search=" and display_name like '%$display_name%'";
	} else {
	$display_search="";
	}

if (ereg("is_company",$query)) {
	echo "Warning: Application uses an obsolete field (is_company). Please contact Jeff to fix. Things will work better as well!<hr>";
	}

$contact_info=getoneb("select * from contacts where contacts_id = '$contacts_id'");

$where="";
if ($expanded_selection != "") {
	$where=$expanded_selection;
	} else {
	$where=$query;
	}


//////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////
// Parse out the information about what exactly we're searching for,
// at least where it matters for what "type" of contact we're looking
// for.  First we find out if we're searching for a contact within
// a specific company, and next we find out what type (site or contact)
//
// In the end, we can use this to give people "Add" buttons directly 
// in this interface, without adding any complexity to the calling
// functions or pages.
//////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////
$company_contact_list=0;
if (eregi("company_id",$where)) {
	$company_id_test=eregi_replace("^.*company_id",'',$where);
	$company_id_test=eregi_replace("^[ =']*","",$company_id_test);
	$company_id_test=eregi_replace("[^0-9].*$","",$company_id_test);
	if ($company_id_test>0) $company_contact_list=1;
	$listed_company_id=$company_id_test;
	}

if (eregi("contact_type",$where)) {
	$contact_type_test=ereg_replace("^.*contact_type",'',$where);
	$contact_type_test=ereg_replace("^[ =']*","",$contact_type_test);
	$contact_type_test=ereg_replace("[' ].*$","",$contact_type_test);
	}



if ($global_user_info->umc_emp=='Y') {
switch ($contact_type_test) {
	case "company":
						$add_link_text="<table border=0 cellspacing=0 cellpadding=0 width=100%>
						<tr><td>
							<font size=+1><b>Showing Companies:</b></font>
						</td><td align=right>
							<a href=/global/contacts$devel_link_addition/?mode=contact_add_wizard&type=company&return_to=$uri_encode><font color=blue size=+1><b><i>Add</i></b></font></a>
						</td></tr></table>";
						break;;
	case "contact":
						if ($company_contact_list!=0) {
							$comp_info=getoneb("select * from contacts where contacts_id = '$listed_company_id'");
							$fortext=" for $comp_info->display_name";
							} else {
							$fortext=""; }
						$add_link_text="
						<table border=0 cellspacing=0 cellpadding=0 width=100%>
						<tr><td>
							<font size=+1><b>Showing Contacts$fortext:</b></font>
						</td><td align=right>
							<a href=/global/contacts$devel_link_addition/?mode=contact_add_wizard&type=contact&company_id=$listed_company_id&return_to=$uri_encode><font color=blue size=+1><i><b>Add</b></i></font></a>
						</td></tr></table>";
						break;;
	case "site":
						if ($company_contact_list!=0) {
							$comp_info=getoneb("select * from contacts where contacts_id = '$listed_company_id'");
							$fortext=" for $comp_info->display_name";
							} else {
							$fortext=""; }
						$add_link_text="<table border=0 cellspacing=0 cellpadding=0 width=100%>
						<tr><td>
							<font size=+1><b>Showing Sites$fortext:</b></font>
						</td><td align=right>
							<a href=/global/contacts$devel_link_addition/?mode=contact_add_wizard&type=site&company_id=$listed_company_id&return_to=$uri_encode><font color=blue size=+1><i><b>Add</b></i></font></a>
						</td></tr></table>";
						break;;
	default:
						$add_link_text="
						<table border=0 cellspacing=0 cellpadding=0 width=100%>
						<tr><td>
							<font size=+1><b>Showing types unknown/various:</b></font>
						</td><td align=right>
							<a href=/global/contacts$devel_link_addition/?mode=contact_add_wizard&return_to=$uri_encode><font color=blue size=+1><i><b>Add</b></i></font></a>
						</td></tr></table>";
						break;;
	}
}

//////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////

$query="select * from contacts where " . $where . $display_search . " order by display_name,employee_num ";
$res=@mysql_query($query);

if ((AccessControl::isAdmin($global_user_id))&&(!($res))) {
	die("<hr>ERROR: Query Failed... Failed query:<hr>$query");
	}

if ($contact_info) {
	$cdisplay_name=ereg_replace(" ","&nbsp;",$contact_info->display_name);
	$cdisplay_name=ereg_replace("'","&#039;",$cdisplay_name);
	echo "<table border=1 cellspacing=0 cellpadding=0 width=100%><tr>
	";
	
	if ($contact_info->photo_file_group_id > 0) {
		$file=getoneb("select * from webfile_files where file_group_id = '$contact_info->photo_file_group_id'");
		$picurl=webfile_medium_image_icon($file->files_id);
		echo "<td align=center valign=top bgcolor=white><img border=0 src=\"$picurl\"></td>";
		}
	
	echo"
	<td valign=top bgcolor=#ffffff>
	<table width=100% border=0 cellspacing=0 cellpadding=3>
	
	<tr><td colspan=2 align=center bgcolor=#dddddd><b>Currently Selected</b></td></tr>
	<tr bgcolor=\"white\"><td colspan=2 width=100%>
		<div style=\"float: right;\">
		";
		if ($global_user_info->umc_emp=="Y") contact_edit_in_popup($contact_info->contacts_id,"<i>Edit</i>");
		else contact_view("<i>View</i>",$contact_info->contacts_id);
		echo"</div>
		<a href=javascript:set_contact('$contact_info->contacts_id','$cdisplay_name')><font color=blue>$cdisplay_name</font></a>
	</td></tr>
	";
	
	//////////////////////////////////////////////////////////////
	//////////////////////////////////////////////////////////////
	// Print the basic details about a contact (if enabled)
	//////////////////////////////////////////////////////////////
	//////////////////////////////////////////////////////////////
	if ($show_no_details_in_popup=="off") {
		if ($contact_info->contact_type!="company") { echo "<tr ";color_print();echo"><td><b>Company:</b></td><td>$contact_info->company</td></tr>"; }
		if ($contact_info->employee_trade_description!="") { echo "<tr ";color_print();echo"><td><b>Trade:</b></td><td>$contact_info->employee_trade_description</td></tr>"; }
		if ($contact_info->phone!="") { echo "<tr ";color_print();echo"><td><b>Phone:</b></td><td>$contact_info->phone&nbsp;$contact_info->phone_ext</td></tr>"; }
		if ($contact_info->phone_fax!="") { echo "<tr ";color_print();echo"><td><b>Fax:</b></td><td>$contact_info->phone_fax</td></tr>"; }
		if ($contact_info->phone_cell!="") { echo "<tr ";color_print();echo"><td><b>Cell:</b></td><td>$contact_info->phone_cell</td></tr>"; }
		if ($contact_info->phone_page!="") { echo "<tr ";color_print();echo"><td><b>Page:</b></td><td>$contact_info->phone_page</td></tr>"; }
		if ($contact_info->address_1!="") { echo "<tr ";color_print();echo"><td><b>Address:</b><br>";map_link_this_contact_here($contact_info->contacts_id);echo"</td><td><pre>$contact_info->address_1<br>$contact_info->address_city, $contact_info->address_state $contact_info->address_zip</pre></td></tr>"; }
		}
	echo "</table></td></tr></table>";
	}

echo "
<script>
function set_contact(contact_id,contact_name) {
	opener.document.${field}.value=contact_id;
	opener.document.${field}_disp.value=contact_name;
	";if ($onchange!="") echo "$onchange";
	$pagename_fixed=ereg_replace("/[^/]*$","/",$pagename);
	
	echo "
	document.location='$pagename_fixed?mode=register_history_and_close&contacts_id=' + contact_id;
	//self.close();
	}
self.focus();
</script>

<form name=contact_selection_search action=/global/contacts${devel}/contact_selection.phtml method=get>
<input type=hidden name=query value=\"$query_next\">
<input type=hidden name=field value=\"$field_next\">
<input type=hidden name=onchange value=\"$onchange_next\">
<input type=hidden name=contacts_id value=\"$contacts_id_next\">
<input type=hidden name=settings value=\"$settings\">
<table border=0 cellspacing=0 cellpadding=2><tr><td><b>Search:&nbsp;</td><td></b><input type=text name=display_name size=20 value=\"$display_name\"></td>";
	if ($locked=="off") {
	echo "<td><b>Options:</b>&nbsp;</td><td><select name=expanded_selection onchange=\"submit()\"><option value=\"$expanded_selection\">*</option><option value=\"\">App Default</option><option value=\" is_company = 'Y' and current = 'Y' \">Companies - Active</option><option value=\" is_company = 'Y' \">Companies - All</option><option value=\" is_company = 'N' and current = 'Y' \">People  - Active</option><option value=\" is_company = 'N' \">People  - All</option><option value=\" 1 = 1 \">Everything</option></select></td>";
	}

echo "
</tr></table></form>
<script>
document.contact_selection_search.display_name.focus();
</script>


$add_link_text
<table border=1 cellspacing=0 cellpadding=0 width=100%><tr><td>
<table border=0 cellspacing=0>";


echo "<tr bgcolor=\"#eeeeee\"><td><a href=\"javascript:set_contact('','')\"><font color=\"$display_color\"><i>none</i></font></td><td width=100% valign=top align=right>&nbsp;</td></tr>";

$odd=1;

$resultscount=@mysql_num_rows($res);

while($row=@mysql_fetch_object($res)) {
	$last_disp=$row->display_name;
	$last_id=$row->contacts_id;
	$record_disp=ereg_replace(' ','&nbsp;',$row->display_name);
	$record_disp=ereg_replace("'",'\&#039;',$record_disp);
	if ($odd==1) {
		$cellbg="#ffffff";
		$odd=0;
	} else {
		$cellbg="#eeeeee";
		$odd=1;
		}
	if ($row->current=='Y') $display_color="blue";
	else $display_color="#aaaaaa";
	$display_name=ereg_replace(" ","&nbsp;",$row->display_name);
	if ($row->contact_type=='contact') {
		$company=ereg_replace(" ","&nbsp;",$row->company);
		$extra="&nbsp;<font size=-1>($company)</font>";
		} else {
		$extra="";
		}
	echo "<tr bgcolor=\"$cellbg\"><td><a href=\"javascript:set_contact('$row->contacts_id','$record_disp')\"><font color=\"$display_color\">$display_name$extra</font></td><td width=100% valign=top align=right>";contact_view("<i>View</i>",$row->contacts_id);echo"</td></tr>";
	}

echo "</table></table>";

if (($resultscount==1)&&(!($no_auto_select))) {
	$contact_name=strtolower($last_disp);
	$search_name=strtolower($display_name);
	$search_name=ereg_replace("&nbsp;"," ",$search_name);
	if ($search_name==$contact_name) {
		$last_disp=ereg_replace("'","\&#039;",$last_disp);
		//contacts_hist_add($last_id);
		echo "
		<script>
		set_contact('$last_id','$last_disp');
		self.close();
		</script>
		";
		}
	
	
	}

?>
