<?


$email_link="";
if ($contact_info->email!="") $email_link="<a href=mailto:$contact_info->email><font color=blue>$contact_info->email</font></a>";


echo "<table border=1 cellspacing=0 cellpadding=0 width=100%><tr>";

if ($contact_info->photo_file_group_id>0) {
	$file=getoneb("select * from webfile_files where file_group_id = '$contact_info->photo_file_group_id'");
	$picurl=webfile_medium_image_icon($file->files_id);
	echo "<td align=center valign=top bgcolor=white><img border=0 src=\"$picurl\"></td>";
	}


echo"
<td valign=top bgcolor=#ffffff>
<table border=0 cellspacing=0 cellpadding=3 width=100%>

<tr><td colspan=2 align=center bgcolor=#dddddd>
	<b>Contact Information</b>
</td></tr>

<tr bgcolor=\"white\"><td colspan=2 align=center>
<b>$contact_info->display_name</b>
</td></tr>

";
if ($contact_info->company!="") { echo "<tr ";color_print(); 
echo"><td valign=top><b>Company:</b></td><td>"; 	contact_view("$info->company","$info->company_id");
echo "</td></tr>"; 

}
if ($contact_info->phone!="") { echo "<tr ";color_print(); echo"><td valign=top><b>Phone:</b></td><td>$contact_info->phone&nbsp;$contact_info->phone_ext</td></tr>"; }
if ($contact_info->phone_fax!="") { echo "<tr ";color_print(); echo"><td valign=top><b>Fax:</b></td><td>$contact_info->phone_fax</td></tr>"; }
if ($contact_info->phone_cell!="") { echo "<tr ";color_print(); echo"><td valign=top><b>Cell:</b></td><td>$contact_info->phone_cell</td></tr>"; }
if ($contact_info->phone_page!="") { echo "<tr ";color_print(); echo"><td valign=top><b>Page:</b></td><td>$contact_info->phone_page</td></tr>"; }
if ($contact_info->address_1!="") { echo "<tr ";color_print(); echo"><td valign=top><b>Address:</b><br>";map_link_this_contact_here($contact_info->contacts_id);echo"</td><td>$contact_info->address_1<br>$contact_info->address_city, $contact_info->address_state $contact_info->address_zip</td></tr>"; }
if ($email_link!="") { echo "<tr ";color_print(); echo"><td valign=top><b>Email:</b></td><td>$email_link</td></tr>"; }
echo"</table></td></tr></table>
<table cellspacing=0 cellpadding=2 border=0 width=100%>
<tr><td colspan=2 width=50%>&nbsp;</td><td colspan=2 width=50%>&nbsp;</td></tr>

<tr><td valign=top>
	<b>Current:</b>
</td><td width=20%>
	$info->current
</td><td valign=top>
	<b>Consultant:</b>
</td><td width=20%>
	$info->consultant
</td></tr>	

<tr><td valign=top>
	<b>Owner/Cust:</b>
</td><td width=20%>
	$info->owner
</td><td valign=top>
	<b>Project Mgr:</b>
</td><td width=20%>
	$info->proj_manager
</td></tr>	

<tr><td valign=top>
	<b>Estimator:</b>
</td><td width=20%>
	$info->estimator
</td><td valign=top>
	<b>Architect:</b>
</td><td width=20%>
	$info->architect
</td></tr>	

<tr><td valign=top>
	<b>Trade:</b>
</td><td>
	$info->employee_trade
</td></tr>

<tr><td valign=top>
	<b>Class:</b>
</td><td>
	$info->employee_class
</td></tr>

</table>
";

/*
<tr><td valign=top>
	<b>Local:</b>
</td><td>
	$info->employee_union_local
</td></tr>
*/



?>
