<?
//require_once("querylib.inc");
require_once("header.phtml");

function check_contact($contact_id,$path,$previous_count=0) {
	if (!(ereg("\.",$path))) echo "Warning: No table/column seperation for \"$path\". Values should be in \"&lt;tablename&gt;.&lt;column&gt\" notation. Not checking data!";
	$part=explode('.',$path);
	$query="select sum(1) as total from $part[0] where $part[1] = '$contact_id'";
	$res=@mysql_query($query);
	if (!($res)) echo "Warning: Lookup failed for path: \"$path\"! Query failed!";
	$total=@mysql_fetch_object($res);
	if ($total->total=="") $total->total=0;
	return $total->total;
	}

function check_contact_pretty ($contact_id,$path,$previous_count=0) {
	$count=check_contact($contact_id,$path,$previous_count);
	if ($count==0) return $count;
	else echo "<b>$path</b><br>Count: $count<hr>";
	return $count;
	}


function contact_fk_search_pretty ($contact_id) {
	$junk_count=0;
	$total=0;
	$res=@mysql_query("select * from contacts_fk_list order by fk_name");
	while($row=@mysql_fetch_object($res)) {
		$count=check_contact_pretty($contact_id,$row->fk_name);
		$total="$total" + "$count";
		}
	echo "<b>Total: $total</b><p>";
	}


echo "<a href=$pagename?mode=main><font color=blue>Return to main menu</font></a><br>";

if ($contacts_id=="") {
	echo "
	<form name=contact_list method=post action=$pagename>
	<input type=hidden name=mode value=contact_search>
	";
	dropbox("select contacts_id,display_name from contacts order by display_name","","20");
	dropbox("select contacts_id as contacts_id_2,display_name from contacts order by display_name","","20");
	echo "
	<br><input type=submit value=Search>
	</form>
	";
	exit;
	}

echo "<table border=1 cellspacing=0 cellpadding=4>
<tr><td>";    
	contact_view("",$contacts_id); echo "<br>
	($contacts_id)
</td><td>";
	contact_view("",$contacts_id_2);echo "<br>
	($contacts_id_2)
</td></tr>

<tr><td valign=top>
	";contact_fk_search_pretty($contacts_id);echo "
</td><td valign=top>
	";
	if ($contacts_id_2>0) contact_fk_search_pretty($contacts_id_2);
	";
</td></tr>
</table>";

?>
