<?
set_time_limit(900);
//////////////////////////////////////////////////////////////////////
//	Connect to both databases
//////////////////////////////////////////////////////////////////////
// GPH TEMP - get past this
return;
// GPH MARK - absolute path
require("/vagrant/public/pipeline/global/contacts/settings.cfg");
//require("/data/web/pipeline/global/contacts/settings.cfg");
//@mssql_connect("viewpoint","reddwarf","cl01st3r");
//@mssql_select_db("Viewpoint");
include("viewpoint_connect_ro.phtml");
include("global_connect_rw.phtml");
require_once("querylib.inc");
require_once("viewpoint_libs.inc");
//@mysql_connect("localhost","globalreadwrite","poilkjbnm");
//@mysql_select_db("global");
?>
