 <?

echo "


<style type=\"text/css\" media=\"print\"> 
thead {
 	    display:table-header-group;
 	}

tbody {
 	    display:table-row-group;
 	}

table td {
 	    border-bottom:1px solid gray;
 	}

table {
	width: 100%;
	}



</style>

<style type=\"text/css\" media=\"screen\"> 
thead {
 	    display:table-header-group;
 	}

tbody {
 	    display:table-row-group;
 	}

table td {
 	    border:1px solid gray;
 	}
 
</style>

<html>
<head>
<title>Approved Drivers List</title>
</head>
<body bgcolor=#ffffff>
";



?>
