<?
include("../webfile$devel/storage_settings.cfg");

$submittallog_id=addslashes($submittallog_id);
$submittallog_info=getoneb("select * from submittallog where submittallog_id = '$submittallog_id'");
if (!($submittallog_info)) {
	$doc_id=addslashes($doc_id);
	$doc_info=getoneb("select * from documents where doc_id = '$doc_id' and doc_type = 'submittallog'");
	$submittallog_info=getoneb("select * from submittallog where submittallog_id = '$doc_info->app_record_id'");
	if (!($submittallog_info)) pdf_generation_error_pdf("ERR(2) - Unable to load submittal information.");
	}
if (!($submittallog_info)) pdf_generation_error_pdf("ERR(1) - Unable to load submittal_information.");
$job=getoneb("select * from jobinfo where jobinfo_id = '$submittallog_info->jobinfo_id'");

$files_res=@mysql_query("select * from webfile_files where file_group_id = '$submittallog_info->document_file_group_id' and mime_type like '%pdf%'");
$pdf_count=@mysql_num_rows($files_res);
if ($pdf_count<1) pdf_generation_error_pdf("ERR(3) - No PDF to include.");
$row=@mysql_fetch_object($files_res);
if ($row->file_group_id==0) pdf_generation_error_pdf("ERR(99) - No File");
pdf_mime_header("Submittal_$doc_info->app_reference.pdf");
while ($row=@mysql_fetch_object($files_res)) {
	if ($row->file_group_id==0) continue;
	readfile("$storage_root$row->file_path");
	}
?>
