<?php
echo "<div id=\"phone_book\" style=\"z-index: 1; display: none; position: absolute; right: 0px;\"></div>
<div id=\"sub_phases\" style=\"z-index: 1; overflow: auto; display: none; position: absolute; right: 0px;\"></div>
<div id=\"material_phases\" style=\"z-index: 1; overflow: auto; display: none; position: absolute;\"></div>
<div id=\"labor_phases\" style=\"z-index: 1; overflow: auto; display: none; position: absolute;\"></div>
<div class=noprint onclick=\"toggle_project_team($jobinfo->jobinfo_id)\" id=\"phone_book_button\" style=\"border-left: 1px solid black; padding: 4px; cursor: hand; cursor: pointer; float: right;\"><font size=-1 color=blue><b>Project Team</b></font></div>
<div class=noprint onclick=\"show_sub_phases($jobinfo->jobinfo_id)\" id=\"sub_phases_button\" style=\"border-left: 1px solid black; padding: 4px; cursor: hand; cursor: pointer; float: right;\"><font size=-1 color=blue><b>Sub Phases</b></font></div>
<div class=noprint onclick=\"show_material_phases($jobinfo->jobinfo_id)\" id=\"material_phases_button\" style=\"border-left: 1px solid black; padding: 4px; cursor: hand; cursor: pointer; float: right;\"><font size=-1 color=blue><b>Material Phases</b></font></div>
<div class=noprint onclick=\"show_labor_phases($jobinfo->jobinfo_id)\" id=\"labor_phases_button\" style=\"border-left: 1px solid black; padding: 4px; cursor: hand; cursor: pointer; float: right;\"><font size=-1 color=blue><b>Labor Phases</b></font></div>
<div class=noprint style=\"float: left; padding: 2px;\"><b>$jobinfo->contract_num&nbsp;-&nbsp;$jobinfo->display_name</b></div>
";
//flush();
if ($jobinfo->weather_station_code!="")
{
	//$jobinfo=check_weather_data($jobinfo);
	$weather_string=standard_weather_string($jobinfo);
	$weather_string=ereg_replace(" ","&nbsp;",$weather_string);
    $weather_string=ereg_replace("Error updating weather data for job " . $jobinfo->jobinfo_id,"",$weather_string);
    //Error updating weather data for job 
    //die( $weather_string );
	echo "<div class=noprint style=\"overflow: hidden; text-align: right; border-left: 1px solid black; padding: 4px; cursor: hand; cursor: pointer;\"><font size=-1>$weather_string</font></div>";
}

?>