<?
require_once('classes/Authorization/AccessControl.php');

use classes\Authorization\AccessControl;

if (!AccessControl::isAdmin($global_user_id))
    die("Security violation! The authorities have been notified.");
require('header.phtml');

if ($field!="") $field=addslashes($field);
if ($table!="") $table=addslashes($table);
if ($value!="") $value=addslashes($value);


echo "Generic Edit";

//echo "hello there";


?>
