<?
if (!(is_admin())) die("Security violation! The authorities have been notified");

$table=addslashes($table);
$primary_key=addslashes($primary_key);
$value=addslashes($value);

$t_info=table_info($table);

if ($t_info->primary_key!=$primary_key) die ("Application error: Primary key mismatch. Please contact your system administrator!");
$data=getone("select * from $table where $primary_key = '$value'");

$res=@mysql_query("describe $table");
if (!($res)) die("Table error! Please contact your system adminstrator!");

echo "<table border=1 cellspacing=0 cellpadding=4>
<form name=generic_edit_record method=post action=$pagename>
<input type=hidden name=mode value=generic_edit_record_submit>
<input type=hidden name=primary_key value=\"$primary_key\">
<input type=hidden name=\"$primary_key\" value=\"$value\">
<input type=hidden name=table value=\"$table\">";


while ($row=@mysql_fetch_object($res)) {
	$rowdata=$data->{$row->Field};
	$rowdata=ereg_replace('"','\"',$rowdata);
	echo "<tr><td>
			<b>$row->Field</b>
		</td><td>
		";
			// Make anything but a timestamp, or the primary key editable
			if (($row->Field!=$primary_key)&&(strncmp($row->Type,"timestamp",8)!=0)) {
				/////////////////////////////////////////////////////////
				/////////////////////////////////////////////////////////
				// Later on, this will be a good place to branch off, and 
				// have different input interfaces depeding on the type
				// of field. We could even include the contact popup 
				// without filtering, since we have a seperate DB to keep
				// track of which fields are contacts and which aren't
				/////////////////////////////////////////////////////////
				/////////////////////////////////////////////////////////
				echo "<input type=text size=20 name=\"$row->Field\" value=\"$rowdata\">";
				} else {
				echo "$rowdata";
				}
		
		
		echo "
		</td></tr>";
	}
echo "
<tr><td colspan=2 align=right>
	<input type=submit value=Save>
	</form>
</td></tr>
</table>";
?>
