<?
// GPH Cleanup warnings
$color_4 = isset($fd_color_4) ? $fd_color_4 : '#888';
echo "
<meta http-equiv=\"X-UA-Compatible\" content=\"chrome=1\">
<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">

<head>
<link rel=\"icon\" type=\"image/png\" href=\"/favicon.png\">
<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">
<link rel=\"stylesheet\" type=\"text/css\" href=\"print.css\" media=\"print\">
<title>$dbdescription</title>
</head>
<body>

";
?>
