<?
$today=date('Y-m-d');

if ($next_action != "") {
	$next_action=addslashes($next_action);
	change_action($issue_id,$next_action);
	}

$expected_completion=vali_date($expected_completion);
$priority=addslashes($priority);

$issue_id=addslashes($issue_id);
add_note($issue_id,"Issue Marked Complete",1);

//$last_hist_info=getoneb("select * from mis_issue_history where issue_id = '$issue_id' and status = 'current'");
//echo "Made it.....";
$last_hist_info=get_current_fixed($issue_id);
$last_hist_info=getoneb("select * from mis_issue_history where issue_id = '$issue_id' and status = 'current'");
$next_action_date=vali_date($next_action_date);
$it_notes=addslashes($it_notes);
if ($next_action=="") $next_action=$last_hist_info->action_required;
$next_action=addslashes($next_action);
$issue_history_id=addslashes($issue_history_id);
$us_or_them=addslashes($us_or_them);
$name=addslashes($name);



//if ($current_project=="on") $project_status="current"; else $project_status="active";

$project_status="complete";



$query="update mis_issue_history set status = 'complete', actual_completion_date = '$today' where issue_history_id = '$issue_history_id'";
$res=@mysql_query($query);if(!($res)) die("ERROR: Query failed. Contact you sys admin.<p>failed query<hr>$query");

$query="update mis_issue_history set status = 'updated' where status = 'current' and issue_id = '$issue_id'";
$res=@mysql_query($query);if(!($res)) die("ERROR: Query failed. Contact you sys admin.<p>failed query<hr>$query.");

$query="update mis_issue_index set name = '$name',status = '$project_status',expected_completion = '$expected_completion' where issue_id = '$issue_id'";
$res=@mysql_query($query);if(!($res)) die("ERROR: Query failed. Contact you sys admin.<p>failed query<hr>$query.");


if ($update_quiet!='yes') {
    // GPH MARK - absolute path
    exec("/data/web/pipeline/php/global/mis_issue_tracking-devel/mail_for_changes.php $issue_id");
}
forward("issue_edit&issue_id=$issue_id");
exit;
?>
