<?
echo "

<html><head><title>MIS Issue Tracking Maintenance</title></head>
<body bgcolor=#ffffff>

<a href=$pagename?mode=main><font color=blue>Return to main menu</font></a><p>

<center><h2>Maintenance Menus</h2></center>
<hr>


<a href=$pagename?mode=uslist><font color=blue>Us vs them List</font></a><br>
<a href=$pagename?mode=categories><font color=blue>Category Maintenance</font></a><br>
<a href=$pagename?mode=priorities><font color=blue>Priority Maintenance</font></a><br>

";




?>
