<?
$qry=getone("select * from mis_issue_query_history where contacts_id = '$global_user_id' order by ts desc limit 1");
$query_id=$qry->query_id;

echo "
<html><head><title>Save Query Dialog</title></head><body bgcolor=#ffffff>

<form name=save_query method=post action=$pagename>
<input type=hidden name=mode value=save_query_submit>
<input type=hidden name=query_id value='$query_id'>
<table border=1>
<tr><td>
	Query Description
</td><td>
	<input type=input name=query_name size=30 maxlength=30>
</td></tr>

<tr><td>
	Priority
</td><td>
	<input type=text name=priority size=5> (numeric/integer)
</td></tr>

<tr><td>
	Show this query in the category list:
</td><td>
	<input type=checkbox name=default_query>
</td></tr>

<tr><td colspan=2 align=right>
	<input type=submit value=Save>
</td></tr>


</form>

<script>
document.save_query.query_name.focus();
</script>

</body></html>

";


?>
