<?
echo "
<table border=1 style=\"border: 0px solid black;\" cellspacing=0 cellpadding=3 width=100%>
<tr><td width=45px>
	<b>Qty</b>
</td><td width=360px>
	<b>Description</b>
</td><td>
	<b>Date</b>
</td><td>
	&nbsp;
</td><td>
	&nbsp;
</td></tr>";
$transmittal_id=addslashes($transmittal_id);
$transmittal_info=getoneb("select * from transmittals where transmittal_id = '$transmittal_id'");
if (!($transmittal_info)) exit;
if ($add_attachment=='true') {
	$quantity=addslashes($quantity);
	$description=addslashes($description);
	$doc_date=vali_date($doc_date);
	mysql_query("insert into transmittal_documents set
	transmittal_id = '$transmittal_info->transmittal_id',
	quantity = '$quantity',
	description = '$description',
	doc_date = '$doc_date'");
	
	}

$query="select * from transmittal_documents where transmittal_id = '$transmittal_id' order by trans_doc_id";
//tabledump($query);
$res=@mysql_query($query);
while ($row=@mysql_fetch_object($res)) {
		$row->doc_date=invali_date($row->doc_date);
		echo "<tr><td>
			$row->quantity
		</td><td>
			$row->description
		</td><td>
			$row->doc_date
		</td><td>
			<a href=$pagename?mode=trans_doc_edit&trans_doc_id=$row->trans_doc_id><font color=blue><i>Edit</i></font></a>
		</td><td>
			<a href=$pagename?mode=del_doc&trans_doc_id=$row->trans_doc_id><font color=blue><i>Delete</i></font></a>
		</td></tr>
		";
	}
echo "</table>";
?>
