<?
$today=date('m-d-Y');
$submit_text="Save";

if ($transmittal_id!="") {
	$transmittal_id=addslashes($transmittal_id);
	$transmittal_info=getoneb("select * from transmittals where transmittal_id = '$transmittal_id'");
	$jobinfo_id=$global_jobinfo_id;
	$creator_info=getoneb("select * from contacts where contacts_id = '$transmittal_info->creator'");
	$doc_id=fd_get_doc_id($transmittal_info->transmittal_id);
	$transmittal_info->sent=checkbreak($transmittal_info->sent);
	$transmittal_info->use_contact_addr_when_available=checkbreak($transmittal_info->use_contact_addr_when_available);
	} else {
	if ($transmittal_to_clone!="") {
		$transmittal_to_clone=addslashes($transmittal_to_clone);
		$transmittal_info=getoneb("select * from transmittals where transmittal_id = '$transmittal_to_clone'");
		$transmittal_info->transmittal_id="";
		}
	//$default_recipient_info=getoneb("select * from contacts where contacts_id = '$global_jobinfo->default_gc_recipient'");
	//$transmittal_info->company_id=$default_recipient_info->company_id;
	//$transmittal_info->site_id=$default_recipient_info->company_id;
	//$transmittal_info->attention_to_id=$default_recipient_info->contacts_id;
	$transmittal_info->trasmittal_date=$today;
	$transmittal_info->transmittal_num='<i>(auto)</i>';
	$jobinfo_id=$transmittal_info->jobinfo_id;
	$submit_text="Save and Add Files";
	$creator_info=getoneb("select * from contacts where contacts_id = '$global_user_id'");
	}
require('header.phtml');
fd_navs_header();
$jobinfo=getoneb("select * from jobinfo where jobinfo_id = '$jobinfo_id'");



if ($transmittal_id!="") {
	echo "<br><a href=\"$pagename?mode=transmittal_finalize&transmittal_id=$transmittal_info->transmittal_id\"><font color=blue>Finalize Transmittal</font></a>";
	}
if ($transmittal_info->transmittal_date=="") $tdate=$today;
else $tdate=invali_date($transmittal_info->transmittal_date);


echo"
<div border=1 id=jscript_pulse></div>
<p>
<form name=transmittal_edit method=post action=\"$pagename\">
<input type=hidden name=mode value=transmittal_submit>
<input type=hidden name=transmittal_id value=\"$transmittal_info->transmittal_id\">

<table border=0 cellspacing=0 cellpadding=4>

<tr><td colspan=2 style=\"border-bottom: 2px solid;\">
	<font size=+2><b>Transmittal&nbsp;Cover&nbsp;Sheet</b></font>
</td><td align=center valign=top>
	<img src=/images/home_umclogo.png>
</td></tr>

<tr><td>
	<b>Job #:</b>
</td><td>
	$jobinfo->contract_num
</td><td width=350px rowspan=15 valign=top>
	<div style=\"float: right;\">Sent&nbsp;<input type=checkbox name=sent $transmittal_info->sent>&nbsp;&nbsp;</div>&nbsp;
	";pal_box($doc_id);echo"
</td></tr>

<tr><td>
	<b>Job Name:</b>
</td><td>
	$jobinfo->display_name
</td></tr>

<tr><td>
	<b>Transmittal #:</b>
</td><td>
	$transmittal_info->transmittal_num
</td></tr>

<tr><td>
	<b>Date:</b>
</td><td>
	<b>$tdate</b>
</td></tr>

<tr><td>
	<b>Company:</b>
</td><td>
	";contactsbox("select * from contacts where contact_type = 'company' and current = 'Y'",$transmittal_info->company_id,"company_id");echo"
</td></tr>

<tr><td valign=top>
	<b>Site:</b>
</td><td id=\"site_box\"";
	$company_id = $transmittal_info->company_id;
	$site_id = $transmittal_info->site_id;
	include("load_site.phtml");
	echo"
</td></tr>
<tr><td colspan=2>site: $transmittal_info->site_id<br></td></tr>
<tr><td>
	<b>Attention:</b>
</td><td bgcolor=$fd_color_1 id=\"attention_box\">";
	$attention_to_id=$transmittal_info->attention_to_id;
	echo"
</td></tr>

<tr><td>
	&nbsp;
</td><td bgcolor=$fd_color_1>
	<font size=-1><i>Try contacts address first:</i></font> <input type=checkbox name=use_contact_addr_when_available $transmittal_info->use_contact_addr_when_available>
</td></tr>

";

if ($transmittal_id!="") {
	echo "<tr><td valign=top align=right>
		<a href=javascript:add_recipient()><font color=blue>Add</font></a>
	</td><td id=\"more_recipients\">
	</td></tr>";
	} else {
	echo "<tr><td>&nbsp;</td><td><i>(Save record to add additional recipients)</i></td></tr>";
	}

echo "
<tr><td>
	<b>CC:</b>
</td><td>";
	contactsbox("select * from contacts where contact_type = 'contact' and current = 'Y'", $transmittal_info->cc_to_id,'cc_to_id');echo"
</td></tr>

<tr><td>
	<b>Transmitted&nbsp;Via:&nbsp;&nbsp;</b>
</td><td>
	";dropbox("select * from transmittal_methods order by name",$transmittal_info->transmitted_via,"","",1);echo "
</td></tr>

<tr><td>
	<b>Transmitted:</b>
</td><td>
	<select name=transmitted>
	<option value=\"$transmittal_info->transmitted\">$transmittal_info->transmitted</option>
	<option value=\"Herewith\">Herewith</option>
	<option value=\"Under Seperate Cover\">Under Seperate Cover</option>
	</select>
</td></tr>

<tr><td>
	<b>Subject:</b>
</td><td>
	<input type=text name=subject maxlength=85 size=40 value=\"$transmittal_info->subject\">
</td></tr>

<tr><td>
	<b>Comments:</b>
</td><td>
	<textarea maxsize=100 name=comments cols=39 rows=5>$transmittal_info->comments</textarea>
</td></tr>

<tr><td colspan=2 align=right>
	<input type=submit name=subtype value=\"Save and New\">&nbsp;<input type=submit name=subtype value=\"Save and Clone\">&nbsp;<input type=submit name=subtype value=\"Apply\">&nbsp;<input name=subtype type=submit value=\"$submit_text\">
</td></tr>


</table>	
</form>


<script>
function blank_site() {
	document.getElementById('site_box').style.visibility='hidden';
	document.transmittal_edit.site_id.value=0;
	}
function blank_attention() {
	document.getElementById('attention_box').style.visibility='hidden';
	document.transmittal_edit.attention_to_id.value=0;
	}
function show_site() {
	document.getElementById('site_box').style.visibility='visible';
	}
function show_attention() {
	document.getElementById('attention_box').style.visibility='visible';
	}

function heartbeat(text) {
	pulse=document.getElementById('jscript_pulse');
	pulse.innerHTML=pulse.innerHTML + text;
	
	}

function check_company_status() {
	setTimeout('check_company_status()',5000);
	heartbeat('.');
	if (document.transmittal_edit.company_id.value<1) { 
			heartbeat('bs'); 
			blank_site(); 
		} else { 
			heartbeat('ss'); 
			show_site(); 
		}
	heartbeat('--');
	heartbeat(document.transmittal_edit.company_id.value);
	heartbeat('--');
	heartbeat(document.transmittal_edit.site_id.value);
	heartbeat('--');
	if (document.transmittal_edit.site_id.value<1) { 
			heartbeat ('ba'); 
			blank_attention();
		} else { 
			heartbeat('sa'); 
			show_attention(); 
		}
	if (document.transmittal_edit.company_id.value!=document.last_company_id) {
		ajaxManager('load_page','$pagename?mode=load_attention_to&company_id=' + document.transmittal_edit.company_id.value + '&attention_to_id=' + document.transmittal_edit.attention_to_id.value ,'attention_box');
		ajaxManager('load_page','$pagename?mode=load_site&company_id=' + document.transmittal_edit.company_id.value + '&site_id=' + document.transmittal_edit.site_id.value,'site_box');
		document.last_company_id=document.transmittal_edit.company_id.value;
		}
	}
check_company_status();
</script>
";


//if ($transmittal_info->site_id=="") echo "blank_site();";
//if ($transmittal_info->attention_to_id=="") echo "blank_attention();";
//if ($transmittal_info->company_id!="") echo "document.last_company_id=document.transmittal_edit.company_id.value;";


if ($transmittal_id != "") {
	echo "<table border=0 cellspacing=0 cellpadding=15>
	<tr><td>
		<b>Front Desk<br>Attached Docs</b>
	</td><td>
		";fd_document_box(array("limit_to_main_types"=>'Y'));echo "
	</td></tr>
	<p><table border=1 cellspacing=0 cellpadding=0>
	<tr><td colspan=4 align=center bgcolor=\"$fd_color_4\">
		<b>Attached Documents</b>
	</td></tr>
	
	<tr><td colspan=4 id=\"attached_docs_list\">
		&nbsp;
	</td></tr>
	";
	
	echo "
	<form name=add_doc method=post action=$pagename>
	<input type=hidden name=mode value=add_doc>
	<input type=hidden name=transmittal_id value=\"$transmittal_info->transmittal_id\">
	
	<tr id=addform><td style=\"padding-top: 4px;\" width=52px>
		<input type=text size=2 name=quantity>
	</td><td style=\"padding-top: 4px;\" width=366px>
		<input type=text size=40 name=description>
	</td><td style=\"padding-top: 4px;\">
		";datebox('','add_doc.doc_date');echo "
	</td><td style=\"padding-top: 4px;\" colspan=2 align=center>
		<input type=button onclick=tdoc_add_row() value=Add></form>
	</td></tr>
	</table>";
	}

if ($transmittal_info->transmittal_date=="") $tdate=$today;
else $tdate=invali_date($transmittal_info->transmittal_date);

echo "<b>Digital signature:</b> <i>$creator_info->display_name&nbsp;&nbsp;&nbsp;&nbsp;$tdate</i>

<script>
function tdoc_add_row() {
	quantity=urlencode(document.add_doc.quantity.value);
	description=urlencode(document.add_doc.description.value);
	doc_date=urlencode(document.add_doc.doc_date.value);
	ajaxManager('load_page','$pagename?mode=transmittal_attachments&transmittal_id=$transmittal_info->transmittal_id&add_attachment=true&quantity=' + quantity + '&description=' + description + '&doc_date=' + doc_date,'attached_docs_list');
	document.add_doc.quantity.value='';
	document.add_doc.description.value='';
	document.add_doc.doc_date.value='';
	document.add_doc.quantity.focus();
	}
function add_recipient() {
	r_obj=document.getElementById('hidden_contactsbox_recipient_id');
	ajaxManager('load_page','$pagename?mode=more_recipients&transmittal_id=$transmittal_info->transmittal_id&add_recipient_id=' + r_obj.value,'more_recipients');
	}
function delete_recipient(recipient_id) {
	ajaxManager('load_page','$pagename?mode=more_recipients&transmittal_id=$transmittal_info->transmittal_id&delete_recipient_id=' + recipient_id,'more_recipients');
	}

ajaxManager('load_page','$pagename?mode=transmittal_attachments&transmittal_id=$transmittal_info->transmittal_id','attached_docs_list');
ajaxManager('load_page','$pagename?mode=more_recipients&transmittal_id=$transmittal_info->transmittal_id','more_recipients');
";
if ($focus_add_form=='true') echo "document.add_doc.quantity.focus();";
	

echo"</script>
";
fd_navs_footer();
?>
