<?
$spool_fab_tracking_id=addslashes($spool_fab_tracking_id);
$spool_info=getone("select * from spool_fab_tracking where spool_fab_tracking_id = '$spool_fab_tracking_id'");

echo "<form name=add_weld method=post action=$pagename>
<input type=hidden name=mode value=submit_weld>
<input type=hidden name=spool_fab_tracking_id value=$spool_info->spool_fab_tracking_id>
<table border=0 cellspacing=0 cellpadding=7>

<tr><td colspan=2 align=center>
	<b>Add Weld</b>
</td></tr>

<tr><td>
	Inches:
</td><td>
	<input type=text name=weld_inches>
</td></tr>

<tr><td>
	Count:
</td><td>
	<input type=text name=weld_count>
</td></tr>

<tr><td colspan=2 align=right>
	<input type=submit value=Save>
</td></tr>
</table>

";





?>
