<?
include("../webfile$devel/storage_settings.cfg");


if ($doc_id=="") pdf_generation_error_pdf("ERR(1) - Unable to load document information.");
$doc_id=addslashes($doc_id);
$doc_info=getoneb("select * from documents where doc_id = '$doc_id' and doc_type = 'spooltrack'");
$spool_info=getoneb("select * from spool_fab_tracking where spool_fab_tracking_id = '$doc_info->app_record_id'");
if (!($spool_info)) pdf_generation_error_pdf("ERR(2) - Unable to load spool information.");

$job=getoneb("select * from jobinfo where jobinfo_id = '$doc_info->jobinfo_id'");

$files_res=@mysql_query("select * from webfile_files where file_group_id = '$spool_info->attached_file' and mime_type like '%pdf%'");
$files_count=@mysql_num_rows($files_res);
if ($files_count<1) pdf_generation_error_pdf("ERR(98) - No file");

pdf_mime_header("OIC_$doc_info->app_reference.pdf");
while ($row=@mysql_fetch_object($files_res)) {
	if ($row->file_group_id==0) continue;
	readfile("$storage_root$row->file_path");
	}
?>
