<?
include("../webfile$devel/storage_settings.cfg");


if ($doc_id=="") die("ERR(1)");
$doc_id=addslashes($doc_id);
$doc_info=getoneb("select * from documents where doc_id = '$doc_id' and doc_type = 'spooltrack'");
$spool_info=getoneb("select * from spool_fab_tracking where spool_fab_tracking_id = '$doc_info->app_record_id'");
if (!($spool_info)) die("ERR(2)");

$job=getoneb("select * from jobinfo where jobinfo_id = '$doc_info->jobinfo_id'");
$sequence=ereg_replace("[^0-9]","",$sequence);
if ($sequence=="") die("ERR(3)");
$sequence=addslashes($sequence); // Shouldn't really be needed, should always be the same, but why not..
$seq_pretty=sprintf("%'04d",$sequence);


$files_res=@mysql_query("select * from webfile_files where file_group_id = '$spool_info->attached_file' and mime_type like '%pdf%'");
//tabledump("select * from webfile_files where file_group_id = '$rev->attached_file_group_id' and mime_type like '%pdf%'");
$files_count=@mysql_num_rows($files_res);
if ($files_count<1) die("ERR(98) - No file");

$file_letter="a";
@mkdir("/tmp/front_desk");
@mkdir("/tmp/front_desk/cook_a_batch");
@mkdir("/tmp/front_desk/cook_a_batch/$global_user->login_name");
@mkdir("/tmp/front_desk/cook_a_batch/$global_user->login_name/$job->contract_num");
@chdir("/tmp/front_desk/cook_a_batch/$global_user->login_name/$job->contract_num");

while ($row=@mysql_fetch_object($files_res)) {
	if ($row->file_group_id==0) die("ERR(99) - No File");
	//$gcrfi_info->gcrfi_num=ereg_replace("[ /]","_",$gcrfi_info->gcrfi_num);
	$description=ereg_replace("[ /]","_",$doc_info->description);
	$file_name=$seq_pretty . $file_letter . "-_$job->contract_num_-_spooltrack_-_${description}.pdf";
	copy("$storage_root$row->file_path",$file_name);
	if (!(is_file($file_name))) die("ERR(5)");
	$file_letter++;
	}
echo "OK";
exit;
?>
