<?
require('querylib.inc');

echo "
<b><i>Please select the job to load:</i></b>

<form name=job_selection method=post action=$pagename>
";dropbox("select jobinfo_id as global_jobinfo_id_set, contract_num , ' - ' , job_name from jobinfo where active = 'Y' and spool_fab_tracking = 'Y' order by contract_num","","20","submit()");echo "
<br>
<input type=button value=\"Load\" onclick=submit();>
</form>
";









?>
