<?
require('querylib.inc');

$dyanmic_1=addslashes($dynamic_1);
$dyanmic_2=addslashes($dynamic_2);
$dyanmic_3=addslashes($dynamic_3);
$dyanmic_4=addslashes($dynamic_4);
$dyanmic_5=addslashes($dynamic_5);
$dyanmic_6=addslashes($dynamic_6);
$spool_fab_tracking_id=escapeshellcmd($spool_fab_tracking_id);
$cad_file_name=escapeshellcmd($cad_file_name);
$spool_tag_size=escapeshellcmd($spool_tag_size);
$spool_tag_line_num=escapeshellcmd($spool_tag_line_num);
$spool_tag_piece=escapeshellcmd($spool_tag_piece);
$spool_rev_num=escapeshellcmd($spool_rev_num);
$shop_drawing_ref=escapeshellcmd($shop_drawing_ref);
$drawn_date=vali_date($drawn_date);
$field_review=escapeshellcmd($field_review);
$priority=escapeshellcmd($priority);
$estimated_hours=escapeshellcmd($estimated_hours);
$actual_hours=escapeshellcmd($actual_hours);
$released_to_fab=vali_date($released_to_fab);
$fab_shop_name=escapeshellcmd($fab_shop_name);
$date_needed=vali_date($date_needed);
$date_received_on_site=vali_date($date_received_on_site);
$status=escapeshellcmd($status);
$material_req_num=escapeshellcmd($material_req_num);
$material_ordered=vali_date($material_ordered);
$material_required=vali_date($material_required);
$material_received=vali_date($material_received);
$po_number=escapeshellcmd($po_number);
$location=escapeshellcmd($location);
$weld_count=escapeshellcmd($weld_count);
$weld_diameter_inches=addslashes($weld_diameter_inches);
$weld_linear_inches=addslashes($weld_linear_inches);
$weld_procedure=escapeshellcmd($weld_procedure);
$field_approval=escapeshellcmd($field_approval);
$pm_approval=escapeshellcmd($pm_approval);
$completed=addslashes($completed);
$attached_file=addslashes($attached_file);

if ($global_jobinfo_id=="") {
	echo "Error: Fatal Error on information submission! No associated job data! Your information WAS NOT SAVED!<p> Please contact your system administrator for help.<p>";
	exit;
	}


if ($spool_fab_tracking_id=="") {
	$query="
	insert into spool_fab_tracking (
	jobinfo_id,
	system_id,
	cad_file_name,
	dynamic_1,
	dynamic_2,
	dynamic_3,
	dynamic_4,
	dynamic_5,
	dynamic_6,
	spool_tag_size,
	spool_tag_line_num,
	spool_tag_piece,
	spool_rev_num,
	shop_drawing_ref,
	drawn_date,
	field_review,
	priority,
	estimated_hours,
	actual_hours,
	released_to_fab,
	fab_shop_name,
	date_needed,
	date_received_on_site,
	status,
	material_req_num,
	material_ordered,
	material_required,
	material_received,
	po_number,
	location,
	weld_count,
	weld_diameter_inches,
	weld_linear_inches,
	weld_procedure,
	field_approval,
	pm_approval,
	completed,
	attached_file
) values (
	'$global_jobinfo_id',
	'$current_system_id',
	'$cad_file_name',
	'$dynamic_1',
	'$dynamic_2',
	'$dynamic_3',
	'$dynamic_4',
	'$dynamic_5',
	'$dynamic_6',
	'$spool_tag_size',
	'$spool_tag_line_num',
	'$spool_tag_piece',
	'$spool_rev_num',
	'$shop_drawing_ref',
	'$drawn_date',
	'$field_review',
	'$priority',
	'$estimated_hours',
	'$actual_hours',
	'$released_to_fab',
	'$fab_shop_name',
	'$date_needed',
	'$date_received_on_site',
	'$status',
	'$material_req_num',
	'$material_ordered',
	'$material_required',
	'$material_received',
	'$po_number',
	'$location',
	'$weld_count',
	'$weld_diameter_inches',
	'$weld_linear_inches',
	'$weld_procedure',
	'$field_approval',
	'$pm_approval',
	'$completed',
	'$attached_file'
	) ";
	$new=1;
} else {
	$query="
	update spool_fab_tracking set
	cad_file_name = '$cad_file_name',
	dynamic_1 = '$dynamic_1',
	dynamic_2 = '$dynamic_2',
	dynamic_3 = '$dynamic_3',
	dynamic_4 = '$dynamic_4',
	dynamic_5 = '$dynamic_5',
	dynamic_6 = '$dynamic_6',
	spool_tag_size = '$spool_tag_size',
	spool_tag_line_num = '$spool_tag_line_num',
	spool_tag_piece = '$spool_tag_piece',
	spool_rev_num = '$spool_rev_num',
	shop_drawing_ref = '$shop_drawing_ref',
	drawn_date = '$drawn_date',
	field_review = '$field_review',
	priority = '$priority',
	estimated_hours = '$estimated_hours',
	actual_hours = '$actual_hours',
	released_to_fab = '$released_to_fab',
	fab_shop_name = '$fab_shop_name',
	date_needed = '$date_needed',
	date_received_on_site = '$date_received_on_site',
	status = '$status',
	material_req_num = '$material_req_num',
	material_ordered = '$material_ordered',
	material_required = '$material_required',
	material_received = '$material_received',
	po_number = '$po_number',
	location = '$location',
	weld_count = '$weld_count',
	weld_diameter_inches = '$weld_diameter_inches',
	weld_linear_inches = '$weld_linear_inches',
	weld_procedure = '$weld_procedure',
	field_approval = '$field_approval',
	pm_approval = '$pm_approval',
	completed = '$completed',
	attached_file = '$attached_file'
	where spool_fab_tracking_id = '$spool_fab_tracking_id'
	";
	$new=0;
}

//echo "$query";exit;

$result=@mysql_query($query);

if (!($result)) {
	echo "There was an errror with your query.<hr>
	<h2>Warning, This error may have occurred because you tried to submit
	a duplicate record. Please make sure the record does not already exist
	before reporting a problem!</h2><hr>";
	echo "The flawed query was: <p>$query";
	exit;
	}

if ($spool_fab_tracking_id==""){
	$spool_fab_tracking_id=mysql_insert_id();
	}
if ($saveandcopy=="yes") {
	forward("spool_fab_edit&makecopy=yes&spool_fab_tracking_id=$spool_fab_tracking_id");
	}
if ($justsave=="yes") {
	$addin="";
	if ($add_weld_now!="no") $addin="&add_weld_popup=yes";
	forward("spool_fab_edit&spool_fab_tracking_id=$spool_fab_tracking_id$addin");
	exit;
	}

if ($loopit=="no")
	forward("main");
else
	forward("spool_fab_edit");

?>
