<?

$jobinfo_id=addslashes($jobinfo_id);
$dynamic_field_info=getone("select * from spool_fab_tag_defs where jobinfo_id = '$jobinfo_id'");

echo "<b>Select Sort Field:</b><hr>$addtoit
";

if ($dynamic_field_info->dynamic_1_active=='Y') echo "<a href=javascript:spool_tag_sort('dynamic_1');>$dynamic_field_info->dynamic_1_name</a></br>";
if ($dynamic_field_info->dynamic_2_active=='Y') echo "<a href=javascript:spool_tag_sort('dynamic_2');>$dynamic_field_info->dynamic_2_name</a></br>";
if ($dynamic_field_info->dynamic_3_active=='Y') echo "<a href=javascript:spool_tag_sort('dynamic_3');>$dynamic_field_info->dynamic_3_name</a></br>";
if ($dynamic_field_info->dynamic_4_active=='Y') echo "<a href=javascript:spool_tag_sort('dynamic_4');>$dynamic_field_info->dynamic_4_name</a></br>";
if ($dynamic_field_info->dynamic_5_active=='Y') echo "<a href=javascript:spool_tag_sort('dynamic_5');>$dynamic_field_info->dynamic_5_name</a></br>";
if ($dynamic_field_info->dynamic_6_active=='Y') echo "<a href=javascript:spool_tag_sort('dynamic_6');>$dynamic_field_info->dynamic_6_name</a></br>";

echo "
<script>

function spool_tag_sort (field) {
	opener.document.location=\"$pagename?orderbyfield_set=\" + field;
	self.close();
}
function spool_tag_size () {
	opener.document.location=\"$pagename?orderbyfield_set=spool_tag_size\";
	self.close();
}
function system_id () {
	opener.document.location=\"$pagename?orderbyfield_set=system_id\";
	self.close();
}
function spool_tag_line_num () {
	opener.document.location=\"$pagename?orderbyfield_set=spool_tag_line_num\";
	self.close();
}
function spool_tag_piece () {
	opener.document.location=\"$pagename?orderbyfield_set=spool_tag_piece\";
	self.close();
}
</script>";

?>
