<?
require('querylib.inc');
$system_name=escapeshellcmd($system_name);
$system_abbreviation=escapeshellcmd($system_abbreviation);
$attached_file=addslashes($attached_file);

if(!($adminuser)) {
	echo "Hey! You're not an administrative user for this database! What
		the hell do you think you're doing?!?!?! Go away, or we'll send
		Roseanne Barr in after you!<p>";
		exit;
	}


if ($spool_fab_systems_id=="") {
	$spool_fab_systems_id=escapeshellcmd($spool_fab_systems_id);
	
	$query="insert into spool_fab_systems (
	jobinfo_id,system_name,system_abbreviation,attached_file 
	) values (
	'$global_jobinfo_id','$system_name','$system_abbreviation','$attached_file' )";
	} else {
	$query="update spool_fab_systems set
	system_name = '$system_name',
	system_abbreviation = '$system_abbreviation',
	attached_file = '$attached_file'
	where spool_fab_systems_id = '$spool_fab_systems_id'";
	}

$result=@mysql_query($query);

if (!($result)) {
	echo "error: query failed! The failing query is listed below... Please contact
			your system administrator for assistance.<hr>";
	exit;
	}

if ($spool_fab_systems_id=="") $spool_fab_systems_id=@mysql_insert_id();

if ($justsave=='yes') forward("systems_maint_edit&spool_fab_systems_id=$spool_fab_systems_id");
else forward('systems_maint');

?>
