<?

if (!($issue_res_admin))
	die ("Fatal Error: Invalid Permissions. You shouldn't be here, so go away now or we'll be sending the cops soon!");

if ( ($global_jobinfo_id=="") || ($issue_res_contacts_id=="") ) 
	die ("Fatal Error: Invalid information supplied, can not continue. Please contact your system administrator for assistence.");

$issue_res_contacts_id=escapeshellcmd($issue_res_contacts_id);

$check_access_query="select * from access where application_name = '$application_name' and contacts_id = '$issue_res_contacts_id' and rightsmode = 'grant' limit 1";
if (!(getoneb($check_access_query))) {
	@mysql_query("insert into access set application_name = '$application_name',contacts_id = '$issue_res_contacts_id',rightsmode = 'grant',type = 'read_only'");
	security_log_email(
		$issue_res_contacts_id,
		0,
		0,
		"added: grant read_only",
		"$application_name");
	}

$query="insert into issue_res_users (jobinfo_id,contacts_id) values ('$global_jobinfo_id','$issue_res_contacts_id')";
	security_log_email(
		$issue_res_contacts_id,
		0,
		$global_jobinfo_id,
		"added to job",
		"$application_name");

$res=@mysql_query($query);

if (!($res))
	die ("Fatal Error: Invalid information supplied, can not continue. Please contact your system administrator for assistence.");


forward('admin_users');

?>
