<?
echo "<body bgcolor=#ffffff>";
if (!($issue_res_admin)) {
	echo "ERROR: Security Violation! The authorities are being notified!";
	exit;
	}



$query="select * from jobinfo where issue_res_tracking = 'Y' order by job_name";
//tabledump($query);

echo "
<a href=$pagename?mode=job_selection_win><font color=blue>Return to Job Selection</font></a><hr>
<h3>";

$res=@mysql_query($query);
while($row=@mysql_fetch_object($res)) {
	echo "<a href=javascript:deactivate($row->jobinfo_id);>Deactivate</a> $row->job_name<p>";
	}

echo "</h3>

<script>

function deactivate(jobinfo_id) {
	if (confirm('Deactivate Job?'))
		document.location='$pagename?mode=admin_job_deactivate_submit&jobinfo_id=' + jobinfo_id
	}



</script>




";

?>
