<?
echo "<body bgcolor=#ffffff>";
if (!($issue_res_admin)) {
	echo "ERROR: Security Violation! The authorities are being notified!";
	exit;
	}



$query="select * from jobinfo where issue_res_tracking != 'Y' and active = 'Y' order by contract_num";

echo "
<a href=$pagename?mode=job_selection_win><font color=blue>Return to Job Selection</font></a><hr>
";

$res=@mysql_query($query);
while($row=@mysql_fetch_object($res)) {
	echo "<a href=javascript:activate($row->jobinfo_id);>Activate</a> $row->contract_num - $row->job_name<p>";
	}

echo "

<script>

function activate(jobinfo_id) {
	if (confirm('Enable issue tracking for job?'))
		document.location='$pagename?mode=admin_job_activate_submit&jobinfo_id=' + jobinfo_id
	}



</script>




";

?>
