<?
if (!($issue_res_admin))
	die("Error: You shouldn't be here, so go away now!");

$issue_res_edit_application_id=escapeshellcmd($issue_res_edit_application_id);
$query="select * from issue_res_category where issue_res_application_id = '$issue_res_edit_application_id'";
$res=@mysql_query($query);
$rescount=@mysql_num_rows($res);

if ($rescount!="0")
	die("Error: You can't delete this application, it still has stuff in it!!! Please contact your system administrator for help.<p><a href=$pagename?mode=app_edit_list><font color=blue>Continue</font></a><p>");

$q="delete from issue_res_application where issue_res_application_id = '$issue_res_edit_application_id'";
//echo "$q";exit;

$r=@mysql_query($q);

if (!($r))
	die("Error: Error updating database. Please contact your system administrator for help!!<hr>$q<p>");

forward('app_edit_list');
?>
