<?
echo "</center><br>";
if ($issue_res_admin) {
	include("header_category_setup.phtml");
	}
echo "
<script>
function cat_set(issue_res_category_id){
opener.document.location='$pagename?mode=main&issue_res_category_id_set=' + issue_res_category_id ;

self.close();
}


</script>
	<font size=+1><b>Please select which category:</b></font><p>
	<a href=$pagename?mode=main&global_jobinfo_id_set=$global_jobinfo_id><img border=0 src=up_arrow.png title=\"Up One Level\"></a><br>";
	$issue_res_catlist_query="select * from issue_res_category where issue_res_application_id = '$issue_res_application_id' order by category_name";
	//tabledump("select * from issue_res_category where issue_res_application_id = '$issue_res_application_id' order by category_name");
	$issue_res_catlist_res=@mysql_query($issue_res_catlist_query);
	while($catlist_entry=@mysql_fetch_object($issue_res_catlist_res)) {
		$issue_list_info=getoneb("select sum(1) as count from issue_res_issues where issue_res_category_id = '$catlist_entry->issue_res_category_id'");
		$issue_add_text="";
		if ($issue_list_info) $issue_add_text="($issue_list_info->count)";
		
		if ($mode!="cat_selection_win")
			echo "<ul><a href='$pagename?mode=main&issue_res_category_id_set=$catlist_entry->issue_res_category_id'>";
		else
			echo "<ul><a href=javascript:cat_set('$catlist_entry->issue_res_category_id');>";
		
		echo "<font color=blue size=+1>
		$catlist_entry->category_name $issue_add_text
		</font>
		</a>
		</ul>";
		}

require("footer.phtml");
	//<a href=$pagename?mode=main&global_jobinfo_id_set=$global_jobinfo_id&global_jobinfo_id=$global_jobinfo_id><img border=0 src=up_arrow.png title=\"Up One Level\"></a><br>";
?>
