<?
$f="black";
$tree_seperator="<font size=+2><b>&nbsp;:::&nbsp;</b></font>";

if ("$opts_set" == "") {
	session_register("opts_set");
	session_register('h_complete');
	session_register('h_new');
	session_register('h_approved');
	$opts_set="yes";
	$h_complete="checked";
	$h_new="checked";
	$h_approved="checked";
	}

if ($issue_res_header_period=="") {
	session_register("issue_res_header_period");
	$issue_res_header_period="0";
	}
if ($header_period_set!="") {
	$issue_res_header_period=escapeshellcmd($header_period_set);
	}
                    

//<a href=$pagename?mode=job_selection_win><font color=$f>Job Selection</font></a>

echo "<body bgcolor=#ffffff><center>
";

if (!(($global_jobinfo)&& $global_jobinfo->issue_res_tracking=="Y")) {
	include("job_selection_win.phtml");
	fd_navs_footer();
	exit;
	} else {
	//echo "<a href=$pagename?mode=main&global_jobinfo_id_set=$global_jobinfo_id&issue_res_application_id_set=0><font color=$f>$global_jobinfo->job_name ($global_jobinfo->contract_num)</font></a>";
	echo "<a href=$pagename?mode=main&global_jobinfo_id_set=$global_jobinfo_id&issue_res_application_id_set=0><font color=$f>Issue Log List</font></a>";
	}

if (!($issue_res_application_info)){
	include("app_selection_win.phtml");
	fd_navs_footer();
	exit;
	} else {
	echo "$tree_seperator<a href=$pagename?mode=main&issue_res_application_id_set=$issue_res_application_id><font color=$f>$issue_res_application_info->issue_res_application_name</font></a>";
	}

if (!($issue_res_category_info)){
	//echo "<hr>went this way<hr>";
	include("cat_selection_win.phtml");
	fd_navs_footer();
	exit;
	} else {
	echo "$tree_seperator<a href=$pagename?mode=main&issue_res_category_id_set=$issue_res_category_id><font color=$f>$issue_res_category_info->category_name</font></a>";
	if ($issue_res_admin) echo " ($issue_res_category_id)";
 	}

echo "</center><hr>";

if ("$submode" == "changeopts") {

	if ($h_complete_new=="checked") {
		$h_complete=$h_complete_new;
		} else {
		$h_complete="";
		}

	if ($h_new_new=="checked") {
		$h_new=$h_new_new;
		} else {
		$h_new="";
		}

	if ($h_approved_new=="checked") {
		$h_approved=$h_approved_new;
		} else {
		$h_approved="";
		}
	}

echo "
<html>
<head>
<title>$dbdescription</title>
</head>
<body bgcolor=#ffffff text=#333333>

<a href=$pagename?mode=main&&issue_res_application_id_set=$issue_res_application_id><img border=0 src=up_arrow.png title=\"Up One Level\"></a>
<table border=0 cellpadding=7 width=100%>
<tr><td>
	<a href=javascript:download_csv();>Download&nbsp;CSV&nbsp;File</a>
</td>";

if ($issue_res_admin)
	echo "<td><a href=$pagename?mode=admin_category><font color=blue>Set&nbsp;Permissions</font></a></td>";

echo"

<td width=100% align=right>
<script>
function set_options () {
	if (document.set_opts.h_new_new.checked==1) 
		document.set_opts.h_new_new.value='checked';
	if (document.set_opts.h_complete_new.checked==1) 
		document.set_opts.h_complete_new.value='checked';
	if (document.set_opts.h_approved_new.checked==1)
		document.set_opts.h_approved_new.value='checked';

if(confirm(\"Reload new view?\")){
	document.set_opts.submit();
	}
}

function download_csv() {
	open('$pagename/download.csv?blah=blah&mode=csv_download','csv_file');
	}

</script>


<form method=get action=$pagename name=set_opts>
<input type=hidden name=mode value=main>
<input type=hidden name=submode value=changeopts>
<b>Showing:&nbsp;&nbsp;&nbsp;&nbsp;</b>

Open  <input type=checkbox name=h_new_new $h_new onclick=set_options();>
Complete <input type=checkbox name=h_complete_new $h_complete onclick=set_options();>
Approved <input type=checkbox name=h_approved_new $h_approved onclick=set_options();>

</form>
</td>

</tr></table>
";

?>
