<?
if ("$opts_set" == "") {
	session_register("opts_set");
	session_register('h_complete');
	session_register('h_new');
	session_register('h_approved');
	$opts_set="yes";
	$h_complete="checked";
	$h_new="checked";
	$h_approved="";
	}

echo "<head><title>$dbdescription</title></head><body bgcolor=#ffffff><center>

$global_jobinfo->job_name ($global_jobinfo->contract_num):
$issue_res_application_info->issue_res_application_name:
$issue_res_category_info->category_name
";

echo "</center><hr>";

?>
