<?
$tablewidth="4";
$hotlist_query="select * from issue_res_notify,issue_res_issues where issue_res_notify.problem_id = issue_res_issues.problem_id and contacts_id = '$global_user_id' and due_date != '0000-00-00' and completed = '0000-00-00' order by due_date limit 20";

$hotlist_result=@mysql_query($hotlist_query);
$hotlist_count=@mysql_num_rows($hotlist_result);

if ($hotlist_count > 0) {
	echo "<table border=1 cellpadding=4><tr><td colspan=$tablewidth><center><h2><i>Hottest Items</i></h2></center></td></tr>";
	while($hotone=@mysql_fetch_object($hotlist_result)) {
		$problem_info=problem_information($hotone->problem_id);
		$owner_info=getoneb("select * from contacts where contacts_id = '$hotone->c_parent'");
		$hotone->due_date=invali_date($hotone->due_date);
		echo "<tr><td colspan=$tablewidth><center><b>ITEM IN: </b><i>$problem_info->textpath</i></center></td></tr>";
		echo "
		<tr><td>
			<a href=$problem_info->problem_url>$problem_info->problem_id</a>
		</td><td bgcolor=$tableheadbgcolor>
			<table border=1 width=100%>
				<tr bgcolor=$tableheadbgcolor><td width=50%>Summary</td>
				<td width=50%>Proposed Solution</td></tr>
			<tr bgcolor=white><td>
				$hotone->summary&nbsp;
			</td><td>
				$hotone->solution&nbsp;
			</td></tr>
			</table>
		</td><td>
			$hotone->due_date
		</td><td>
			Initiated By: $owner_info->last_name,&nbsp;$owner_info->first_name
		</td></tr>";
		
		}
	echo "</table>";
	}
?>
