<?
if ($issue_res_category_id) testrights("read_only");
include('header.phtml');
$query="
	select 
	problem_id,
	conflict_id,
	login_name,
	bld_floor,
	grid,
	summary,
	solution,
	actual_solution,
	responsibility,
	completed_by,
	due_date,
	last_action,
	completed,
	approved,
	issue_child,
	attached_files
	
	from issue_res_issues,contacts
	
	where issue_res_category_id = '$issue_res_category_id'
	and c_parent = contacts_id
	and issue_parent = 0
	";

//
//	Filter Builder adds to and rewrites the "query" veriable
//	to give the desired results based on what the users have
//	clicked on to sort and filter things...
//
require('filter_builder.phtml');


//
//	Tableprint takes the "query" variable, and prints out the
//	table of issues that results from that query. Sub issue trees
//	are followded as the parent issues are run into, during
//	processing of each record (from inside of tableprint)

require("tableprint-$issue_res_category_info->category_template_id.phtml");
require("footer.phtml");
?>
