<?
//require("querylib.inc");
require("header4.phtml");
testrights("read_only");

$tsize=5;
$tableheadtext="#ffffff";

if (!($tableprint_subissues)){
	$tableprint_subissue=1;
	function subissue_show($issue_id,$rev) {
		global $normal_cell_color,$overdue_cell_color,$complete_cell_color,$approved_cell_color,$parent_cell_color;
		if ($issue_id <= 0) return 0;
		$issue_id=escapeshellcmd($issue_id);	
		$problem=getone("select * from issue_res_issues,contacts where problem_id = '$issue_id' and contacts_id = c_parent");
		$rev++;
		$this_second=mktime();
	
		$problem->due_date=invali_date($problem->due_date);
		$cellbgcolor=$normal_cell_color;
		
		if($problem->completed!="0000-00-00")
			$cellbgcolor=$complete_cell_color;;
			
		if($problem->approved!="")
			$cellbgcolor=$approved_cell_color;
			
		$problem->completed=invali_date($problem->completed);
		
		if ($problem->due_date != "") {
			$due_year=ereg_replace("^.*-","",$problem->due_date);	
			$due_month=ereg_replace("-.*$","",$problem->due_date);	
			$due_day_tmp=ereg_replace("^[^-]*-","",$problem->due_date);	
			$due_day=ereg_replace("-[^-]*$","",$due_day_tmp);	
			$due_second=mktime(0,0,0,$due_month,$due_day,$due_year);
			if (($due_second < $this_second)&& ($problem->completed==""))
				$cellbgcolor=$overdue_cell_color;
			} else {
			$due_second="";
			}
		if ($problem->issue_child>0)
			$cellbgcolor=$parent_cell_color;
		$problem->summary=ereg_replace("","<p>",$problem->summary);
		$problem->solution=ereg_replace("","<p>",$problem->solution);
		$problem->actual_solution=ereg_replace("","<p>",$problem->actual_solution);
		echo "
		<tr bgcolor=$cellbgcolor><td valign=top>	
			$problem->conflict_id ($rev)</font> &nbsp;
		</td><td>
			<center>-</center>
		</td><td valign=top>
			$problem->bld_floor &nbsp;
		</td><td valign=top>
			$problem->grid &nbsp;
		</td><td valign=top>
			$problem->summary &nbsp;
		</td><td valign=top>
				$problem->solution &nbsp;
		</td><td valign=top>
			$problem->actual_solution &nbsp;
		</td><td valign=top>
			$problem->responsibility &nbsp;
		</td><td valign=top>
			$problem->completed_by &nbsp;
		</td><td valign=top>
			$problem->due_date &nbsp;
		</td><td valign=top>
			$problem->completed &nbsp;
		</td><td valign=top>
			$problem->login_name
		</td></tr>
		";
		subissue_show($problem->issue_child,$rev);
	}

}






$query="select 

	problem_id,
	conflict_id,
	login_name,
	contacts_id,
	bld_floor,
	grid,
	summary,
	solution,
	actual_solution,
	responsibility,
	completed_by,
	due_date,
	completed,
	approved,
	issue_child
	
	from issue_res_issues,contacts
	
	where issue_res_category_id = '$issue_res_category_id'
	and c_parent = contacts_id
	and issue_parent = 0
	";

if ($h_new != "checked")
	$query="$query and completed != '0000-00-00' and approved != '0000-00-00'";

if ($h_complete != "checked")
	$query="$query and ((completed != '0000-00-00' and  approved != '') or ( completed = '0000-00-00'))";

if ($h_approved != "checked")
	$query="$query and approved = ''";



$additional=" and ";

if ( $conflict_id_filter != "" ) {
	$query=$query . $additional . "conflict_id like '%$conflict_id_filter%'";
	$b_conflict_id="<font color=yellow>";
	$nb_conflict_id="</font>";
	$additional=" and ";
	}
	
if ( $bld_floor_filter != "" ) {
	$query=$query . $additional . "bld_floor like '%$bld_floor_filter%'";
	$b_bld_floor="<font color=yellow>";
	$nb_bld_floor="</font>";
	$additional=" and ";
	}

if ( $grid_filter != "" ) {
	$query=$query . $additional . "grid like '%$grid_filter%'";
	$b_grid="<font color=yellow>";
	$nb_grid="</font>";
	$additional=" and ";
	}

if ( $summary_filter != "" ) {
	$query=$query . $additional . "summary like '%$summary_filter%'";
	$b_summary="<font color=yellow>";
	$nb_summary="</font>";
	$additional=" and ";
	}
	
if ( $solution_filter != "" ) {
	$query=$query . $additional . "solution like '%$solution_filter%'";
	$b_solution="<font color=yellow>";
	$nb_solution="</font>";
	$additional=" and ";
	}
	
if ( $actual_solution_filter != "" ) {
	$query=$query . $additional . "actual_solution like '%$actual_solution_filter%'";
	$b_actual_solution="<font color=yellow>";
	$nb_actual_solution="</font>";
	$additional=" and ";
	}
	
if ( $responsibility_filter != "" ) {
	$query=$query . $additional . "responsibility like '%$responsibility_filter%'";
	$b_responsibility="<font color=yellow>";
	$nb_responsibility="</font>";
	$additional=" and ";
	}
	
if ( $completed_by_filter != "" ) {
	$query=$query . $additional . "completed_by like '%$completed_by_filter%'";
	$b_completed_by="<font color=yellow>";
	$nb_completed_by="</font>";
	$additional=" and ";
	}
	
if ( $due_date_filter != "" ) {
	$due_date_filter2=vali_date($due_date_filter);
	$query=$query . $additional . "due_date = '$due_date_filter2'";
	$b_due_date="<font color=yellow>";
	$nb_due_date="</font>";
	$additional=" and ";
	}
	
if ( $completed_filter != "" ) {
	$completed_filter2=vali_date($completed_filter);
	$query=$query . $additional . "completed = '$completed_filter2'";
	$b_completed="<font color=yellow>";
	$nb_completed="</font>";
	$additional=" and ";
	}
	
if ( $approved_filter != "" ) {
	$query=$query . $additional . "approved = '$approved_filter'";
	$b_approved="<font color=yellow>";
	$nb_approved="</font>";
	$additional=" and ";
	}
	
if ( $login_name_filter != "" ) {
	$query=$query . $additional . "login_name like '%$login_name_filter%'";
	$b_approved="<font color=yellow>";
	$nb_approved="</font>";
	$additional=" and ";
	}
	
if ( $sort_order_filter != "" ) {
	$query=$query . " order by $sort_order_filter ";
	} else { 
	$query=$query . " order by conflict_id ";
	}
	
$ndresult=mysql_query("select completed from issue_res_issues where issue_res_category_id = '$issue_res_category_id' and completed = ''");
$notdone=mysql_num_rows($ndresult);
$naresult=mysql_query("select completed from issue_res_issues where issue_res_category_id = '$issue_res_category_id' and approved = ''");
$notapproved=mysql_num_rows($naresult);
$tr_result=mysql_query("select problem_id from issue_res_issues where issue_res_category_id = '$issue_res_category_id'");
$total_records=mysql_num_rows($tr_result);

//echo "$query<p>";
$result=mysql_query($query);

$total_showing=mysql_num_rows($result);


function printhdr() {
	global $category_template_text;
	echo "
	<tr><td valign=top align=center>
		$category_template_text->conflict_id
	</td><td valign=top align=center>
		Status
	</td><td valign=top align=center>
		$category_template_text->bld_floor
	</td><td valign=top align=center>
		$category_template_text->grid_short
	</td><td valign=top align=center>
		$category_template_text->summary
	</td><td valign=top align=center>
		$category_template_text->solution
	</td><td valign=top align=center>
		$category_template_text->actual_solution
	</td><td valign=top align=center>
		$category_template_text->responsibility
	</td><td valign=top align=center>
		$category_template_text->completed_by
	</td><td valign=top align=center>
		$category_template_text->due_date
	</td><td valign=top align=center>
		$category_template_text->completed
	</td><td valign=top align=center>
		Initiated By
	</td></tr>
	";
}

echo"

<table border=0 width=100% cellpadding=1 cellspacing=0>
<tr bgcolor=#eeeeee>
</td><td align=center>
	Not Complete:
</td><td align=center>
	$notdone
</td><td align=center>
	Not Approved:
</td><td align=center>
	$notapproved
</td><td align=center>
	Showing:
</td><td align=center>
	$total_showing / $total_records
</td></tr>
</table>
<p>
<table width=100% border=1>
";

printhdr();

$hdrcount=1;
while ($problem=mysql_fetch_object($result)) {
	$this_second=mktime();

	$problem->due_date=invali_date($problem->due_date);
	$cellbgcolor="#ffffff";
	$itemstatus="";
	
	if($problem->completed!="0000-00-00")
		$itemstatus="Completed";
		
	if($problem->approved!="")
		$itemstatus="Approved";
		
	$problem->completed=invali_date($problem->completed);

	if ($problem->due_date != "") {
		$due_year=ereg_replace("^.*-","",$problem->due_date);	
		$due_month=ereg_replace("-.*$","",$problem->due_date);	
		$due_day_tmp=ereg_replace("^[^-]*-","",$problem->due_date);	
		$due_day=ereg_replace("-[^-]*$","",$due_day_tmp);	
		$due_second=mktime(0,0,0,$due_month,$due_day,$due_year);
		if (($due_second < $this_second)&& ($problem->completed==""))
			$itemstatus="Overdue";
		} else {
		$due_second="";
		}

	echo "
	<tr bgcolor=$cellbgcolor><td valign=top align=center>	
		$problem->conflict_id &nbsp;
	</td><td valign=top>
		$itemstatus&nbsp;
	</td><td valign=top>
		$problem->bld_floor &nbsp;
	</td><td valign=top>
		$problem->grid &nbsp;
	</td><td valign=top>
		$problem->summary &nbsp;
	</td><td valign=top>
		$problem->solution &nbsp;
	</td><td valign=top>
		$problem->actual_solution &nbsp;
	</td><td valign=top>
		$problem->responsibility &nbsp;
	</td><td valign=top>
		$problem->completed_by &nbsp;
	</td><td valign=top>
		$problem->due_date &nbsp;
	</td><td valign=top>
		$problem->completed &nbsp;
	</td><td valign=top>
		$problem->login_name &nbsp;
	</td></tr>
	";
	subissue_show($problem->issue_child,"a");
	
	if ($hdrcount == $issue_res_header_period) {
		$hdrcount=0;
		printhdr();
		}
	$hdrcount++;
	}
echo "
</table>
</body>
<script>
print();
</script>
";

?>
