<?
//require('querylib.inc');

if ($problem_id=="") {
	$problem_info=getone("select * from issue_res_issues where issue_res_category_id = '$issue_res_category_id' order by conflict_id desc limit 1");
	$problem_id=$problem_info->problem_id;
	}

$problem_id=escapeshellcmd($problem_id);

$current_problem=getone("select * from issue_res_issues where problem_id = '$problem_id'");

$query="select * from issue_res_issues where conflict_id > '$current_problem->conflict_id' and issue_res_category_id = '$issue_res_category_id' order by conflict_id asc limit 1";
//tabledump($query);exit;
$result=getoneb($query);

if ($result) $problem_id=$result->problem_id;
else $problem_id="";

include("problem_edit.phtml");

?>




