<?
//require('querylib.inc');

$result=getoneb("select * from issue_res_issues where conflict_id = '$conflict_id' and issue_res_category_id = '$issue_res_category_id'");

if ($result) {
	$problem_id=$result->problem_id;
	include("problem_edit.phtml");
	} else {
	include("header2.phtml");
	echo "Error: Record not unique or not found!<p>
	<form><input type=button value='<--Back--' onclick=history.go(-1);></form>";
	}


?>




