<?
//$folder_name=addslashes($folder_name);
$template_id=addslashes($template_id);
$folder_parent=addslashes($folder_parent);

$template_info=getoneb("select * from file_cabinet_templates where template_id = '$template_id'");
//die("select * from file_cabinet_templates where template_id = '$template_id'");
if (!($template_info)) die("Invalid template information");
$parent_info=getoneb("select * from file_cabinet_tree where tree_id = '$folder_parent'");


$query="
insert into file_cabinet_tree set 
jobinfo_id = '$parent_info->jobinfo_id',
parent_id = '$parent_info->tree_id',
template_id = '$template_info->template_id',
sort_priority = '$template_info->sort_priority',
folder_name = '$template_info->folder_name',
folder_creator = '$global_user_id',
folder_description = '$template_info->folder_description',
free_for_all = '$template_info->free_for_all',
correspondence_children = '$template_info->for_correspondence'
";

$exists=getoneb("select * from file_cabinet_tree where template_id = '$template_info->template_id' and jobinfo = '$praent_info->jobinfo_id' limit 1");
if (!($exists)) {
	$res=@mysql_query($query);
	if (!($res)) die("Query error. Please contact your system administrator!<hr>$query");
	}


if ($parent_info->correspondence_children=='Y') {
	$insert_id=@mysql_insert_id();
	$query_in="
	insert into file_cabinet_tree set 
	jobinfo_id = '$parent_info->jobinfo_id',
	parent_id = '$insert_id',
	template_id = '$template_info->template_id',
	sort_priority = '$template_info->sort_priority',
	folder_name = 'In',
	folder_creator = '$global_user_id',
	folder_description = '$template_info->folder_description - In',
	correspondence_children = 'N'";
	
	$query_out="
	insert into file_cabinet_tree set 
	jobinfo_id = '$parent_info->jobinfo_id',
	parent_id = '$insert_id',
	template_id = '$template_info->template_id',
	sort_priority = '$template_info->sort_priority',
	folder_name = 'Out',
	folder_creator = '$global_user_id',
	folder_description = '$template_info->folder_description - Out',
	correspondence_children = 'N'";
	@mysql_query($query_in);
	@mysql_query($query_out);
	}
forward("main&current_folder=$parent_info->tree_id");
?>
