<?
if ($template_id!="") {
	$template_id=addslashes($template_id);
	$query_start="update";
	$query_end="where template_id = '$template_id'";
	} else {
	$query_start="insert into";
	$query_end="";
	}
	
$folder_parent=addslashes($folder_parent);
$sort_priority=addslashes($sort_priority);
$folder_name=addslashes($folder_name);
$folder_description=addslashes($folder_description);
$team_folders=checkfix($team_folders);
$for_correspondence=checkfix($for_correspondence);
$free_for_all=checkfix($free_for_all);
$active=checkfix($active);
$keywords=addslashes($keywords);

$query_middle="
folder_parent = '$folder_parent',
sort_priority = '$sort_priority',
folder_name = '$folder_name',
keywords = '$keywords',
folder_description = '$folder_description',
for_correspondence = '$for_correspondence',
free_for_all = '$free_for_all',
team_folders = '$team_folders',
active = '$active'
";
$full_query=$query_start . " file_cabinet_templates set " . $query_middle . $query_end;
@mysql_query($full_query);

if ($template_id!="") {
	@mysql_query("update file_cabinet_tree set free_for_all = '$free_for_all', correspondence_children = '$for_correspondence' where template_id = '$template_id'");
	}


forward("admin_template_manage&current_folder=$folder_parent");
?>
