<?
if(!($adminuser)) die_security();
require("header.phtml");
fd_navs_header();


if ($template_id!="") {
	$template_id=addslashes($template_id);
	$template_info=getoneb("select * from file_cabinet_templates where template_id = '$template_id'");
	} else {
	if ($folder_parent=="") die("Application error: Could not ID parent!");
	$template_info->folder_parent=addslashes($folder_parent);
	$template_info->active='Y';
	$template_info->team_folders='N';
	}
$template_info->active=checkbreak($template_info->active);
$template_info->team_folders=checkbreak($template_info->team_folders);
$template_info->for_correspondence=checkbreak($template_info->for_correspondence);
$template_info->free_for_all=checkbreak($template_info->free_for_all);

echo "
<form name=admin_template_edit method=post action=$pagename>
<input type=hidden name=mode value=admin_template_submit>
<input type=hidden name=template_id value=\"$template_info->template_id\">
<input type=hidden name=folder_parent value=\"$template_info->folder_parent\">
<table border=0 cellspacing=0 cellpadding=4>
<tr><td>
	Name
</td><td>
	<input onchange=\"dupe_if_blank()\" type=text name=folder_name value=\"$template_info->folder_name\">
</td></tr>

<tr><td>
	Description
</td><td>
	<input type=text name=folder_description value=\"$template_info->folder_description\">
</td></tr>

<tr><td>
	Keywords
</td><td>
	<input type=text name=keywords value=\"$template_info->keywords\">&nbsp;<i>(must include folder name)</i>
</td></tr>

<tr><td>
	Sort Priority
</td><td>
	<input type=text size=5 name=sort_priority value=\"$template_info->sort_priority\">
</td></tr>

<tr><td>
	Allow Team Folders
</td><td>
	<input type=checkbox name=team_folders $template_info->team_folders>
</td></tr>

<tr><td>
	For correspondence
</td><td>
	<input type=checkbox name=for_correspondence $template_info->for_correspondence>
</td></tr>

<tr><td>
	Free for all folder
</td><td>
	<input type=checkbox name=free_for_all $template_info->free_for_all>
</td></tr>

<tr><td>
	Active
</td><td>
	<input type=checkbox name=active $template_info->active>
</td></tr>

<tr><td colspan=2 align=right>
	<input type=button onclick=\"confirm_add()\" value=\"Save\">
</td></tr>
</form>
</table>
<script>
function confirm_add() {
	if (confirm('Are you sure you want to modify this record? This will affect all new jobs?'))
		document.admin_template_edit.submit();
	}

function dupe_if_blank() {
	nameobj=document.admin_template_edit.folder_name;
	kwobj=document.admin_template_edit.keywords;
	if (kwobj.value=='') kwobj.value=nameobj.value;
	}
document.admin_template_edit.folder_name.focus();
</script>

";







fd_navs_footer();
?>
