<?
if(!($adminuser)) die_security();
require("header.phtml");
fd_navs_header();
$template_root_info=getone("select * from file_cabinet_templates where template_id = '$template_root'");
if ($current_folder=="") $current_folder=$template_root_info->template_id;
$current_folder_info=getoneb("select * from file_cabinet_templates where template_id = '$current_folder'");

$folder_info=$current_folder_info;
$count=0;

$folder_path='/';

while (($folder_info)&&($folder_info->template_id!=$folder_info->folder_parent)) {
	$count++;
	$folder_path='/' . "<a href=$pagename?mode=$mode&current_folder=$folder_info->template_id><font color=blue>$folder_info->folder_name</font></a>" . $folder_path;
	$folder_info=getoneb("select * from file_cabinet_templates where template_id = '$folder_info->folder_parent'");
	}

if ($cabinet_warning=="") {
	echo "<script>alert('Warning, this template is for all jobs, not just this one, and many changes can not be undone!');</script>";
	session_register('cabinet_warning');
	$cabinet_warning="warned";
	}

$layer_text=$flevels[$count];
echo "
<a href=$pagename?mode=main><font color=blue>Main Menu</font></a><br>
<font size=+2>File Cabinet Template Definition</font><br>($layer_text)
<p>
";
$res=@mysql_query("select * from file_cabinet_templates where folder_parent = '$current_folder' and template_id != folder_parent order by sort_priority, folder_name");

echo "<table border=0 cellspacing=0 cellpadding=0>
<tr><td colspan=2>$folder_path</td></tr>
<tr><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>";

if ($current_folder_info->folder_parent!=$current_folder_info->template_id) echo "<a href=$pagename?mode=$mode&current_folder=$current_folder_info->folder_parent><font color=blue>..</font></a><br>";


while ($row=@mysql_fetch_object($res)) {
	echo "<table border=0 cellspacing=0 cellpadding=2 width=100%<tr><td><a href=$pagename?mode=$mode&current_folder=$row->template_id><font size=+1 color=blue>$row->folder_name</font></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td align=right><a href=$pagename?mode=admin_template_edit&template_id=$row->template_id><font color=blue size=-1><i>Edit</i></font></td></tr></table>";
	}

echo "
<a href=$pagename?mode=admin_template_edit&folder_parent=$current_folder_info->template_id><font color=red>New folder</font></a>
</td></tr></table>";

fd_navs_footer();
?>
