<?

if ($tree_id!="") {
	$tree_id=addslashes($tree_id);
	} else {
	die("Application error!");
	}
$tree_info=getoneb("select * from file_cabinet_tree where tree_id = '$tree_id'");
if (!($tree_info)) die ("Application error!");
if ($tree_info->free_for_all!="Y") die_security();

if ($folder_name!="") {
	$folder_name=addslashes($folder_name);
	} else {
	$folder_name="????";
	}
$query="update file_cabinet_tree set folder_name = '$folder_name' where tree_id = '$tree_id'";
@mysql_query($query);
forward("main&current_folder=$tree_info->parent_id");

?>
