<?
//////////////////////////////////////////////////////////////////////
// We need to keep track of a few things so we can exit to the right
// spot again for most any scenario:
// #1) doc_id - this is the document that opened us
// #2) doc_edit_id - this is the document we're editing
// #3) $doc_type, but from here it is fixed 
//
//	Anything else that we load off of, should probably get overriden 
//  by the above data (IE: if we know we're load a particular 
//  doc_edit_id, we don't care about the edit text that is for
//  trying to locate it.
//////////////////////////////////////////////////////////////////////

$doc_type="file_cabinet";
include ('fd_document_box_header.phtml');
include("../file_cabinet$devel/local.inc");
fd_document_box_header_print($doc_id,$doc_type,$doc_edit_id);

///////////////////////////////////////////////////////////////////////////////////////////////////
//	This is the end of the generics section
//	...now on to the app specific stuff
///////////////////////////////////////////////////////////////////////////////////////////////////

if ($doc_edit_info) {
	$file_cabinet_info=getoneb("select * from file_cabinet where file_cabinet_id = '$doc_edit_info->app_record_id'");
	$tree_id=$file_cabinet_info->tree_id;
	
	if ($new_file_cabinet_description!="") {
		$new_file_cabinet_description=addslashes($new_file_cabinet_description);
		@mysql_query("update file_cabinet set description = '$new_file_cabinet_description' where file_cabinet_id = '$file_cabinet_info->file_cabinet_id'");
		$file_cabinet_info=getoneb("select * from file_cabinet where file_cabinet_id = '$doc_edit_info->app_record_id'");
		}
	} 

if ($tree_id!="") {
	$tree_id=addslashes($tree_id);
	$tree_info=getoneb("select * from file_cabinet_tree where tree_id = '$tree_id'");
	}

if (!($tree_info)) {
	$tree_info=get_root();
	}

if (!($tree_info)) {
	$template_root="1";
	create_root();
	$tree_info=get_root();
	}

$ul_style="cursor: hand; cursor: pointer; padding: 0; margin: 0; margin-left: 8px; list-style-type: none;";

if (!($tree_info)) die ("Application error!");
$tree_template_info=getoneb("select * from file_cabinet_templates where template_id = '$tree_info->template_id'");
$tree_path_link=get_tree_path_mini($tree_info->tree_id);

/*
if ($tree_info->free_for_all=='Y') {
	echo ("free_for_all");
	//die("free_for_all");
	
	}
*/

if ($add_folder_id!="") {
	$add_folder_id=addslashes($add_folder_id);
	$template_info=getoneb("select * from file_cabinet_templates where template_id = '$add_folder_id'");
	
	if (!($template_info)) {
		if ($tree_info->free_for_all=='Y') {
			
			$query="insert into file_cabinet_tree set 
			jobinfo_id = '$tree_info->jobinfo_id',
			parent_id = '$tree_info->tree_id',
			template_id = '$tree_info->template_id',
			sort_priority = '$tree_info->sort_priority',
			folder_name = '$add_folder_id',
			folder_creator = '$global_user_id',
			folder_description = '$tree_info->folder_description',
			free_for_all = 'Y',
			correspondence_children = '$tree_info->for_correspondence'
			";
			} else {
			echo "Warning: add action failed for an unknown reason. Please contact your system administrator.";
			}
			
		
		
		} else {
	
		$query="insert into file_cabinet_tree set 
		jobinfo_id = '$tree_info->jobinfo_id',
		parent_id = '$tree_info->tree_id',
		template_id = '$template_info->template_id',
		sort_priority = '$template_info->sort_priority',
		folder_name = '$template_info->folder_name',
		folder_creator = '$global_user_id',
		folder_description = '$template_info->folder_description',
		correspondence_children = '$template_info->for_correspondence'
		";
		}
	@mysql_query($query);
	$new_tree_id=@mysql_insert_id();
	
	
	if ($tree_info->correspondence_children=="Y") {
		$query="insert into file_cabinet_tree set 
		jobinfo_id = '$tree_info->jobinfo_id',
		parent_id = '$new_tree_id',
		template_id = '$template_info->template_id',
		sort_priority = '$template_info->sort_priority',
		folder_name = 'In',
		folder_creator = '$global_user_id',
		folder_description = '$template_info->folder_description - In',
		correspondence_children = 'N'
		";
		@mysql_query($query);
		$query="insert into file_cabinet_tree set 
		jobinfo_id = '$tree_info->jobinfo_id',
		parent_id = '$new_tree_id',
		template_id = '$template_info->template_id',
		sort_priority = '$template_info->sort_priority',
		folder_name = 'Out',
		folder_creator = '$global_user_id',
		folder_description = '$template_info->folder_description - Out',
		correspondence_children = 'N'
		";
		@mysql_query($query);
		}
	$tree_info=getoneb("select * from file_cabinet_tree where tree_id = '$new_tree_id'");
	$tree_id=$tree_info->tree_id;
	$tree_template_info=getoneb("select * from file_cabinet_templates where template_id = '$tree_info->template_id'");
	$tree_path_link=get_tree_path_mini($tree_info->tree_id);
	}

if ($start_new_document=='Y') {
	$file_num=getoneb("select max(file_num) as largest from file_cabinet where tree_id = '$tree_info->tree_id' limit 1");
	if ($file_num->largest=="") {
	    $new_file_num=1;
	    } else {
	    $new_file_num=$file_num->largest + 1;
	    }
	$query="insert into file_cabinet set 
		description = '',
		folder_name = '$tree_info->folder_name',
		tree_id = '$tree_info->tree_id',
		jobinfo_id = '$tree_info->jobinfo_id',
		file_num = '$new_file_num',
		create_date = now(),
		creator = '$global_user_id',
		inbound_attached = 'Y'";
	$res=@mysql_query($query);
	if (!($res)) die("Application error: query failed:<hr>$query");
	$id=mysql_insert_id();
	@update_directory_counts($tree_info->tree_id);
	$file_cabinet_info=getoneb("select * from file_cabinet where file_cabinet_id = '$id'");
	$doc_edit_info=getoneb("select * from documents where doc_type = 'file_cabinet' and app_record_id = '$id'");
	$doc_edit_id=$doc_edit_info->doc_id;
	@mysql_query("call doc_link('$doc_id','$doc_edit_info->doc_id','$global_user_id','Automatic inbound creation link')");
	}


if ($file_cabinet_info) {
	$creator=getoneb("select * from contacts where contacts_id = '$file_cabinet_info->creator'");
	$create_date=invali_date($file_cabinet_info->create_date,'/');
	echo "
	
	
	<table style=\"font-size: 12px;\" border=0 cellspacing=0 cellpadding=2>
	
	<tr><td>
		Location:
	</td><td>
		$file_cabinet_info->folder_name
	</td></tr>
	
	<tr><td>
		File #:
	</td><td>
		$file_cabinet_info->file_num
	</td></tr>
	
	<tr><td>
		Creator:
	</td><td>
		$creator->display_name
	</td></tr>
	
	<tr><td>
		Create Date:
	</td><td>
		$create_date
	</td></tr>
	
	
	<tr><td colspan=2 align=center>
		Description / Keywords
	</td></tr>
	
	<tr><td colspan=2 align=center>
		<input id=\"file_cabinet_description_input\" type=text size=15 name=description value=\"$file_cabinet_info->description\" onchange=\"file_cabinet_submit_description('$doc_id','$doc_edit_id')\">
	</td></tr>
	
	
	";
	
	die();
	
	}




$folder_list_res=@mysql_query("select * from file_cabinet_tree where parent_id = '$tree_info->tree_id' and tree_id != parent_id order by folder_name");
echo "<table width=100% border=0 cellspacing=0 cellpadding=0 style=\"font-size: 9px; align: left;\">

<tr><td colspan=2>
	<input onchange=\"search_file_cabinet('$doc_info->doc_id','$doc_edit_id','$tree_info->tree_id')\" style=\"font-size: 9px;\" type=text size=8 name=load_text id=doc_box_load_text value=\"$load_text\">
	<input style=\"font-size: 9px;\" type=button 
	onclick=search_file_cabinet('$doc_info->doc_id','$doc_edit_info->doc_id','$tree_info->tree_id') value=\"Find Drawer\">
</td></tr>
";

if ($load_text!="") {
	$hits_array=keyword_hits_array($load_text);
	echo "
	<tr><td colspan=2>
		<span style=\"background: yellow; border: 1px solid black;\">#</span>=Search results
	</td></tr>";
	}

echo "
<tr><td style=\"border: 1px solid black; background: $fd_color_4;\" colspan=2>$tree_path_link</td></tr>
<tr><td><p>
";
//<tr><td><font color=blue onclick=\"fc_sh_tree('$doc_id','$doc_edit_id','$tree_info->parent_id')\">..</font></td></tr>
$total_hits=0;
$required_hits=$hits_array[$tree_info->template_id];
if ($direct_hits_array[$tree_info->template_id]>0)
	$required_hits=$required_hits - $direct_hits_array[$tree_info->template_id];

while ($folder=@mysql_fetch_object($folder_list_res)) {
	$hitlist="";
	if ($hits_array[$folder->template_id]>0) {
		 $hits=$hits_array[$folder->template_id];
		 $hitlist="<span style=\"background: yellow; border: 1px solid black;\">&nbsp;$hits&nbsp;</span>";
		 $total_hits=$total_hits + $hits;
		 }
	echo "<ul style=\"$ul_style\"><img onclick=\"fc_sh_tree('$doc_id','$doc_edit_id','$folder->tree_id')\" src=/global/file_cabinet$devel/right.png>$hitlist $folder->folder_name</ul>";
	}
if ($required_hits>$total_hits) {
	$diff=$required_hits - $total_hits;
	echo "<ul style=\"$ul_style\"><span style=\"background: yellow; border: 1px solid black;\">&nbsp;$diff more in inactive folders&nbsp;</span></ul>";
	}
$new_folders_res=@mysql_query("select file_cabinet_templates.template_id,left(file_cabinet_templates.folder_name,20) as folder_name from file_cabinet_templates left join file_cabinet_tree on (file_cabinet_templates.template_id = file_cabinet_tree.template_id and file_cabinet_tree.jobinfo_id = '$tree_info->jobinfo_id') where folder_parent = '$tree_template_info->template_id' and folder_parent != file_cabinet_templates.template_id and file_cabinet_tree.folder_name is null order by file_cabinet_templates.folder_name");
$new_folders_count=@mysql_num_rows($new_folders_res);

if (($new_folders_count > 0)||($tree_info->free_for_all=="Y")) {
	
	if ($tree_info->free_for_all=="Y") {
		echo "<ul style=\"$ul_style\">
		<input type=text size=8 style=\"padding: 0px; width: 150px; font-size: 12px; margin: 0px; background: blue; color: white;\" id=\"add_template_id_select\" name=\"add_template_id\">";
		//echo "<option style=\"color: blue;\" value=\"\" selected>Activate Folder</option>";
		echo "<input type=button value=\"Add\" style=\"padding: 0px; margin: 0px; height: 18px; font-size: 9px;\" onclick=\"add_subfolder('$doc_info->doc_id','$doc_edit_info->doc_id','$tree_info->tree_id')\"></ul>";
		} else {
		echo "<ul style=\"$ul_style\"><select style=\"padding: 0px; width: 150px; font-size: 12px; margin: 0px; background: blue; color: white;\" id=\"add_template_id_select\" name=\"add_template_id\">";
		echo "<option style=\"color: blue;\" value=\"\" selected>Activate Folder</option>";
		while ($new_folder=@mysql_fetch_object($new_folders_res)) {
			$text_option_add="";
			if ($hits_array[$new_folder->template_id]>0) {
				$text_option_add="&nbsp;(" . $hits_array[$new_folder->template_id] . ")";
				}
			echo "<option value=\"$new_folder->template_id\">$new_folder->folder_name$text_option_add</option>";
			}
		echo "</select><input type=button value=\"Add\" style=\"padding: 0px; margin: 0px; height: 18px; font-size: 9px;\" onclick=\"add_subfolder('$doc_info->doc_id','$doc_edit_info->doc_id','$tree_info->tree_id')\"></ul>";
		}
	
	//if ($tree_inf0->free_for_all=="N") {
	//	} else {
	//	echo "</select><input type=button value=\"Add\" style=\"padding: 0px; margin: 0px; height: 18px; font-size: 9px;\" onclick=\"add_subfolder('$doc_info->doc_id','$doc_edit_info->doc_id','$tree_info->tree_id')\"></ul>";
	//	}
	
	}
echo "</td></tr></table>";

echo "<table border=0 cellspacing=0 cellpadding=1>";

if (!($file_cabinet_info)) {
	exit;
	} else {
	echo "editing";
	}
?>
