<?
require("header.phtml");
fd_navs_header();
$subcontracts_id=addslashes($subcontracts_id);
echo "
<center>
<a href=$pagename?mode=scope_selections_pdf&subcontracts_id=$subcontracts_id>
<font color=blue>
Download Scope Document
</font></a><br>
or<br>
<a href=$pagename?mode=build_contract><font color=blue>
Build a full contract
</font></a><br>
or<br>
<a href=$pagename?mode=main><font color=blue>
Continue to main menu
</font></a>
</center>
";
fd_navs_footer();
?>
