<?
require("header.phtml");
fd_navs_header();
$today=date('m-d-Y');
$ca=member_of_global_group_named("Contract Admin");
$pm=pm_for_this_job();

echo "<a href=$pagename?mode=subcontracts_edit><font color=blue>Start Subcontract Request</font></a><p>";

//tabledump("select * from subcontracts where jobinfo_id = '$global_jobinfo_id'");
$res=@mysql_query("select * from subcontracts where jobinfo_id = '$global_jobinfo_id'");

echo "<table border=1 cellspacing=0 cellpadding=2>
<tr bgcolor=$fd_color_1><td>
	<b>Req #</b>
</td><td>
	<b>Status</b>
</td><td>
	<b>Description</b>
</td><td>
	<b>Sub Type</b>
</td><td>
	<b>Sub</b>
</td><td>
	<b>Amount</b>
</td><td>
	&nbsp;
</td></tr>
";
while ($row=@mysql_fetch_object($res)) {
	$sub_type=getoneb("select * from subcontractor_types where subcontractor_type_id = '$row->subcontractor_type_id'");
	$sub=getoneb("select * from contacts where contacts_id = '$row->subcontractor_id'");
	$row->contract_amount=round($row->contract_amount);
	echo "<tr><td>
			<a href=$pagename?mode=subcontracts_edit&subcontracts_id=$row->subcontracts_id><font color=blue><i>$row->request_number</i></font></a>
		
		</td><td>
			$row->status
		</td><td>
			$row->description
		</td><td>
			$sub_type->sub_type
		</td><td>
			$sub->display_name
		</td><td>
			$row->contract_amount
		</td><td>";
			if ($row->status=="submitted") {
				//if ($ca) {
					//echo "<a href=$pagename?mode=subcontracts_retrieve&subcontracts_id=$row->subcontracts_id><font color=blue><i>return to pm</i></font></a>";
				//	} else {
					if ($pm) echo "<a href=$pagename?mode=subcontracts_retrieve&subcontracts_id=$row->subcontracts_id><font color=blue><i>retrieve</i></font></a>";
				//	}
				}
		echo "&nbsp;</td></tr>";
	}
echo "</table>";
















//echo "
//<table border=1 cellspacing=0 cellpadding=3>
//<tr><td colspan=5 align=center>
//<b><font size=+1>$dbdescription</font></b><br>$today<br></td></tr>";
//echo "</table>";









fd_navs_footer();
?>
