<?
if (($in_scope!="Yes") && ($in_scope!="No") && ($in_scope!="N/A")) {
	die("Applicatio error! Invalid scope item setting!");
	}
$selections_id=addslashes($selections_id);
@mysql_query("update subcontractor_scope_selections set in_scope = '$in_scope' where selections_id = '$selections_id'");
//echo "<hr>update subcontractor_scope_selections set in_scope = '$in_scope' where selections_id = '$selections_id'<hr>";

$ysel="";
$nsel="";
$msel="";
$bgcolor="#ffffff";
if ($in_scope=="Yes") $ysel="checked"; 
if ($in_scope=="No") $nsel="checked";
if ($in_scope=="N/A") $msel="checked";
	

echo "
	<table border=0 cellspacing=0 cellpadding=2><tr>
	<td style=\"width: 40px;\"><input onchange=\"update_scope_selection($selections_id)\" type=radio name=radio$selections_id value='Yes' $ysel></td>
	<td style=\"width: 40px;\"><input onchange=\"update_scope_selection($selections_id)\" type=radio name=radio$selections_id value='No' $nsel></td>
	<td style=\"width: 40px;\"><input onchange=\"update_scope_selection($selections_id)\" type=radio name=radio$selections_id value='N/A' $msel></td>
	</table>
";

/*
echo "
<select name=in_scope onchange=\"update_scope_selection_old(this,$selections_id)\">
<option>$in_scope</option>
<option>Yes</option>
<option>No</option>
<option>N/A</option>
</select>";
*/
?>
