<?
$subcontracts_id=addslashes($subcontracts_id);
$subcontracts_info=getoneb("select * from subcontracts where subcontracts_id = '$subcontracts_id'");
$job_information=getoneb("select * from jobinfo where jobinfo_id = '$subcontracts_info->jobinfo_id'");

if ($subcontracts_info->subcontractor_type_id>0) {
	$s_type_info=getoneb("select * from subcontractor_types where subcontractor_type_id = '$subcontracts_info->subcontractor_type_id'");
	}


$subcontractor_info=getoneb("select * from contacts where contacts_id = '$subcontracts_info->subcontractor_id'");
$subcontractor_contact_info=getoneb("select * from contacts where contacts_id = '$subcontracts_info->subcontractor_contact'");
$prime_contractor_info=getoneb("select * from contacts where contacts_id = '$subcontracts_info->prime_contractor'");
$owner_info=getoneb("select * from contacts where contacts_id = '$subcontracts_info->owner'");

if ($subcontracts_info->subcontractor_type_id==12) {
	if ($subcontracts_info->other_subcontractor_type!="") $s_type_info->sub_type=$subcontracts_info->other_subcontractor_type;
	}

require_once('pdf_lib2.inc');
$pdf=&new Cezpdf("$global_user->pref_paper_size","portrait");
$pdf->selectFont("$pdf_font_path/Helvetica.afm");
$pdf->ezSetMargins(36,36,72,72);


if ($subcontracts_info->job_name_alias!="") $job_name=$subcontracts_info->job_name_alias;
else $job_name=$job_information->display_name;

$font_size="8";
$header_font_size=$font_size;
$spaces="                                 ";

$y=$pdf->y;$pdf->ezText("Project Name:",$header_font_size);
$pdf->y=$y;$pdf->ezText("$spaces$job_name",$header_font_size);

$y=$pdf->y;$pdf->ezText("UMC Job #:",$header_font_size);
$pdf->y=$y;$pdf->ezText("$spaces$job_information->contract_num",$header_font_size);

$y=$pdf->y;$pdf->ezText("Subcontractor:",$header_font_size);
$pdf->y=$y;$pdf->ezText("$spaces$subcontractor_info->display_name",$header_font_size);

$y=$pdf->y;$pdf->ezText("Address:",$header_font_size);
$pdf->y=$y;$pdf->ezText("$spaces$subcontractor_info->address_1,\r\n$spaces$subcontractor_info->address_city $subcontractor_info->address_zip",$header_font_size);

$y=$pdf->y;$pdf->ezText("Contract Amount:",$header_font_size);
$subcontracts_info->contract_amount=format_long_decimal($subcontracts_info->contract_amount);
$pdf->y=$y;$pdf->ezText("$spaces\$$subcontracts_info->contract_amount",$header_font_size);

$y=$pdf->y;$pdf->ezText("Request #:",$header_font_size);
$pdf->y=$y;$pdf->ezText("$spaces$subcontracts_info->request_number",$header_font_size);

$y=$pdf->y;$pdf->ezText("Sub Type:",$header_font_size);
$pdf->y=$y;$pdf->ezText("$spaces$s_type_info->sub_type",$header_font_size);

$y=$pdf->y;$pdf->ezText("T & M:",$header_font_size);
$pdf->y=$y;$pdf->ezText("$spaces$subcontracts_info->is_t_and_m",$header_font_size);

$y=$pdf->y;$pdf->ezText("Sub Contact:",$header_font_size);
$pdf->y=$y;$pdf->ezText("$spaces$subcontractor_contact_info->display_name",$header_font_size);

$y=$pdf->y;$pdf->ezText("Retainage:",$header_font_size);
$pdf->y=$y;$pdf->ezText("$spaces$subcontracts_info->retainage",$header_font_size);

$y=$pdf->y;$pdf->ezText("Prime Contractor:",$header_font_size);
$pdf->y=$y;$pdf->ezText("$spaces$prime_contractor_info->display_name",$header_font_size);

$y=$pdf->y;$pdf->ezText("Phase:",$header_font_size);
$pdf->y=$y;$pdf->ezText("$spaces$subcontracts_info->phase_code",$header_font_size);

$y=$pdf->y;$pdf->ezText("Owner:",$header_font_size);
$pdf->y=$y;$pdf->ezText("$spaces$owner_info->display_name",$header_font_size);

$y=$pdf->y;$pdf->ezText("\r\nScope:",$header_font_size);
//$pdf->y=$y;
$pdf->ezHR();
$pdf->ezText("$subcontracts_info->scope",$header_font_size);
$pdf->ezHR();





/*
if (($subcontracts_info->status!="complete")||($subcontracts_info->status!="processing")) {
	$pdf->ezText("<b>Draft Scope Document</b>",$font_size + 6,array("justification"=>"center"));
	//$pdf->addText(220,400,50,"DRAFT",315);
	}
*/




$pdf->ezText("Scope Checklist:\r\n",$font_size + 1);

$pdf->ezTableDumpStart();
$pdf->ezTableDumpAdd("","DESCRIPTION","INCLUDED");


$scope_res=@mysql_query("select * from subcontractor_scope_selections where subcontractor_type_id = '$subcontracts_info->subcontractor_type_id' and subcontracts_id = '$subcontracts_info->subcontracts_id' order by sort_priority");
while ($current=@mysql_fetch_object($scope_res)) {
	if ($current->in_scope!="Yes") $current->in_scope="           $current->in_scope";
	if ($current->custom_scope_item=='Y') $current->sort_priority='*' . $current->sort_priority;
	$pdf->ezTableDumpAdd($current->sort_priority,$current->description,$current->in_scope);
	}

$pdf->ezTableDumpPrint(1,array(
		"fontSize"=>"7",
		"width"=>"464",
		"showLines"=>"1",
		"cols"=>array(
				"0"=>array("width"=>"30"),
				"2"=>array("width"=>"62")
			)
		));

if (($subcontracts_info->status!="complete")||($subcontracts_info->status!="processing")) {
	$pdf->setColor(1,.3,.3);
	$pdf->addText(180,170,75,"DRAFT",330);
	$pdf->setColor(0,0,0);
	}








$pdf->ezStream();

?>
