5A<?
$jobinfo_id=addslashes($jobinfo_id);
$submitted_to_eng=vali_date($submitted_to_eng);
$current_submittal_date=vali_date($current_submittal_date);
$returned_from_eng=vali_date($returned_from_eng);
$issued_for_construction_date=vali_date($issued_for_construction_date);

$correction_submitted=vali_date($correction_submitted);
$returned_file_id=addslashes($returned_file_id);
$jobinfo_id=addslashes($jobinfo_id);
$sheet_num=addslashes($sheet_num);
$description=addslashes($description);
$type=addslashes($type);
$floor=addslashes($floor);
$area=addslashes($area);
$dwg_section=addslashes($dwg_section);
$correction_required=addslashes($correction_required);
$issued_for=addslashes($issued_for);
$submittal_status=addslashes($submittal_status);
$originator=addslashes($originator);
$lead_engineer=addslashes($lead_engineer);
$lead_engineer_notify=checkfix($lead_engineer_notify);
$engineer_required_date=vali_date($engineer_required_date);
$submitted_to_umc=checkfix($submitted_to_umc);
$submitted_to_gc=checkfix($submitted_to_gc);
$submitted_to_owner=checkfix($submitted_to_owner);
$submitted_to_consultant=checkfix($submitted_to_consultant);
$correction_file_group_id=addslashes($correction_file_group_id);
$submitted_file_group_id=addslashes($submitted_file_group_id);

if ($submittal_status=='N/A') {
	$lead_engineer="";
	$lead_engineer_notify='N';
	$engineer_required_date="";
	$submitted_to_eng="";
	$returned_from_eng="";
	$correction_required="";
	$correction_submitted="";
	}
	


$cust_1=addslashes($cust_1);
$cust_2=addslashes($cust_2);
$cust_3=addslashes($cust_3);
$cust_4=addslashes($cust_4);
$cust_5=addslashes($cust_5);

//if ($file_group_id!="") $file_group_id=addslashes($file_group_id);

if ($revision!="") $revision=addslashes($revision);
	else $revision="1";

if ($drawing_id=="") {
	$query_start="insert into drawinglog set creator = '$global_user_id', ";
	$orig_issue=vali_date($orig_issue);
	$query_end="";
	} else {
	$drawing_id=addslashes($drawing_id);
	$query_start="update drawinglog set ";
	
	$query_end="where drawing_id = '$drawing_id'";
	$old_drawing_info=getone("select * from drawinglog where drawing_id = '$drawing_id'");
	//if ($old_drawing_info->orig_issue!=$orig_issue) {
	//	if (($old_drawing_info->orig_issue=="0000-00-00")||($adminuser)) {
	//		$orig_issue=vali_date($orig_issue);
	//		} else {
	//		$orig_issue=$old_drawing_info->orig_issue;
	//		echo "not admin and not an old blank!!!!!!!!";exit;
	//		}
	//	}
	$orig_issue=vali_date($orig_issue);

	if ($old_drawing_info) {
		if (!($write)) {
			if (!(($guest)&&($old_drawing_info->creator==$global_user_id))) die_security();
			}
		}
	}

if ($sort_priority=="") {
	$sort_priority=1;
	}
/*
if (($sort_priority=="")||($sort_priority==0)) {
	$sort_info=getone("select max(sort_priority) as current_max from drawinglog where jobinfo_id = '$jobinfo_id' and type = '$type'");
	$sort_priority=$sort_info->current_max + 1;
	}
*/

$query_middle="
jobinfo_id = '$jobinfo_id',
section = '$current_drawinglog_section',
sheet_num = '$sheet_num',
description = '$description',
type = '$type',
orig_issue = '$orig_issue',
floor = '$floor',
area = '$area',
dwg_section = '$dwg_section',
sort_priority = '$sort_priority',
issued_for = '$issued_for',
submittal_status = '$submittal_status',
current_submittal_date = '$current_submittal_date',
submitted_to_eng = '$submitted_to_eng',
submitted_file_group_id = '$submitted_file_group_id',
returned_from_eng = '$returned_from_eng',
issued_for_construction_date = '$issued_for_construction_date',
correction_required = '$correction_required',
correction_submitted = '$correction_submitted',
correction_file_group_id = '$correction_file_group_id',
returned_file_id = '$returned_file_id',
originator = '$originator',
lead_engineer = '$lead_engineer',
lead_engineer_notify = '$lead_engineer_notify',
engineer_required_date = '$engineer_required_date',
submitted_to_umc = '$submitted_to_umc',
submitted_to_gc = '$submitted_to_gc',
submitted_to_owner = '$submitted_to_owner',
submitted_to_consultant = '$submitted_to_consultant',
cust_1 = '$cust_1',
cust_2 = '$cust_2',
cust_3 = '$cust_3',
cust_4 = '$cust_4',
cust_5 = '$cust_5'
";

$query_full=$query_start . $query_middle . $query_end;

@mysql_query($query_full);
if ($drawing_id=="") {
	$drawing_id=@mysql_insert_id();
	}

if ($savemode=='next') {
	//section = '$current_drawinglog_section',
	//sheet_num = '$sheet_num',
	$nextitem=getoneb("select * from drawinglog where jobinfo_id = '$jobinfo_id' and section = '$current_drawinglog_section' and sort_priority >= '$sort_priority' and sheet_num > '$sheet_num' and type = '$type' order by sheet_num limit 1");
	if (!($nextitem)) forward("drawinglog_edit");
	else forward("drawinglog_edit&drawing_id=$nextitem->drawing_id");
	exit;
	}

if ($savemode=='clone') {
	forward("drawinglog_edit&drawing_id=$drawing_id&load_mode=$savemode");
	exit;
	}

if ($savemode=='apply') {
	forward("drawinglog_edit&drawing_id=$drawing_id");
	exit;
	}
forward('main');
?>
