<?
if (!($adminuser)) {
	die_security();
	}
$dwg_rev_id=addslashes($dwg_rev_id);
$rev_info=getoneb("select * from drawinglog_revs where dwg_rev_id = '$dwg_rev_id'");

if ($rev_info->attached_file_group_id > 0) {
	include("../webfile/storage_settings.cfg");
	include("../webfile/local.inc");
	delete_webfile_group($rev_info->attached_file_group_id);
	}

$query="delete from drawinglog_revs where dwg_rev_id = '$dwg_rev_id'";
@mysql_query($query);

update_rev($rev_info->drawing_id);

forward("drawinglog_edit&drawing_id=$rev_info->drawing_id");
?>
