<?
if ($global_user->umc_emp!='Y') die("ERROR");
if ($drawing_id=="") die("ERROR");
else $drawing_id=addslashes($drawing_id);
$dwg_info=getoneb("select * from drawinglog where drawing_id = '$drawing_id'");
$data="";
if ($field=='sort_priority') $data=$dwg_info->sort_priority;
if ($field=='revision') $data=$dwg_info->revision;
if ($field=='description') $data=$dwg_info->description	;
if ($field=='cust_1') $data=addslashes($dwg_info->cust_1);
if ($field=='cust_2') $data=addslashes($dwg_info->cust_2);
if ($field=='cust_3') $data=addslashes($dwg_info->cust_3);
if ($field=='cust_4') $data=addslashes($dwg_info->cust_4);
if ($field=='cust_5') $data=addslashes($dwg_info->cust_5);
if ($field=='current_rev_date') $data=invali_date($dwg_info->current_rev_date);

echo "<form name=form_foo onsubmit='return(false)' style=\"display: inline\">";
switch ($field) {
	case "revision":	
	case "sort_priority":	
	case "cust_1":	
	case "cust_2":	
	case "cust_3":	
	case "cust_4":	
	case "cust_5":	
		echo "<input autocomplete=off type=text size=15 id=ajax_form_data_field value=\"$data\" onblur=\"save_data('$drawing_id','$field',this)\" onchange=\"blur();\">";
		break;;
	case "description":	
		//echo "<textarea rows=3 cols=30 id=ajax_form_data_field onblur=\"save_data('$drawing_id','$field',this)\" onchange=\"blur()\">$data</textarea>";
		echo "<input  autocomplete=off type=text size=45 id=ajax_form_data_field value=\"$data\" onblur=\"save_data('$drawing_id','$field',this)\" onchange=\"blur();\">";
		break;;
	case "current_rev_date":	
		//datebox($data,"form_foo.ajax_form_data_field","","alert(this.id);save_data('$drawing_id','$field',this)\" id=\"ajax_form_data_field\"");
		datebox2($data,"form_foo.ajax_form_data_field","save_data('$drawing_id','$field',this)\"  autocomplete=off id=\"ajax_form_data_field\"");
		break;;
	default: die("Field Error ($field)");
		break;;
	}

echo "</form>";
?>
