<?
if ($dwg_rev_id=="") die("Application Error: No dwg_rev_id specified! Please contact your system administrator!");
else $dwg_rev_id=addslashes($dwg_rev_id);

if ($attached_file_group_id=="") die("Application Error: No attached_file_group_id specified! Please contact your system administrator!");
else $attached_file_group_id=addslashes($attached_file_group_id);

$query="update drawinglog_revs set attached_file_group_id = '$attached_file_group_id' where dwg_rev_id = '$dwg_rev_id'";
@mysql_query($query);
$info=getoneb("select * from drawinglog_revs where dwg_rev_id = '$dwg_rev_id'");
//forward("drawinglog_edit&drawing_id=$info->drawing_id");

echo "NAAAAAAAAAAAAAAAAAAAAAACCCCCCCCCCCHHHHHHHHHOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO!!!!<p>...good one Beavis..";
?>
