<?
echo "
<html>
<head>
<title>
Item not received by MIS yet.
</title>
</head>
<body bgcolor=#ffffff>
<b>Item not received yet.</b><hr>

The item you are trying to view/modify has not be received and prioritized by MIS yet. You must wait for that to happen before you and do anything with it.

<hr>
<a href=$pagename?mode=main><font color=blue>Return to tasklist</font></a>









</body>
</html>
















";










?>
