<?
$today=date('Y-m-d');
$project_status="approved";

$issue_id=escapeshellcmd($issue_id);

$query="update mis_issue_history set status = 'complete', actual_completion_date = '$today' where issue_id = '$issue_id' and status = 'current'";
$res=@mysql_query($query);if(!($res)) die("ERROR: Query failed. Contact you sys admin.<p>failed query<hr>$query");

$query="update mis_issue_index set status = '$project_status',expected_completion = '$expected_completion' where issue_id = '$issue_id'";
$res=@mysql_query($query);if(!($res)) die("ERROR: Query failed. Contact you sys admin.<p>failed query<hr>$query.");



$children_res=@mysql_query("select * from mis_issue_index where reference_this_issue = '$issue_id'");
while ($child=@mysql_fetch_object($children_res)) {
	$issue_id=$child->issue_id;
	
	$query="update mis_issue_history set status = 'complete', actual_completion_date = '$today' where issue_id = '$issue_id' and status = 'current'";
	$res=@mysql_query($query);if(!($res)) die("ERROR: Query failed. Contact you sys admin.<p>failed query<hr>$query");
	
	$query="update mis_issue_index set status = '$project_status' where issue_id = '$issue_id'";
	$res=@mysql_query($query);if(!($res)) die("ERROR: Query failed. Contact you sys admin.<p>failed query<hr>$query.");
	}

forward("issue_edit&issue_id=$issue_id");

?>
