<?
if (!($adminuser)) {
	echo "ERROR: Security Violation Attempt! The authorities have been notified.     
	Go away now. If you believe this is in error, then contact your system administrator.";
	exit;
	}

//require_once('querylib.inc');

if ($status=="") {
	echo "ERROR: You've got to put something in for the status description.. That's all you've got!<hr>
	<a href=javascript:history.go(-1)>Go Back</a> and try that again!<p>";
	exit;
	}

$status=escapeshellcmd($status);

if ($svc_proposals_status_id!="") {
	$svc_proposals_status_id=escapeshellcmd($svc_proposals_status_id);
	$query="update svc_proposals_status set status = '$status' where svc_proposals_status_id = '$svc_proposals_status_id'";
	} else {
	$query="insert into svc_proposals_status set status = '$status'";
	}


//echo "$query";exit;

$res=@mysql_query($query);
if (!($res)) {
	echo "ERROR submitting your query. Please contact your system administrator. The query that failed is printed
	below. Please keep this on the screen or print it so that your system amdinistrator may examine it.<hr>$query";
	exit;
	}


forward('proposals_status_maint');

?>
