<?
if (!($adminuser)) {
	echo "ERROR: Security Violation Attempt! The authorities have been notified. 
	Go away now. If you believe this is in error, then contact your system administrator.";
	exit;                    
	}

//require_once('querylib.inc');

if ($svc_proposals_status_id!="") {
	$svc_proposals_status_id=escapeshellcmd($svc_proposals_status_id);
	$status_info=getone("select * from svc_proposals_status where svc_proposals_status_id = '$svc_proposals_status_id'");
	}


echo "

<html><head><title>Proposal Status Edit</title></head><body bgcolor=white>

<center><h2>Proposal Status Edit</h2></center>

<form name=proposals_status_edit action=$pagename method=post>
<input type=hidden name=mode value=proposals_status_submit>
<input type=hidden name=svc_proposals_status_id value=\"$status_info->svc_proposals_status_id\">
Description: <br>
<input type=text name=status value=\"$status_info->status\"><br>
<input type=submit value=Save>
<input type=button onclick=document.location=\"$pagename?mode=proposals_status_maint\" value=Cancel>
</form>



";









?>
