<?
//require_once('querylib.inc');

if ($contacts_id=="") die("ERROR: No user specified. Please <a href=javascript:history.go(-1)>go back</a> and try again..<p>");

$contacts_id=escapeshellcmd($contacts_id);
$contact_info=getone("select * from contacts where contacts_id = '$contacts_id'");

echo "
<html><head><title>User Edit ($contact_info->first_name $contact_info->last_name)</title></head>

<body bgcolor=#ffffff>

<h3>Please Set user's initials below</h3><p>
<table border=0>
<tr><td>
	<b>User's Name: </b>
</td><td>
	$contact_info->first_name $contact_info->last_name<br>
</td></tr>

<tr><td>
	<b>Login Name:  </b>
</td><td>
	$contact_info->login_name<br>
</td></tr>

<tr><td>
	<form name=initials_set method=post action=$pagename>
	<input type=hidden name=mode value=user_submit>
	<input type=hidden name=contacts_id value=$contact_info->contacts_id>
	<b>Initials: </b>
</td><td>
	<input type=text name=initials value=\"$contact_info->initials\">
</td></tr>

<tr><td colspan=2 align=right><input type=submit value=Save></td></tr>

</form>
</table>

</body>
";












?>
