<?
include ('fd_document_box_header.phtml');
//echo "nike! ($reply_from)";
$reply_from=addslashes($reply_from);
@mysql_query("update gcrfilog set reply_from = '$reply_from' where gcrfi_id = '$doc_edit_info->app_record_id'");
$gcrfi_info=getoneb("select * from gcrfilog where gcrfi_id = '$doc_edit_info->app_record_id'");
contact("select * from contacts where contact_type = 'contact' and umc_emp != 'Y' and current = 'Y'",$gcrfi_info->reply_from,'reply_from',"ajaxManager('load_page','/global$devel/gcrfilog$devel/?mode=mini_edit_update_reply_from&doc_id=$doc_info->doc_id&doc_edit_id=$doc_edit_info->doc_id&reply_from=' + document.contact_changed_value,'fd_document_box_reply_from_cell');",array('hidden_input'=>'N','input_size'=>'10','jobinfo_id'=>"$global_jobinfo->jobinfo_id"));




?>
