<?
include ('fd_document_box_header.phtml');
$has_cost=addslashes($has_cost);
@mysql_query("update gcrfilog set has_cost = '$has_cost' where gcrfi_id = '$doc_edit_info->app_record_id'");
$gcrfi_info=getoneb("select * from gcrfilog where gcrfi_id = '$doc_edit_info->app_record_id'");

echo "
<font size=-2>Cost/Sched&nbsp;Impact:</font>
<select id=\"doc_box_has_cost\" name=has_cost onchange=fd_doc_change_has_cost(this.value,$doc_info->doc_id,$doc_edit_info->doc_id)>
<option>$gcrfi_info->has_cost</option>
<option>Y</option>
<option>N</option>
<option></option>
</select>
";
?>
