<?
require('header.phtml');

echo "<a href=$pagename?mode=main><font color=blue>Return to main menu</font></a><p>";
if (!($adminuser)) die("ERROR: Security violation!!! The authorities have been notified!");

require('header.phtml');

echo "<a href=$pagename?mode=send_emails><font color=blue>Test E-mail processing</font></a><p>";


echo "Bidlist Contact Methods:<hr>";tabledump("select * from bidlist_contact_methods");

echo "<hr>Bidlist Types:<hr>";tabledump("select * from bidlist_types order by type");

echo "<hr>Bidlist Proposal Types:<hr>";tabledump("select * from bidlist_proptypes order by proposal_type");



?>
