<?
require('header.phtml');

if ($query_id!="") {
	$query_id=escapeshellcmd($query_id);
	$query_info=getone("select * from bidlist_saved_queries where contacts_id = '$global_user_id' and query_id = '$query_id'");
	}

echo "
<form name=sq_form method=post action=$pagename>

<table border=1 cellspacing=0 cellpadding=5>
<input type=hidden name=mode value=proposal_save_search_submit>
<input type=hidden name=query_id value=\"$query_info->query_id\">
<tr><td>
	<b>Name</b>
</td><td>
	<input type=text size=40 name=query_name value=\"$query_info->query_name\">
</td></tr>

<tr><td>
	Sort Priority (integer)
</td><td>
	<input type=text size=3 name=sort_num value=\"$query_info->sort_num\">
</td></tr>

<tr><td colspan=2 align=right>
	<input type=submit value=Save>
</td></tr>
	



</table>
</form>
";









?>
