<?
require('header.phtml');

echo "
<a href=$pagename?mode=reports><font color=blue>Return to reports</font></a><br>

<h2>Please select options for this report:</h2><hr>

<table border=0 cellspacing=0 cellpadding=5>
<form name=report_1_form method=post action=$pagename>
<input type=hidden name=mode value=reports_output_6b>

<b>For who:</b>&nbsp;
";

contactbox("select * from contacts where umc_emp = 'Y' and current = 'Y' order by display_name");


echo "

<tr><td colspan=2 align=right>
	<input type=submit value='Go'>
</td></tr>

</table>
";

?>
