<?
if ($el_id=="") die("Missing EL_ID! How could I possibly continue? Please contact your system administrator, cause this shouldn't happen!!!!");
else $el_id=addslashes($el_id);
$el_info=getone("select * from svc_agreement_equip_list where el_id = '$el_id'");

if ($tag_num!="") {
	$tag_num=addslashes($tag_num);
	$query="update svc_agreement_equip_list set tag_num = '$tag_num' where el_id = '$el_info->el_id'";
	@mysql_query($query);
	echo "
	<script>
	opener.tag_set($el_id,'$tag_num');
	self.close();
	</script>
	";
	exit;
	}
require('header.phtml');

echo "<form name=tn_popup method=post action=$pagename>
<input type=hidden name=mode value=equip_tag_num_popup>
<input type=hidden name=el_id value=\"$el_info->el_id\">
<input type=text size=40 name=tag_num value=\"$el_info->tag_num\" onchange=submit();>
</form>
<script>
document.tn_popup.tag_num.focus();
</script>
";

?>
