<?
if ($category_id=="") die("application error: contact your system administrator.");
$category_id=escapeshellcmd($category_id);
$category_info=getone("select * from svc_equip_categories where category_id = '$category_id'");


if ($equip_type_id!="") {
	$equip_type_id=escapeshellcmd($equip_type_id);
	$equip_type_info=getone("select * from svc_equip_types where equip_type_id = '$equip_type_id'");
	$equip_type_info->predict_vibration=checkbreak($equip_type_info->predict_vibration);
	$equip_type_info->predict_oil=checkbreak($equip_type_info->predict_oil);
	$equip_type_info->predict_refrigerant_lp=checkbreak($equip_type_info->predict_refrigerant_lp);
	$equip_type_info->predict_refrigerant_hp=checkbreak($equip_type_info->predict_refrigerant_hp);
	$equip_type_info->predict_laser_alignment=checkbreak($equip_type_info->predict_laser_alignment);
	$equip_type_info->predict_eddy_current_tube_anal=checkbreak($equip_type_info->predict_eddy_current_tube_anal);
	$equip_type_info->predict_thermography=checkbreak($equip_type_info->predict_thermography);
	$equip_type_info->predict_combustion=checkbreak($equip_type_info->predict_combustion);
	//$equip_type_info->predict_oil=checkbreak($equip_type_info->predict_oil);
	}

echo "
<a href=$pagename?mode=lists_equip_types&category_id=$category_info->category_id><font color=blue>Return</font></a><br>
<h3>Equipment Category: $category_info->category</h3>
<form name=equip_type_edit method=post action=$pagename>
<input type=hidden name=mode value=lists_equip_type_submit>
<input type=hidden name=category_id value='$category_info->category_id'>
<input type=hidden name=equip_type_id value='$equip_type_id'>
<table border=0>
<tr><td>
	<b>Equipment Type</b> 
</td><td>
	<input type=text name=type value='$equip_type_info->type'>
</td></tr>

<tr bgcolor=#eeeeee><td colspan=2j align=center>
	Predictive Services
</td></tr>

<tr><td>
	Vibration Analysis
</td><td>
	<input type=checkbox name=predict_vibration $equip_type_info->predict_vibration>
</td></tr>

<tr><td>
	Oil Analysis
</td><td colspan=2>
	<input type=checkbox name=predict_oil $equip_type_info->predict_oil>&nbsp;&nbsp;Cost&nbsp;
	<input size=5 type=text name=predict_oil_cost value=\"$equip_type_info->predict_oil_cost\">
</td></tr>

<tr><td>
	Refrigerant LP
</td><td>
	<input type=checkbox name=predict_refrigerant_lp $equip_type_info->predict_refrigerant_lp>
</td></tr>

<tr><td>
	Refrigerant HP
</td><td>
	<input type=checkbox name=predict_refrigerant_hp $equip_type_info->predict_refrigerant_hp>
</td></tr>

<tr><td>
	Laser Alignment
</td><td>
	<input type=checkbox name=predict_laser_alignment $equip_type_info->predict_laser_alignment>
</td></tr>

<tr><td>
	Eddy/Current Tube Analysis
</td><td>
	<input type=checkbox name=predict_eddy_current_tube_anal $equip_type_info->predict_eddy_current_tube_anal>
</td></tr>

<tr><td>
	Thermography
</td><td>
	<input type=checkbox name=predict_thermography $equip_type_info->predict_thermography>
</td></tr>

<tr><td>
	Combustion/Gas Analysis
</td><td>
	<input type=checkbox name=predict_combustion $equip_type_info->predict_combustion>
</td></tr>

</table>
	
<input type=submit value=Save>
</form>
";


if ($equip_type_id!="") {
	echo "<b>Defined Agreements</b><br><table border=0 cellspacing=0 cellpadding=3>";
	$ag_res=@mysql_query("select * from svc_agreement_types order by sort_priority,agreement_type");
	while($row=@mysql_fetch_object($ag_res)) {
		$task_list_res=@mysql_query("select * from svc_task_items where equip_type_id = '$equip_type_id' and agreement_type_id = '$row->agreement_type_id' group by maint_type_id");echo "<p>";
		$maint_type_count=@mysql_num_rows($task_list_res);
		if ($maint_type_count<1) {
			$textcolor="red";
			$status="No maintenance types defined";
			} else {
			$textcolor="black";
			$status="$maint_type_count maintenance types defined";
			}
	
		if ($agreement_type_id==$row->agreement_type_id) $status="<i>Service Types</i>";

		echo "
		<tr><td>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</td><td>
			<a href=$pagename?mode=$mode&category_id=$category_id&equip_type_id=$equip_type_id&agreement_type_id=$row->agreement_type_id><font color=$textcolor>$row->agreement_type</font></a>
		</td><td>
			$status
		</td></tr>
		";
		if ($agreement_type_id==$row->agreement_type_id) {
			$mt_list_res=@mysql_query("select * from svc_maint_types order by maint_type");
			while ($mt_list_row=@mysql_fetch_object($mt_list_res)) {
				$mt_defined=getoneb("select * from svc_task_items where equip_type_id = '$equip_type_id' and agreement_type_id = '$row->agreement_type_id' and maint_type_id = '$mt_list_row->maint_type_id' limit 1");
				//tabledump("select * from svc_task_items where equip_type_id = '$equip_type_id' and agreement_type_id = '$row->agreement_type_id' and maint_type_id = '$mt_list_row->maint_type_id' limit 1");echo "<p>";
				
				if ($mt_defined) {
					$mt_color="blue";
					$mt_link="Edit";
					} else {
					$mt_color="red";
					$mt_link="Create";
					}
				
				echo "
				<tr><td>
					&nbsp;
				</td><td>
					&nbsp;
				</td><td>
					<a href=$pagename?mode=task_item_edit&task_id=$mt_defined->task_id&equip_type_id=$equip_type_id&agreement_type_id=$row->agreement_type_id&maint_type_id=$mt_list_row->maint_type_id><font color=$mt_color>$mt_link</font></a>&nbsp;&nbsp;&nbsp;&nbsp;$mt_list_row->maint_type
				</td></tr>
				";
				}
			
			}
		
		}
	
echo "</table>";	
	
	
	
	
	
	
	
	
	
	
	
	
	}





?>
