<?

if ($material_list_id=="") die("ERROR: \$material_list_id missing.");
//if ($material_list_parent=="") die ("ERROR: \$material_list_parent missing. Please contact your system administrator!");
if ($name=="") die ("ERROR: \$name not specified!");
if ($qty_name=="") $qty_name="Qty";

//$mat_info=material_info($material_list_id);

$name=escapeshellcmd($name);
$qty_name=escapeshellcmd($qty_name);
$ss_name=checkfix($ss_name);
$ss_cost=checkfix($ss_cost);
$disabled=checkfix($disabled);
$cost=float_clean($cost);

$query="update svc_materials_list set
type = 'item',
name = '$name',
qty_name = '$qty_name',
ss_name = '$ss_name',
ss_cost = '$ss_cost',
disabled = '$disabled',
cost = '$cost'
where material_list_id = '$material_list_id'
";

//echo "<hr>$query<hr>";exit;

$res=@mysql_query($query);
forward("lists_material_types&material_list_id=$material_list_parent");

?>
