<?
if (!($adminuser)) die("ERROR: Security Violation! The authorities have been notified!!!");


if ($labor_type_id!="") {
	$labor_type_id=escapeshellcmd($labor_type_id);
	$labor_type_info=getone("select * from svc_labor_types where labor_type_id = '$labor_type_id'");
	}

echo "
<form name=edit_labor_type method=post action=$pagename>
<input type=hidden name=mode value=lists_labor_type_submit>
<input type=hidden name=labor_type_id value=\"$labor_type_info->labor_type_id\">

<table border=1 cellspacing=0 cellpadding=5>

<tr><td colspan=2 align=center bgcolor=#eeeeee>
	<b>Labor Type Definition</b>
</td></tr>

<tr><td>
	<b>Labor type name:</b>
</td><td>
	<input type=text size=20 name=labor_type value=\"$labor_type_info->labor_type\">
</td></tr>

<tr><td colspan=2 bgcolor=#eeeeee>
	<b>Rates:</b>
</td></tr>

<tr><td align=right>
	<b>ST</b>
</td><td>
	<input type=text name=st_rate value=\"$labor_type_info->st_rate\">
</td></tr>

<tr><td align=right>
	<b>OT</b>
</td><td>
	<input type=text name=ot_rate value=\"$labor_type_info->ot_rate\">
</td></tr>

<tr><td align=right>
	<b>DT</b>
</td><td>
	<input type=text name=dt_rate value=\"$labor_type_info->dt_rate\">
</td></tr>

<tr><td colspan=2 align=right>
	<input type=submit value=Save>
</td></tr>

</table>

";


?>
