<?
if (!($adminuser)) die("ERROR: Security Violation!!! The authorities have been notified!");

if ($maint_type_id!="") {
	$maint_type_id=escapeshellcmd($maint_type_id);
	$maint_type_info=getone("select * from svc_maint_types where maint_type_id = '$maint_type_id'");
	$maint_type_info->alternate_frequency_options=checkbreak($maint_type_info->alternate_frequency_options);
	$maint_type_info->salesman_selects_start_date=checkbreak($maint_type_info->salesman_selects_start_date);
	$maint_type_info->def_times_a_year=float_break($maint_type_info->def_times_a_year);
	$maint_type_info->def_min_times_a_year=float_break($maint_type_info->def_min_times_a_year);
	}




echo "
<center><h3>Edit Maintenance Type</h3></center><hr>


<form name=maint_type_edit>
<input type=hidden name=mode value=lists_maintenance_type_submit>
<input type=hidden name=maint_type_id value=\"$maint_type_info->maint_type_id\">
<table border=1 cellspacing=0 cellpadding=5>

<tr><td>
	<b>Maintenance type:</b>
</td><td>
	<input type=text size=20 name=maint_type value=\"$maint_type_info->maint_type\">
</td></tr>

<tr><td>
	<b>Default times a year</b>
</td><td>
	<input type=text size=20 name=def_times_a_year value=\"$maint_type_info->def_times_a_year\">
</td></tr>

<tr><td>
	<b>Default minimum times a year</b>
</td><td>
	<input type=text size=20 name=def_min_times_a_year value=\"$maint_type_info->def_min_times_a_year\">
</td></tr>

<tr><td>
	<b>Alternate frequency selection</b>
</td><td>
	<input type=checkbox name=alternate_frequency_options $maint_type_info->alternate_frequency_options>
</td></tr>

<tr><td>
	<b>Salesman can set effective date</b>
</td><td>
	<input type=checkbox name=salesman_selects_start_date $maint_type_info->salesman_selects_start_date>
</td></tr>





<tr><td colspan=2 align=right>
	<input type=submit value=Save
</td></tr>


</table>
</form>







";










?>
