<?

if ($el_id=="") die("Application error: Missing el_id. Aborting!");
else $el_id=addslashes($el_id);
$equip_info=load_equip_info($el_id);
$frequency_in_months=addslashes($frequency_in_months);
$agreement_id=$equip_info->agreement_id;
$material_list_id=addslashes($material_list_id);
$qty=addslashes($qty);
$description=addslashes($description);
$cost=clean_float($cost);
$show_in_summary=checkfix($show_in_summary);
$event_type=addslashes($event_type);

if ($cost==0) die("ERROR: Cost must not be zero or below!!!!!");



$dates=agreement_event_dates_by_month($agreement_id,vali_date($event_date),$frequency_in_months);

$count=0;
$endcount=sizeof($dates);
while ($dates[$count]!="") {
	$query="insert into svc_agreement_equipment_events set
	el_id = '$equip_info->el_id',
	event_type = '$event_type',
	event_date = '" . $dates[$count] . "',
	cost = '$cost',
	inflation = 'Y',
	description = '$description',
	show_in_summary = '$show_in_summary'";

	$res=@mysql_query($query);
	//echo "<hr>$query";
	
	if (!($res)) die("query failed:<hr>$query");
	$count++;
	}
	
echo "
<script>
opener.document.location.reload();
self.close();
</script>
";
?>
