<?

switch ($event_type) {
	case "materials":
					include("svc_agreement_equipment_event_add_materials.phtml");
					exit;
					break;;

	case "predict_vibration":
					include("svc_agreement_equipment_event_add_predict_vibration.phtml");
					exit;
					break;;

	case "predict_refrigerant_lp":
					include("svc_agreement_equipment_event_add_predict_refrigerant_lp.phtml");
					exit;
					break;;

	case "predict_refrigerant_hp":
					include("svc_agreement_equipment_event_add_predict_refrigerant_hp.phtml");
					exit;
					break;;

	case "predict_laser_alignment":
					include("svc_agreement_equipment_event_add_predict_laser_alignment.phtml");
					exit;
					break;;

	case "predict_eddy_current_tube_anal":
					include("svc_agreement_equipment_event_add_predict_eddy_current_tube_anal.phtml");
					exit;
					break;;

	case "predict_thermography":
					include("svc_agreement_equipment_event_add_predict_thermography.phtml");
					exit;
					break;;

	case "predict_combustion":
					include("svc_agreement_equipment_event_add_predict_combustion.phtml");
					exit;
					break;;

	case "predict_oil":
					include("svc_agreement_equipment_event_add_predict_oil.phtml");
					exit;
					break;;


}


echo "oops";





?>
