<?
if ($agreement_id=="") die ("ERROR: Missing agreement_id. Can not continue. Please contact your system administrator.");
else $agreement_id=addslashes($agreement_id);
$agreement_info=load_agreement_info($agreement_id);
if (!($agreement_info)) die ("ERROR: Could not load agreement info. Fatal error. Please contact your system administrator!");


include("header.phtml");


echo "
<a href=$pagename?mode=svc_agreement_edit&agreement_id=$agreement_info->agreement_id><font color=blue>Cancel</font></a><p>

<form name=copy_agreement method=post action=$pagename>
<input type=hidden name=mode value=\"svc_agreement_copy_submit\">
<input type=hidden name=agreement_id value=\"$agreement_info->agreement_id\">



<h2>Agreement Copy</h2>
<table border=1>

<tr bgcolor=#88aa88><td align=center colspan=2>
	<font size=+1><b>Source</b></font>
</td></tr>

<tr bgcolor=#eeeeee><td> Agreement Name
</td><td>
	$agreement_info->agreement_name
</td></tr>

<tr bgcolor=#eeeeee><td>
	Status
</td><td>
	$agreement_info->status
</td></tr>

<tr bgcolor=#eeeeee><td>
	Agreement Type
</td><td>
	$agreement_info->agreement_type
</td></tr>

<tr bgcolor=#eeeeee><td>
	Start Date
</td><td>
	$agreement_info->expected_start_date
</td></tr>

<tr bgcolor=#eeeeee><td>
	Term
</td><td>
	$agreement_info->years
</td></tr>

<tr bgcolor=#cc6666><td align=center colspan=2>
	<font size=+1><b>Target</b></font>
</td></tr>

<tr><td>
	Agreement_name
</td><td>
	<input type=text size=45 name=agreement_name value=\"$agreement_info->agreement_name copy\">
</td></tr>

<tr><td>
	Status
</td><td>
	New
</td></tr>

<tr><td>
	Agreement Type
</td><td>
	<select name=agreement_type>
	<option value=\"\">Copy</option>
	<option>PSP</option>
	<option>ESP</option>
	<option>ISP</option>
	</select>
</td></tr>

<tr><td>
	Start Date
</td><td>
	$agreement_info->expected_start_date
</td></tr>

<tr><td>
	Term
</td><td>
	$agreement_info->years
</td></tr>

<tr><td colspan=2 align=right>
	<input type=submit value=Copy>
</td></tr>

</table>
</form>

";
?>
