<?
if ($agreement_id=="") die("ERROR: Application error. Please call your system administrator!");
$agreement_info=load_agreement_info($agreement_id);
if (!($agreement_info)) die("ERROR: Invalid agreement. Application error! Please contact your system administrator!");
if ($agreement_info->status!="New") {
	forward("svc_agreement_edit_finalize&agreement_id=$agreement_id");
	exit;
	}


echo "
<a href=$pagename?mode=main><font color=blue>Cancel</font></a>
<br>

<script>
function shorten_term() {
	if(confirm(\"Are you sure? You CAN'T undo this (make a copy first!)\")) {
		newterm=prompt('What is the new term you desire?','1');
		if (newterm) document.location='$pagename?mode=svc_agreement_shorten_term&agreement_id=$agreement_info->agreement_id&newterm=' + newterm;
		}
	}
</script>

<table border=1 cellspacing=0 cellpadding=3 align=right><tr><td bgcolor=blue>
<table border=1 cellspacing=0 cellpadding=2>
<tr><td bgcolor=#ffffaa><b>Status Changes</b></td></tr>
<tr><td bgcolor=#ffffff><a href=$pagename?mode=svc_agreement_transfer&agreement_id=$agreement_info->agreement_id><font color=blue>Change Owner</font></a></td></tr>";
if ($agreement_info->years > 1) echo "<tr><td bgcolor=#ffaaaa><a href=javascript:shorten_term();><font color=blue>Shorten Term</font></a></td></tr>";echo "
<tr><td bgcolor=#aaffaa><a href=$pagename?mode=svc_agreement_copy&agreement_id=$agreement_info->agreement_id><font color=blue>Copy Agreement</font></a></td></tr>
<tr><td bgcolor=#ffffff><a href=$pagename?mode=svc_agreement_edit_finishing&agreement_id=$agreement_info->agreement_id><font color=blue>Complete Agreement</font></a></td></tr>
</table>
</td></tr></table>



";

if (is_admin()) {
	if ($agreement_info->agreement_type=="ESP") {
		echo "<script>
		function approve_all_equip() {
		open('$pagename?mode=svc_agreement_equipment_approve_all_popup&agreement_id=$agreement_info->agreement_id','equip_approve_all_win','width=100,height=100');
		}
		</script>
		<br><a href=javascript:approve_all_equip();><font color=red>
		Mark all equipment approved</font></a>
		";
		}
	}

if (!(isset($show_totals))) {
	$show_totals=FALSE;
	session_register('show_totals');
	}
if ($show_totals_change=='N') $show_totals=FALSE;
if ($show_totals_change=='Y') $show_totals=TRUE;

if (($show_totals==TRUE)&&(is_admin())) {
	echo "<br><a href=$pagename?mode=svc_agreement_edit_new&agreement_id=$agreement_id&show_totals_change=N><font color=blue>Hide totals</font></a>";
	} 
	
if (($show_totals==FALSE)&&(is_admin())) {
	echo "<br><a href=$pagename?mode=svc_agreement_edit_new&agreement_id=$agreement_id&show_totals_change=Y><font color=blue>Show totals</font></a>";
	}


echo "
<h3>Agreement Edit</h3><hr>
<form method=post action=$pagename name=agreement_edit>
<input type=hidden name=mode value=svc_agreement_submit>
<input type=hidden name=agreement_id value=\"$agreement_info->agreement_id\">
<input type=hidden name=status value=\"$agreement_info->status\">
<input type=hidden name=agreement_type_id value=\"$agreement_info->agreement_type_id\">
<table border=0>

<tr><td>
	Agreement Name:
</td><td>
	<input type=text size=50 name=agreement_name value=\"$agreement_info->agreement_name\">
</td></tr>

<tr><td>
	Printed Agreement Title <i>(optional)</i>:
</td><td>
	<input type=text size=50 name=agreement_printed_title value=\"$agreement_info->agreement_printed_title\">
</td></tr>

<tr><td>
	Agreement notes:
</td><td>
	<textarea rows=3 cols=50 name=agreement_notes>$agreement_info->agreement_notes</textarea>
</td></tr>

<tr><td>
	Company:
</td><td>
	";contactsbox("select * from contacts where contact_type = 'company' and current = 'Y'",$agreement_info->company_id,"company_id","",2);echo "
</td></tr>

<tr><td>
	Site:
</td><td>
	";contactsbox("select * from contacts where ( contact_type = 'site' and company_id = '$agreement_info->company_id' and current = 'Y' ) or contacts_id = '$agreement_info->company_id'",$agreement_info->site_id,"site_id","",0);echo "
</td></tr>

<tr><td>
	Contact:
</td><td>
	";contactsbox("select * from contacts where contact_type = 'contact' and current = 'Y' and company_id = '$agreement_info->company_id'",$agreement_info->customer_contact_id,"customer_contact_id","",0);echo "
</td></tr>

<tr><td>
	Status:
</td><td>
	$agreement_info->status
</td></tr>

<tr><td>
	Agreement&nbsp;Type:
</td><td>
	$agreement_info->agreement_type
</td></tr>

<tr><td>
	Term:
</td><td>
	$agreement_info->years
	<input type=hidden name=years value=\"$agreement_info->years\">
</td></tr>

<tr><td>
	Start&nbsp;Date:";if ($adminuser) { echo "<br>Override&nbsp;Date:"; } echo"
</td><td>
	$agreement_info->expected_start_date
	<input type=hidden name=expected_start_date value=\"$agreement_info->expected_start_date\">
	";
	//datebox($agreement_info->expected_start_date,"agreement_edit.expected_start_date");
	
	if ($adminuser) {
		datebox($agreement_info->expected_start_date_override,"agreement_edit.expected_start_date_override");
		} else {
		echo "<input type=hidden name=expected_start_date_override value=\"$agreement_info->expected_start_date_override\">";
		}
	
	echo "
</td></tr>

<tr><td>
	Billing<br>Method:
</td><td>
	<select name=billing_frequency>
		<option selected>$agreement_info->billing_frequency</option>
		<option>Monthly</option>
		<option>Quarterly</option>
		<option>Semiannually</option>
		<option>Annual Sum Only</option>
	</select>
</td></tr>


";
if (is_admin()) {
	echo "
	<tr><td>
		Admin Forced Final Total<br>
		<i>(0.00 = disabled)</i>
	</td><td>
		<input type=text size=10 name=forced_total_value value='$agreement_info->forced_total_value'>
	</td></tr>
	";
	}
echo "
<tr><td colspan=2 align=right>
	<input type=submit value=Save>
</td></tr>
</table>
</form>

";

if ($agreement_info->agreement_type_id==2) {
	echo "<b>Equipment</b>&nbsp;&nbsp;&nbsp;<a href=$pagename?mode=svc_agreement_equipment_add_1&agreement_id=$agreement_info->agreement_id><font color=blue><i>(Add)</i></font></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href=$pagename/bogus/inspection_summary.pdf?mode=show_inspection_summary_pdf&agreement_id=$agreement_info->agreement_id target=inspection_summary><font color=blue>Show Inspection Summary</font></a><hr>";
	} else {
	echo "<b>Equipment</b>&nbsp;&nbsp;&nbsp;<a href=$pagename?mode=svc_agreement_equipment_add_2&agreement_id=$agreement_info->agreement_id><font color=blue><i>(Add)</i></font></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href=$pagename/bogus/inspection_summary.pdf?mode=show_inspection_summary_pdf&agreement_id=$agreement_info->agreement_id target=inspection_summary><font color=blue>Show Inspection Summary</font></a><hr>";
	}	
echo "<a href=$pagename?mode=svc_agreement_download_equipment&agreement_id=$agreement_info->agreement_id><font color=blue><i>Download Equipment List to Excel</i></font></a>";


//$query="select * from svc_agreement_equip_list 
//left join svc_equip_categories using (category_id) 
//left join svc_equip_types using (category_id)
//where agreement_id = '$agreement_info->agreement_id' order by category,type";



$query="select el_id,supervisor_approved,age from svc_agreement_equip_list 
left join svc_equip_categories using (category_id) 
left join svc_equip_types on svc_agreement_equip_list.equip_type_id = svc_equip_types.equip_type_id
where agreement_id = '$agreement_info->agreement_id' 
order by svc_equip_categories.category,svc_equip_types.type,svc_agreement_equip_list.el_id ";
$res=@mysql_query($query);

$rowcount=@mysql_num_rows($res);
if ($rowcount>0) {
	echo "
	<script>
	function delete_equip(el_id) {
		if (confirm('Are you sure you want to delete this equipment?')) open('$pagename?mode=delete_equipment_popup&el_id=' + el_id,'equip_delete_popup','width=100,height=100');
		}

	function copy_equip(el_id) {
		open('$pagename?mode=copy_equipment_popup&el_id=' + el_id,'equip_copy_popup','width=100,height=150');
		}

	function tag_edit(el_id) {
		open('$pagename?mode=equip_tag_num_popup&el_id=' + el_id,'eqtnpopup','width=300,height=100');
		}

	function tag_set(el_id,newtext) {
		tag_id=\"tag_num\" + el_id;
		document.getElementById(tag_id).innerHTML=newtext;
		}
		
	function serial_edit(el_id) {
		open('$pagename?mode=equip_serial_num_popup&el_id=' + el_id,'eqsnpopup','width=300,height=100');
		}

	function serial_set(el_id,newtext) {
		serial_id=\"serial_num\" + el_id;
		document.getElementById(serial_id).innerHTML=newtext;
		}
	</script>
	
	<table border=1 cellspacing=0 cellpadding=2>
	<tr bgcolor=#dddddd><td>
		#
	</td><td align=center>
		<b>Type</b>
	</td><td>
		<b>Manufacturer</b>
	</td><td>
		<b>Age</b>
	</td><td>
		<b>Cust Tag #</b>
	</td><td>
		<b>Serial #</b>
	</td><td>
		&nbsp;
	</td><td>
		&nbsp;
	</td><td>
		&nbsp;
	</td></tr>
	";
	if ($agreement_info->agreement_type=="ESP") $check_age=1;
	else $check_age=0;
	$count=1;
	while ($row=@mysql_fetch_object($res)) {
		$equip_info=load_equip_info($row->el_id,$check_age);
		if ($row->supervisor_approved!='Y') {
			$rowcolor="#ffffff";
			if ($equip_info->age_safe==TRUE) {
				$rowcolor="#ffffff";
				} else {
				$rowcolor="#dd7777";
				}
		} else {
			$rowcolor="#aaffaa";
			}
		if ($equip_info->tag_num=="") $equip_info->tag_num="<i>&lt;missing&gt;</i>";
		//<tr bgcolor=\"$rowcolor\"><td>
		
		echo "
		<tr bgcolor=$rowcolor><td>
			$count
		</td><td>
			$equip_info->class
		</td><td>
			$equip_info->mfg_name
		</td><td>
			$equip_info->age_text
		</td><td>
			<a href=javascript:tag_edit($equip_info->el_id);><font id=\"tag_num$equip_info->el_id\" color=blue>$equip_info->tag_num</font></a>
		</td><td>
			<a href=javascript:serial_edit($equip_info->el_id);><font id=\"serial_num$equip_info->el_id\" color=blue>$equip_info->serial_num</font></a>
		</td><td>
			<a href=$pagename?mode=svc_agreement_equipment_edit&el_id=$equip_info->el_id><font color=blue><i>Edit</i></font></a>
		</td><td>
			<a href=javascript:copy_equip($equip_info->el_id);><font color=blue><i>Copy</i></font></a>
		</td><td>
			<a href=javascript:delete_equip($equip_info->el_id);><font color=blue><i>Delete</i></font></a>
		</td></tr>
		";
		$count++;
		}
	echo "</table>";
	
	
	
	
	
	}

if ($show_totals) {
	$cost=agreement_cost($agreement_info->agreement_id);
	echo "<b>Total current UMC cost: </b> \$$cost<p>";
	}
echo "<p>";
include("svc_agreement_edit_doclist.phtml");


?>
