<?

$agreement_id=escapeshellcmd($agreement_id);
$agreement_info=load_agreement_info($agreement_id);
$age=escapeshellcmd($age);
$category_id=escapeshellcmd($category_id);
$equip_type_id=escapeshellcmd($equip_type_id);
$mfg=escapeshellcmd($mfg);
$age=escapeshellcmd($age);
$model_number=escapeshellcmd($model_number);
$serial_num=escapeshellcmd($serial_num);
$tag_num=escapeshellcmd($tag_num);
$location=escapeshellcmd($location);

$query="
insert into svc_agreement_equip_list set
agreement_id = '$agreement_id',
category_id = '$category_id',
equip_type_id = '$equip_type_id',
mfg = '$mfg',
age = '$age',
model_number = '$model_number',
serial_num = '$serial_num',
tag_num = '$tag_num',
location = '$location'
";


$res=@mysql_query($query);
$insid=@mysql_insert_id();
echo "Equipment inserted<hr>";flush();

el_create_tasks($insid);

forward("svc_agreement_equipment_edit&el_id=$insid");

?>
