<?
require('header.phtml');
$borrowed_task_list=0;

if (FALSE) {
$res=@mysql_query("select task_id from svc_task_items");
$total_count=@mysql_num_rows($res);
echo "Going to sync a total of $total_count<p>";
while ($row=@mysql_fetch_object($res)) {
	echo ".....$row->task_id.....<br>";
	sync_psp_task($row->task_id);
	sync_psp_task($row->task_id,"ISP");
	flush();
	}
exit;
}

if ($task_id!="") {
	$task_id=escapeshellcmd($task_id);
	//$task_info=getone("select * from svc_task_items where task_id = '$task_id'");
	$task_info=load_task_info($task_id);
	$task_info->subs_required=checkbreak($task_info->subs_required);
	$task_info->predictive_svc_avail=checkbreak($task_info->predictive_svc_avail);
	$task_info->export_psp_to_esp=checkbreak($task_info->export_psp_to_esp);
	$task_info->export_psp_to_esp_force=checkbreak($task_info->export_psp_to_esp_force);
	$equip_type_id=$task_info->equip_type_id;
	$agreement_type_id=$task_info->agreement_type_id;
	$maint_type_id=$task_info->maint_type_id;
	$new=0;

	///////////////////////////////////////////////////////////////
	// Load ID's of all the agreement types for this equipment type
	///////////////////////////////////////////////////////////////
	$esptmp=getone("select agreement_type_id from svc_agreement_types where agreement_type = 'ESP'"); 
	$espid=$esptmp->agreement_type_id;
	
	$psptmp=getone("select agreement_type_id from svc_agreement_types where agreement_type = 'PSP'"); 
	$pspid=$psptmp->agreement_type_id;
	
	$isptmp=getone("select agreement_type_id from svc_agreement_types where agreement_type = 'ISP'"); 
	$ispid=$isptmp->agreement_type_id;
	} else {
	$new=1;
	}

if (($equip_type_id=="")||($agreement_type_id=="")||($maint_type_id=="")) die("ERROR: Application error. Please contact your system administrator.");
	
$equip_type_id=escapeshellcmd($equip_type_id);
$agreement_type_id=escapeshellcmd($agreement_type_id);
$maint_type_id=escapeshellcmd($maint_type_id);

$equip_info=getone("select * from svc_equip_types where equip_type_id = '$equip_type_id'");
$category_info=getone("select * from svc_equip_categories where category_id = '$equip_info->category_id'");
$agreement_info=getone("select * from svc_agreement_types where agreement_type_id = '$agreement_type_id'");
$maint_info=getone("select * from svc_maint_types where maint_type_id = '$maint_type_id'");

if ($new==1) {
	$task_info->recommended_times_a_year=float_break($maint_info->def_times_a_year);
	$task_info->required_times_a_year=float_break($maint_info->def_min_times_a_year);
	$task_info->approval_required_age="30";
	}


//if (!(compare_task_items(48,48))) echo "!Same<br>";


echo "

<a href=$pagename?mode=lists_equip_type_edit&category_id=$equip_info->category_id&agreement_type_id=$agreement_type_id&maint_type_id=$maint_type_id&equip_type_id=$equip_type_id><font color=blue>Return to equipment type</font></a><br>

<h3>Task Information</h3>
$category_info->category&nbsp;:&nbsp;
$task_info->equip_type&nbsp;:&nbsp;$agreement_info->agreement_type&nbsp;:&nbsp;$maint_info->maint_type<br>
<hr>
<form name=task_item_edit method=get action=$pagename>
<input type=hidden name=task_id value=\"$task_info->task_id\">
<input type=hidden name=mode value=task_item_submit>
<input type=hidden name=equip_type_id value=\"$equip_type_id\">
<input type=hidden name=agreement_type_id value=\"$agreement_type_id\">
<input type=hidden name=maint_type_id value=\"$maint_type_id\">
<table border=0 cellspacing=0 cellpadding=3>
<tr><td>
	Recommended times a year:
</td><td>
	<input type=text size=3 name=recommended_times_a_year value=\"$task_info->recommended_times_a_year\">
</td></tr>

<tr><td>
	Minimum times a year:
</td><td>
	<input type=text size=3 name=required_times_a_year value=\"$task_info->required_times_a_year\">
</td></tr>

<tr><td>
	Approval required age:
</td><td>
	<input type=text size=3 name=approval_required_age value=\"$task_info->approval_required_age\">
</td></tr>

<tr><td>
	Subs Required:
</td><td>
	<input type=checkbox name=subs_required $task_info->subs_required>
</td></tr>

<tr><td>
	Predictive Service Available:
</td><td>
	<input type=checkbox name=predictive_svc_avail $task_info->predictive_svc_avail>
</td></tr>

<tr><td>
	Misc Fees
</td><td>
	<input type=text size=6 name=misc_fees value=\"$task_info->misc_fees\">
</td></tr>
";

if ($task_info->agreement_type_id==$pspid) {
echo "
	<tr><td>
		Copy to ESP if blank:
	</td><td>
		<input type=checkbox name=export_psp_to_esp $task_info->export_psp_to_esp>
	</td></tr>
	
	<tr><td>
		Overwrite existing ESP:
	</td><td>
		<input type=checkbox name=export_psp_to_esp_force $task_info->export_psp_to_esp_force>
	</td></tr>
	";
	}
///////////////////////////////////////////////////////////////////////////////////////////
//	This is the old version that warned for ISP's when the sync was configured
//	...just remove 1/2 of the "or" and the warning side of isp->psp link is broken
///////////////////////////////////////////////////////////////////////////////////////////
//if (($task_info->agreement_type_id==$espid) || ($task_info->agreement_type_id==$ispid)) {
if ($task_info->agreement_type_id==$espid) {
	$psp_task=getoneb("select * from svc_task_items where equip_type_id = '$task_info->equip_type_id' and agreement_type_id = '$pspid' and maint_type_id = '$task_info->maint_type_id'");
	if ($psp_task) {
		if ($psp_task->export_psp_to_esp_force=='Y') {
			echo "<script>alert('Warning! This will be overwritten the next time PSP is viewed or modified!!!!');</script>";
			}
		}
	}

echo "
<tr><td colspan=2 align=right>
	<input type=submit value=Save>
</form>
</td></tr>

";

if ($task_id!="") {
sync_psp_task($task_id);

///////////////////////////////////////////////////////////////
//	It looks like this is the only place that I need to hit
//	to break the link between ESP's and ISP's..
///////////////////////////////////////////////////////////////
//sync_psp_task($task_id,"ISP");
	echo "
<tr><td>
	<table border=1 cellspacing=0 cellpadding=3>
		<tr><td colspan=3 align=center>
			&nbsp;&nbsp;<b>Required&nbsp;Hours</b>&nbsp;<i>(<a href=$pagename?mode=task_hrs_edit&task_id=$task_id><font color=blue>Add</font></a>)&nbsp;&nbsp;
		</td></tr>";
		
		$hrs_res=@mysql_query("select * from svc_task_hrs,svc_labor_types where task_id = '$task_id' and svc_task_hrs.labor_type_id = svc_labor_types.labor_type_id");
		while ($hrs_row=@mysql_fetch_object($hrs_res)) {
			echo "<tr><td>
					$hrs_row->labor_type
				</td><td>
					$hrs_row->hrs
				</td><td>
					<a href=$pagename?mode=task_hrs_edit&task_hrs_id=$hrs_row->task_hrs_id><font color=blue><i>Edit</i></font></a>
				</td></tr>
				";
			}
		echo "
	</table>
</td><td>
";
}

echo "</td></tr></table>";


if ($task_info->task_id >0) {
	//echo "Task info seems to be set<p>";


$tasks=@mysql_query("select * from svc_task_lists where task_id = '$task_info->task_id' order by task_list_number");
$task_count=@mysql_num_rows($tasks);

//if ($task_info->agreement_type_id==$ispid) {
//	if ($task_count < 1) {
//		$psp_task=getoneb("select task_id from svc_task_items 
//		where equip_type_id = '$task_info->equip_type_id' 
//		and agreement_type_id = '$pspid' 
//		and maint_type_id = '$task_info->maint_type_id'");
//		if ($psp_task) {
//			copy_task_list($psp_task->task_id,$task_info->task_id);
//			echo "<script>
//			alert('Task list initialized using the task list from the PSP agreement type');
//			</script>
//			";
//			$tasks=@mysql_query("select * from svc_task_lists where task_id = '$task_info->task_id' order by task_list_number");
//			$task_count=@mysql_num_rows($tasks);
//			}
//		
//		}
//	
//	
//	}
//
//echo "<hr>$pspid/$ispid<hr>";
//tabledump("select task_id from svc_task_items where equip_type_id = '$task_info->equip_type_id' and agreement_type_id = '$pspid' and maint_type_id = '$task_info->maint_type_id'");
//exit;

if ($task_count>0) $confirm_paste='Y';
else $confirm_paste='N';

echo "
<script>
function copy_task_list() {
	open(\"$pagename?mode=copy_task_list&task_id=$task_info->task_id\",\"copy_task_list_win\",\"height=100,width=100\");
	}
function paste_task_list() {
	if ('$confirm_paste'!='N') {
		if (confirm('Overwrite existing task list?'))
			open(\"$pagename?mode=paste_task_list&task_id=$task_info->task_id\",\"paste_task_list_win\",\"height=200,width=200\");
		} else {
			open(\"$pagename?mode=paste_task_list&task_id=$task_info->task_id\",\"paste_task_list_win\",\"height=200,width=200\");
		}
	}
</script>
<hr>
<h3>Task list for this item:</h3><hr>
<a target=_pdf_task_list href=\"$pagename/task_list-$task_id.php?blash=blah&mode=show_task_list_pdf&task_id=$task_id&blah=blah/task_list-$task_id.pdf\"><font color=blue>View PDF</font></a>&nbsp;&nbsp;&nbsp;<a href=javascript:copy_task_list();><font color=blue>Copy Task List</font></a>&nbsp;&nbsp;&nbsp;<a href=javascript:hello_tasks()><font color=blue>EZ Task List</font></a>";

if (($task_list_copy_task_id!="")&&($task_list_copy_task_id!=$task_info->task_id)) {
	echo "&nbsp;&nbsp;&nbsp;<a href=javascript:paste_task_list();><font color=blue>Paste Task List</font></a>";
	}





echo "<br>
<table border=0>
<form name=task_append method=post action=$pagename>
<input type=hidden name=mode value=task_list_append>
<input type=hidden name=task_id value=\"$task_info->task_id\">
<tr><td><b>ADD: </b></td><td><input type=text size=60 name=task_text onchange=submit();></td></tr>
</form>
";

if ($task_count<1) {
	echo "
	<form name=task_list_import method=post action=$pagename>
	<input type=hidden name=mode value=task_list_import>
	<input type=hidden name=task_id value=\"$task_info->task_id\">
	<tr><td><b>Batch Add: </b></td><td><textarea name=task_text rows=5 cols=45></textarea>&nbsp;<input type=submit value=\"Submit Batch\"></td></tr>
	</form>
	";
	
	$short_query="select * from svc_task_lists_shorted where agreement_type_id = '$agreement_type_id' and maint_type_id = '$maint_type_id'";
	//tabledump($short_query);
	$shorted_results=getoneb($short_query);
	if ($shorted_results) {
		$new_task_info=getone("select * from svc_task_items where equip_type_id = '$equip_type_id' and agreement_type_id = '$shorted_results->agreement_type_id_target' and maint_type_id = '$maint_type_id'");
		
		//tabledump("select * from svc_task_items where equip_type_id = '$equip_type_id' and agreement_type_id = '$shorted_results->agreement_type_id_target' and maint_type_id = '$maint_type_id'");
		$tasks=@mysql_query("select * from svc_task_lists where task_id = '$new_task_info->task_id' order by task_list_number");
		//$tasks=@mysql_query("select * from svc_task_lists where task_id = '$task_info->task_id' order by task_list_number");
		$borrowed_task_list=1;
		}
	
	}

echo "</table>";

if ($borrowed_task_list==1) {
	echo "<table border=1 cellspacing=4 cellpadding=0 bgcolor=#dddddd><tr><td align=center><font size=+2><b>Borrowed Task List</b></font><br><i>(Add tasks to override this list)</i>";
	}
echo "<table border=0>";
$t_list_text="";
while($trow=@mysql_fetch_object($tasks)) {
	echo "<tr><td>
			";
			if ($borrowed_task_list==1) echo "&nbsp;";
			else echo "<a href=$pagename?mode=task_lists_move_up&task_list_id=$trow->task_list_id style=\"color: blue;\">/\\</a>";
			echo "
		</td><td>
			<b>$trow->task_list_number.</b>
		</td><td>
			<b>$trow->task_text</b>
		</td><td>
			";
			if ($borrowed_task_list==1) echo "&nbsp;";
			else echo "
			<a href=$pagename?mode=task_list_item_edit&task_list_id=$trow->task_list_id style=\"color: blue;\"><i>Edit</i></a>
			&nbsp;&nbsp;
			<a href=$pagename?mode=task_list_item_delete&task_list_id=$trow->task_list_id style=\"color: blue;\"><i>Delete</i></a>
			";
			echo "
		</td></tr>
		";
		$t_list_text=$t_list_text . $trow->task_list_number . ". " . $trow->task_text . "\r\n";
		}
echo "</table>

<script>
function hello_tasks() {
	//alert('hi');
	document.t_list_holder.t_list_text.style.display='block';
	document.t_list_holder.t_list_text.select();
	}
</script>

<form name=t_list_holder>
<textarea STYLE=\"display:none\" name=t_list_text rows=5 cols=30>
$t_list_text
</textarea>
</form>
";

if ($borrowed_task_list==1) {
	echo "</table>";
	}

if ($focus_tlist==1) {
	echo "
	<script>
	document.task_append.task_text.focus();
	</script>
	";
	}
}


?>
