<?
$task_list_id=escapeshellcmd($task_list_id);
$task_item_info=getone("select * from svc_task_lists where task_list_id = '$task_list_id'");
$del_res=@mysql_query("delete from svc_task_lists where task_list_id = '$task_list_id'");


$res=@mysql_query("select * from svc_task_lists where task_id = '$task_item_info->task_id' and task_list_number > '$task_item_info->task_list_number'");
while ($row=@mysql_fetch_object($res)) {
	$new_task_list_number=$row->task_list_number - 1;
	$query="update svc_task_lists set task_list_number = '$new_task_list_number' where task_list_id = '$row->task_list_id'";
	//echo "$query<hr>";
	@mysql_query($query);
	}
forward("task_item_edit&task_id=$task_item_info->task_id");

?>
