<? 
require('header.phtml');
fd_navs_header();
//pal_javascripts();

if ($form_defaults=='Y') {
	$pal_status="Active";
	$pal_assigned=$global_user_id;
	$list_description="My To Do List";
	}

echo "

<form name=pal_extras method=post action=$pagename>
<input type=hidden name=mode value=main>
<table border=1 cellspacing=0 cellpadding=4>
<tr><td bgcolor=#dddddd>
	<b>Status</b>
</td><td>
	<select name=pal_status>
	<option value=\"$pal_status\">$pal_status</option>
	<option value=\"\"></option>
	<option value=\"active\">Active</option>
	<option value=\"complete\">Complete</option>
	</select>
<b>Priority</b>
	<select name=pal_priority>
	<option value=\"$pal_priority\">$pal_priority</option>
	<option value=\"\"></option>
	<option value=\"normal\">Normal</option>
	<option value=\"high\">High</option>
	</select>
</td></tr>

<tr><td>
	<b>Assigned</b>
</td><td>
	";contact("select * from contacts where contact_type = 'contact' and login_name != '' and current = 'Y'","$pal_assigned",'pal_assigned','',array('jobinfo_id'=>"$global_jobinfo_id"));echo"
</td></tr>

<tr><td>
	<b>Creator</b>
</td><td>
	";contact("select * from contacts where contact_type = 'contact' and login_name != '' and current = 'Y'","$pal_creator",'pal_creator','',array('jobinfo_id'=>"$global_jobinfo_id"));echo"
</td></tr>
<tr><td colspan=2 align=right>
	<input type=submit value=\"Filter\">
</td></tr>
</table>
</form>

<a href=$pagename?mode=pal_create_unlinked&jobinfo_id=$global_jobinfo_id&pal_assigned=$pal_assigned&pal_status=$pal_status><font color=blue>Create New PAL</font></a>
";
$morewhere="";
if ($pal_status!="") {
	$pal_status=addslashes($pal_status);
	$morewhere=$morewhere . " and status = '$pal_status' ";
	}
if ($pal_priority!="") {
	$pal_priority=addslashes($pal_priority);
	$morewhere=$morewhere . " and priority = '$pal_priority' ";
	}
if ($pal_assigned!="") {
	$pal_assigned=addslashes($pal_assigned);
	$morewhere=$morewhere . " and owner_id = '$pal_assigned' ";
	}
if ($pal_creator!="") {
	$pal_creator=addslashes($pal_creator);
	$morewhere=$morewhere . " and creator_id = '$pal_creator' ";
	}
$query="select * from pal_buddies where jobinfo_id = '$global_jobinfo_id' $morewhere group by pal_id order by pal_num + 0 desc";
include("fd_log_paging.phtml");
show_pal_list($query);
fd_navs_footer();
?>
