<?
if ($pal_id=="") die ("Application error: Pal_ID!");
else $pal_id=addslashes($pal_id);
$pal_info=getone("select * from pal where pal_id = '$pal_id'");
$team_query="
select contacts.contacts_id,display_name from contacts_groups 
right join contacts_groups_members on 
	(contacts_groups.group_id = contacts_groups_members.group_id) 
right join contacts on 
	(contacts_groups_members.contacts_id = contacts.contacts_id) 
where jobinfo_id = '$pal_info->jobinfo_id' and contacts.umc_emp = 'Y' order by alphasort";

//////////////////////////////////////////////////////////////////
// Toggle things on & off if we have permissions.. 
//////////////////////////////////////////////////////////////////
if ($toggle_contacts_id!="") {
	$toggle_contacts_id=addslashes($toggle_contacts_id);
	$contact_info=getone("select * from contacts where contacts_id = '$toggle_contacts_id'");
	$current_ass=getoneb("select * from pal_assignments where pal_id = '$pal_info->pal_id' and owner_id = '$toggle_contacts_id'");
	if (!($current_ass)) {
		@mysql_query("insert into pal_assignments set pal_id = '$pal_info->pal_id', creator_id = '$global_user->contacts_id', owner_id = '$contact_info->contacts_id'");
		} else {
		@mysql_query("delete from pal_assignments where pal_id = '$pal_info->pal_id' and owner_id = '$contact_info->contacts_id'");
		}
	}
	
//////////////////////////////////////////////////////////////////
// Toggle people in batches (if we have permissions.. 
//////////////////////////////////////////////////////////////////
if ($batch_select_users=="true") {
	$ass_check_query=$team_query;
	$ass_res=@mysql_query($ass_check_query);
	while($ass_member=@mysql_fetch_object($ass_res)) {
		$ass=getoneb("select * from pal_assignments where pal_id = '$pal_info->pal_id' and owner_id = '$ass_member->contacts_id'");
		if ($ass) {
			if ($which_ones!="all") {
				if ($ass->creator_id==$global_user->contacts_id) {
					@mysql_query("delete from pal_assignments where pal_id = '$pal_info->pal_id' and owner_id = '$ass_member->contacts_id'");
					}
				}
			} else {
			if ($which_ones=="all") {
				@mysql_query("insert into pal_assignments set pal_id = '$pal_info->pal_id', creator_id = '$global_user->contacts_id', owner_id = '$ass_member->contacts_id'");
				}
			
			}
		}
	}	
/////////////////////////////////////////////////////////////////	
//	Mark all or none required as needed.. 
/////////////////////////////////////////////////////////////////	
if ($batch_select_required=="true") {
	if ($which_ones=="all") {
		@mysql_query("update pal_assignments set mso = 'Y' where pal_id = '$pal_info->pal_id' and creator_id = '$global_user->contacts_id'");
		} else {
		@mysql_query("update pal_assignments set mso = 'N' where pal_id = '$pal_info->pal_id' and creator_id = '$global_user->contacts_id'");
		}
	}
////////////////////////////////////////////////////////////////
// Toggle MSO on and off for specific assignments..  
////////////////////////////////////////////////////////////////
if ($pass_id_toggle!="") {
	$pass_id_toggle=addslashes($pass_id_toggle);
	$pass_info=getoneb("select * from pal_assignments where pass_id = '$pass_id_toggle'");
	if ($pass_info->mso=='Y') $pass_info->mso='N';
	else $pass_info->mso='Y';
	@mysql_query("update pal_assignments set mso = '$pass_info->mso' where pass_id = '$pass_info->pass_id'");
	}





include('pal_current.phtml');



exit;
$res=@mysql_query($team_query);
echo "
<center>
<div align=center style=\"margin-top: 5px; margin-bottom: 1px; width: 230px; border: 1px solid black;\">
	<font size=-2>
	<div>
		Select&nbsp;<a href=\"javascript:pal_select_ass($pal_info->pal_id,'all');\"><font color=blue>all</font></a>&nbsp;/&nbsp;<a href=\"javascript:pal_select_ass($pal_info->pal_id,'none');\"><font color=blue>none</font></a>&nbsp;&nbsp;&nbsp;&nbsp;Require&nbsp;<a href=\"javascript:pal_batch_select_required($pal_info->pal_id,'all');\"><font color=blue>selected</font></a>&nbsp;/&nbsp;<a href=\"javascript:pal_batch_select_required($pal_info->pal_id,'none');\"><font color=blue>none</font></a>
	</div>
	</font>
</div>
</center>
";
while($row=@mysql_fetch_object($res)) {
	$assignment=getoneb("select * from pal_assignments where pal_id = '$pal_info->pal_id' and owner_id = '$row->contacts_id'");
	$write="OK";
	$bgcolor=$fd_color_1;
	if ($assignment) {
		$bgcolor=$fd_color_4;
		if ($assignment->creator_id!=$global_user->contacts_id) {
			$creator_info=getoneb("select * from contacts where contacts_id = '$assignment->creator_id'");
			$write="NO";
			}
		}
	echo "<div width=100% align=left style=\"background: $bgcolor;\"><font size=-1>";
	
		echo "<div style=\"background: transparent; float: left; width: 180px;\">";
		if ($write=="OK") {
			echo "<a href=\"javascript:toggle_assignment($pal_info->pal_id,$row->contacts_id);\"><font color=blue>$row->display_name</font></a>";
			} else {
			echo "<font title=\"Created by: $creator_info->display_name\">$row->display_name</font>";
			}
		echo "</font></div>";
		
		echo "<div style=\"float: left; width: 70px;\"><font size=-1>";
		if ($assignment) {
			if ($write=="OK") {
				echo "
				<a href=\"javascript:pal_mso_toggle($pal_info->pal_id,$assignment->pass_id);\"><font color=blue>MSO: $assignment->mso</font></a>
				";
			} else {
				echo "
				MSO: $assignment->mso
				";
				}
			} else {
			echo "&nbsp;";
			} 
		echo "</font></div>";
		
		echo "<div style=\"float: left; width: 60px;\"><font size=-1>";
		if ($assignment) {
			echo "
			OK: $assignment->signed_off
			";
			} else {
			echo "&nbsp;";
			} 
		echo "</font></div>";
		
	if ($write!="OK") {
		echo "<div style=\"float: right; text-align: center; background: white; width: 8px;\"><a href=\"javascript:owner_alert('$creator_info->first_name $creator_info->last_name');\"><font size=-2 color=red>!</font></a></div>";
		}
	
	echo "<font size=-1>&nbsp;</font></div>";
	}



?>
