<?

//excel_dump("select sum(1) as count,display_name,fw_profile,ip_address,request_time_start,request_time_end,ip_tables_rule,enabled,expired,request_description from front_desk_remote_access_requests left join contacts on (contacts.contacts_id = front_desk_remote_access_requests.contacts_id) group by display_name order by sum(1) desc, display_name");
//die("select request_id,display_name,fw_profile,ip_address,request_time_start,request_time_end,ip_tables_rule,enabled,expired,request_description from front_desk_remote_access_requests left join contacts on (contacts.contacts_id = front_desk_remote_access_requests.contacts_id) order by request_id");
//excel_dump("select request_id,display_name,fw_profile,ip_address,request_time_start,request_time_end,ip_tables_rule,enabled,expired,request_description from front_desk_remote_access_requests left join contacts on (contacts.contacts_id = front_desk_remote_access_requests.contacts_id) order by request_id");
//exit;

$pal_id=addslashes($pal_id);
$pal_info=getoneb("select * from pal where pal_id = '$pal_id'");
if (!($pal_info)) {
	echo "<script>alert('Application error. Unable to load information for print.');self.close();</script>";
	die();
	}

$creator=getoneb("select * from contacts where contacts_id = '$pal_info->creator'");
$pal_job_info=getoneb("select * from jobinfo where jobinfo_id = '$pal_info->jobinfo_id'");
//echo "<pre>";
//print_r($pal_info);
//echo "</pre>";
echo "
<table border=1 cellspacing=0 cellpadding=2>

<tr><td colspan=2 bgcolor=$fd_color_4 align=center>
	<b>Pal Information</b>
</td></tr>

<tr><td>
	Pal #
</td><td>
	$pal_info->pal_num
</td></tr>

<tr><td>
	Job #
</td><td>
	$pal_job_info->contract_num
</td></tr>

<tr><td>
	Status
</td><td>
	$pal_info->status
</td></tr>

<tr><td>
	Priority
</td><td>
	$pal_info->priority
</td></tr>

<tr><td>
	Created
</td><td>
	$pal_info->create_date
</td></tr>

<tr><td>
	Creator
</td><td>
	$creator->display_name
</td></tr>

<tr><td>
	Subject
</td><td>
	$pal_info->short_description
</td></tr>

<tr><td>
	Action Required
</td><td>
	$pal_info->full_description
</td></tr>

<tr><td colspan=2 bgcolor=$fd_color_4 align=center>
	<b>Assignments</b>
</td></tr>

";
$res=@mysql_query("select * from pal_assignments where pal_id = '$pal_info->pal_id'");
while ($row=@mysql_fetch_object($res)) {
	$owner=getoneb("select * from contacts where contacts_id = '$row->owner_id'");
	echo "<tr valign=top><td>
			$owner->display_name
		</td><td>
			MSO: $row->mso<br>
			Viewed: $row->viewed<br>
			Signoff: $row->signed_off<br>
		</td></tr>
		";
	}
echo "
</table>

<script>
print();
self.close();
</script>

";


?>
