<?
if ($pal_id=="") die("ERROR");
else $pal_id=addslashes($pal_id);

$pal_info=getone("select * from pal where pal_id = '$pal_id'");
$res=@mysql_query("select * from pal_assignments right join contacts on (pal_assignments.owner_id = contacts.contacts_id) where pal_id = '$pal_info->pal_id' order by alphasort");
$count=@mysql_num_rows($res);
if ($count==0) echo "<font size=-1><b>Currently no one assigned to this item.</b></font>";
while ($row=@mysql_fetch_object($res)) {
	if ($bgcolor==$fd_color_1) $bgcolor=$fd_color_2;
	else $bgcolor=$fd_color_1;
	$mso_text="";
	if (($row->signed_off!='Y')&&($row->mso=='Y')) {
		$mso_text="<i>&nbsp;(OK&nbsp;reqd)</i>";
		}
	echo "<font size=-1>
	<div style=\"text-align: left; width: 100%; background: $bgcolor;\">
	<div style=\"overflow: hidden; float: left; height: 17px; width: 200px;\">$row->display_name$mso_text</div>";
		
	if ($row->signed_off=='Y') {
		$row->signed_off_date=invali_date($row->signed_off_date,'/');
		echo "<div style=\"float: right; width: 88px; color: white; background: green; text-align: center;\">$row->signed_off_date</div>";
	} else {
		//if ($row->owner_id!=$global_user->contacts_id) {
			
		//	if ($row->mso == 'Y') echo "<div style=\"float: left; width: 8px; text-align: center; background: white;\"><a href=\"javascript:mso_alert();\"><font color=red>!</font></a></div>";
		//	else echo "<div style=\"float: right; width: 8px;\">&nbsp;</div>";
		 //	echo "<div style=\"float: right; width: 80px;\">Cleared: $row->signed_off</div>";
		//	}
			 
		//	else {
		
		
		
		//echo "$row->owner_id / $global_user_id";
		$somebody=0;
		if ($pal_info->creator_id==$global_user_id) {
			// if I'm the pal owner, put a 'required' toggle... (mso)
			echo "<div style=\"float: right;\"><a href=\"javascript:pal_mso_toggle($pal_info->pal_id,$row->pass_id);\"><font color=blue>Reqd: $row->mso</font></a></div>";
			$somebody=1;
			}
		if ($row->owner_id==$global_user_id) {
			// else if I'm the assignee, then put a 'sign off' link..
			echo "<div style=\"float: right; width: 88px;\"><a href=\"javascript:pal_sign_off($pal_info->pal_id,$row->pass_id);\"><font color=blue>Sign Off</font></a></div>";
			$somebody=1;
			}
		if ($somebody==0) {
			// if I'm anyone else, put a signed off yes/no
			echo "N";
			}
		
		
		
		
		
		//	}
		}
	echo "
	&nbsp;</div></font>";
	}

	//hi




?>
