<?
if ($pal_id=='') die('Application error: Pal ID');

$pal_id=addslashes($pal_id);
$pal_info=getone("select * from pal where pal_id = '$pal_id'");

$pri_text_bg='';

if ($pal_info->priority=='normal') { $newpri='high'; $pri_text_bg='yellow'; }
else $newpri='normal';

@mysql_query("update pal set priority = '$newpri' where pal_id = '$pal_id'");
$pal_info->priority=$newpri;
echo "Pri:&nbsp;<font onclick=\"pal_change_priority($pal_info->pal_id);\" style=\"color: blue; background-color: $pri_text_bg;\">$pal_info->priority</font>";
?> 
