<?
include ('fd_document_box_header.phtml');
$response_needed_date=vali_date($response_needed_date);
@mysql_query("update gcrfilog set response_needed_date = '$response_needed_date' where gcrfi_id = '$doc_edit_info->app_record_id'");
//echo "<input type=text size=8 name=key_description id=doc_box_key_description value=\"$key_description\" onchange=fd_doc_change_key_description('$doc_info->doc_id','$doc_edit_info->doc_id')>";

datebox2($response_needed_date, 'form1.response_needed_date', "fd_doc_gcrfi_change_resp_reqd_date(this.id,$doc_info->doc_id,$doc_edit_info->doc_id)");

?>
