<?
//require_once("querylib.inc");
//require_once('local.inc');

echo "
<html><head><title>Service Proposals - List All</title></head>
<body bgcolor=white>
<a href=$pagename?mode=proposal_lists><font color=blue>Return to proposal lists</font></a><hr>
";


$query="select svc_proposals_id from svc_proposals,contacts where contacts_id = sales_person and sales_person = '$global_user_id' order by proposal_date,last_name,first_name,proposal_daily_count";
proplist($query);

?>
