<?
echo "
<html>
<head>
<title>Plotter use log</title>
</head>
<body bgcolor=white>
";

echo "
<form name=plotterform method=post>
<input type=hidden name=mode value=copy_submit>
<center>

<table border=1>
<td valign=top rowspan=3>
	<table border=0 width=100%>
	<tr><td bgcolor=#dddddd width=100%>Job Number:</td></tr>
	<tr><td><input type=hidden name=jobinfo_id value=\"$lastjob\" size=8 onchange=recalculate();>";
	dropbox("select jobinfo_id as 'rjob_num',contract_num, ' - ',left(job_name,13) from jobinfo where active = 'Y' and exclude_from_reproduction != 'y' order by contract_num","$lastjob",17,"swapjob()");echo "
	</td></tr>
	</table>
</td>

<tr><td valign=top>
	<table border=0 width=100%>
	<tr><td bgcolor=#dddddd width=100%>
		Username:
	</td></tr>
	</table>
	<input type=text name=user value=\"$lastuser\" onchange=recalculate();><br>
	";
	//dropbox("select user as 'luser',user as 'lusers' from $current group by user order by user","$lastuser",7,"swapuser()");
	dropbox("select user as 'luser',user as 'lusers' from $current where ((YEAR(CURRENT_DATE) - YEAR(entrydate)) < 1) group by user order by user","$lastuser",7,"swapuser()");
	echo "

</td>

<td valign=top align=right>

<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr><td bgcolor=#dddddd width=100%>
	Mode: 
</td></tr>
<tr><td>
	<input type=radio name=scanmode value=plot onclick=recalculate();>Plot
	<input type=radio name=scanmode value=scan onclick=recalculate();>Scan
	<input type=radio name=scanmode value=archive onclick=recalculate();>Archive<br>
</td></tr>
<tr><td bgcolor=#dddddd>
Size:
</td></tr>
</table>
<center>
<input type=button value=24x36 onclick=setsize1();>
<input type=button value=30x42 onclick=setsize2();>
<input type=button value=36x48 onclick=setsize3();>
</center>
Height:&nbsp;&nbsp;&nbsp;
<a href=javascript:heightminus();><img border=0 src=minus.png></a>
<input type=text name=height size=3 value=\"$lastheight\" onchange=recalculate();>
<a href=javascript:heightplus();><img border=0 src=plus.png></a>&nbsp;<br>
Width:&nbsp;&nbsp;&nbsp;
<a href=javascript:widthminus();><img border=0 src=minus.png></a>
<input type=text name=width size=3 value=\"$lastwidth\" onchange=recalculate();>
<a href=javascript:widthplus();><img border=0 src=plus.png></a>&nbsp;<br>

</td>

<td align=right valign=top>
<table border=0 width=100%>
<tr><td bgcolor=#dddddd width=100%>
Media:
</td></tr>
<tr><td>
<input type=radio name=media value=bond onclick=recalculate();>Bond
<input type=radio name=media value=vellum onclick=recalculate();>Vellum
<input type=radio name=media value=mylar onclick=recalculate();>Mylar
<input type=radio name=media value=digital onclick=recalculate();>Digital<br>

Color: <input type=checkbox name=color>

</td></tr>
<tr><td bgcolor=#dddddd>
Quantity:
</table>


<table border=0 cellspacing=0 cellpadding=0>
	<tr><td align=right>
		Originals:&nbsp;&nbsp;&nbsp;
	</td><td rowspan=2 valign=top>
		<a href=javascript:sheetsminus();><img border=0 src=minus.png></a>
		<input type=text name=sheets size=3 onchange=recalculate();>
		<a href=javascript:sheetsplus();><img border=0 src=plus.png></a>&nbsp;
	</td></tr>
	<tr><td align=right>
		<font size=-3 color=#777777>(Plotted or Scanned)&nbsp;&nbsp;&nbsp;</font> 
	</td></tr>
</table>
Copies:&nbsp;&nbsp;&nbsp;
<a href=javascript:usetsminus();><img border=0 src=minus.png></a>
<input type=text name=usets size=3 onchange=recalculate();>
<a href=javascript:usetsplus();><img border=0 src=plus.png></a>&nbsp;<br>
<input type=hidden name=sets>
</td>

</tr><tr>

<td valign=top>
	<table border=0 width=100%>
	<tr><td bgcolor=#dddddd width=100%>
	Plotter:
	</td></tr>
	<tr><td>
	<input type=radio name=plotter value=oce checked>OCE
	<input type=radio name=plotter value=\"iPF 820\">iPF 820
	</td></tr>
	<tr><td bgcolor=#dddddd>&nbsp;</td></tr>
	</table>
</td><td valign=top>
	<table border=0 width=100%>
	<tr><td align=right bgcolor=#dddddd width=100%>
	Notes:
	</td></tr>
	</table>
	<textarea name=notes rows=9 cols=26 wrap=soft scroll=auto></textarea>
</td><td bgcolor=#eeeeee>
	Total&nbsp;Sheets&nbsp;<input type=text size=9 name=total_sheets onchange=recalculate();><br>
	<input type=hidden size=9 name=area>
	<center>
	<input type=reset value=\"Clear Form\" width=100%><br>
	<input type=button value=\"Save Entry\" onclick=gosubmit(); width=100%><br>
	</center>
</td></tr>



</table>
</center>
</form>

<script>

function recalculate() {
	if (checkfields()) {
	usemode=scanmodecheck();
		if (usemode == 'plot') { document.plotterform.sets.value=document.plotterform.usets.value; }
		if (usemode == 'scan') { document.plotterform.sets.value=document.plotterform.usets.value; }
		if (usemode == 'archive') { 
			document.plotterform.sets.value=document.plotterform.usets.value; 
			document.plotterform.media.value='digital';
			}
	inchesarea=document.plotterform.width.value * document.plotterform.height.value;
	document.plotterform.area.value=Math.round((inchesarea / 144)*10)/10;
	document.plotterform.total_sheets.value=document.plotterform.sets.value * document.plotterform.sheets.value;
	}
}

function checkfields() {
	if (document.plotterform.width.value=='') return (cleartotals());
	if (document.plotterform.height.value=='') return (cleartotals());
	if (document.plotterform.sheets.value=='') return (cleartotals());
	if (document.plotterform.usets.value=='') return (cleartotals());

	if (document.plotterform.scanmode.value=='') return (cleartotals());
	if (document.plotterform.jobinfo_id.value=='') return (cleartotals());
	if (document.plotterform.user.value=='') return (cleartotals());
	if (!(scanmodecheck())) return (cleartotals());
	if (!(mediatypecheck())) return (cleartotals());
	
	return true;
	}

function cleartotals() {
	document.plotterform.area.value='';
	return false;
	}

function scanmodecheck() {
	t = document.plotterform.scanmode;
	for (i=0; i<= t.length; i++) if ((t[i]) && (t[i].checked)) return t[i].value;
	return false;
	}

function mediatypecheck() {
	t = document.plotterform.media;
	for (i=0; i<= t.length; i++) if ((t[i]) && (t[i].checked)) return t[i].value;
	return false;
	}

function mediatypeuncheck() {
	t = document.plotterform.media;
	for (i=0; i<= t.length; i++) if ((t[i]) && (t[i].checked)) return t[i].value;
	return false;
	}

function setsize1(){
	document.plotterform.height.value='24';
	document.plotterform.width.value='36';
	recalculate();
}
function setsize2(){
	document.plotterform.height.value='30';
	document.plotterform.width.value='42';
	recalculate();
}
function setsize3(){
	document.plotterform.height.value='36';
	document.plotterform.width.value='48';
	recalculate();
}
function setsize4(){
	document.plotterform.height.value='36';
	document.plotterform.width.value='100';
	recalculate();
}
function widthplus() {
	document.plotterform.width.value++;
	recalculate();
	}

function widthminus() {
	document.plotterform.width.value--;
	recalculate();
	}

function heightplus() {
	document.plotterform.height.value++;
	recalculate();
	}

function heightminus() {
	document.plotterform.height.value--;
	recalculate();
	}

function sheetsplus() {
	document.plotterform.sheets.value++;
	recalculate();
	}

function sheetsminus() {
	document.plotterform.sheets.value--;
	recalculate();
	}

function usetsplus() {
	document.plotterform.usets.value++;
	recalculate();
	}

function usetsminus() {
	document.plotterform.usets.value--;
	recalculate();
	}

function swapjob() {
	document.plotterform.jobinfo_id.value=document.plotterform.rjob_num.options[document.plotterform.rjob_num.selectedIndex].value;
	recalculate();
	}

function swapuser() {
	document.plotterform.user.value=document.plotterform.luser.options[document.plotterform.luser.selectedIndex].value;
	recalculate();
	}



function gosubmit() {
	if (checkfields()) {
		recalculate();
		if (document.plotterform.total_sheets.value<=0) {
			alert ('Error, Total # of sheets must be > 0');
			return false;
			}
		if (document.plotterform.total_sheets.value>=500) {
			alert('Too many sheets.. Take it in smaller chunks please (fewer than 500 sheets at a time).');
			return(cleartotals());
			}
		if (document.plotterform.total_sheets.value>=100) {
			if(!(confirm('That is a lot of sheets.. are you sure?!?!')))
				return(cleartotals());
			}
		//if (document.plotterform.
		total_area=document.plotterform.area.value * document.plotterform.total_sheets.value;
		if (total_area > 5988) {
			alert('ERROR: Total area can not exceed 5998 square feet! (Largest sheet size times maximum sheet count, or 12 feet x 499 sheets');
			return false;
			}
		if (confirm('Does Everything Look Correct?')) {
			document.plotterform.submit();
			}
		} else {
		alert('You must complete the entire form first!');
		}
	}

function confirmdelete(copylog_id){
	destination='$SCRIPT_NAME?mode=delete&copylog_id=' + copylog_id;
	if (confirm('Are you sure you want to delete this record!?!?')) {
		document.location=destination;
		}
	}



var mtype = new Array();

mtype['bond']='1';
mtype['vellum']='2';
mtype['mylar']='3';
mtype['digital']='4';



</script>
<center><h2>Recently Added Entries</h2></center>

<center>
";

$query="select * from $current, jobinfo
				where $current.jobinfo_id = jobinfo.jobinfo_id
				and billed = 'no'
				order by copylog_id desc
				limit 20
				";

echo "
<table border=1>
<tr bgcolor=#eeeeee><td>
	User
</td><td>
	Job Number
</td><td>
	Job Description
</td><td>
	Entry Date
</td><td>
	Height
</td><td>
	Width
</td><td>
	Mode
</td><td>
	Sheets
</td><td>
	Plotter
</td><td>
	Paper
</td><td>
	Color
</td><td>
	&nbsp;
</td></tr>";

//tabledump("$query");

$result=mysql_query($query);

while($row=@mysql_fetch_object($result)) {
	$row->entrydate=invali_date($row->entrydate);
	echo "<tr><td>
			$row->user
		</td><td>
			$row->contract_num
		</td><td>
			$row->job_name
		</td><td>
			$row->entrydate
		</td><td>
			$row->height
		</td><td>
			$row->width
		</td><td>
			$row->scanmode
		</td><td>
			$row->sheets
		</td><td>
			$row->plotter
		</td><td>
			$row->media
		</td><td>
			$row->color
		</td><td>
			<a href=javascript:confirmdelete('$row->copylog_id');>
			<font color=blue>Delete</font>
			</a>
		</td></tr>";


}


?>
</table>
</center>
