<?
//require("querylib.inc");
//require("tableprint.phtml");

if ($setfield == "") {
	echo "Error: No Fields selected for modification! Please go <a href=javascript:history.go(-1);>BACK</a> and try that again!<p>";
	exit;
	}


$setfield=escapeshellcmd($setfield);
$sterilized=sterilize($setfield,$setvalue,"spool_fab_tracking");

if (!($spool_batch_id)) {
	echo "Error: Nothing to be processed. Please go <a href=javascript:history.go(-1);>back</a> and select which records you'd like processed.";
	exit;
	}
require("system_chooser.phtml");
spooltableprint_batch_header();
while ($record=@each($spool_batch_id)) {
	$query="update spool_fab_tracking set $setfield = '$sterilized' where spool_fab_tracking_id = $record[value]";
	@mysql_query($query);
	spooltableprint_batch_row($record[value]);
	}
spooltableprint_batch_footer();

?>
