<?
require("querylib.inc");
require("header.phtml");
fd_navs_header();

//require("system_chooser.phtml");


if ($spool_fab_tracking_id=="") {
	$new=1;
	} else {
	$spool_fab_tracking_id=escapeshellcmd($spool_fab_tracking_id);
	$spool=getone("select * from spool_fab_tracking where spool_fab_tracking_id = '$spool_fab_tracking_id'");

	$spool->drawn_date=invali_date($spool->drawn_date);
	$spool->released_to_fab=invali_date($spool->released_to_fab);
	$spool->date_needed=invali_date($spool->date_needed);
	$spool->date_received_on_site=invali_date($spool->date_received_on_site);
	$spool->material_ordered=invali_date($spool->material_ordered);
	$spool->material_required=invali_date($spool->material_required);
	$spool->material_received=invali_date($spool->material_received);

	if ($makecopy=="yes") {
		$spool->spool_fab_tracking_id="";
		$spool->spool_tag_piece="";		
		}

	}


echo "
<script>
function add_weld() {
	open(\"$pagename?mode=add_weld&spool_fab_tracking_id=$spool->spool_fab_tracking_id\",\"add_weld\",\"width=400,height=400\");
	}
function save_then_add_weld() {
	document.spool_fab.add_weld_now.value='yes';
	document.spool_fab.justsave.value='yes';
	document.spool_fab.submit();
	}

function savencopy() {
	document.spool_fab.saveandcopy.value='yes';
	document.spool_fab.submit();
	}

function cancelit() {
	document.location=\"$pagename?mode=main\";
	}
function saveandloop () {
	document.spool_fab.loopit.value='yes';
	document.spool_fab.submit();
	}

function apply_changes () {
	document.spool_fab.justsave.value='yes';
	document.spool_fab.submit();
	}

</script>

<form name=spool_fab action=$pagename method=post>

<input type=hidden name=mode value=spool_fab_edit_submit>
<input type=hidden name=spool_fab_tracking_id value=\"$spool->spool_fab_tracking_id\">
<input type=hidden name=loopit value=no>
<input type=hidden name=justsave value=no>
<input type=hidden name=add_weld_now value=no>
<input type=hidden name=saveandcopy value=no>
<table border=0 cellpadding=1 cellspacing=0>

<tr bgcolor=$fd_color_4><td colspan=4 align=center style=\"border: 1px solid black;\"><font size=-2><br>
<input type=button value=\"Save\" onclick=submit()>&nbsp;&nbsp;
<input type=button value=\"Save and New Record\" onclick=saveandloop();>&nbsp;&nbsp;
<input type=button value=\"Save and Copy Record\" onclick=savencopy();>&nbsp;&nbsp;
<input type=button value=\"Cancel\" onclick=cancelit()><br>&nbsp;</font>
</td></tr>

<tr><td>
Cad File name:
</td><td>
<input type=text name=cad_file_name value=\"$spool->cad_file_name\">
</td></tr>

<tr><td>
Spool Tag:
</td><td>
	<table border=1 cellspacing=0 cellpadding=1>
	<tr valign=top>";

	if ($dynamic_field_info->dynamic_1_active=='Y') {
		//echo "booya!";
		if ($dynamic_field_info->dynamic_1_name=='System') {
			echo "<td align=center>System<br><input type=hidden name=\"dynamic_1\" value=\"$system_information->system_abbreviation\">
			$system_information->system_abbreviation
			</td>";
			} else {
			echo "<td>$dynamic_field_info->dynamic_1_name<br><input size=5 type=text name=\"dynamic_1\" value=\"$spool->dynamic_1\"></td>";
			}
		} else {
		echo "<input type=hidden name=\"dynamic_1\" value=\"$spool->dynamic_1\">";
		}
	
	if ($dynamic_field_info->dynamic_2_active=='Y') {
		if ($dynamic_field_info->dynamic_2_name=='System') {
			echo "<td align=center>System<br><input type=hidden name=\"dynamic_2\" value=\"$system_information->system_abbreviation\">
			$system_information->system_abbreviation
			</td>";
			} else {
			echo "<td>$dynamic_field_info->dynamic_2_name<br><input size=5 type=text name=\"dynamic_2\" value=\"$spool->dynamic_2\"></td>";
			}
		} else {
		echo "<input type=hidden name=\"dynamic_2\" value=\"$spool->dynamic_2\">";
		}
	
	if ($dynamic_field_info->dynamic_3_active=='Y') {
		if ($dynamic_field_info->dynamic_3_name=='System') {
			echo "<td align=center>System<br><input type=hidden name=\"dynamic_3\" value=\"$system_information->system_abbreviation\">
			$system_information->system_abbreviation
			</td>";
			} else {
			echo "<td>$dynamic_field_info->dynamic_3_name<br><input size=5 type=text name=\"dynamic_3\" value=\"$spool->dynamic_3\"></td>";
			}
		} else {
		echo "<input type=hidden name=\"dynamic_3\" value=\"$spool->dynamic_3\">";
		}
	
	if ($dynamic_field_info->dynamic_4_active=='Y') {
		if ($dynamic_field_info->dynamic_4_name=='System') {
			echo "<td align=center>System<br><input type=hidden name=\"dynamic_4\" value=\"$system_information->system_abbreviation\">
			$system_information->system_abbreviation
			</td>";
			} else {
			echo "<td>$dynamic_field_info->dynamic_4_name<br><input size=5 type=text name=\"dynamic_4\" value=\"$spool->dynamic_4\"></td>";
			}
		} else {
		echo "<input type=hidden name=\"dynamic_4\" value=\"$spool->dynamic_4\">";
		}
	
	if ($dynamic_field_info->dynamic_5_active=='Y') {
		if ($dynamic_field_info->dynamic_5_name=='System') {
			echo "<td align=center>System<br><input type=hidden name=\"dynamic_5\" value=\"$system_information->system_abbreviation\">
			$system_information->system_abbreviation
			</td>";
			} else {
			echo "<td>$dynamic_field_info->dynamic_5_name<br><input size=5 type=text name=\"dynamic_5\" value=\"$spool->dynamic_5\"></td>";
			}
		} else {
		echo "<input type=hidden name=\"dynamic_5\" value=\"$spool->dynamic_5\">";
		}
	
	if ($dynamic_field_info->dynamic_6_active=='Y') {
		if ($dynamic_field_info->dynamic_6_name=='System') {
			echo "<td align=center>System<br><input type=hidden name=\"dynamic_6\" value=\"$system_information->system_abbreviation\">
			$system_information->system_abbreviation
			</td>";
			} else {
			echo "<td>$dynamic_field_info->dynamic_6_name<br><input size=5 type=text name=\"dynamic_6\" value=\"$spool->dynamic_6\"></td>";
			}
		} else {
		echo "<input type=hidden name=\"dynamic_6\" value=\"$spool->dynamic_6\">";
		}
	






	echo "</tr></table>
</td></tr>

<tr><td>
Spool Revision Number:
</td><td>
<input type=text size=5 name=spool_rev_num value=\"$spool->spool_rev_num\">
</td></tr>

<tr><td>
Shop Drawing Reference:
</td><td>
<input type=text name=shop_drawing_ref value=\"$spool->shop_drawing_ref\">
</td></tr>

<tr><td>
Drawn Date:
</td><td>
<input type=text size=10 name=drawn_date value=\"$spool->drawn_date\"> (mm/dd/yyyy)
</td></tr>

<tr><td>
Field Review:
</td><td>
<input type=text name=field_review value=\"$spool->field_review\">
</td></tr>

<tr><td>
Priority:
</td><td>
<input type=text size=2 name=priority value=\"$spool->priority\">
</td></tr>

<tr><td>
Estimated Hours:
</td><td>
<input type=text size=5 name=estimated_hours value=\"$spool->estimated_hours\"> ##.## <i>(no letters)
</td></tr>

<tr><td>
Actual Hours:
</td><td>
<input type=text size=5 name=actual_hours value=\"$spool->actual_hours\"> ##.## <i>(no letters)
</td></tr>

<tr><td>
Released to Fab (date):
</td><td>
<input type=text size=10 name=released_to_fab value=\"$spool->released_to_fab\"> (mm/dd/yyyy)
</td><td align=right colspan=2>
	Status: <select name=completed>
				<option>$spool->completed</option>
				<option></option>
				<option>On Hold</option>
				<option>Fab Complete</option>
				<option>Installed</option>
			</select>
</td></tr>

<tr><td>
Fab Shop Name:
</td><td>
<input type=text name=fab_shop_name value=\"$spool->fab_shop_name\">
</td></tr>

<tr><td>
Date Needed:
</td><td>
<input type=text size=10 name=date_needed value=\"$spool->date_needed\"> (mm/dd/yyyy)
</td></tr>

<tr><td>
Date Received On Site:
</td><td>
<input type=text size=10 name=date_received_on_site value=\"$spool->date_received_on_site\"> (mm/dd/yyyy)
</td></tr>

<tr><td>
Weld Color:
</td><td>
<input type=text name=status value=\"$spool->status\">
</td></tr>

<tr><td>
Material Req Num:
</td><td>
<input type=text size=11 name=material_req_num value=\"$spool->material_req_num\">
</td></tr>

<tr><td>
Material Ordered:
</td><td>
<input type=text size=10 name=material_ordered value=\"$spool->material_ordered\"> (mm/dd/yyyy)
</td></tr>

<tr><td>
Material Required:
</td><td>
<input type=text size=10 name=material_required value=\"$spool->material_required\"> (mm/dd/yyyy)
</td></tr>

<tr><td>
Material Received:
</td><td>
<input type=text size=10 name=material_received value=\"$spool->material_received\"> (mm/dd/yyyy)
</td></tr>

<tr><td>
PO Number:
</td><td>
<input type=text size=15 name=po_number value=\"$spool->po_number\">
</td></tr>

<tr><td>
Building Location:
</td><td>
<input type=text name=location value=\"$spool->location\">
</td></tr>

<tr><td>
Weld Count:
</td><td>
<input type=hidden name=weld_count value=\"$spool->weld_count\">
$spool->weld_count
</td></tr>

<tr><td>
Weld Diameter In:
</td><td>
<input type=hidden name=weld_diameter_inches value=\"$spool->weld_diameter_inches\">
$spool->weld_diameter_inches
</td></tr>

<tr><td>
Weld Linear In:
</td><td>
<input type=hidden name=weld_linear_inches value=\"$spool->weld_linear_inches\">
$spool->weld_linear_inches
</td></tr>

<tr><td>
Weld Procedure:
</td><td>
<input type=text name=weld_procedure value=\"$spool->weld_procedure\">
</td></tr>

<tr><td>
Field Approval:
</td><td>
<input type=text name=field_approval value=\"$spool->field_approval\">
</td></tr>

<tr><td>
PM Approval:
</td><td>
<input type=text name=pm_approval value=\"$spool->pm_approval\">
</td></tr>

<tr><td>
	Attached File(s):
</td><td>
	";webfilebox($spool->attached_file,"attached_file");echo"
</td></tr>

</table>
</form>";

if ($add_weld_popup=="yes") echo "
<script>
add_weld();
</script>
";

if ($spool) {
	echo "<a href=javascript:add_weld();><font color=blue>Add</font></a>";
	} else {
	echo "<a href=javascript:save_then_add_weld();><font color=blue>Add</font></a>";
	}

$res=@mysql_query("select wc_id,weld_inches,weld_count,spool_fab_tracking_id
from spool_weld_counts 
where spool_fab_tracking_id = '$spool->spool_fab_tracking_id' order by weld_inches");

echo "<table border=1 cellspacing=0 cellpadding=5>
<tr bgcolor=#eeeeee><td colspan=3 align=center><b><font size=+1>Welds:</font></b></td></tr>
<tr bgcolor=#eeeeee><td><b>Inches</b></td><td colspan=2><b>Count</b></td></tr>
";

while ($row=@mysql_fetch_object($res)) {
	echo "<tr><td>
			$row->weld_inches
		</td><td>
			$row->weld_count&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</td><td>
			<a href=$pagename?mode=delete_weld&wc_id=$row->wc_id&spool_fab_tracking_id=$row->spool_fab_tracking_id><font color=blue><i>Delete</i></font></a>
		</td></tr>";
	
	
	}


echo "</table>


<script>
document.spool_fab.cad_file_name.focus();
</script>

";
fd_navs_footer();

?>
