<?
require("header.phtml");
fd_navs_header();

echo "<a href=$pagename?mode=main><font color=blue>Cancel</font></a><p>";
$std_info=getoneb("select * from spool_fab_tag_defs where jobinfo_id = '$global_jobinfo->jobinfo_id'");
$std_info->dynamic_1_name=addslashes($std_info->dynamic_1_name);
$std_info->dynamic_2_name=addslashes($std_info->dynamic_2_name);
$std_info->dynamic_3_name=addslashes($std_info->dynamic_3_name);
$std_info->dynamic_4_name=addslashes($std_info->dynamic_4_name);
$std_info->dynamic_5_name=addslashes($std_info->dynamic_5_name);
$std_info->dynamic_6_name=addslashes($std_info->dynamic_6_name);

$d1a=checkbreak($std_info->dynamic_1_active);
$d2a=checkbreak($std_info->dynamic_2_active);
$d3a=checkbreak($std_info->dynamic_3_active);
$d4a=checkbreak($std_info->dynamic_4_active);
$d5a=checkbreak($std_info->dynamic_5_active);
$d6a=checkbreak($std_info->dynamic_6_active);

echo "
<form name=std_edit method=post action=$pagename>
<input type=hidden name=tag_def_id value=$std_info->tag_def_id>
<input type=hidden name=mode value=std_submit>
<table border=1 cellspacing=0 cellpadding=3>
<tr bgcolor=#eeeeee><td>
	<b>Active</b>
</td><td>
	<b>Field</b>
</td><td>
	<b>Name</b>
</td></tr>

<tr><td align=center>
	<input type=checkbox name=dynamic_1_active $d1a>
</td><td>
	Field 1
</td><td>
	<input type=text size=20 name=dynamic_1_name value=\"$std_info->dynamic_1_name\">
</td></tr>
	
<tr><td align=center>
	<input type=checkbox name=dynamic_2_active $d2a>
</td><td>
	Field 2
</td><td>
	<input type=text size=20 name=dynamic_2_name value=\"$std_info->dynamic_2_name\">
</td></tr>
	
<tr><td align=center>
	<input type=checkbox name=dynamic_3_active $d3a>
</td><td>
	Field 3
</td><td>
	<input type=text size=20 name=dynamic_3_name value=\"$std_info->dynamic_3_name\">
</td></tr>
	
<tr><td align=center>
	<input type=checkbox name=dynamic_4_active $d4a>
</td><td>
	Field 4
</td><td>
	<input type=text size=20 name=dynamic_4_name value=\"$std_info->dynamic_4_name\">
</td></tr>
	
<tr><td align=center>
	<input type=checkbox name=dynamic_5_active $d5a>
</td><td>
	Field 5
</td><td>
	<input type=text size=20 name=dynamic_5_name value=\"$std_info->dynamic_5_name\">
</td></tr>
	
<tr><td align=center>
	<input type=checkbox name=dynamic_6_active $d6a>
</td><td>
	Field 6
</td><td>
	<input type=text size=20 name=dynamic_6_name value=\"$std_info->dynamic_6_name\">
</td></tr>
	
<tr><td colspan=3 align=right>
	<input type=submit value=\"Save\">
</td></tr>

</table>



</form>
";

fd_navs_footer();


?>
