<?


$spool_fab_tracking_id=addslashes($spool_fab_tracking_id);
$weld_inches=addslashes($weld_inches);
$weld_count=addslashes($weld_count);
$query="insert into spool_weld_counts set
	spool_fab_tracking_id = '$spool_fab_tracking_id',
	weld_inches = '$weld_inches',
	weld_count = '$weld_count'
	";
@mysql_query($query);
//echo "<hr>$query<hr>";exit;

$welds=getoneb("select 
	sum(weld_count) as weld_count,
	sum(weld_inches * weld_count) as weld_diameter_inches,
	sum(weld_inches * weld_count * PI()) as weld_linear_inches
from spool_weld_counts
where spool_fab_tracking_id = '$spool_fab_tracking_id'

group by spool_fab_tracking_id
");

echo "
<script>
opener.document.spool_fab.weld_count.value='$welds->weld_count'
opener.document.spool_fab.weld_diameter_inches.value='$welds->weld_diameter_inches'
opener.document.spool_fab.weld_linear_inches.value='$welds->weld_linear_inches'
opener.apply_changes();
self.close();
</script>
";

?>
