<?

/*
echo "
<html>
<head>
<title>UMC Contact Management Page</title>
</head>
<body bgcolor=white>
";

if ($mode=="main") {
	echo "
	<script>
	function apply_changes() {
	document.location.reload();
	}
	</script>
	";
	}

if ($set_global_job!="") {
	$global_jobinfo_id=addslashes($set_global_job);
	}

if ($global_jobinfo_id!="") {
	$global_jobinfo=getoneb("select * from jobinfo where jobinfo_id = '$global_jobinfo_id'");
	$dynamic_field_info=getoneb("select * from spool_fab_tag_defs where jobinfo_id = '$global_jobinfo->jobinfo_id'");
	
	$dynamic_field_info->dynamic_table_header="";
	}

echo "<table border=1 cellspacing=0 cellpadding=5>
<tr><td valign=top>
";
$res=@mysql_query("select * from jobinfo where spool_fab_tracking = 'Y' and active = 'Y' order by contract_num,job_name");
while($row=@mysql_fetch_object($res)) {
	if ($row->jobinfo_id==$global_jobinfo->jobinfo_id) {
		echo "<b>$row->contract_num - $row->job_name</b>";
		if ($adminuser) echo "<a href=$pagename?mode=std_edit&set_global_job=$row->jobinfo_id><font color=blue>&nbsp;STD</font></a>";
		echo "<br>";
		} else {
		echo "
			<a href=$pagename?mode=main&set_global_job=$row->jobinfo_id><font color=blue>$row->contract_num - $row->job_name</font></a><br>
		";
		
		}
	}
*/
//if ($set_current_system!="") $current_system_id=addslashes($set_current_system);
echo "
	<form name=system_chooser method=post action=$pagename>
	<input type=hidden name=mode value=main>
	<select onchange=\"submit()\" name=set_current_system>
	<option value=\"\"> </option>
	";
	$listres=@mysql_query("select * from spool_fab_systems where jobinfo_id = '$global_jobinfo->jobinfo_id' order by system_name");
	while ($listrow=@mysql_fetch_object($listres)) {
		$selected="";
		if ($system_information->spool_fab_systems_id == $listrow->spool_fab_systems_id) {
			$selected="selected";
			$preview_file_group=$system_information->attached_file;
			} 
		echo "<option value=\"$listrow->spool_fab_systems_id\" $selected>$listrow->system_name</option>";
		}
		echo "</select></form>";
if ($preview_file_group>0) {
	webfile_group_horiz_preview($preview_file_group);
	}
echo "
";







?>
