<?
require("querylib.inc");
require("header.phtml");

if ($spool_fab_systems_id=="") {
	$system=new bsclass;
	$new=1;
	} else {
	$spool_fab_systems_id=escapeshellcmd($spool_fab_systems_id);
	$system=getone("select * from spool_fab_systems where spool_fab_systems_id = '$spool_fab_systems_id'");
	$new=0;
	}

echo " 
<script>
function apply_changes() {
	document.spool_system.justsave.value='yes'
	document.spool_system.submit()
	}
</script>

<form name=spool_system action=$pagename method=post>
<input type=hidden name=mode value=systems_maint_edit_submit>
<input type=hidden name=spool_fab_systems_id value=\"$system->spool_fab_systems_id\">
<input type=hidden name=justsave value=no>

<table border=0 cellspacing=0 cellpadding=1>
<tr><td>
	System Name:
</td><td>
	<input type=text name=system_name value=\"$system->system_name\">
</td></tr>

<tr><td>
	System Abbreviation:
</td><td>
	<input type=text size=10 name=system_abbreviation value=\"$system->system_abbreviation\">
</td></tr>

<tr><td>
	Attached File(s) (preview)
</td><td>
	";webfilebox($system->attached_file,"attached_file");echo"
</td></tr>

<tr><td>
</td><td valign=top>
	<input type=button value=\"Save/Add\" onclick=submit()>
	<input type=button value=Cancel onclick=\"document.location='$pagename?mode=main'\">
</td></tr>
</table>




</form>
";
?>
