<?
require("header.phtml");
fd_navs_header();


echo "
<form name=systems method=post action=$pagename>
<input type=hidden name=mode value=systems_maint_edit>
";
dropbox("select spool_fab_systems_id,system_name,' (',system_abbreviation,')' from spool_fab_systems where jobinfo_id = '$global_jobinfo_id' order by system_name","submit()","20");
//tabledump("select spool_fab_systems_id,system_name,' (',system_abbreviation,')' from spool_fab_systems where jobinfo_id = '$global_jobinfo_id' order by system_name");


echo "
<br>
<input type=button value=\"Add/Edit\" onclick=\"submit()\">
<input type=button value=Cancel onclick=\"document.location='$pagename?mode=main'\">
</form>";
fd_navs_footer();
?>
