<?

if ($subcontracts_id=="") {
	$max_request_num=getoneb("select request_number from subcontracts where jobinfo_id = '$global_jobinfo->jobinfo_id' order by request_number desc limit 1");
	$subcontractor_type_id=addslashes($subcontractor_type_id);
	if (!($max_request_num)) $request_num=1;
	else $request_num=$max_request_num->request_number + 1;
	$start_query="insert into subcontracts set request_number = '$request_num', jobinfo_id = '$global_jobinfo->jobinfo_id', subcontractor_type_id = '$subcontractor_type_id', create_date = now()";
	echo "<hr>$start_query<hr>";
	@mysql_query($start_query);
	$subcontracts_id=@mysql_insert_id();
	}
$subcontracts_id=addslashes($subcontracts_id);
$subcontracts_info=getoneb("select * from subcontracts where subcontracts_id = '$subcontracts_id'");

$description=addslashes($description);
$subcontractor_id=addslashes($subcontractor_id);
$subcontractor_type_id=addslashes($subcontractor_type_id);
$subcontractor_contact=addslashes($subcontractor_contact);
$contract_amount=float_clean($contract_amount);
$job_name_alias=addslashes($job_name_alias);
$phase_code=addslashes($phase_code);
$prime_contractor=addslashes($prime_contractor);
$owner=addslashes($owner);
$scope=addslashes($scope);
$is_t_and_m=addslashes($is_t_and_m);
$retainage=addslashes($retainage);
$exhibit_name=addslashes($exhibit_name);

if (($other_subcontractor_type=="")&&($subcontractor_type_id!=12)) {
	$subcontractor_type_info=getoneb("select * from subcontractor_types where subcontractor_type_id = '$subcontractor_type_id'");
	$other_subcontractor_type=$subcontractor_type_info->sub_type;
	} else {
	$other_subcontractor_type=addslashes($other_subcontractor_type);
	}
if ($special_action=="submit_request") {
	$add_submit_date=",submit_date = now() ";
	} else {
	$add_submit_date="";
	}
$query="
update subcontracts set
description = '$description',
subcontractor_id = '$subcontractor_id',
subcontractor_type_id = '$subcontractor_type_id',
subcontractor_contact = '$subcontractor_contact',
job_name_alias = '$job_name_alias',
phase_code = '$phase_code',
prime_contractor = '$prime_contractor',
contract_amount = '$contract_amount',
owner = '$owner',
scope = '$scope',
other_subcontractor_type = '$other_subcontractor_type',
is_t_and_m = '$is_t_and_m',
retainage = '$retainage',
exhibit_name = '$exhibit_name'
$add_submit_date

where subcontracts_id = '$subcontracts_id'
";
$res=@mysql_query($query);

if (!($res)) die ("Failed query: <hr>$query");

if ($special_action=="submit_request") {
	if (verify_scope_completion($subcontracts_info->subcontracts_id)) {
		$doc_id=fd_get_doc_id($subcontracts_id);
		
		$this_job_info=getoneb("select * from jobinfo where jobinfo_id = '$subcontracts_info->jobinfo_id'");
		
		if ($this_job_info->contract_admin<1) {
			$this_job_info->contract_admin=133;
			}
		$contract_admin=getoneb("select * from contacts where contacts_id = '$this_job_info->contract_admin'");
		$message="There is a new 
		<a href=https://pipeline.umci.com/global/front_desk/?mode=open_doc&doc_id=$doc_id><font color=blue>subcontract request</font></a>
		that has been submitted on front desk. The subcontract is for job <b>$this_job_info->contract_num ($this_job_info->job_name)</b>. For further details please 
		<a href=https://pipeline.umci.com/global/front_desk/?mode=open_doc&doc_id=$doc_id><font color=blue>follow the link</font></a>
		to check it out in front desk.
		";
		queue_email($contract_admin->contacts_id,"New Subcontract Request on Front Desk",$message,"Y");
		@mysql_query("update subcontracts set status = 'submitted',submitted_by = '$global_user_id' where subcontracts_id = '$subcontracts_id'");
		
		forward("main");
		die();
		}
	}

if ($special_action=="mark_complete") {
	if (member_of_global_group_named("Contract Admin")) {
		if (verify_scope_completion($subcontracts_info->subcontracts_id)) {
			@mysql_query("update subcontracts set status = 'complete' where subcontracts_id = '$subcontracts_id'");
			
			//echo "<script>open(\"$pagename?mode=scope_selections_pdf&subcontracts_id=$subcontracts_info->subcontracts_id\",\"pdf_scope_$subcontracts_info->subcontracts_id\",\"width=1000,height=900\");</script>";
			forward("downloadpause&subcontracts_id=$subcontracts_info->subcontracts_id");
			die();
			}
		}
	}

if ($special_action=="return_to_user") {
	if (member_of_global_group_named("Contract Admin")) {
		@mysql_query("update subcontracts set status = 'new' where subcontracts_id = '$subcontracts_id'");
		forward("main");
		die();
		}
	}

if ($special_action=="save_and_view_data") {
	if (member_of_global_group_named("Contract Admin")) {
		//@mysql_query("update subcontracts set status = 'new' where subcontracts_id = '$subcontracts_id'");
		forward("view_data&subcontracts_id=$subcontracts_id");
		die();
		}
	}

forward("subcontracts_edit&subcontracts_id=$subcontracts_info->subcontracts_id");
?>
