<?require("pageheader.phtml");?>
<? 
echo "

<b><i>Welcome to the UMC CD tracker</i></b><br>

Please make a selection:

<ul><a href=\"$pagename?mode=cdinfo_edit\"><font color=blue>Add a new CD</font></a></ul>
<ul><a href=\"$pagename?mode=jobsearch\"><font color=blue>Search</font></a></ul>
<ul><a href=\"$pagename?mode=listcd\"><font color=blue>List all CD's</font></a></ul>
<ul><a href=\"$pagename?mode=cdcountsum\"><font color=blue>CD Count Summary</font</a></ul>

";/*<ul><a href=\"$pagename?mode=search\"><font color=blue>Search for a CD</font></a></ul>
<ul><a href=\"$pagename?mode=search2\"><font color=blue>Search for a CD II</font></a></ul>
*/echo"<p>
<ul><font size=-1><a href=\"$pagename?mode=lookuplist\"><font color=blue>Edit reference tables</font></a></font></ul>




";
?>
<?require("footer.phtml");?>
