<?require("lookup_deny.inc");?>
<?require("querylib.inc");?>
<?
$lookupmode=ereg_replace("^lookup_delete_","",$mode);
$query="select * from $lookupmode where 0 = 1";
$result=mysql_query($query);
$record_id_name=mysql_field_name($result,0);


$query="delete from $lookupmode where $record_id_name = '$record'";
mysql_query($query);
$mode="lookup_$lookupmode";
include("lookup_$lookupmode.phtml");

?>




