<?require("lookup_deny.inc");?>
<?require("pageheader.phtml");?>
<?require("querylib.inc");?>
<?

$lookupmode=ereg_replace("^lookup_edit_","",$mode);
$query="select * from $lookupmode where 0 = 1";
$result=mysql_query($query);
$record_id_name=mysql_field_name($result,0);
$record_data_name=mysql_field_name($result,1);
$query="select * from $lookupmode where $record_id_name = '$record'";

$current_record=getone($query);
$record_data_text=htmlspecialchars("$current_record[1]");

echo "
<form action=$pagename method=post>
<input type=hidden name=mode value=lookup_update_$lookupmode>
<input type=hidden name=record value=$record>
<input type=text name=$record_data_name value=\"$record_data_text\" size=25>
<input type=button value=Save onclick=submit();>
<input type=button value=Back onclick=history.go(-1);>
</form>";

?>




