<?
if ($show=="") $show=1;
else $show=$show + 1;
echo "
	<font color=blue onclick=\"doc_select(18999)\">Test 1</font><br>
	<font color=blue onclick=\"doc_select(19138)\">Test 2</font><br>
	<font color=blue onclick=\"doc_select(19563)\">Test 3</font><br>
	<font color=blue onclick=\"doc_select(19904)\">Test 4</font><br>
	<font color=blue onclick=\"doc_select(20192)\">Test 5</font><br>
	<font color=blue onclick=\"doc_select(20203)\">Test 6</font><br>
	<font color=blue onclick=\"doc_select(20236)\">Test 7</font><br>
	<font color=blue onclick=\"doc_select(20824)\">Test 8</font><br>


";
?>
