<?
if (!($write)) die_security("mode: $mode");
if ($files_id!="") $files_id=addslashes($files_id);
$file_info=getoneb("select * from cnstdwglog_files where files_id = '$files_id'");

if ($doc_id!="") $doc_id=addslashes($doc_id);
else die("Application error. Please contact your system administrator!");

$description=addslashes($description);
@mysql_query("insert into cnstdwglog_addenda set files_id = '$file_info->files_id', description = '$description', doc_id = '$doc_id'");
$id=@mysql_insert_id();
//@mysql_query("update cnstdwglog_addenda set parent_addenda_id = '$id' where addenda_id = '$id'");
forward("cnstdwglog_edit&cnstdwglog_id=$file_info->cnstdwglog_id");

?>
