<?
fd_navs_header();
require("header.phtml");
if ($files_id!="") $files_id=addslashes($files_id);
else die("Application error!");

$file_info=getoneb("select * from cnstdwglog_files where files_id = '$files_id'");
$issuance_info=getoneb("select * from cnstdwglog_issuances where issance_id = '$file_info->issuance_id'");
$drawing_info=getoneb("select * from cnstdwglog where cnstdwglog_id = '$file_info->cnstdwglog_id'");

echo "
<script>
function check_and_submit() {
	//alert(document.new_addendum.file_groups_id.value);
	if (document.new_addendum.file_groups_id.value < 1) alert('You must first attach a document before you submit this form.');
	else document.new_addendum.submit();
	}
</script>
<center><h2>Adding a supplemental sheet to issuance \"$issuance_info->name\" for drawing \"$drawing_info->drawing_num\"</h2></center>

<form name=new_addendum method=post action=$pagename>
<input type=hidden name=mode value=\"add_addendum_file_submit\">
<input type=hidden name=files_id value=\"$file_info->files_id\">
<table border=1 cellspacing=0 cellpadding=4>
<tr><td>
	<b>Description</b>
</td><td>
	<input type=text name=description value=\"\">
</td></tr>

<tr><td>
	<b>File</b>
</td><td>
	";webfilebox("","file_groups_id");echo"
</td></tr>

<tr><td colspan=2 align=right>
	<input type=button onclick=\"check_and_submit()\" value=Save>
</td></tr>



</table>
</form>
";












fd_navs_footer();
?>
