<?
if (!($write)) die_security("Attempt to submit an update to the cnstdwglog records by as user that doesn't have write permissions!");
$current_section=current_section();
//die($save_button);
if ($cnstdwglog_id!="") {
	$cnstdwglog_id=addslashes($cnstdwglog_id);
	$query_start="update cnstdwglog ";
	$query_end=" where cnstdwglog_id = '$cnstdwglog_id'";
	} else {
	$duplicate=getoneb("select * from cnstdwglog where 
	section = '$current_cnstdwglog_section' and
	jobinfo_id = '$global_jobinfo->jobinfo_id' and 
	drawing_num = '" . addslashes($drawing_num) . "' limit 1
	");
	
	if ($duplicate) {
		die("Error! Could not create record because a duplicate record already exists! Please use the search function to find the original record and edit that!<p>*TIP* Sometimes they've got an incorrect document type putting them into the wrong section. Use the search function with the drawing number since that's the field that is required to be unique.");
		}
	
	$query_start="insert into cnstdwglog ";
	$query_end=",section = '$current_cnstdwglog_section',jobinfo_id = '$global_jobinfo->jobinfo_id'";
	//$APPLY=TRUE;
	}

$drawing_num=addslashes($drawing_num);
$drawing_type=addslashes($drawing_type);
$description=addslashes($description);
$document_file_group_id=addslashes($document_file_group_id);
$active=checkfix($active);


$query_middle=" set drawing_num = '$drawing_num', drawing_type = '$drawing_type', description = '$description', active = '$active' ";

$query_full=$query_start . $query_middle . $query_end;

$res=@mysql_query($query_full);

if (!($res)) die("query failed:<hr>$query_full");
if ($cnstdwglog_id=="") {
	$cnstdwglog_id=@mysql_insert_id();
	$sort_rank_query="select max(sort_rank) as max from documents where jobinfo_id = '$global_jobinfo->jobinfo_id' and section = '$current_cnstdwglog_section' and doc_type = 'cnstdwglog'";
	$sort_rank=getoneb($sort_rank_query);
	if (!($sort_rank)) die("couldn't find sort rank current max<hr>$sort_rank_query");
	
	if ($sort_rank->max<1) {
		$sort_rank_new=0;
		} else {
		$sort_rank_new=$sort_rank->max + 1;
		}
	$rank_query="update documents set sort_rank = '$sort_rank_new' where doc_type = 'cnstdwglog' and app_record_id = '$cnstdwglog_id'";
	$rankres=@mysql_query($rank_query);
	if (!($rankres)) die("Error updating rank... <hr>$rank_query");
	}


if ($save_button=="Apply") {
	forward("cnstdwglog_edit&cnstdwglog_id=$cnstdwglog_id");
	die();
	}

if ($save_button=="Save") {
	forward("main");
	die();
	}

if ($save_button=="Create") {
	forward("cnstdwglog_edit&cnstdwglog_id=$cnstdwglog_id");
	die();
	}
	
if ($save_button=="Save and Clone") {
	forward("cnstdwglog_edit&clone_id=$cnstdwglog_id");
	die();
	}

if ($save_button=="Save and New") {
	forward("cnstdwglog_edit");
	die();
	}



forward('main');
?>
