<?
ajax_load();

//if ($doc_id!="") $doc_id=addslashes($doc_id);
//$doc_info=getone("select * from documents where doc_id = '$doc_id'");


$query="select * from documents where jobinfo_id = '$global_jobinfo_id' and doc_type != 'inbound' and doc_type != 'pal' order by section,doc_type,app_reference + 0 ASC";
$res=@mysql_query($query);


require('header.phtml');
echo "
<table border=0 cellspacing=0 cellpadding=0 width=100%><tr><td align=right><a href=javascript:self.close();><font color=blue>Done</font></a></td></tr></table>

<style>
tr {
  cursor: hand;
  cursor: pointer;
  background-color: white;
  h: expression(	onmouseover=new Function(\"this.style.backgroundColor='#dddddd';\"),
					onmouseout=new Function(\"this.style.backgroundColor='#ffffff';\"));
  }
tr:hover {
  background-color: #dddddd;
  cursor: hand;
  cursor: pointer;
  }
</style>

<script>
function t (doc_id) {
	//document.getElementById(row_id).innerHTML='<td bgcolor=yellow colspan=2>&nbsp;</td>';
	opener.document.add_link_form.doc_id.value=doc_id;
	opener.document.add_link_form.submit();
	self.close();
	}
</script>

<div style=\"display: none;\" id=\"doc_list_object\"></div>
";

$last_section="";
$last_type=="";
$first_table='Y';
while ($row=@mysql_fetch_object($res)) {
	if (($last_section != $row->section)|| ($last_type != $row->doc_type)) {
		$section_text=$row->section;
		$last_section=$row->section;
		$last_type=$row->doc_type;
		if ($section_text=='default') $section_text='';
		if ($first_table=='Y') $first_table='N';
		else echo "</table>";
		
		$print_doc_type=$row->doc_type;
		if ($print_doc_type=='rfi') $print_doc_type='umcrfi';

		echo "<table width=100% id=\"$row->section$row->doc_type\" cellspacing=0 cellpadding=2>
		<tr><td colspan=2 align=center bgcolor=\"#333333\"><font color=\"#ffffff\" size=+1><b>$print_doc_type&nbsp;$section_text</td></tr>";
		}
	$row_doc_id=$row->doc_id;
	echo "<tr onclick=\"t($row_doc_id);\"><td><font title=\"section: $row->section\">$row->doc_type $row->app_reference - $row->description</font></td></tr>";
	//include("fd_doclist_doc_row.phtml");
	//echo "";
	}
echo "</table>";

?>
