<?
$devel="-devel";
echo "
function fd_doc_submit_gcrfi_num(doc_id,gcrfi_id) {
	obj=document.getElementById('doc_box_gcrfi_num');
	sub_value=encodeURI(obj.value);
	ajaxManager('load_page','/global$devel/gcrfilog$devel/?mode=mini_edit&doc_id=' + doc_id + '&gcrfi_num_submitted=' + sub_value + '&gcrfi_id=' + gcrfi_id,'fd_document_box');
	}

function create_new_gcrfi(doc_id) {
	one_selection_only=document.getElementById('fd_document_box_opt_one_selection_only').value;
	gcrfi_num=encodeURI(document.getElementById('doc_box_gcrfi_num').value);
	if (gcrfi_num=='') {
		alert('Please fill in the new GCRFI Number');
		return 0;
		}
    ajaxManager('load_page','/global$devel/gcrfilog$devel/?mode=mini_edit_create&gcrfi_num=' + gcrfi_num + '&doc_id=' + doc_id + '&one_selection_only=' + one_selection_only,'fd_document_box');
	}

function fd_doc_change_gcrfi_num(doc_id,doc_edit_id) {
	obj=document.getElementById('doc_box_gcrfi_num');
	obj.style.background='yellow';
	newval=encodeURI(obj.value);
	ajaxManager('load_page','/global$devel/gcrfilog$devel/?mode=mini_edit_update_gcrfi_num&doc_id=' + doc_id + '&doc_edit_id=' + doc_edit_id + '&gcrfi_num=' + newval,'fd_document_box_gcrfi_num_cell');
	}

function fd_doc_change_key_description(doc_id,doc_edit_id) {
	obj=document.getElementById('doc_box_key_description');
	obj.style.background='yellow';
	newval=encodeURI(obj.value);
	ajaxManager('load_page','/global$devel/gcrfilog$devel/?mode=mini_edit_update_key_description&doc_id=' + doc_id + '&doc_edit_id=' + doc_edit_id + '&key_description=' + newval,'fd_document_box_key_description_cell');
	}

function fd_doc_change_has_cost(doc_id,doc_edit_id) {
	obj=document.getElementById('doc_box_has_cost');
	obj.style.background='yellow';
	newval=encodeURI(obj.value);
	ajaxManager('load_page','/global$devel/gcrfilog$devel/?mode=mini_edit_update_has_cost&doc_id=' + doc_id + '&doc_edit_id=' + doc_edit_id + '&has_cost=' + newval,'fd_document_box_has_cost_cell');
	}

function fd_doc_gcrfi_change_resp_reqd_date(id,doc_id,doc_edit_id) {
	obj=document.getElementById(id);
	obj.style.background='yellow';
	encoded_value=encodeURI(obj.value);
	ajaxurl='/global$devel/gcrfilog$devel/?mode=mini_edit_update_resp_reqd_date&response_needed_date=' + encoded_value + '&doc_id=' + doc_id + '&doc_edit_id=' + doc_edit_id;
	ajaxManager('load_page',ajaxurl,'fd_document_box_resp_reqd_cell');
	}

function fd_doc_gcrfi_change_reply_date(id,doc_id,doc_edit_id) {
	obj=document.getElementById(id);
	obj.style.background='yellow';
	encoded_value=encodeURI(obj.value);
	ajaxurl='/global$devel/gcrfilog$devel/?mode=mini_edit_update_reply_date&reply_date=' + encoded_value + '&doc_id=' + doc_id + '&doc_edit_id=' + doc_edit_id;
	ajaxManager('load_page',ajaxurl,'fd_document_box_reply_cell');
	}

function fd_doc_gcrfi_change_pm_complete_date(id,doc_id,doc_edit_id) {
	obj=document.getElementById(id);
	obj.style.background='yellow';
	encoded_value=encodeURI(obj.value);
	ajaxurl='/global$devel/gcrfilog$devel/?mode=mini_edit_update_pm_complete_date&pm_complete_date=' + encoded_value + '&doc_id=' + doc_id + '&doc_edit_id=' + doc_edit_id;
	ajaxManager('load_page',ajaxurl,'fd_document_box_pm_complete_cell');
	}

ajaxManager('load_js','/javascript/urlencode.js');
ajaxManager('load_js','/javascript/contacts_new.js');
ajaxManager('load_js','/javascript/cal2.js');
";
?>
