<?
if (!($write)) die_security("mode: $mode");
$section_id=addslashes($section_id);
$section_info=getoneb("select * from ${application_name}_sections where section_id = '$section_id'");
if (!($section_info)) die("Application error: Bad section info. Please contact your system administrator!");

if ($section=="") $section="&nbsp;";
else $section=addslashes($section);
@mysql_query("update ${application_name}_sections set section = '$section' where section_id = '$section_info->section_id'");
@mysql_query("update ${application_name} set section = '$section' where section = '$section_info->section' and jobinfo_id = '$section_info->jobinfo_id'");
@mysql_query("update ${application_name}_issuances set section = '$section' where section = '$section_info->section' and jobinfo_id = '$section_info->jobinfo_id'");
forward('manage_sections');
?>
