<?
fd_navs_header();
require("header.phtml");

if ($files_id!="") $files_id=addslashes($files_id);
else die("Application error!");

$file_info=getoneb("select * from cnstdwglog_files where files_id = '$files_id'");
$issuance_info=getoneb("select * from cnstdwglog_issuances where issance_id = '$file_info->issuance_id'");
$drawing_info=getoneb("select * from cnstdwglog where cnstdwglog_id = '$file_info->cnstdwglog_id'");

echo "
<script>
function check_and_submit() {
	//alert(document.new_addendum.file_groups_id.value);
	if (document.new_addendum.file_groups_id.value < 1) alert('You must first attach a document before you submit this form.');
	else document.new_addendum.submit();
	}
function select_doc() {
	open('$pagename?mode=fd_doclist_popup','cnstdwgloglistpu','width=500,height=700,scrollbars=1');
	}
</script>
<center><h2>Link a supplemental sheet to issuance \"$issuance_info->name\" for drawing \"$drawing_info->drawing_num\"</h2></center>

<form name=add_link_form method=post action=$pagename>
<input type=hidden name=mode value=\"add_addendum_link_submit\">
<input type=hidden name=files_id value=\"$file_info->files_id\">
<table border=1 cellspacing=0 cellpadding=4>
<tr><td>
	<b>Description</b>
</td><td>
	<input type=text name=description value=\"\">
</td></tr>

<tr><td>
	<b>Link/Document</b>
</td><td>
	<font color=blue onclick=\"select_doc()\">Link document</font>
	<input type=hidden name=doc_id value=''>
</td></tr>

</table>
</form>
";












fd_navs_footer();
?>



















fd_navs_footer();
?>
