<?
include ("../webfile$devel/local.inc");
if (!(fd_manager($global_jobinfo_id,$global_user_id)||$adminuser||pm_for_this_job()||is_member_of_group_named("BIM Admins"))) {
	die_security("Trying to delete in cnstdwglog without correct permissions");
	}
$cnstdwglog_id=addslashes($cnstdwglog_id);
$cnstdwglog_info=getoneb("select * from cnstdwglog where cnstdwglog_id = '$cnstdwglog_id'");

if(!($cnstdwglog_info)) die("Application error! Couldn't load record info.");


$files_list=@mysql_query("select * from cnstdwglog_files where cnstdwglog_id = '$cnstdwglog_info->cnstdwglog_id'");
while ($file=@mysql_fetch_object($files_list)) {
	$supp_list=@mysql_query("select * from cnstdwglog_addenda where files_id = '$file->files_id'");
	while ($supp=@mysql_fetch_object($supp_list)) {
		//echo "$supp->addenda_id,$supp->files_id<br>";
		delete_webfile_group($supp->file_groups_id);
		if ($supp->file_groups_id>0) delete_webfile_file($supp->file_groups_id);
		@mysql_query("delete from cnstdwglog_addenda where addenda_id = '$supp->addenda_id'");
		}
	if ($file->file_group_id>0) delete_webfile_group($file->file_group_id);
	@mysql_query("delete from cnstdwglog_files where files_id = '$file->files_id'");
	}
@mysql_query("delete from cnstdwglog where cnstdwglog_id = '$cnstdwglog_info->cnstdwglog_id'");
forward('main');

?>
