<?
$today=date('m-d-Y');
$issuance_list=issuances();
$query_search_add=query_search_add_text();
session_write_close();
$last_issuance_info=getoneb("select * from cnstdwglog_issuances where jobinfo_id = '$global_jobinfo_id' and section = '$current_cnstdwglog_section' order by cnstdwglog_issuances.issuance_type, cnstdwglog_issuances.issuance_date desc, cnstdwglog_issuances.sort_priority desc, cnstdwglog_issuances.name desc limit 1");


if ($cnstdwglog_view=="") { session_register('cnstdwglog_view'); $cnstdwglog_view='normal'; }

/////////////////////////////////////////////////////////////////////////////////////////////////
// Query to list the whole log in order...
/////////////////////////////////////////////////////////////////////////////////////////////////
$query="select * from cnstdwglog right join documents on ( doc_type = 'cnstdwglog' and documents.app_record_id = cnstdwglog.cnstdwglog_id ) where ( cnstdwglog.jobinfo_id = '$global_jobinfo->jobinfo_id' and cnstdwglog.section = '$current_cnstdwglog_section' ) $query_search_add order by 	cnstdwglog.drawing_type, documents.sort_rank, documents.doc_id, cnstdwglog.drawing_num";
$res=@mysql_query($query);

header("Content-disposition: inline; filename=\"" . $global_jobinfo->contract_num . "_cnstdwglog.csv\"");
header("Content-type: application/octet-stream; ");
header("Content-Transfer-Encoding: binary");
header("Expires: 0");
header("Cache-Control: private");
header("Pragma: cache");

echo "Supplemental Count,Drawing Type,DWG #,Description,Current Revision,Current Issuance";

if ($cnstdwglog_view=="expanded") {
	reset($issuance_list);
	$current_id=current($issuance_list);
	$current_name=next($issuance_list);
	$current_type=next($issuance_list);
	$current_current=next($issuance_list);
	while (!($current_id===FALSE)) {
		echo ",$current_name";
		$current_id=next($issuance_list);
		$current_name=next($issuance_list);
		$current_type=next($issuance_list);
		$current_current=next($issuance_list);
		}
	}
echo "\r\n";


while ($dwg=@mysql_fetch_object($res)) {
	$cnstdwglog_info=getoneb("select * from cnstdwglog_files right join cnstdwglog_issuances on (cnstdwglog_issuances.issuance_id = cnstdwglog_files.issuance_id) right join webfile_groups on ( cnstdwglog_files.file_group_id = webfile_groups.file_group_id ) right join webfile_files on ( webfile_groups.file_group_id = webfile_files.file_group_id ) where cnstdwglog_id = '$dwg->cnstdwglog_id' and cnstdwglog_issuances.issuance_id = cnstdwglog_files.issuance_id order by cnstdwglog_issuances.issuance_type, cnstdwglog_issuances.issuance_date desc, cnstdwglog_issuances.sort_priority desc, cnstdwglog_issuances.name desc limit 1");
	$last_file_info=getoneb("select * from cnstdwglog_files where cnstdwglog_id = '$dwg->cnstdwglog_id' and issuance_id = '$last_issuance_info->issuance_id'");
	$addenda_files=getoneb("select sum(1) as count from cnstdwglog_addenda where files_id = '$last_file_info->files_id' and required_in_this_issuance = 'Y'");


	$addenda_count="$addenda_files->count";
	if ($addenda_count=="") $addenda_count="0";
	
	echo "$addenda_count,$dwg->drawing_type,$dwg->drawing_num,$dwg->description,$cnstdwglog_info->revision,$cnstdwglog_info->name";
	
	if ($cnstdwglog_view=="expanded") {
		$issuances_res=@mysql_query("select * from cnstdwglog_files right join cnstdwglog_issuances on (cnstdwglog_issuances.issuance_id = cnstdwglog_files.issuance_id) left join webfile_groups on ( cnstdwglog_files.file_group_id = webfile_groups.file_group_id ) left join webfile_files on ( webfile_groups.file_group_id = webfile_files.file_group_id ) where cnstdwglog_files.cnstdwglog_id = '$dwg->cnstdwglog_id' and cnstdwglog_issuances.issuance_id = cnstdwglog_files.issuance_id order by cnstdwglog_issuances.issuance_type desc, cnstdwglog_issuances.issuance_date, cnstdwglog_issuances.sort_priority, cnstdwglog_issuances.name");
		$rowcount=@mysql_num_rows($issuances_res);
		while ($issuance_row=@mysql_fetch_object($issuances_res)) {
			$paperclip_link=webfile_paperclip_view($issuance_row->file_group_id);
			if ($paperclip_link!="&nbsp;") $paperclip_link="X";
			else $paperclip_link=" ";
			echo ",$paperclip_link";
			}
		}
	echo "\r\n";
	}
?>
