<?php

require_once('classes/ReportTable.php');
use classes\ReportTable\ReportTable;

$today = date('m-d-Y');
$issuance_list = issuances();

$base_columns = 7;
include("header.php");
fd_navs_header();

if (!empty($cnstdwglog_view)) {
    $_SESSION['cnstdwglog_view'] = $cnstdwglog_view;
} else {
    unset($_SESSION['cnstdwglog_view']);
}
if (empty($_SESSION['cnstdwglog_view'])) {
    if (slow_connection()) {
        $_SESSION['cnstdwglog_view'] = 'normal';
    } else {
        $_SESSION['cnstdwglog_view'] = 'expanded';
    }
}
if (empty($_SESSION['cnstdwglog_paging'])) {
    if (slow_connection()) {
        $_SESSION['cnstdwglog_paging'] = 'Y';
    } else {
        $_SESSION['cnstdwglog_paging'] = 'N';
    }
}
if (!empty($cnstdwglog_view_set)) {
    $_SESSION['cnstdwglog_view'] = $cnstdwglog_view_set;
}
if (!empty($cnstdwglog_paging_set)) {
    $_SESSION['cnstdwglog_paging'] = $cnstdwglog_paging_set;
}
if ($_SESSION['cnstdwglog_view'] == "expanded") {
    $base_columns = $base_columns + (sizeof($issuance_list) / 4);
}

ReportTable::cnstdwglogSearchFilters(2, array(
    'Drawing #', 'Description', 'Current Revision', 'Current Issuance', 'DWG Type'
), $issuance_list);

session_write_close();
//die($_SESSION['global_jobinfo_id']);
echo "<div style='float:left'>
<table border=0 cellspacing=0 cellpadding=0><tr><td style=\"width: 600px;\"><center>
<div style=\"float: right; width: 150px; height: 100px;\">";

if ($issuance_list) {
    if ($write) echo "<a href=$pagename?mode=cnstdwglog_edit>Add New DWG</a><br>";
    echo "<a target=_blank href=$pagename?mode=excel_dump&$search_url_append>CSV DL</a><br>";
    $last_issuance_info = getoneb("select * from cnstdwglog_issuances where jobinfo_id = '{$_SESSION['global_jobinfo_id']}' and section = '{$_SESSION['current_cnstdwglog_section']}' order by cnstdwglog_issuances.issuance_type, cnstdwglog_issuances.issuance_date desc, cnstdwglog_issuances.sort_priority desc, cnstdwglog_issuances.name desc limit 1");
}
if ((fd_manager($_SESSION['global_jobinfo_id'])) || (pm_for_this_job()) || ($adminuser)) echo "
	<a href=$pagename?mode=issuance_edit&global_jobinfo_id_set={$_SESSION['global_jobinfo_id']}>Add New Issuance</a><br>";

if ($_SESSION['cnstdwglog_view'] == "expanded") {
    echo "<a href=$pagename?cnstdwglog_view_set=normal&page_num=$page_num&mode=$mode&$search_url_append>Collapse Issuances</a><br>";
} else {
    echo "<a href=$pagename?cnstdwglog_view_set=expanded&page_num=$page_num&mode=$mode&$search_url_append>Expand Issuances</a><br>";
}

if (false) {
    if ($_SESSION['cnstdwglog_paging'] == "Y") {
        echo "<a href=$pagename?cnstdwglog_paging_set=N&mode=$mode&$search_url_append>Disable Paging</a>";
    } else {
        echo "<a href=$pagename?cnstdwglog_paging_set=Y&page_num=$page_num&mode=$mode&$search_url_append>Enable Paging</a>";
    }
}

echo "
</div>

<b><font size=+1>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;UMC&nbsp;Construction&nbsp;Drawing&nbsp;Log&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</font></b>
<br>$today<br>";

echo "<br>";

$fd_manager = fd_manager($_SESSION['global_jobinfo_id'], $_SESSION['global_user_id']);
select_section_box();

echo "
</center></td></tr></table></div><div class='clearfix'></div>";


echo " <table class='standard' id='cnstdwglog' border=1 cellspacing=0 cellpadding=3> ";
?>
<thead>
<tr bgcolor=<?php echo $fd_color_4; ?>>
    <th valign=bottom align=center><span>
<?php        
vertical_text("Current Full Sheet", 14, "$fd_color_4");
?>
    </span></th>
    <th>
<?php
vertical_text("Supplemental Count", 14, "$fd_color_4");
?>
    </span></th>
    <th valign=bottom align=center valign=bottom><span><font size=-1>DWG #</font></span></th>
    <th valign=bottom align=center valign=bottom><span><font size=-1>Description</font></span></th>
    <th valign=bottom align=center valign=bottom><span><font size=-1>Current<br>Revision</font></span></th>
    <th valign=bottom align=center valign=bottom>
        <table bgcolor=white border=1 cellspacing=0 cellpadding=0 style="font-height:12px;">
            <tr>
                <td colspan=2 align=center><b>Key</b></td>
            </tr>
            <tr>
                <td>Not issued</td><td bgcolor=<?php echo $fd_color_2;?>>&nbsp;&nbsp;&nbsp;</td>
            </tr>
            <tr>
                <td>Design</td><td bgcolor=<?php echo $fd_color_6;?>>&nbsp;&nbsp;&nbsp;</td>
            </tr>
            <tr>
                <td>Orig Const Issue&nbsp;</td><td bgcolor=<?php echo $fd_color_5; ?>>&nbsp;&nbsp;&nbsp;</td>
            </tr>
            <tr>
                <td >Const/Change</td><td bgcolor='#fff'>&nbsp;&nbsp;&nbsp;</td>
            </tr>
        </table>
        <span><font size=-1>
    Current<br>Issuance</font>
        </span></th>
    <th valign=bottom align=center valign=bottom><span><font size=-1>DWG Type</font></span></th>
<?php
if (($_SESSION['cnstdwglog_view'] == "expanded") && ($issuance_list)) {
    reset($issuance_list);
    $current_id = current($issuance_list);
    $current_name = next($issuance_list);
    $current_type = next($issuance_list);
    $current_current = next($issuance_list);
    while (!($current_id === FALSE)) {
        echo "<th align=center valign=bottom><span>";
        echo "<a href=$pagename?mode=issuance_edit&issuance_id=$current_id>";
        vertical_text($current_name, 14, "$fd_color_4");
        echo "</a>";
        echo "</span></th>";
        $current_id = next($issuance_list);
        $current_name = next($issuance_list);
        $current_type = next($issuance_list);
        $current_current = next($issuance_list);
    }
}
echo "</tr></thead><tbody>";

//content fetched by ajax call
ReportTable::cnstdwglogTable($global_jobinfo->jobinfo_id, $_SESSION['current_cnstdwglog_section'], $last_issuance_info->issuance_id);

fd_navs_footer();
