<?
//$mctime=microtime(TRUE);
// GPH ADDED TODO: REMOVE!
/*
@mysql_close();
$global_link_id = @mysql_connect('10.0.0.23', 'root', '');
$error = @mysql_error();
@mysql_select_db('global');
$error = @mysql_error();
*/

$today=date('m-d-Y');
$issuance_list=issuances();
$query_search_add=query_search_add_text();
$base_columns=6;
include("header.phtml");
fd_navs_header();

if ($cnstdwglog_view=="") {
	session_register('cnstdwglog_view'); 
	if (slow_connection()) $cnstdwglog_view='normal'; 
	else  $cnstdwglog_view='expanded'; 
	}
if ($cnstdwglog_paging=="") { 
	session_register('cnstdwglog_paging'); 
	if (slow_connection()) {
		$cnstdwglog_paging='Y'; 
		} else {
		$cnstdwglog_paging='N'; 
		}
	}
if ($cnstdwglog_view_set!="") $cnstdwglog_view=$cnstdwglog_view_set;
if ($cnstdwglog_paging_set!="") $cnstdwglog_paging=$cnstdwglog_paging_set;
if ($cnstdwglog_view=="expanded") {
	$base_columns=$base_columns + (sizeof($issuance_list)/4);
	}
/////////////////////////////////////////////////////////////////////////////////////////////////
// Query to list the whole log in order...
/////////////////////////////////////////////////////////////////////////////////////////////////
$query="select * from cnstdwglog right join documents on ( doc_type = 'cnstdwglog' and documents.app_record_id = cnstdwglog.cnstdwglog_id ) where ( cnstdwglog.jobinfo_id = '$global_jobinfo->jobinfo_id' and cnstdwglog.section = '$current_cnstdwglog_section' ) $query_search_add order by cnstdwglog.drawing_type, documents.sort_rank, documents.doc_id, cnstdwglog.drawing_num";
//die($query);
//tabledump ("explain " . $query);die;
$res=@mysql_query($query);
search_div();
if ($cnstdwglog_paging=='Y') include("fd_log_paging.phtml");
session_write_close();

echo "
<table  border=1 cellspacing=0 cellpadding=3\";>
<tr><td colspan=$base_columns>
<table border=0 cellspacing=0 cellpadding=0><tr><td style=\"width: 800px;\"><center>
<div style=\"float: left; width: 150px; height: 100px;\">&nbsp;</div>
<div style=\"float: right; width: 150px; height: 100px;\">";

if ($issuance_list) { 
	if ($write) echo "<a href=$pagename?mode=cnstdwglog_edit><font color=blue>Add New DWG</font></a><br>";
	echo "<a target=_blank href=$pagename?mode=excel_dump&$earch_url_append><font color=blue>CSV DL</font></a><br>";
	$last_issuance_info=getoneb("select * from cnstdwglog_issuances where jobinfo_id = '$global_jobinfo_id' and section = '$current_cnstdwglog_section' order by cnstdwglog_issuances.issuance_type, cnstdwglog_issuances.issuance_date desc, cnstdwglog_issuances.sort_priority desc, cnstdwglog_issuances.name desc limit 1");
	}
if ((fd_manager($global_jobinfo_id))||(pm_for_this_job())||($adminuser)) echo "
	<a href=$pagename?mode=issuance_edit&global_jobinfo_id_set=$global_jobinfo_id><font color=blue>Add New Issuance</font></a><br>";

if ($cnstdwglog_view=="expanded") {
	echo "<a href=$agename?cnstdwglog_view_set=normal&page_num=$page_num&mode=$mode&$earch_url_append><font color=blue>Collapse Issuances</font></a><br>";
	} else {
	echo "<a href=$agename?cnstdwglog_view_set=expanded&page_num=$page_num&mode=$mode&$earch_url_append><font color=blue>Expand Issuances</font></a><br>";
	}

if ($cnstdwglog_paging=="Y") {
	echo "<a href=$agename?cnstdwglog_paging_set=N&mode=$mode&$earch_url_append><font color=blue>Disable Paging</font></a>";
	} else {
	echo "<a href=$agename?cnstdwglog_paging_set=Y&page_num=$page_num&mode=$mode&$earch_url_append><font color=blue>Enable Paging</font></a>";
	}

echo "
</div>

<b><font size=+1>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;UMC&nbsp;Construction&nbsp;Drawing&nbsp;Log&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</font></b>
<br>$today<br>";

if ($cnstdwglog_paging=='Y') echo "$page_page_insert";

echo "<br>";

$fd_manager=fd_manager($global_jobinfo_id,$global_user_id);
select_section_box();

echo "
</center></td></tr></table>
</td></tr>
<tr bgcolor=$fd_color_4><td valign=bottom align=center>";vertical_text("Current Full Sheet",14,"$fd_color_4");echo"</td><td>";vertical_text("Supplemental Count",14,"$fd_color_4");echo "</td><td valign=bottom align=center valign=bottom><font size=-1>DWG #</font></td>
<td valign=bottom align=center valign=bottom><font size=-1>Description</font></td><td valign=bottom align=center valign=bottom><font size=-1>Current<br>Revision</font></td>
<td valign=bottom align=center valign=bottom><font size=-1>
<table bgcolor=white border=1 cellspacing=0 cellpadding=0 style=\"font-size: 12;\">
<tr><td colspan=2 align=center><b>Key</b></td></tr>
<tr><td>Not issued</td><td bgcolor=$fd_color_2>&nbsp;&nbsp;&nbsp;</td></tr>
<tr><td>Design</td><td bgcolor=$fd_color_6>&nbsp;&nbsp;&nbsp;</td></tr>
<tr><td>Orig Const Issue&nbsp;</td><td bgcolor=$fd_color_5>&nbsp;&nbsp;&nbsp;</td></tr>
<tr><td>Const/Change</td><td>&nbsp;&nbsp;&nbsp;</td></tr>
</table>
Current<br>Issuance</font></td>";

if (($cnstdwglog_view=="expanded")&&($issuance_list)) {
	reset($issuance_list);
	$current_id=current($issuance_list);
	$current_name=next($issuance_list);
	$current_type=next($issuance_list);
	$current_current=next($issuance_list);
	while (!($current_id===FALSE)) {
		echo "<td align=center valign=bottom>";
		echo "<a href=$pagename?mode=issuance_edit&issuance_id=$current_id>";
		vertical_text($current_name,14,"$fd_color_4");
		echo "</a>";
		echo"</td>";
		$current_id=next($issuance_list);
		$current_name=next($issuance_list);
		$current_type=next($issuance_list);
		$current_current=next($issuance_list);
		}
	}
echo "</tr>";


while ($dwg=@mysql_fetch_object($res)) {
	if ($dwg->drawing_type!=$last_drawing_type) {
		echo "<tr bgcolor=$fd_color_4><td colspan=$base_columns align=center><b>$dwg->drawing_type</td></tr>";
		$last_drawing_type=$dwg->drawing_type;
		}
	$cookie_link=batch_this_document($dwg->doc_id);
	//////////////////////////////
	// look at this next line and
	// include jobinfo_id to pre-
	// vent errors in display
	//////////////////////////////
	$cnstdwglog_info=getoneb("select * from cnstdwglog_files right join cnstdwglog_issuances on (cnstdwglog_issuances.issuance_id = cnstdwglog_files.issuance_id) right join webfile_groups on ( cnstdwglog_files.file_group_id = webfile_groups.file_group_id ) right join webfile_files on ( webfile_groups.file_group_id = webfile_files.file_group_id ) where cnstdwglog_id = '$dwg->cnstdwglog_id' and cnstdwglog_issuances.issuance_id = cnstdwglog_files.issuance_id order by cnstdwglog_issuances.issuance_type, cnstdwglog_issuances.issuance_date desc, cnstdwglog_issuances.sort_priority desc, cnstdwglog_issuances.name desc limit 1");
	$paperclip_link=webfile_paperclip_view($cnstdwglog_info->file_group_id);
	$last_file_info=getoneb("select * from cnstdwglog_files where cnstdwglog_id = '$dwg->cnstdwglog_id' and issuance_id = '$last_issuance_info->issuance_id'");
	$addenda_files=getoneb("select sum(1) as count from cnstdwglog_addenda where files_id = '$last_file_info->files_id' and required_in_this_issuance = 'Y' and posted = 'N'");
	
	
	$drawing_num_text=ereg_replace(" ","&nbsp;",$dwg->drawing_num);
	$drawing_num_text=ereg_replace("-","&#x2011;",$drawing_num_text);
	if ($drawing_num_text=="") $drawing_num_text="??????";
	
	if ($write) {
		$edit_record_link="<a href=$pagename?mode=cnstdwglog_edit&cnstdwglog_id=$dwg->cnstdwglog_id><font color=blue>$drawing_num_text</font></a>";
		$addenda_count="<a href=\"$pagename?mode=cnstdwglog_edit&cnstdwglog_id=$dwg->cnstdwglog_id&showmode=current_only\"><font color=blue>$addenda_files->count</font></a>";
		} else {
		$edit_record_link="$drawing_num_text";
		$addenda_count="$addenda_files->count";
		}
	
	$bgcolortext="";
	if ($cnstdwglog_info->issuance_type=="Design") $bgcolortext=" bgcolor=\"$fd_color_6\"";
	if ($cnstdwglog_info->issuance_type=="Construction Orig Issue") $bgcolortext=" bgcolor=\"$fd_color_5\"";
	if ($cnstdwglog_info->issuance_type=="") $bgcolortext=" bgcolor=\"$fd_color_2\"";

	echo "
	<tr><td>
		<table border=0 cellspacing=0 cellpadding=1>
		<tr><td width=10px>
		$paperclip_link
		</td><td>
		$cookie_link
		</td></tr></table>
	</td><td>
		$addenda_count&nbsp;
	</td><td>
		$edit_record_link
	</td><td>
		<font size=-1>" . ereg_replace(" ","&nbsp;",$dwg->description) . "</font>
	</td><td>
		" . ereg_replace(" ","&nbsp;",$cnstdwglog_info->revision) . "&nbsp;
	</td><td$bgcolortext>
		" . ereg_replace("-","&#x2011;",ereg_replace(" ","&nbsp;",$cnstdwglog_info->name)) . "
	</td>
	";
	if ($cnstdwglog_view=="expanded") {
		// Just revised to hide errant extra data.. There are extra cnstdwglog_files items from a different job showing up.. they have
		// the cnstdwglog_id from a record in job a, but have a issuance_id from a issuance in job b - must look into.
		$issuances_res=@mysql_query("select * from cnstdwglog_files right join cnstdwglog_issuances on (cnstdwglog_issuances.issuance_id = cnstdwglog_files.issuance_id) left join webfile_groups on ( cnstdwglog_files.file_group_id = webfile_groups.file_group_id ) left join webfile_files on ( webfile_groups.file_group_id = webfile_files.file_group_id ) where cnstdwglog_files.cnstdwglog_id = '$dwg->cnstdwglog_id' and cnstdwglog_issuances.issuance_id = cnstdwglog_files.issuance_id and cnstdwglog_issuances.jobinfo_id = '$global_jobinfo_id' group by cnstdwglog_issuances.issuance_id order by cnstdwglog_issuances.issuance_type desc, cnstdwglog_issuances.issuance_date, cnstdwglog_issuances.sort_priority, cnstdwglog_issuances.name");
		$rowcount=@mysql_num_rows($issuances_res);
		while ($issuance_row=@mysql_fetch_object($issuances_res)) {
			$paperclip_link=webfile_paperclip_view($issuance_row->file_group_id);
			$bgcolortext="";
			if ($issuance_row->issuance_type=="Design") $bgcolortext=" bgcolor=\"$fd_color_6\"";
			if ($issuance_row->issuance_type=="Construction Orig Issue") $bgcolortext=" bgcolor=\"$fd_color_5\"";
			echo "<td$bgcolortext>$paperclip_link</td>";
			}
		}
	echo "</tr>";
	}
echo "</table>";

fd_navs_footer();
//$mctime2=microtime(TRUE);
//$mctimediff=$mctime2 - $mctime;
//echo $mctime . "/" . $mctime2 . "<br>" . $mctimediff;

?>
