<?
include("../webfile$devel/storage_settings.cfg");

$cnstdwglog_id=addslashes($cnstdwglog_id);
$cnstdwglog_info=getoneb("select * from cnstdwglog where cnstdwglog_id = '$cnstdwglog_id'");
if (!($cnstdwglog_info)) {
	$doc_id=addslashes($doc_id);
	$doc_info=getoneb("select * from documents where doc_id = '$doc_id' and doc_type = 'cnstdwglog'");
	$cnstdwglog_info=getoneb("select * from cnstdwglog where cnstdwglog_id = '$doc_info->app_record_id'");
	if (!($cnstdwglog_info)) pdf_generation_error_pdf("ERR(2) - Unable to load drawing information.");
	}
if (!($cnstdwglog_info)) pdf_generation_error_pdf("ERR(1) - Unable to load drawing information");
$job=getoneb("select * from jobinfo where jobinfo_id = '$cnstdwglog_info->jobinfo_id'");

$latest_full_sheet=getoneb("select * from cnstdwglog_sheet_history_descending where cnstdwglog_id = '$cnstdwglog_info->cnstdwglog_id' limit 1");
$files_res=@mysql_query("select * from webfile_files where file_group_id = '$latest_full_sheet->file_group_id' and mime_type like '%pdf%'");
$pdf_count=@mysql_num_rows($files_res);
if ($pdf_count<1) pdf_generation_error_pdf("ERR(3) - No PDF to include.");


$row=@mysql_fetch_object($files_res);
if ($row->file_group_id==0) pdf_generation_error_pdf("ERR(99) - No File");
pdf_mime_header("Const_DWG_-_$doc_info->app_reference.pdf");
readfile("$storage_root$row->file_path");
?>
