<?
include("../webfile$devel/storage_settings.cfg");

$cnstdwglog_id=addslashes($cnstdwglog_id);
$cnstdwglog_info=getoneb("select * from cnstdwglog where cnstdwglog_id = '$cnstdwglog_id'");
if (!($cnstdwglog_info)) {
	$doc_id=addslashes($doc_id);
	$doc_info=getoneb("select * from documents where doc_id = '$doc_id' and doc_type = 'cnstdwglog'");
	$cnstdwglog_info=getoneb("select * from cnstdwglog where cnstdwglog_id = '$doc_info->app_record_id'");
	if (!($cnstdwglog_info)) die("ERR(2)");
	}
if (!($cnstdwglog_info)) die("ERR(1)");
$job=getoneb("select * from jobinfo where jobinfo_id = '$cnstdwglog_info->jobinfo_id'");

$sequence=ereg_replace("[^0-9]","",$sequence);
//if ($sequence=="") die("Application error! (seq error)");
if ($sequence=="") die("ERR(3)");
$sequence=addslashes($sequence); // Shouldn't really be needed, should always be the same, but why not..
$seq_pretty=sprintf("%'04d",$sequence);



//$latest_full_sheet=getoneb("select * from cnstdwglog_latest_full_sheet where cnstdwglog_id = '$cnstdwglog_info->cnstdwglog_id'");
$sql = "select * from cnstdwglog_sheet_history_descending where cnstdwglog_id = '$cnstdwglog_info->cnstdwglog_id' limit 1";
$latest_full_sheet=getoneb($sql);





$sql = "select * from webfile_files where file_group_id = '$latest_full_sheet->file_group_id' and mime_type like '%pdf%'";
$files_res=@mysql_query($sql);
$pdf_count=@mysql_num_rows($files_res);
if ($pdf_count<1) die("ERR(3.5 - No PDF to include)");
$file_letter="a";
@mkdir("/tmp/front_desk");
@mkdir("/tmp/front_desk/cook_a_batch");
@mkdir("/tmp/front_desk/cook_a_batch/$global_user->login_name");
@mkdir("/tmp/front_desk/cook_a_batch/$global_user->login_name/$job->contract_num");
@chdir("/tmp/front_desk/cook_a_batch/$global_user->login_name/$job->contract_num");

while ($row=@mysql_fetch_object($files_res)) {
	if ($row->file_group_id==0) die("ERR(99) - No File");
	$cnstdwglog_info->drawing_num=ereg_replace("[ /]","_",$cnstdwglog_info->drawing_num);
	$latest_full_sheet->issuance_name=ereg_replace("[ /]","_",$latest_full_sheet->issuance_name);
	$file_name=$seq_pretty . $file_letter . "-_$job->contract_num_-_cnstdwg_-_$cnstdwglog_info->drawing_num_-_$latest_full_sheet->issuance_name.pdf";
	copy("$storage_root$row->file_path",$file_name);
	if (!(is_file($file_name))) die("ERR(4)");
	$file_letter++;
	}
echo "OK";
exit;
?>
15