<?
if ($addenda_id!="") $addenda_id=addslashes($addenda_id);
else die("Application error!");
$addendum_info=getoneb("select * from cnstdwglog_addenda where addenda_id = '$addenda_id'");
if (!($addendum_info)) die("Application error!");

$file_info=getoneb("select * from cnstdwglog_files where files_id = '$addendum_info->files_id'");

if ($addendum_info->posted=="Y") { $posted="N"; }
else { $posted="Y"; }


@mysql_query("update cnstdwglog_addenda set posted = '$posted' where addenda_id = '$addendum_info->addenda_id'");
check_addenda($file_info->cnstdwglog_id);
forward("cnstdwglog_edit&cnstdwglog_id=$file_info->cnstdwglog_id");

?>
