<?
if ($addenda_id!="") $addenda_id=addslashes($addenda_id);
else die("Application error!");
$addendum_info=getoneb("select * from cnstdwglog_addenda where addenda_id = '$addenda_id'");
if (!($addendum_info)) die("Application error!");

$file_info=getoneb("select * from cnstdwglog_files where files_id = '$addendum_info->files_id'");

if ($addendum_info->required_in_this_issuance=="Y") { $required="N"; $posted="Y"; }
else { $required="Y"; $posted="N"; }


@mysql_query("update cnstdwglog_addenda set required_in_this_issuance = '$required', posted = '$posted' where addenda_id = '$addendum_info->addenda_id'");
check_addenda($file_info->cnstdwglog_id);
forward("cnstdwglog_edit&cnstdwglog_id=$file_info->cnstdwglog_id");

?>
