<?

//@mkdir("/tmp/front_desk");
//@mkdir("/tmp/front_desk/cook_a_batch");
//@mkdir("/tmp/front_desk/cook_a_batch/$global_user->login_name");
//@mkdir("/tmp/front_desk/cook_a_batch/$global_user->login_name/$job->contract_num");
$job=getoneb("select * from jobinfo where jobinfo_id = '$global_jobinfo_id'");
$directory="/tmp/front_desk/cook_a_batch/$global_user->login_name/$job->contract_num";
@chdir($directory);
$actual=getcwd();
//die($actual);
if ($actual!=$directory) die("Application Error!($actual****$directory)");
@unlink("ouput.pdf");
@unlink("ouput.zip");
$command_output=array();
//echo "hi";
exec("pdftk *.pdf cat output output.pdf",$command_output);
//print_r($command_output);
//passthru("pwd");

header("Content-disposition: attachment; filename=\"output.pdf\";");
header('Content-type: application/pdf');
header("Content-Transfer-Encoding: binary");
header("Expires: 0");
header("Cache-Control: private");
header("Pragma: cache");
readfile("output.pdf");
?>
