<?
if ($global_group_id!="") $global_group_id=addslashes($global_group_id);
else die("Application error: Invalid group_id");
$global_group_info=getoneb("select * from contacts_groups where group_id = '$global_group_id'");



//if ($add_global_member!="") {
//	$add_global_member=addslashes($add_global_member);
//	$tmpqry="insert into contacts_groups_members set group_id = '$global_group_id', contacts_id = '$add_global_member'";
//	@mysql_query($tmpqry);
//	}

//if ($rem_global_member!="") {
//	$rem_global_member=addslashes($rem_global_member);
//	$tmpqry="delete from contacts_groups_members where membership_id = '$rem_global_member'";
//	@mysql_query($tmpqry);
//	}


$query="select contacts.display_name,contacts.contacts_id,contacts_groups_members.membership_id,contacts_groups_members.group_id from contacts_groups_members,contacts where contacts_groups_members.contacts_id = contacts.contacts_id and group_id = '$global_group_id' order by alphasort";
$res=@mysql_query($query);

echo "<table border=0 cellspacing=0 cellpadding=1>
<tr><td colspan=2>
	<b>Members ($global_group_info->description)</b>
";

while ($row=@mysql_fetch_object($res)) {
	echo "<tr><td>
			<form style=\"display: inline;\" name=member$row->membership_id>
			";contactsbox("select * from contacts where 1 = 1",$row->contacts_id,'contacts_id','',1);echo"
			</form>
		</td><td>
		</td></tr
		";
	}	
			// <a href=javascript:rem_global_member($row->group_id,$row->membership_id);><font color=blue><i>Remove</i></font></a>

//echo "
//
//<tr><td>
//	<form style=\"display: inline;\" name=add_global_member method=post action=$pagename>";
//	contactsbox("select * from contacts where login_name != '' and current = 'Y'","",'contacts_id');echo "
//	</form>
//</td><td>
//	<a href=javascript:add_global_member($global_group_id);><font color=blue>ADD</font></a>
//</td></tr>

echo"</table>";
?>
