<?
require('viewpoint_connect_ro.phtml');
require('viewpoint_libs.inc');
if ($global_user->umc_emp!='Y') exit;


if ($jobinfo_id=='') die("Application error. Job ID missing. Please contact your system administrator.");
$jobinfo_id=addslashes($jobinfo_id);
$jobinfo=getone("select * from jobinfo where jobinfo_id = '$jobinfo_id'");
if (!($jobinfo)) die("Application error! Invalid job information.");

//if ($sub_job!="") $sub_job=addslashes($sub_job);
$vp_job_info=is_valid_viewpoint_job($jobinfo->contract_num);
if (!($vp_job_info)) {
	die("<div style=\"border: 1px solid black; background: $fd_color_3; width: 150px; height: 200px;\">Error acquiring job information from viewpoint!</div>");
	}
$base_contract=$vp_job_info->Job;

if ($sub_job!="") {
	$sub_job=str_pad($sub_job,3," ",STR_PAD_LEFT);
	$sub_job=addslashes($sub_job);
	$vp_job_info->Job=$vp_job_info->Job . $sub_job;
	}



$phases_locked=ms_getoneb("select * from JCJM with (NOLOCK) where JCCo = 1 and Job = '$vp_job_info->Job' and LockPhases = 'Y'");
if ($phases_locked) {
	$query="select * from JCJP with (NOLOCK) INNER JOIN JCCH with (NOLOCK) on JCJP.JCCo = JCCH.JCCo and JCJP.Job = JCCH.Job and JCJP.Phase = JCCH.Phase where JCJP.Job = '$vp_job_info->Job' and JCJP.JCCo = 1 and JCJP.ActiveYN = 'Y' and JCCH.CostType = '1'";
	} else { 
	$query="select * from JCPC with (NOLOCK),JCPM with (NOLOCK) where JCPC.Phase = JCPM.Phase and JCPC.CostType = 1 and JCPC.PhaseGroup = 1 and JCPM.PhaseGroup = 1";
	}

//ms_tabledump($query);
$res=@mssql_query($query);

if ($mode=="report_show") {
	include("header.phtml");
	fd_navs_header();
	}

echo "<table border=1 cellspacing=0 cellpadding=0 style=\"background: white;\">";


/////////////////////////////////////////////////
//	Sub jobs
/////////////////////////////////////////////////
//ms_tabledump("select * from JCJM where Job like '$base_contract%' and JCCo = 1 order by Job");
$subjobs_list_res=@mssql_query("select * from JCJM with (NOLOCK) where Job like '$base_contract%' and JCCo = 1 order by Job");
while ($sjrow=@mssql_fetch_object($subjobs_list_res)) {
	$sj_temp=ereg_replace(".*- *","",$sjrow->Job);
	if ($sjrow->Job == $vp_job_info->Job) {
		echo "<tr bgcolor=$fd_color_1 title=\"$sjrow->Description\" ><td colspan=2 valign=top align=center><b>$sjrow->Job</b></td></tr>";
		$cd=$sjrow->Description;
		} else {
		echo "<tr style=\"cursor: pointer; cursor: hand;\" bgcolor=$fd_color_4 title=\"$sjrow->Description\" onclick=show_labor_phases($jobinfo->jobinfo_id,'$sj_temp',1);><td colspan=2 valign=top align=center><b>$sjrow->Job</b></td></tr>";
		}
	}
/////////////////////////////////////////////////

echo "<tr style=\"cursor: pointer; cursor: hand;\" bgcolor=$fd_color_3 title=\"$sjrow->Description\" onclick=show_labor_phases($jobinfo->jobinfo_id,'$sj_temp');><td colspan=2 valign=top align=center><b>$vp_job_info->Job</b></td></tr>";
echo "<tr><td colspan=2 align=center valign=top><i><b>$cd</b></i></td></tr>";
while ($row=@mssql_fetch_object($res)) {
	$phase=ereg_replace("- *$","",$row->Phase);
	$phase=ereg_replace("- *$","",$phase);
	echo "<tr><td valign=top><font size=-1>$phase</font></td><td><font size=-1>$row->Description</font></td></tr>";
	}






echo "</table>";
if ($mode=="report_show") fd_navs_footer();
?>
