<?
require_once('classes/Authorization/AccessControl.php');

use classes\Authorization\AccessControl;

echo "<form name=pm_add_form>";
	contactsbox("",$global_jobinfo->project_manager_id,'asdf','',1);
	echo "<br>";
	if (($global_user_id==$global_jobinfo->project_manager_id)||($global_user_id<3)||($global_user_id==158)||($global_user_id==11)||($global_user_id==5809)) {
		contactsbox("select * from contacts where umc_emp = 'Y' and current = 'Y'","","pm_to_add","opener.add_pm_to_job()");
		echo "&nbsp;<i>Add</i><br>";
		}
	$pmres=@mysql_query("select * from front_desk_job_pms where jobinfo_id = '$global_jobinfo->jobinfo_id'");
	while ($pmrow=@mysql_fetch_object($pmres)) {
		contactsbox("",$pmrow->contacts_id,"pm_guest_$pmrow->pm_guest_id",'',1);
		if (($global_user_id==$global_jobinfo->project_manager_id)||(AccessControl::isAdmin($global_user_id))||($global_user_id==11)||($global_user_id==5809)||($global_user_id==$pmrow->contacts_id)) echo "&nbsp;<i><a href=\"javascript:pm_remove('$pmrow->contacts_id','$global_jobinfo->jobinfo_id')\">Remove</a></i>";
		else echo "<i>&nbsp;guest</i>";
		echo "<br>";
		}
echo "</form>";

?>
