<?
require("header.phtml");
require('mh_lib.inc');
mh_navs_header();

$output="";
echo "<center><h2>U-Connections</h2></center>

<table height=100% width=100% border=0 cellspacing=0 cellpadding=10>
<tr><td valign=top>

";


// GPH MARK - absolute path
exec("/bin/ls -1 -t /data/web/pipeline/intra/newsblasts/*.pdf",$output);
$count=0;
$totalcount=sizeof($output);
if ($totalcount>20) $totalcount=20;
$first="";
while ($count <= $totalcount) {
	$basename=ereg_replace("^.*/","",$output[$count]);
	$filename=$output[$count];
	$filedate=date('m-d-Y',filemtime($filename));
	if ($filename != "") echo "<a target=\"viewport\" href=\"https://pipeline.umci.com/intra/newsblasts/$basename\" title=\"Filename: $basename\"><font color=blue>Posted:&nbsp;$filedate</font></a><br>";
	if ($first=="") $first="https://pipeline.umci.com/intra/newsblasts/$basename";
	$count++;
	}
echo "
</td><td width=100% valign=top height=100%>
<iframe src=\"$first\" name=viewport width=100% height=100%>No file loaded</iframe>
</td></tr>
</table>

";

mh_navs_footer();
?>
