<?
$doc_id=addslashes($doc_id);
$doc_info=getoneb("select * from documents where doc_id = '$doc_id'");

if (!($doc_info)) {
	if ($pal_open_bitte_schon!="") {
		$link="pal$devel/?mode=pal_edit&pal_id=$pal_open_bitte_schon";
		header("Location: $link");
		exit;
		}
	}




$key=$doc_info->doc_type + '_id';

switch ($doc_info->doc_type) {
	case "gcrfi":	$application="gcrfilog" . $devel;
					$newmode="gcrfi_edit";
					$key="gcrfi_id";
					break;;
	case "rfi":		$application="rfilog" . $devel;
					$newmode="rfi_edit";
					$key="rfi_id";
					break;;
	case "transmittal":		$application="transmittals" . $devel;
					$newmode="transmittal_edit";
					$key="transmittal_id";
					break;;
	default: 		
					$application=$doc_info->doc_type . $devel;
					$newmode=$doc_info->doc_type . '_edit';
					$doc_type_tmp=$doc_info->doc_type;
					$key="${doc_type_tmp}_id";
					break;;
	}
if ($pal_open_bitte_schon!="") $pal_open_bitte_schon=addslashes($pal_open_bitte_schon);

$record=$doc_info->app_record_id;
$link="$application/?mode=$newmode&$key=$doc_info->app_record_id&global_jobinfo_id_set=$doc_info->jobinfo_id&pal_open_bitte_schon=$pal_open_bitte_schon";
header("Location: $link");
exit;
?>
