<?
session_write_close();
$recent_jobs_query="select * from jobinfo_history where contacts_id = '$global_user_id' group by jobinfo_id order by accessed desc limit 5";
//tabledump($recent_jobs_query);
echo "<table width=100% border=0 cellspacing=0 cellpadding=3>";
$res=@mysql_query($recent_jobs_query);
while ($row=@mysql_fetch_object($res)) {
	/////////////////////////////////////////
	$new_tasks_style="";
	$task_summary="";
	$pal_active=getone("select sum(1) as total from pal_buddies where jobinfo_id = '$row->jobinfo_id' and owner_id = '$global_user_id' and status = 'active' and pass_signed_off = 'N'");
	if ($pal_active->total!="") {
		$pal_new=getone("select sum(1) as total from pal_buddies where jobinfo_id = '$row->jobinfo_id' and owner_id = '$global_user_id' and status = 'active' and viewed = 'N'");
		if ($pal_new->total=="") {
			$pal_new->total='0';
			} else {
			$new_tasks_style="border: 1px solid red; background: yellow;";
			}
		$task_summary="<font size=-1><i>&nbsp;($pal_new->total/$pal_active->total)</i></font>";
		}
	/////////////////////////////////////////
	$jobinfo=getoneb("select project_manager_id,contract_num,display_name from jobinfo where jobinfo_id = '$row->jobinfo_id'");
	$jobmark="";
	if ($jobinfo->project_manager_id==$global_user->contacts_id) $jobmark="*&nbsp;";
	echo "<tr style=\"$new_tasks_style cursor: hand; cursor: pointer;\" onclick=\"load_job($row->jobinfo_id)\" onmouseover=\"this.style.background_orig=this.style.background;this.style.background='#dddddd'\" onmouseout=\"this.style.background=this.style.background_orig\"><td>
		<font size=-1><b>$jobmark$jobinfo->contract_num</b>&nbsp;-&nbsp;$jobinfo->display_name</font>
		</td><td>
			$task_summary
		</td></tr>";
	}
echo "<tr><td>&nbsp;</td></tr></table>";
?>
